### ISSUE TITLE
Running gqlgen behind corporate proxy

### ISSUE THREAD

**Issue by dtrinh100** [99designs/gqlgen#1000]
### What happened?

I tried running gqlgen behind a corporate proxy and got a few caching errors, not sure if it's proxy related, it only ended up generating a `gqlgen.yml` file and nothing else:

```
modelgen: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false --github.com/99designs/gqlgen/graphql/introspection gitHub.com/99designs/gqlgen/graphql]: exit status 1: 
go build math/bits: failed to cache compiled Go files
go build internal/race: failed to cache compiled Go files
...
```

The mod file looks like this after the `init` command is called:

```
module github.com/testing/gqlgen-todos

go 1.13

require github.com/99designs/gqlgen v0.10.2 // indirect
```

It works fine on my personal computer though.

### What did you expect?

To generate all the expected files.

### Minimal graphql.schema and models to reproduce

Using the one from the "Get Started" guide:
```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

### versions
 - `gqlgen version`? 0.10.2
 - `go version`?  1.13.7
 - dep or go modules? go modules

**Comment by vektah** [comment]
> go build math/bits: failed to cache compiled Go files
> go build internal/race: failed to cache compiled Go files

Looks like you have a broken go install and packages cant write to wherever it writes to. I'm not sure how to help, other than to say check your file permissions.
