### ISSUE TITLE
make distinguishable about between null and empty list

### ISSUE THREAD

**Issue by vvakame** [99designs/gqlgen#1023]
### What happened?

I want distinguish about mutation A and B in resolver.

```
mutation A {
  # update tags to zero length list
  updateFoo(id: "Foo:1", input: { name: "foo", tags: []) { ... }
}
mutation B {
  # don't modify tags. only update about "name".
  updateFoo(id: "Foo:1", input: { name: "foo") { ... }
}
```

Is there a way I can do this now?
current generated code is below. I think We can't do that now... 🤔 

```
	var err error
	res := make([]ID, len(vSlice))
	for i := range vSlice {
		res[i], err = ec.unmarshalFoo(ctx, vSlice[i])
		if err != nil {
			return nil, err
		}
	}
	return res, nil
```

### versions
 - `gqlgen version`? master/HEAD
 - `go version`? go version go1.13.7 darwin/amd64
 - dep or go modules? go modules

**Comment by ngorohov** [comment]
Hi there!
I have same question.
Having nullable field I can't determine difference between "set to nil" and "do nothing", because in input data structure this field will be "nil" in both cases.

**Comment by lwc** [comment]
Fixed via https://github.com/99designs/gqlgen/pull/1242
