### ISSUE TITLE
 Using Backticks in comments in federated services causes invalid code to be generated.

### ISSUE THREAD

**Issue by BitPhinix** [99designs/gqlgen#1030]
### What happened?
Using backticks in comments in federated services causes invalid code to be generated. (They aren't replaced thus breaking the string).

### What did you expect?
The backticks to be replaced.

### Minimal graphql.schema and models to reproduce
See the [File Upload](https://gqlgen.com/reference/file-upload/) example.

### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?

**Comment by vektah** [comment]
It's pretty important to include the version when working with `master`. It looks like this has been already fixed, likely by https://github.com/99designs/gqlgen/pull/1019.
