### ISSUE TITLE
[Federation] Allow multiple entity keys.

### ISSUE THREAD

**Issue by BitPhinix** [99designs/gqlgen#1031]
### What happened?
GQLGen only generates one entity resolver function for an entity with 2 (or more) keys.

### What did you expect?
2 (or more) Entity resolver functions.

### Minimal graphql.schema and models to reproduce
```
type Product @key(fields: "upc") @key(fields: "sku") {
  upc: UPC!
  sku: SKU!
  name: String
}
```
[See Apollo Documentation](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#query_entities)

### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?

Also, thanks for the awesome work :+1:

**Comment by vektah** [comment]
Yeah, this is a known limitation for now. We will continue to iterate, but this wont make 0.11.

**Comment by jclyons52** [comment]
It looks like this was resolved by https://github.com/99designs/gqlgen/pull/1723
