### ISSUE TITLE
(Federation) Is_Entity is unloved by golint

### ISSUE THREAD

**Issue by carldunham** [99designs/gqlgen#1032]
### What happened?
On generated model file:
```
% golint company.go
company.go:12:16: don't use underscores in Go names; method Is_Entity should be IsEntity
% 
```
### What did you expect?
```
% golint company.go
% 
```

### Minimal graphql.schema and models to reproduce
schema:
```
type Company @extends @key(fields: "name") {
  name: String! @external
  moreStuff: [int]
}
```
### versions
 - `gqlgen version`? v0.10.2-dev (commit 4ece3857c9ab)
 - `go version`? go version go1.13.7 darwin/amd64
 - dep or go modules? modules

**Comment by BitPhinix** [comment]
A nice solution would be to do it like [dig](https://github.com/uber-go/dig) and providing a Entity struct which could be embedded into all entity structs.

Something like:
```
type Account struct {
	graphql.Entity
}
```

**Comment by carldunham** [comment]
Wow, that was quick and way more throrough than what I expected. Thanks!
