### ISSUE TITLE
dataloaden usage example is not appropriate

### ISSUE THREAD

**Issue by GazeboXu** [99designs/gqlgen#1035]
### What happened?
when you execute dataloaden without parameter, it prints:
```
usage: name keyType valueType
 example:
 dataloaden 'UserLoader int []*github.com/my/package.User'
```
### What did you expect?
it should be
```
usage: name keyType valueType
 example:
 dataloaden UserLoader int '[]*github.com/my/package.User'
```
the quotation mark is the point.
### versions
 - `gqlgen version v0.10.2` 
 - `go version go1.13.6`
 - `go modules`

**Comment by vektah** [comment]
Please open an issue / PR against the dataloaden repo.
