### ISSUE TITLE
Feature parity with graphql implementations

### ISSUE THREAD

**Issue by nitin302** [99designs/gqlgen#1037]
Hello I'm looking for comparisons in feature parity with the latest graphql specification.

Is gqlgen at par with the latest stable one? http://spec.graphql.org/ and what is the plan for feature releases when a new specification is out.

I'm mainly trying to find out if there is a parity difference between the JS implementations (as they seem to be the most used in production) in comparison to gqlgen. 

- Are all features covered? Is there anything missing?  in comparison with the JS implementation or the latest available spec
- If there is a new spec release, how fast would it be able to implement those changes.

**Comment by vektah** [comment]
We use https://github.com/vektah/gqlparser

> spec target: June 2018 (Schema definition language, block strings as descriptions, error paths & extension)

Which is still the latest stable spec https://spec.graphql.org/June2018/. Take a look at [the diff](https://github.com/graphql/graphql-spec/compare/June2018...master) to see whats going to land in the next release.

[Almost everything](https://gqlgen.com/feature-comparison/) is supported, notable exception is the ability to implement [some directives](https://github.com/99designs/gqlgen/issues/760). 


The tests from the reference implementation (graphql-js) are used to test the go parser, but they haven't been imported in a while and some [work is needed](https://github.com/vektah/gqlparser/pull/112) to get them running again. Will likely happen before 1.0.

**Comment by nitin302** [comment]
Thank you, when the target for 1.0?

Also, Is it possible to add directives to the [comparison](https://gqlgen.com/feature-comparison/), do you know if others in the list support the,?

**Comment by vektah** [comment]
Yeah that list needs an update, it takes a bit of effort to go through the libraries to review them. I'll create a new issue and close this - https://github.com/99designs/gqlgen/issues/1042
