### ISSUE TITLE
0.11.0 Cannot use type *Server as type http.HandlerFunc

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1040]
### What happened?

Upgrading from `v0.10.2` to `v0.11.0` and using https://github.com/go-chi/chi I can't use this code anymore:

```go
r := chi.NewRouter()
gqlgenServer := handler.GraphQL(graphql.NewExecutableSchema(graphql.Config{}}),config.GraphqlHandlerOptions)
r.Post("/query", gqlgenServer)
```

because of:

`Cannot use 'gqlgenServer' (type *Server) as type http.HandlerFunc`

### What did you expect?

I expected to be able to use it like this again. Or how?

### versions
 - `gqlgen version`? 0.11.0
 - `go version`? 1.13
 - dep or go modules? mod

**Comment by vektah** [comment]
*Server is a http.Handler, not a http.HandlerFunc.

Use 
```
r.Handle("/query", gqlgenServer)
```
or
```
r.Post("/query", gqlgenServer.ServeHTTP)
```
