### ISSUE TITLE
Is it possible to make arbitrary queries without a server?

### ISSUE THREAD

**Issue by technoweenie** [99designs/gqlgen#1041]
I'd like to make queries with a `graphql.ExecutableSchema` without having to go through a server (For example: in a command line app). Judging by the `*transport.Post` code, this should be possible with a `graphql.GraphExecutor`. However, the only implementation is a private type inside the `gqlgen/graphql` package. 

Is there any interest in exporting that in some way? I saw #730, but it looks like the code base has changed a lot since then.

**Comment by vektah** [comment]
Great use case, I don't feel comfortable exposing that type as it stands. It has a really wide interface and accepts all of *Server.  

If you want to take the time to remove the *Server dependency (should probably be ExecutableSchema) and make it public, with the tests required for it, I would accept a PR.

If not, the easiest way forward for you is likely to copy what the test client is doing - Create the *Server, but **dont** start a http server and just feed it requests directly. https://github.com/99designs/gqlgen/blob/master/client/client.go#L106-L134

**Comment by technoweenie** [comment]
> If you want to take the time to remove the *Server dependency (should probably be ExecutableSchema) and make it public, with the tests required for it, I would accept a PR.

Sounds good. I'll try my hand at a new type in that same package and file a PR for more feedback. :metal: 

Thanks!
