### ISSUE TITLE
Validation failed when using new resolver layout

### ISSUE THREAD

**Issue by sonatard** [99designs/gqlgen#1044]
### What happened?

```
$ gqlgen generate
validation failed: packages.Load: /Users/sonatard/go/src/github.com/sonatard/myrepo/lib/tasks/cloudtasks
.go:9:2: could not import github.com/sonatard/myrepo/entrypoint/gen/graphql/api/apiclient (invalid package name: "")
../../../../lib/tasks/cloudtasks.go:9:2: no matching versions for query "latest"

```

https://gqlgen.com/recipes/migration-0.11/#new-resolver-layout

I guess that occur validation error when generated code dose not exist.

### What did you expect?

no validation error

My Workaround are use `skip_validation: true` in gqlgen.yml or dosen't delete generated code before exec gqlgen generate.

### Minimal graphql.schema and models to reproduce

```
schema:
  - ./*/*.graphql

exec:
  filename: ../../../gen/graphql/api/server_gen.go
  package: api
model:
  filename: ../../../gen/graphql/api/model_gen.go
  package: api
resolver:
  layout: follow-schema
  dir: ../../../src/api/resolver
```

### versions
 - `gqlgen version`? master
 - `go version`?  go version go1.13.7 darwin/amd64
 - dep or go modules? go modules

**Comment by sonatard** [comment]
I understood what happens.

I have two gqlgen.yml for api and admin, `.go` file has dependncy for api and admin.

1. Delete generated code api and admin.
2. `gqlgen generate` for api.
3. `.go` file can't find admin code.

@vektah I have some options. Please give me your advice.

1.  Do nothing. This is only my problem.
2. Add `gqlgen validate` sub command. 
    - enable `skip_validation: true` for `gqlgen generate`.
    -  `gqlgen varidate` after all gqlgen generate.
3. Add `gqlgen validate` sub command.  and stop to validate in `gqlgen generate` default.

I prefer `2. Add gqlgen validate sub command. `

I will make Pull Request by  your choice.

**Comment by matiasanaya** [comment]
@sonatard I also have this problem.

Did you ever figure out an elegant way around it? For now, I've set all my configs to `skip_validation: true`.

**Comment by dragonfax** [comment]
I'm trying to start out with gqlgen and I"m hitting this too. In fact none of the commands in the get started doc are working completely. (https://gqlgen.com/getting-started/)

**Comment by frederikhors** [comment]
Please, all, push a reproduction. gqlgen works!

**Comment by williamflynt** [comment]
I ran into this problem when I already had all my `struct` created.

* Create a `.schema.graphqls` using only existing `struct` names
* Add paths to the files containing `struct` to `gqlgen.yml`
* Run `generate` - note that `model/model_gen.go` is deleted.

I saw this error at that time. To fix, I added `model_gen.go` back to `model` directory.

```
package model

// models/model_gen.go
```

I ran `generate` again. No issues.

**Comment by kockok** [comment]
I am also having this kind of error:

```
type Mutation {
	toggleContactable(email: String!): Boolean!
}
````


```
validation failed: packages.Load: /graph/schema.resolvers.go:499:67: cannot use &(mutationResolver literal) (value of type *mutationResolver) as generated.MutationResolver value in return statement: *mutationResolver does not implement generated.MutationResolver (missing method ToggleContactable)

exit status 3
```

Wondering if it's related to different versions of gqlgen and gqlparser.

I use:

```
	github.com/99designs/gqlgen v0.17.14-0.20220805235724-f5d603269502
        github.com/vektah/gqlparser/v2 v2.4.7
```
