### ISSUE TITLE
Document issue about new resolver layout

### ISSUE THREAD

**Issue by sonatard** [99designs/gqlgen#1045]
### What happened?

Generated comment says , "The code below was going to be deleted when updating resolvers. "
But I exec `gqlgen generate` again, code didn't delete.

I don't understand `when updating resolvers` mean.

```
// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
```

**Comment by vektah** [comment]
It means theres code in that file that gqlgen doesnt know about, but we cant tell the difference between 
 - helper methods:  eg code you've written that arent resolvers
 - code that is no longer required: eg resolvers that arent in the interface and will never be called.

To be safe we leave them all there under that big comment. If they are helpers move them out, if they are no longer required delete them.

**Comment by navicstein** [comment]
In my case, I just want `gqlgen` to ignore the files rather than copying them over just like models can be configured to be generated or not with `autobind`
