### ISSUE TITLE
Why the schema file is using `.graphqls` extension?

### ISSUE THREAD

**Issue by rohmanhm** [99designs/gqlgen#1047]
Hi, I'm new to this lib and wondering why do you use `.graphqls` extension rather than `.graphql`.

Thanks in advance.

**Comment by vektah** [comment]
To differentiate between graphql schema files and graphql query files that often live in the same repo.

AFAIK all tools tools will accept both, but as of 0.11 the default include path is getting a little broader and I don't want to accidentally include graphql queries in the server.

Is this causing an issue?

**Comment by rohmanhm** [comment]
> Is this causing an issue?

@vektah Nope, it's not caused any issue. I just wondering.

I thought you have some special treatment for a file with extension `.graphqls` rather than `.graphql`.

Thanks for the explanation. ❤️
