### ISSUE TITLE
Autogenerated models with unions cannot be unmarshaled

### ISSUE THREAD

**Issue by vishvananda** [99designs/gqlgen#1055]
### What happened?

Given a schema with a type that contains a union, the model cannot be loaded from json, even if the appropriate `__typename`s are included

### What did you expect?

Calling json.unmarshal on an autogenerated model file given a graphql response would be successful. This can be worked around using a custom json unmarshal function, but then the unmarshal function has to be kept in sync with the schema. This seems like something that could be autogenerated.

### Minimal graphql.schema and models to reproduce
Schema:
```
type Foo {
  id: ID!
}

type Bar {
  id: ID!
}

union Part = Foo | Bar

type Widget {
  id: ID!
  part: Part!
}
```

Resulting models

```
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
  "encoding/json"
)

type Part interface {
  IsPart()
}

type Bar struct {
  ID string `json:"id"`
}

func (Bar) IsPart() {}

type Foo struct {
  ID string `json:"id"`
}

func (Foo) IsPart() {}

type Widget struct {
  ID   string `json:"id"`
  Part Part   `json:"part"`
}
```

### Test code

```
package graph

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/.../gqlgen-example/graph/model"
)

func TestJsonUnmarshal(t *testing.T) {
	j := []byte(`
	[
		{
			"id": "1000",
			"part": {
				"__typename": "Foo",
				"id": "1000"
			}
		},
		{
			"id": "2000",
			"part": {
				"__typename": "Bar",
				"id": "2000"
			}
		}
	]
	`)
	fmt.Printf("Json: %s\n", j)
	var w []model.Widget
	if err := json.Unmarshal(j, &w); err != nil {
		t.Fatal(err)
	}
	fmt.Printf("Unmarshal: %+v\n", w)
}
```

result:

```marshal_test.go:33: json: cannot unmarshal object into Go struct field Widget.part of type model.Part```

### Workaround that allows json marshal to work

```
type TypedObject struct {
	Typename string `json:"__typename"`
}

type SafeWidget struct {
	ID   string      `json:"id"`
	Part TypedObject `json:"part"`
}

func (o *Widget) UnmarshalJSON(b []byte) error {
	var safe SafeWidget
	if err := json.Unmarshal(b, &safe); err != nil {
		return err
	}
	// set non-union fields here
	o.ID = safe.ID

	switch safe.Part.Typename {
	case "Foo":
		var partial struct {
			Part Foo `json:"part"`
		}
		if err := json.Unmarshal(b, &partial); err != nil {
			return err
		}
		o.Part = partial.Part
	case "Bar":
		var partial struct {
			Part Bar `json:"part"`
		}
		if err := json.Unmarshal(b, &partial); err != nil {
			return err
		}
		o.Part = partial.Part
	}
	return nil
}
```
### versions
 - `gqlgen version`? 0.11.1
 - `go version`?  1.13.4
 - dep or go modules? go modules

**Comment by vishvananda** [comment]
Note that this came up in the context of using the generated models to create a go client library. I can look at modifying the autogen code to (optionally?) add the json unmarshal code but I wanted to get some feedback first:

1. Is there a way to do this that I missed?
2. Is this is a terrible idea or out of scope?
3. Is there a codgen expert out there that could whip this up really quickly so I don't have to go figure out how it works?

**Comment by vektah** [comment]
The details of how this should work are being worked on in the [input union RFC](https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md) , it looks likely that some kind of input polymorphism will be part of the next spec, but for now it does not exist.

**Comment by vektah** [comment]
Closing, this will be addressed when the spec is released.

**Comment by tonyabracadabra** [comment]
This is actually a pretty valid question and worth more attentions here, @vishvananda did u have any working progresses? I would also love to contribute if that's something people care

**Comment by selaux** [comment]
I just stumbled over this as well. I think at least reopening this would make sense as it does not relate to the unreleased graphql input union types spec, but the existing [union types](https://github.com/graphql/graphql-spec/blob/main/spec/Section%203%20--%20Type%20System.md#unions), if I understand correctly.
