### ISSUE TITLE
i want to init with gqlgen version 0.10.2

### ISSUE THREAD

**Issue by xuanlongvts** [99designs/gqlgen#1060]
Now, you have version v0.11.1. So i want How to init with gqlgen version v0.10.2

Thanks!

**Comment by vektah** [comment]
create a new directory for your project and then inside it run:
```
export GO111MODULE=on
go mod init github.com/you/project
go get github.com/99designs/gqlgen@0.10.2
go run github.com/99designs/gqlgen init
```

**Comment by sureshattaluri** [comment]
go get github.com/99designs/gqlgen@0.10.2 --> this is not working

go get github.com/99designs/gqlgen@v0.10.2 --> this works for me
