### ISSUE TITLE
graphql.AddError() in OperationMiddleware / return generic error in middleware

### ISSUE THREAD

**Issue by Pokerkoffer** [99designs/gqlgen#1062]
### What happened?
In versions < 0.11 it was possible to add a graphql Error in the `RequestMiddleware` via graphql.AddError() and return `nil` instead of `next(ctx)`. Now (0.11) it throws an `missing response context` error.
**Use case**: Check for auth token and abort request before any resolver is executed and return error to client.

https://github.com/99designs/gqlgen/blob/14dccc57885df5d5ca4ef347c1b80f5f3648719a/graphql/context_response.go#L49-L57

old RequestMiddleware:
```go
// in request middleware
graphql.AddError(ctx, errors.New("MyError"))
return nil
```

### What did you expect?
Abort the current request and send an error to the client

**Edit: Solved.**
The new approach seems to be using 
```go
return gqlgen.OneShot(gqlgen.ErrorResponse(ctx, "MyError"))
``` 
instead of attaching 
```go
graphql.AddError(ctx, err)
return nil
```

**Comment by Pokerkoffer** [comment]
Another question:
It was possible before 0.11 to add a custom error struct to the response (with `graphql.AddError(MyErr{})`, e.g.
```go
// MyErr implements Error()
type MyErr struct {
  Code int
  Message string
}

// in RequestMiddleware
  graphql.AddError(MyErr{})
  return nil
```
and convert it in the ErrorPresenter to a GraphQL error with custom properties (here MyErr.Code) as extension (according to GraphQL spec). Currently this isn't possible anymore, because the Response struct expects an `gqlerror.List` which itself is a slice of gqlerror.Error.

```go
type Response struct {
	Errors     gqlerror.List          `json:"errors,omitempty"` // <- []*gqlerror.Error
	Data       json.RawMessage        `json:"data"`
	Extensions map[string]interface{} `json:"extensions,omitempty"`
}
```
So how can I return my custom errors in my domain and convert it in the ErrorPresenter to a GraphQL error?

**Comment by AdieOlami** [comment]
Please how did you resolve this?
