### ISSUE TITLE
gqlgen init doesn't use the provided schema

### ISSUE THREAD

**Issue by a-venture** [99designs/gqlgen#1064]
### What happened?
I am trying to use my custom schema to generate the server code, but gqlgen init doesn't use the provided schema and it just pulls in the todo example. How can I mitigate this? to me it seems like a configuration problem because it doesn't bind to any of my custom models  and it doesn't generate the resolvers.

### Minimal graphql.schema and models to reproduce

```
type User {
    id: ID!
    username: String!
    email: String!
    meetups: [Meetup!]!
}

type Meetup {
    id: ID!
    name: String!
    description: String!
    user: User!
}

type Query {
    meetups: [Meetup!]!
}
```

### versions
 - `gqlgen version`?  github.com/99designs/gqlgen v0.11.1
 - `go version`? 1.13

**Comment by vektah** [comment]
`init` gives you an example project, after you've done that modify to your needs and run `generate`

**Comment by emicklei** [comment]
sorry for commenting on a closed issue.

The package clearly states that tooling is use a "schema first" design so it makes sense to only generate an example schema if no schema was provided.
