### ISSUE TITLE
Request Hit multiple times.

### ISSUE THREAD

**Issue by tyagip966** [99designs/gqlgen#1068]
### What happened?
I just follow your instructions mentioned in https://gqlgen.com/getting-started/
without any change i run server.go 
and hit request **create Todo** as result 21 entries inserted in my DB
after that i insert a log message inside schema.resolver.go to cross check is this happening because of my code or by default then i found it hit schema.resolver 21 times by default in my case 
I'm attaching snap shots please check  
![Screenshot from 2020-02-27 12-38-58](https://user-images.githubusercontent.com/29175591/75421067-79e46d80-595f-11ea-85b8-e64d48397299.png)

### What did you expect?
Resolve issue as soon as possible.

### versions
 - `gqlgen version`v0.11.1
 - `go version`go version go1.13.5 linux/amd64
 - dep or go modules?

**Comment by danishsatkut** [comment]
Since you are mostly following along the getting started guide, can you please share the code through a Github repo?
