### ISSUE TITLE
Regenerating resolvers from schema removes comments of resolver methods

### ISSUE THREAD

**Issue by malyusha** [99designs/gqlgen#1069]
### What happened?
Comments of methods in autogenerated resolvers `{name}.resolvers.go` are deleted every time i re-generate schema.  

### What did you expect?
That all comments of resolver's methods are kept on their places.

### Minimal graphql.schema and models to reproduce
Schema from  `examples/config` can be used 

### versions
 - `gqlgen version` 0.11.0 
 - `go version` 1.13.1
 - dep or go modules - go modules

**Comment by mmmveggies** [comment]
Some generated function signatures fail lint, e.g. https://github.com/golangci/golangci-lint will complain that the following
```
func (r *queryResolver) Things(ctx context.Context, a *int, b *int, c *int) (interface{}, error) {
```

should be shortened to
```
func (r *queryResolver) Things(ctx context.Context, a, b, c *int) (interface{}, error) {
```

I would "solve" this by prepending a `//nolint` command, but subsequent `gqlgen` commands strip it.

**Comment by hsblhsn** [comment]
Facing the same issue.

**Comment by Sonamp** [comment]
@vektah any resolution done on this issue?

**Comment by frederikhors** [comment]
I think https://github.com/99designs/gqlgen/pull/2263 fixed this.
