### ISSUE TITLE
Use gorilla/mux instead of go-chi

### ISSUE THREAD

**Issue by nitin302** [99designs/gqlgen#1070]
Hello,
I'm trying to use gorilla/mux instead of go-chi. I am unable to add the middleware dataloader correctly. 

When I run the app and try a sample query, it does not pass through the LoaderMiddleware, hence throwing at error with resolving.

Can you show a sample example with gorilla/mux instead of go-chi. What am i missing.

```
r := mux.NewRouter()
v1Router := r.PathPrefix("").Subrouter()
v1Router.Use(model.LoaderMiddleware)
v1Router.Handle("/", playground.Handler("GraphQL playground", "/graphql"))
srv := handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}}))
v1Router.Handle("/graphql", srv).Methods(http.MethodPost).Name("graphql")
return r
```

**Comment by nitin302** [comment]
@vvakame any thoughts?

**Comment by nitin302** [comment]
I find when there are 2 Subrouter()s, it does not call the middleware correctly.

**Comment by marko911** [comment]
I second this. How to set up the graphql route and playground with gorillla/mux ?

**Comment by mmacheerpuppy** [comment]
Second let me copy and paste how I do it

**Comment by mmacheerpuppy** [comment]
ok it looks like the method is deprecated but I have been doing this for the longest time 
```
	es := generated.NewExecutableSchema(
		generated.Config{
			Resolvers: rootResolver,
		})
	r.Handle("/graphql", middleware.AuthMiddleware(handler.GraphQL(
		es,
	))).Methods("POST", "OPTIONS", "PUT", "DELETE")
```

**Comment by mmacheerpuppy** [comment]
Where AuthMiddleware just is a regular middleware that adds auth info to context
