### ISSUE TITLE
Possible generate graphql schema from struct or protobuf?

### ISSUE THREAD

**Issue by WLun001** [99designs/gqlgen#1078]
### What happened?
Now we need to write schema, then generate struct

### What did you expect?
Possible another way round, we have ready to use struct, and want to generate schema

### versions
 - `gqlgen version`: 0.10.1
 - `go version`: 1.13.5
 - dep or go modules: go modules

**Comment by danishsatkut** [comment]
As the README doc says, gqlgen uses a **Schema First** approach. It is a very fundamental design approach taken by the library. I am not sure if generating schema from structs/protobuf is something that will be supported in the near future.

@vektah Thoughts?

**Comment by vektah** [comment]
Yeah, sorry thats not how gqlgen works.

Try https://github.com/samsarahq/thunder instead
