### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by shanthkumar079** [99designs/gqlgen#1082]
### What happened?
Execution of command failed  : go run github.com/99designs/gqlgen init
Error : package github.com/99designs/gqlgen: rename C:\goworkspace\pkg\mod\github.com\99designs\gqlgen@v0.11.1.tmp-856248200 C:\goworkspace\pkg\mod\github.com\99designs\gqlgen@v0.11.
1: Access is denied.

### What did you expect?
       Should download the packages
### versions
 - `gqlgen version`? latest
 - `go version`? 1.3
 - dep or go modules?

**Comment by mmacheerpuppy** [comment]
Wondering if this is related to https://github.com/99designs/gqlgen/issues/1087
