### ISSUE TITLE
Panic when generating models, seems like new generation tooling in 0.11.1 is trying to download modules w/ Go 1.14?

### ISSUE THREAD

**Issue by mmacheerpuppy** [99designs/gqlgen#1087]
### What happened?
Panic when generating models, seems like new generation tooling in 0.11.1 is trying to download modules. Can you kindly clarify the conditions in which that index would be out of range? I experience this issue with **only** Go 1.14 and the version 0.11.1 or 0.11.0 version of your repositories. That is...

When I try to generate from Go 1.14 and 0.10.2 I experience no error and the following diffs from 0.11.1 in the server and model...

```
2590 insertions(+), 1647 deletions(-)
```

When I try to generate from Go 1.14 and 0.11.1 I experience various stack-traces (depending on my environment) and the following diffs from 0.11.1 in the server and model...
```
1647 insertions(+), 2583 deletions(-)
```
 
I would appreciate it if you guys could confirm whether 0.11.1 works with Go 1.14, or if there are any incompatibilities with Golang monorepos I should be aware of.

### What did you expect?
Models to be regenerated without error. It looks like the files have been generated, but I'm afraid to try them on the environment. It may be appropriate to try and set up a debugging repository at a more convenient time.

### Minimal graphql.schema and models to reproduce
Unsure, we are using Golang as a monorepo though, so git fetches to the package root are destined to fail as the gomod package name differs from the repository.

### versions
 - `gqlgen 0.11.1 is affected, 0.11.0 is affected, 0.10.2 is not` 
 - `go version 1.14`
 - `go modules`

### stacktrace 

When trying to force my git to download the repositories (with some hacking around Git) I get...
```
go: finding module for package github.com/company/repo/packages/monorepo/graphql/generated
go: downloading github.com/company/repo v0.0.0-20200304170403-d12f7282cfb7
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/99designs/gqlgen/internal/code.(*Packages).LoadWithTypes(0xc0003220c0, 0xc00081b360, 0x43, 0x9ddf55)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/internal/code/packages.go:93 +0x2bb
github.com/99designs/gqlgen/codegen/config.(*Binder).FindObject(0xc000f7f8c0, 0xc00081b360, 0x43, 0xc000b59854, 0xc, 0xc, 0xc00081b310, 0x924d20, 0xc0003e3750)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/codegen/config/binder.go:118 +0xdd
github.com/99designs/gqlgen/codegen/config.(*Binder).DefaultUserObject(0xc000f7f8c0, 0xc000266082, 0xc, 0x9e4fc5, 0x8, 0xc00093f100, 0x14)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/codegen/config/binder.go:101 +0x11a
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc00113f8e0, 0xc0002fd500, 0xc0003e3900, 0x0, 0xc000cecec0)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/codegen/object.go:56 +0x651
github.com/99designs/gqlgen/codegen.BuildData(0xc0002263c0, 0xac4b40, 0xe978c0, 0x0)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/codegen/data.go:75 +0x613
github.com/99designs/gqlgen/api.Generate(0xc0002263c0, 0x0, 0x0, 0x0, 0x0, 0xc000125bb8)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/api/generate.go:72 +0x353
github.com/99designs/gqlgen/cmd.glob..func1(0xc00022c000)
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/cmd/gen.go:39 +0xa8
github.com/urfave/cli.HandleAction(0x9227a0, 0xa264b8, 0xc00022c000, 0xc00020e120, 0x0)
	E:/GoPath/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x83
github.com/urfave/cli.(*App).Run(0xc000220000, 0xc00005e1d0, 0x1, 0x1, 0x0, 0x0)
	E:/GoPath/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5e4
github.com/99designs/gqlgen/cmd.Execute()
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/cmd/root.go:41 +0x22b
main.main()
	E:/GoPath/pkg/mod/github.com/99designs/gqlgen@v0.11.1/main.go:8 +0x27
exit status 2
```

On a fresh Linux environment with regular SSH access the stacktrace is...

```
$ gqlgen generate
validation failed: packages.Load: -: github.com/<company>/<root-package>@v0.0.0-20200304170403-d12f7282cfb7: verifying module:  github.com/<company>/<root-package>@v0.0.0-20200304170403-d12f7282cfb7: reading  github.com/<company>/<root-package>@v0.0.0-20200304170403-d12f7282cfb7: 410 Gone
        server response:
        not found:  github.com/<company>/<root-package>@v0.0.0-20200304170403-d12f7282cfb7: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/11bcc1eede75b7d018359e3d81e73011b792274b83d6fca525aa8d7738be407e: exit status 128:
                fatal: could not read Username for 'https://github.com': terminal prompts disabled

exit status 3
main.go:3: running "go": exit status 1
```

As discussed this is experienced only for certain Golang version `1.14` and 0.11.1 (used against a private repository).

**Comment by mmacheerpuppy** [comment]
```
go: downloading github.com/99designs/gqlgen v0.10.2
go: downloading github.com/vektah/gqlparser v1.2.0
go: downloading github.com/agnivade/levenshtein v1.0.1
go: downloading golang.org/x/tools v0.0.0-20190823170909-c4a336ef6a2f
```

**Comment by mmacheerpuppy** [comment]
Update: This may have been resolved by removing some old gqlgen yaml declarations...

```
resolver:
  filename: graphql/resolver/main.go
  type: Resolver
autobind:
  # Binds models to GQL input types if they exists
  - github.com/company/monorepo/packages/package/graphql/models
```

Will play around with it tomorrow GMT

**Comment by vektah** [comment]
Yeah this isnt great, I'm not sure what the best approach is here. On one hand its quite nice that go modules just figures it out. On the other, package misses are brutally slow, and quite noisy.

You can set `GOPROXY=off` to disable this fetch for now, but I'm considering doing it automatically internally. It would force people to `go mod download` though which isnt normally required when working with go modules.

**Comment by mmacheerpuppy** [comment]
@vektah Just for some clarity on the file structure we use

```
monorepo_root/
├──  packages/
│   ├── service1/ ── go.mod
│   ├── service2/ ── go.mod
│   └── service3  ── go.mod
│    
├── circleci/
│   └── circleci.yaml
└── docs/
    └── examples/
```

**Comment by mmacheerpuppy** [comment]
@vektah I can advise that removing the following lines from our gqlgen config and setting GOPROXY=off is a workaround to this issue.
```
resolver:
  filename: graphql/resolver/main.go
  type: Resolver
autobind:
  # Binds models to GQL input types if they exists
  - github.com/company/monorepo/packages/package/graphql/models
```

**Comment by yckbilly1929** [comment]
for 0.11.0+, clean install following the docs does not work
go version 1.13 or 1.14

there will be a prompt for username and password that interrupts the setup
```
go run github.com/99designs/gqlgen init
Username for 'https://github.com':
```

workaround from above  will trigger:
```
panic: (config.ResolverLayout) (0x9377a0,0xc000c58640)

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*ResolverConfig).Dir(0xc00015f6f8, 0x44, 0xc000c70900)
```

> @vektah I can advise that removing the following lines from our gqlgen config and setting GOPROXY=off is a workaround to this issue.
> 
> ```
> resolver:
>   filename: graphql/resolver/main.go
>   type: Resolver
> autobind:
>   # Binds models to GQL input types if they exists
>   - github.com/company/monorepo/packages/package/graphql/models
> ```
> 
> However, this workaround does not work for the latest release #1095

**Comment by frederikhors** [comment]
@mmacheerpuppy please tell me if this is still an issue with v0.16.0 and I'll re-open it.
