### ISSUE TITLE
T infront of integer

### ISSUE THREAD

**Issue by JonathanHo16** [99designs/gqlgen#1088]
### What happened?
Hi (fully disclosure that I am currently learning Go and Graphql via a project where I used the gqlgen library). I noticed that when returning an integer there is a "T" infront of the number. Is it supposed to be there I couldn't find anything in my schema.
`{
  "data": {
    "createUser": {
      "userID": "T498081"
    }
  }
}`

### What did you expect?
I expected to return a number without the T in front 
`"userID":"498081"`
### Minimal graphql.schema and models to reproduce
schema entry:
`type User {
  userID: ID!
  password: String!
  username: String!
  email: String!
}`
using 
`type Mutation {
  createUser(input: newUser!): User!`
on the following query
`
mutation createUser {
  createUser(input:{username:"test3", email:"email@address.com",password:"test123"}) {
    userID
  }
`
here is my resolver
`func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	//get the next userID from the server
	//up to 1 million users
	var newUserID = -1

	for ok := true; ok; ok = isNewUserID(newUserID) {
		newUserID = rand.Intn(1000000)
		fmt.Printf("trying: %d \n", newUserID)
	}

	userName := input.Username
	password := GetMD5Hash(input.Password)
	email := input.Email
	//network call to put the user in the database
	client, ctx := getDbClient()
	_, _, err := client.Collection("users").Add(ctx, map[string]interface{}{
		"username":  userName,
		"emailAddress": email,
		"password": password,
		"userID": newUserID,
	})

	if err != nil {
		panic(fmt.Errorf(err.Error()))
	}
	user := &model.User{
		UserID:  fmt.Sprintf("T%d", newUserID),
		Password: password,
		Username: userName,
		Email:    email,
	}
	return user, nil
}`

### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?
This application is running against a google.cloud instance of firestore.

Thanks in advance for the help.

**Comment by vektah** [comment]
>	UserID:  fmt.Sprintf("T%d", newUserID),
