### ISSUE TITLE
gqlgen generate issue when running in non-gomodule mode

### ISSUE THREAD

**Issue by han-so1omon** [99designs/gqlgen#1105]
### What happened?
I am building this package in my $GOPATH instead of as a gomodule. The following occurs:
```
> gqlgen generate
> ... <my-path>/generated.go:16:2: could not import github.com/vektah/gqlparser/v2/ast (invalid package name: "")
```

This occurs because the repository is available at github.com/vektah/gqlparser (without the /v2), and thus it is retrieved via `go get` at the given url. The `go.mod` file defines the module with the /v2, and thus the error.

### What did you expect?
I expect my project to build normally

### Minimal graphql.schema and models to reproduce
== .graphql
type Test {
  mynum: Int!
}
== .go
type Test struct {
  MyNum int `json:"mynum"`
}

### versions
 - `gqlgen version`? v0.11.3-dev
 - `go version`? go1.13.8
 - dep or go modules? dep

**Comment by mtibben** [comment]
Unless github.com/vektah/gqlparser goes pre-mod `go get` compatible (i.e. using a directory structure for versioning), this may be the end of dep compatibility. Older versions of gqlgen should still work with dep.. Thoughts @vektah?

**Comment by vektah** [comment]
I regret semver :sweat_smile: 

I've already dropped the dep getting started docs in 0.11, the added surface area makes for a lot of work.

I guess we could gopkg.in, but that would break all of the mod users too, if they make direct references for things like error handling.

**Comment by han-so1omon** [comment]
One solution could be to use gopkg.in and check `GO111MODULE` variable from `go env`. If the user explicitly sets `GO111MODULE=off` then gqlgen can reference the gopkg.in. I don't know the overhead of gopkg.in, though.

**Comment by han-so1omon** [comment]
As a note, the reason that I am using godeps and not gomodules is because my app uses libcontainer, which can only be used with godeps at current due to a capitalization bug in the sirupsen/logrus dependency.

**Comment by han-so1omon** [comment]
My workaround for now is to have a symlink directory called v2 in the github.com/vektah/gqlparser directory

**Comment by john-m-liu** [comment]
Similar to @han-so1omon, we've been working around this by moving the directory itself so that it matches: https://github.com/evergreen-ci/evergreen/commit/d9dfade9c0cb72107084e3bc6f3e075f2e44d781

This fixes the import problem, but there's still the issue of the generated code not aliasing the github.com/vektah/gqlparser/v2 package (needed if not using gomod). We've also worked around it by modifying the template: https://github.com/evergreen-ci/evergreen/commit/b401cb2446764a414056b62995932f0366d6db00
