### ISSUE TITLE
Cannot install latest version of gqlgen using dep

### ISSUE THREAD

**Issue by marcenacp** [99designs/gqlgen#1108]
### What happened?

When trying to follow Prisma/gqlgen initial tutorial (found [here](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-GO-g201/)), I have an error when installing package.

### Minimal graphql.schema and models to reproduce

- In an empty folder, create a file `gqlgen.go`:

```
// +build ignore

package main

import "github.com/99designs/gqlgen/cmd"

func main() {
    cmd.Execute()
}
```

- Run `dep init`
- Error => `init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/vektah/gqlparser met constraints`

### versions
 - `gqlgen version`: Not yet installed (the error pops up when trying to install gqlgen)
 - `go version`: go version go1.12.4 darwin/amd64
 - dep or go modules: dep

**Comment by michaeloverton** [comment]
i have the same issue, which has led me down the path of converting my team's project to use modules, but there appear to be issues with the modules as well.

**Comment by marcenacp** [comment]
@michaeloverton Thanks for the hint, I'll try again with go modules.

**Comment by marcenacp** [comment]
@michaeloverton Go modules did the trick. I haven't encountered any other problem so far. What were the issues with the modules?
