### ISSUE TITLE
resolver cannot be generated

### ISSUE THREAD

**Issue by yuina1056** [99designs/gqlgen#1110]
### What happened?
resolver cannot be generated.

I added the schema to the sample code schema.
```
type Query {
  todos: [Todo!]!
  todo(id: ID!): Todo! // new schema.
}
```
The following error occurred:
```
% go run github.com/99designs/gqlgen                                            (git)-[error]
validation failed: packages.Load: test_go_graphql/interfaces/resolvers/root_resolver.go:25:60: cannot use &(queryResolver literal) (value of type *queryResolver) as graphql.QueryResolver value in return statement: missing method Todo
exit status 1
```

I am trying with the following repository.
https://github.com/yuina1056/go-graphql-sample

### What did you expect?
I want to generate a resolver.

### Minimal graphql.schema and models to reproduce
It is the same as the schema of the sample code.
```
type Query {
  todos: [Todo!]!
  todo(id: ID!): Todo! // new schema.
}
```

### versions
 - `gqlgen version`? : v0.11.4
 - `go version`? : 1.13.4
 - dep or go modules? : gomodules

**Comment by stuart-himmer-nacelle** [comment]
what was your solution?
