### ISSUE TITLE
Directives do not run on Objects

### ISSUE THREAD

**Issue by seaskyways** [99designs/gqlgen#1120]
### What happened?
I added a directive that is meant to provide some new values in the context and used this directive on a type for example Query. The directive function did not run.

### What did you expect?
The directive function should run and pass the related info in the context.

### Minimal graphql.schema and models to reproduce
```graphql
directive @provideLoaders on OBJECT
type Query @provideLoaders {
  hello: String!
}
```

`provideLoaders` will not be run when `hello` is queried.

### versions
 - `gqlgen version`? 0.11.3
 - `go version`? 1.14
 - dep or go modules? go modules

**Comment by dtrckd** [comment]
Hey,
the pulled request #1117 seems to have fixed this.

Nevertheless, I observed that the OBJECT directive still doesn't run if it is defined like this:

```
directive @provideLoaders on OBJECT
```

But do works when the directive is defined like this:

```
directive @provideLoaders on OBJECT|FIELD_DEFINITION
```

**Comment by ibantoo** [comment]
i cant log the object like your gave example

**Comment by dtrckd** [comment]
I am not sure of what you mean ?
