### ISSUE TITLE
Why does resolver with ID type cause generation?

### ISSUE THREAD

**Issue by milesalex** [99designs/gqlgen#1132]
Why does this resolver generate if I include the type `ID!` in a model?

```go
func (r *userResolver) ID(ctx context.Context, obj *model.User) (string, error) {
	panic(fmt.Errorf("not implemented"))
}
```

A model

```gql
type User {
  id: ID!
  name: String!
  email: String!
  admin: Boolean!
}
```

**Comment by danishsatkut** [comment]
@milesalex if the `model.User` type does not have `ID`(or `Id`) field or method, a resolver function will be generated, as gqlgen generated code (`generated.go`) has to call something to resolve the field.

**Comment by milesalex** [comment]
Got it. Thanks!
