### ISSUE TITLE
i don't have hanlder.GraphQL

### ISSUE THREAD

**Issue by YankeeTube** [99designs/gqlgen#1142]
### What happened?
![image](https://user-images.githubusercontent.com/34546950/78968814-750b0000-7b40-11ea-850a-04148dd7d712.png)

![image](https://user-images.githubusercontent.com/34546950/78968862-910ea180-7b40-11ea-900c-92ff9b52cb06.png)

how can i use handler.GraphQL or LimitingQuery ?

### versions
 - `gqlgen version`?  v0.11.3
 - `go version`? 1.14 windows/amd64
 - dep or go modules? go mod

**Comment by tyagip966** [comment]
Hi, @YankeeTube 
`github.com/99designs/gqlgen/handler`
inside this 'GraphQL' is deprecated.
Please use 
`handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}}))`
in place of
`handler.Graphql`

**Comment by YankeeTube** [comment]
@tyagip966 tk for your response.

I understood what you were talking about.
but Is there only the last way I mentioned to use LimitingQuery?
