### ISSUE TITLE
GraphQL playground bug in Google Cloud Function - error: Server cannot be reached

### ISSUE THREAD

**Issue by isuhendro** [99designs/gqlgen#1143]
### What happened?
Deployed it in Google Cloud Function

### What did you expect?
Playground works

### Actual Outcome
`Server cannot be reached`
![Screen Shot 2020-04-11 at 1 24 18 PM](https://user-images.githubusercontent.com/241914/79036152-fffb0180-7bf7-11ea-926c-1d2e830edf84.png)

### Root cause
The wrong URL - playground simply add `/query` to the base URL hence the full URL is `https://us-central1-iwan-specialty.cloudfunctions.net/query`
The correct URL - playground should add `/query` to the existing URL (of Cloud Function project) to get something like `https://us-central1-iwan-specialty.cloudfunctions.net/GraphQL/query`

**Comment by tyagip966** [comment]
Hi , @isuhendro 
Please have a look

![Screenshot (10)](https://user-images.githubusercontent.com/29175591/79044207-9394f800-7c21-11ea-9e60-407843d7fdbd.png)

Your **UPPER URL** is `https://us-central1-iwan-specialty.cloudfunctions.net/GraphQL`
and your **BELOW URL**  for **`query`** is
 **`https://us-central1-iwan-specialty.cloudfunctions.net/GraphQL/query`** 
**not `https://us-central1-iwan-specialty.cloudfunctions.net/query`**
I hope you'll get your mistak.
