### ISSUE TITLE
Introspection example is not working with 0.11.3

### ISSUE THREAD

**Issue by kazmerdome** [99designs/gqlgen#1149]
### What happened?
I tried to implement authentication based introspection in my project.

First, I tried to follow https://gqlgen.com/reference/introspection/ guide, but the demo code just threw this error:

`cannot use (func(ctx context.Context, next func(ctx context.Context) []byte) []byte literal) (value of type func(ctx context.Context, next func(ctx context.Context) []byte) []byte) as graphql.ResponseMiddleware value in argument to handler.RequestMiddleware`

I was not sure about the reason, maybe because of the handler.GraphQL function was deprecated.
Second time I tried to use handler.New() instead of handler.GraphQL(), but the documentation was not clear for implementing authentication based introspection.

### What did you expect?
Updated Introspection example for 0.11.3

### Minimal graphql.schema and models to reproduce
init project with https://gqlgen.com/reference/introspection guide

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? go1.14 linux/amd64
 - dep or go modules? go modules

**Comment by AndreySlashman** [comment]
@kazmerdome 
Please refer to https://gqlgen.com/recipes/migration-0.11/

You need to use **AroundOperations** handler instead of **RequestMiddleware** starting from v0.11

It seems that documentation is not yet fully updated

**Comment by sneko** [comment]
Hi,

There is an example in tests: https://github.com/99designs/gqlgen/blob/412a72fe26b093b08d27e90adf0390ad0ea0a7ea/codegen/testserver/introspection_test.go#L68-L72

But it's still a middleware runs each time, is there a way to disable it globally at start?

From what I understand according to:
https://github.com/99designs/gqlgen/blob/412a72fe26b093b08d27e90adf0390ad0ea0a7ea/codegen/testserver/introspection_test.go#L16-L26

By removing the GET method handler I prevent the introspection. It's not very clear it will only disable this and nothing else.

**Comment by kazmerdome** [comment]
@AndreySlashman  thank you for your response!

Based on your comment finally i have a fully working version.


	...
    queryHandler := handler.New(gqlgen.NewExecutableSchema(config))
	queryHandler.AroundOperations(func(ctx context.Context, next graphql.OperationHandler) graphql.ResponseHandler {
		rc := graphql.GetOperationContext(ctx)
		if playgroundPassword == c.GetSecret("PLAYGROUND_PASSWORD") {
			rc.DisableIntrospection = false
		} else {
			rc.DisableIntrospection = true
		}
		return next(ctx)
	})

    e.POST("/query", echo.WrapHandler(dataloader.DataLoaderMiddleware(queryHandler)))
    ...


@sneko i think so can use handler middleware if you don't need action based introspection
