### ISSUE TITLE
How to test authorization with client?

### ISSUE THREAD

**Issue by weeee9** [99designs/gqlgen#1157]
From the [authentication recipes](https://gqlgen.com/recipes/authentication/) that I know you can get the user's info from context and do auth check, this works fine in real api.

But in unit tests, I currently can't find a way to test my resolver that with the auth check, I tried to `AddHeader("authorization", "Bearer xxxx")` to the client options but it seems but still can't get user's info from resolver context.

here's mockup test:
```golang
func TestGetPost(t *testing.T) {

	cli := client.New(handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &Resolver{}})))

	var resp struct {
		Post struct {
			ID    int64
			Title string
			Text  string
		}
	}

	err := cli.Post(`{
		getPost(id: 1) {
			id
			title
			text
		}
	}`, &resp, client.AddHeader("authorization", "Bear xxxx"))

	assert.NoError(t, err)
}
```

and the result will get:
`[{"message":"you are not login","path":["getPost"]}]`

is there anything I missed ?

**Comment by Hamzsd** [comment]
How did you overcome this? @weeee9

**Comment by geertjanvdk** [comment]
(this could be moved to discussions)

`AddHeader` doesn't look like working well, though looking at the source, it is what we would need to use. However, you can add a context to the client directly by introduction a new functional option, for example:

```go
func addTestContext(ctx context.Context) client.Option {
	return func(req *client.Request) {
		req.HTTP = req.HTTP.WithContext(ctx)
	}
}
```

This you can then use, after populating the context, like this:

```go
gqlClient := client.New(yourHandler)

ctx := context.Background()
// add your values to context

gqlClient(yourQuery, &yourDest, addTestContext(ctx))
```

The above is really for unittesting the resolvers. If doing blackbox testing, you would need to skip the gqlgen client and simply do it yourself (start server in goroutine; using Go's HTTP client).
