### ISSUE TITLE
Gqlgen generate errors when go.mod is saved in Windows environment (possible different carriage return character)

### ISSUE THREAD

**Issue by thienohs** [99designs/gqlgen#1158]
### What happened?
When running gqlgen on **Windows**, encounter error:
```
build object definition: unable to find type example_gqlgen_windows_issue
build input definition: unable to find type example_gqlgen_windows_issue
```

or sometime:
```
/modules/example/gql/models)is not in GOROOT (/usr/local/go/src/example_gqlgen_windows_issue
/modules/example/gql/resolvers/generated)is not in GOROOT (/usr/local/go/src/example_gqlgen_windows_issue
/modules/example/gql)is not in GOROOT (/usr/local/go/src/example_gqlgen_windows_issue
exit status 1
```

**Because** go.mod have special (possible carriage return) character when define module
If copy the go.mod from Mac, it will have no problem.

### What did you expect?
Generate graphql work as normal on Windows as it is on Mac using go modules without error

### Minimal graphql.schema and models to reproduce
Please use the repo here with instruction on how to reproduce
https://github.com/thienohs/example_gqlgen_windows_issue

### versions
 - `gqlgen version`-> 0.11.3
 - `go version`? -> 1.14
 - dep or go modules? -> go modules

**Comment by gabrielcuvillier** [comment]
Hello, 
I stumbled on the same issue, but additionally, I had some panic at random times. 

Thanks for the proposed workaround. Actually moving the go.mod to LF solves the crashes or errors

**Comment by Igorpollo** [comment]
same error here...

**Comment by conjohnerton** [comment]
Kinda getting the same error but only with the resolver gen.
