### ISSUE TITLE
Gqlgen panics when I tried to create []byte scalar type with runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jokicnikola07** [99designs/gqlgen#1159]
### What happened?
I created scalar type Bytes as []byte type and wrote methods for marhaling and unmarshaling.
Stack trace is:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88ecbc]
> 
> goroutine 1 [running]:
> github.com/99designs/gqlgen/codegen/config.(*TypeReference).IsPtr(...)
> github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc000715a38, 0xc000598300, 0xc00031d570, 0xc000638f00, 0x0, 0x0)
> github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc000715a38, 0xc000313380, 0x8, 0x8, 0x9)
> github.com/99designs/gqlgen/codegen.BuildData(0xc0002bc000, 0xadef40, 0xec64b8, 0x0)
> github.com/99designs/gqlgen/api.Generate(0xc0002bc000, 0x0, 0x0, 0x0, 0x0, 0xc000296380)
> github.com/99designs/gqlgen/cmd.glob..func1(0xc000296380, 0x3, 0x4)
> github.com/urfave/cli/v2.(*Command).Run(0xe90060, 0xc000296200, 0x0, 0x0)
> github.com/urfave/cli/v2.(*App).RunContext(0xc0002a0180, 0xaea3a0, 0xc0000b8030, 0xc0000a2150, 0x3, 0x3, 0x0, 0x0)
> github.com/urfave/cli/v2.(*App).Run(...)
> github.com/99designs/gqlgen/cmd.Execute()
> main.main()
> exit status 2

### Expected Behaviour
I wanted to create byte slice scalar type

### Aditional info

```
scalar Bytes
type Query {
	getProfilePicture: Bytes!
}
```
Schema:
```
schema:
- schema.graphql
models:
  Bytes:
    model:
      - github.com/me/myrepositoryname/types.Bytes
```
types.go
```
package types

import (
	"fmt"
	"io"

	"github.com/99designs/gqlgen/graphql"
)

func MarshalBytes(b []byte) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = fmt.Fprintf(w, "%q", string(b))
	})
}

func UnmarshalBytes(v interface{}) ([]byte, error) {
	switch v := v.(type) {
	case string:
		return []byte(v), nil
	case *string:
		return []byte(*v), nil
	case []byte:
		return v, nil
	default:
		return nil, fmt.Errorf("%T is not []byte", v)
	}
}
```

### versions
 - `gqlgen version`? 0.11.3
 - `go version`? 1.13
 - dep or go modules? go modules

**Comment by songmink** [comment]
I got a similar error, "nil pointer dereferences".
Check this [Fixing the Billion Dollar Mistake in Go by Borrowing From Rust](https://dzone.com/articles/fixing-the-billion-dollar-mistake-in-go-by-borrowi). It might help you to fix the error. In my case, I implemented it on the resolver.go instead of **scalar**.

**Comment by frederikhors** [comment]
Nope.
