### ISSUE TITLE
Gqlgen init unable to find type

### ISSUE THREAD

**Issue by dcam0050** [99designs/gqlgen#1162]
### What happened?
When following the getting started doc:
I create an empty dir
run `go mod init repo_name`
run `go get github.com/99designs/gqlgen`
and then I get the following errors:
```
go run github.com/99designs/gqlgen init
modelgen: unable to find type github.com/99designs/gqlgen/graphql.ID
```
or
```
gqlgen init
modelgen: unable to find type github.com/99designs/gqlgen/graphql.String
```

### What did you expect?
Expected init to complete successfully or at least yield the same error when running in different ways

### Minimal graphql.schema and models to reproduce
Using the generated schema:
```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

### versions
 - `gqlgen version = 0.11.3`
 - `go version = 1.14.2`
 - dep or go modules - Using go modules

**Comment by dcam0050** [comment]
Confirmed issue not present in `gqlgen version v0.11.2`

**Comment by denysvitali** [comment]
```
(⎈ |adm@ded2:traefik)dvitali@denvit-ws1:denysvitali/konn $ gqlgen init
modelgen: unable to find type github.com/99designs/gqlgen/graphql.ID

Exec "go run ./server.go" to start GraphQL server
(⎈ |adm@ded2:traefik)dvitali@denvit-ws1:denysvitali/konn $ gqlgen version                         
v0.11.2
```

I'm able to reproduce the issue in both 0.11.3 and 0.11.2 :thinking: 

Edit:
I'm dumb, I forgot to run `go mod init`, now it does work

**Comment by mittalyashu** [comment]
I ran the `init` command and got this error message

```
Creating gqlgen.yml
Creating graph/schema.graphqls
Creating server.go
Generating...
modelgen: unable to find type: github.com/99designs/gqlgen/graphql.String
```

gqlgen v0.17.66

**Comment by vijayarun00100** [comment]
add the below code in go.mod 

require (
	github.com/99designs/gqlgen v0.17.45
	github.com/jackc/pgx/v5 v5.7.6
)

and the run  : go mod tidy 

if go mod tidy removes the updated code then type go get github.com/99designs/gqlgen 

then update the code and then run : go  mod tidy

finally type gqlgen generate
