### ISSUE TITLE
Add comments through generated code

### ISSUE THREAD

**Issue by iamclaytonray** [99designs/gqlgen#118]
### Expected Behaviour
`gqlgen` strips away comments. Is this intentional? If not, is this a bug or a feature to be added in the future?

```go
// This is a User
type User struct {
  FirstName: string
  ID: string
}
```

### Actual Behavior
```go
type User struct {
  FirstName: string
  ID: string
}
```

### Minimal graphql.schema and models to reproduce
```gql
# This is a User
type User {
  firstName: String!
  id: ID!
}
```

**Comment by vektah** [comment]
Not intentional, it just hasn't been built yet. Model generation is is pretty basic at the moment.

**Comment by iamclaytonray** [comment]
Cool. I'll play around with this

**Comment by andrioid** [comment]
@iamclaytonray Any progress?
@vektah Can you elaborate on what needs to be done for this to work? Maybe I can take a look.

**Comment by vektah** [comment]
It should be pretty straightforward, all the descriptions have been parsed they just aren't being put in the generated models.

Enums do though, so heres an example https://github.com/99designs/gqlgen/blob/master/codegen/templates/models.gotpl#L31


The example provided isn't quite right any more, because descriptions are strings, not comments, so it should be:
```
"""This is a User"""
type User {
  firstName: String!
  id: ID!
}
```

**Comment by andrioid** [comment]
Sorry to bother you again. But does this mean that if you're using your own models and models.go is not being generated, that the descriptions will not be populated?

**Comment by vektah** [comment]
This issue is only for adding comments to the generated code, descriptions should already be exposed via introspection. If they arent showing up its probably because you're using comments instead of strings. 
```
# This is a comment, it wont do anything
type User {

"""This is a description, it will be exposed via introspection and maybe added to generated code"""
type User {
```
