### ISSUE TITLE
Few/no documentation or examples for `resolver` tag

### ISSUE THREAD

**Issue by han-so1omon** [99designs/gqlgen#1182]
### What happened?
Following [tutorial](https://www.youtube.com/watch?v=cphghdh1DoY&t=603s) for working with gqlgen. Upon placing my resolvers in `graph/resolver.go` and running `go run github.com/99designs/gqlgen generate`, I receive a bunch of "... already declared for type Resolver{}". This is also mentioned in #1168 

### What did you expect?
I expected a clean generation.

### Minimal graphql.schema and models to reproduce
I have provided some boilerplate below, but I will tell you that the issue is that the resolver definitions are copied into the same package in which they are already defined. E.g. using the default gqlgen.yml file, the resolver tag causes all of these "... already declared" validation errors. Taking out/commenting this tag solves the problem

```
# gqlgen.yml fragment
...
resolver:
  layout: follow-schema
  dir: graph
  package: graph
...
```

```
# schema.graphqls fragment
...
type User {
  id: ID!
  projects: [Project!]!
}

type Project {
  id: ID!
}

type Query {
  projects: [Project!]!
}
...
```

```
// Models
type User struct {
  ID string `json:"id"`
  Projects []*Project `json:"projects"`
}
type Project struct {
  ID string `json:"id"`
}
```

```
// Resolver manual definitions
var projects = []*Project{
  {
    ID: "1",
  }
}
type Resolver struct{}
func (r *Resolver) Query() QueryResolver{
  return &queryResolver{r}
}
type queryResolver struct{ *Resolver }
func (q *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
  return projects, nil
}
```

### versions
 - `gqlgen version` v0.11.3
 - `go version` go1.14.2
 - dep or go modules? only defaults

**Comment by frederikhors** [comment]
Nope, stale.
