### ISSUE TITLE
Make the documentation on plugins easier to understand

### ISSUE THREAD

**Issue by tsauvajon** [99designs/gqlgen#1186]
### What happened?

I tried to write a plugin and don't understand how to register it.

### What did you expect?

I would like the documentation to include all the steps needed to write a plugin and register it.  
Currently there's only https://gqlgen.com/reference/plugins/ .

Where to put this file? How to call it?  

- It doesn't look like I should put it in [the configuration](https://gqlgen.com/config/)
- I assume I shouldn't call `go run ./my/plugin` because of the `// +build ignore` directive
- `gqlgen --help` doesn't give me any indication

I assume I have to use `go generate` somehow: some help in the documentation would help a lot!

### Minimal graphql.schema and models to reproduce

n/a but the code looks like:

```go
func main() {
	cfg, _ := gqlconf.LoadConfigFromDefaultLocations()
        api.Generate(cfg,
		api.AddPlugin(MyPlugin()),
	)
}

func mutateHook(b *modelgen.ModelBuild) *modelgen.ModelBuild {
	fmt.Println("mutate!")
	return b
}

func MyPlugin() *modelgen.Plugin {
	return &modelgen.Plugin{
		MutateHook: mutateHook,
	}
}

```

In the code above, `mutateHook` never seems to be called whenever I try to call main (with or without `go generate`.

EDIT: after more trial and error, I got to a working version:
```go
api.Generate(cfg,
	api.NoPlugins(),
	api.AddPlugin(MyPlugin()),
)
```

Why is that needed?

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? 1.14.2
 - dep or go modules?  Go modules

**Comment by frederikhors** [comment]
@tsauvajon can I ask you if you use the code from https://gqlgen.com/recipes/modelgen-hook/ is the generator generating resolvers files?

Thanks.

**Comment by malaDev** [comment]
can anyone give some more insights here?
so far I was not able to generate codes using this plugins recipe, nothing in docs says how to do so

**Comment by malaDev** [comment]
For those one stucking on this like I did

you should have something like `go:generate go run github.com/99designs/gqlgen` somewhere for eg. in ./graph/resolver.go
now add a new file `generate.go` for eg in same folder and flag it with `// +build ignore`, this should be your entrypoint for codes generation, see [https://gqlgen.com/reference/plugins/](https://gqlgen.com/reference/plugins/.) 
then just change go generate to run that new file

```diff
- go:generate go run github.com/99designs/gqlgen
+ go:generate go run generate.go
```

**Comment by aleybovich** [comment]
> you should have something like `go:generate go run github.com/99designs/gqlgen` somewhere for eg. in ./graph/resolver.go 

Could you please elaborate on this? I don't have `//go:generate go run github.com/99designs/gqlgen` in any of the graph files

**Comment by DavidJS01** [comment]
> For those one stucking on this like I did
> 
> you should have something like `go:generate go run github.com/99designs/gqlgen` somewhere for eg. in ./graph/resolver.go now add a new file `generate.go` for eg in same folder and flag it with `// +build ignore`, this should be your entrypoint for codes generation, see [https://gqlgen.com/reference/plugins/](https://gqlgen.com/reference/plugins/.) then just change go generate to run that new file
> 
> ```diff
> - go:generate go run github.com/99designs/gqlgen
> + go:generate go run generate.go
> ```

Thank you!
