### ISSUE TITLE
Upload file causes memory leak

### ISSUE THREAD

**Issue by arkhvoid** [99designs/gqlgen#1193]
### What happened?
After a file being uploaded, memory usage is dramatically bumped.
### Minimal graphql.schema and models to reproduce
`type Mutation {
    addVideo(video: Upload!): Video
}`
### versions
 - `v0.11.3`
 - `1.14.2`
 - basic net/http only
### Resolver
`func (r *mutationResolver) AddVideo(ctx context.Context, video graphql.Upload) (*model.Video, error) {
	return nil, nil
}`
### pprof
I have try to use [net/http/pprof](https://golang.org/pkg/net/http/pprof/) to check memory usage, and this is some of the result of them.
- heap

> (pprof) top
Showing nodes accounting for 768MB, 99.80% of 769.50MB total
Dropped 13 nodes (cum <= 3.85MB)
Showing top 10 nodes out of 16
      flat  flat%   sum%        cum   cum%
     768MB 99.80% 99.80%      768MB 99.80%  bytes.makeSlice
         0     0% 99.80%      768MB 99.80%  bytes.(*Buffer).ReadFrom
         0     0% 99.80%      768MB 99.80%  bytes.(*Buffer).grow
         0     0% 99.80%      768MB 99.80%  github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
         0     0% 99.80%      768MB 99.80%  github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
         0     0% 99.80%      768MB 99.80%  io.Copy (inline)
         0     0% 99.80%      768MB 99.80%  io.CopyN
         0     0% 99.80%      768MB 99.80%  io.copyBuffer
         0     0% 99.80%      768MB 99.80%  main.Header.func1
         0     0% 99.80%      768MB 99.80%  mime/multipart.(*Reader).ReadForm (inline)

- alloc

> (pprof) top
Showing nodes accounting for 2GB, 99.83% of 2GB total
Dropped 32 nodes (cum <= 0.01GB)
Showing top 10 nodes out of 16
      flat  flat%   sum%        cum   cum%
       2GB 99.83% 99.83%        2GB 99.83%  bytes.makeSlice
         0     0% 99.83%        2GB 99.83%  bytes.(*Buffer).ReadFrom
         0     0% 99.83%        2GB 99.83%  bytes.(*Buffer).grow
         0     0% 99.83%        2GB 99.81%  github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
         0     0% 99.83%        2GB 99.81%  github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
         0     0% 99.83%        2GB 99.81%  io.Copy (inline)
         0     0% 99.83%        2GB 99.81%  io.CopyN
         0     0% 99.83%        2GB 99.81%  io.copyBuffer
         0     0% 99.83%        2GB 99.81%  main.Header.func1
         0     0% 99.83%        2GB 99.81%  mime/multipart.(*Reader).ReadForm (inline)

I have tried to upload different video (from 50mb to 1gb), both will cause the problem, just the different of size that memory they consumed.

Keep uploading the same or other file without restart the program will even higher the memory usage.

In the client side, I am using apollo with [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client).

**Comment by RichardLindhout** [comment]
Are using same server side code as https://github.com/99designs/gqlgen/blob/master/example/fileupload/server/server.go or customized?

**Comment by arkhvoid** [comment]
I tried to use the [example code](https://github.com/99designs/gqlgen/blob/master/example/fileupload/) with `srv.AddTransport(transport.MultipartForm{
    MaxMemory:     32 * mb,
                MaxUploadSize: 1000 * mb,
        })` to higher the max upload size, but sadly, the problem is still exist.

### pprof
- heap

> (pprof) tree
Showing nodes accounting for 1.50GB, 100% of 1.50GB total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                            1.50GB   100% |   bytes.(*Buffer).grow
    1.50GB   100%   100%     1.50GB   100%                | bytes.makeSlice
----------------------------------------------------------+-------------
                                            1.50GB   100% |   io.copyBuffer
         0     0%   100%     1.50GB   100%                | bytes.(*Buffer).ReadFrom
                                            1.50GB   100% |   bytes.(*Buffer).grow
----------------------------------------------------------+-------------
                                            1.50GB   100% |   bytes.(*Buffer).ReadFrom
         0     0%   100%     1.50GB   100%                | bytes.(*Buffer).grow
                                            1.50GB   100% |   bytes.makeSlice
----------------------------------------------------------+-------------
                                            1.50GB   100% |   net/http.(*ServeMux).ServeHTTP
         0     0%   100%     1.50GB   100%                | github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
                                            1.50GB   100% |   github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
----------------------------------------------------------+-------------
                                            1.50GB   100% |   github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
         0     0%   100%     1.50GB   100%                | github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
                                            1.50GB   100% |   net/http.(*Request).ParseMultipartForm
----------------------------------------------------------+-------------
                                            1.50GB   100% |   io.CopyN (inline)
         0     0%   100%     1.50GB   100%                | io.Copy
                                            1.50GB   100% |   io.copyBuffer
----------------------------------------------------------+-------------
                                            1.50GB   100% |   mime/multipart.(*Reader).readForm
         0     0%   100%     1.50GB   100%                | io.CopyN
                                            1.50GB   100% |   io.Copy (inline)
----------------------------------------------------------+-------------
                                            1.50GB   100% |   io.Copy
         0     0%   100%     1.50GB   100%                | io.copyBuffer
                                            1.50GB   100% |   bytes.(*Buffer).ReadFrom
----------------------------------------------------------+-------------
                                            1.50GB   100% |   net/http.(*Request).ParseMultipartForm (inline)
         0     0%   100%     1.50GB   100%                | mime/multipart.(*Reader).ReadForm
                                            1.50GB   100% |   mime/multipart.(*Reader).readForm
----------------------------------------------------------+-------------
                                            1.50GB   100% |   mime/multipart.(*Reader).ReadForm
         0     0%   100%     1.50GB   100%                | mime/multipart.(*Reader).readForm
                                            1.50GB   100% |   io.CopyN
----------------------------------------------------------+-------------
                                            1.50GB   100% |   github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
         0     0%   100%     1.50GB   100%                | net/http.(*Request).ParseMultipartForm
                                            1.50GB   100% |   mime/multipart.(*Reader).ReadForm (inline)
----------------------------------------------------------+-------------
                                            1.50GB   100% |   net/http.serverHandler.ServeHTTP
         0     0%   100%     1.50GB   100%                | net/http.(*ServeMux).ServeHTTP
                                            1.50GB   100% |   github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
----------------------------------------------------------+-------------
         0     0%   100%     1.50GB   100%                | net/http.(*conn).serve
                                            1.50GB   100% |   net/http.serverHandler.ServeHTTP
----------------------------------------------------------+-------------
                                            1.50GB   100% |   net/http.(*conn).serve
         0     0%   100%     1.50GB   100%                | net/http.serverHandler.ServeHTTP
                                            1.50GB   100% |   net/http.(*ServeMux).ServeHTTP
----------------------------------------------------------+-------------

- allocs

> (pprof) tree
Showing nodes accounting for 2GB, 99.88% of 2GB total
Dropped 18 nodes (cum <= 0.01GB)
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                               2GB   100% |   bytes.(*Buffer).grow
       2GB 99.88% 99.88%        2GB 99.88%                | bytes.makeSlice
----------------------------------------------------------+-------------
                                               2GB   100% |   io.copyBuffer
         0     0% 99.88%        2GB 99.88%                | bytes.(*Buffer).ReadFrom
                                               2GB   100% |   bytes.(*Buffer).grow
----------------------------------------------------------+-------------
                                               2GB   100% |   bytes.(*Buffer).ReadFrom
         0     0% 99.88%        2GB 99.88%                | bytes.(*Buffer).grow
                                               2GB   100% |   bytes.makeSlice
----------------------------------------------------------+-------------
                                               2GB   100% |   net/http.(*ServeMux).ServeHTTP
         0     0% 99.88%        2GB 99.88%                | github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
                                               2GB   100% |   github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
----------------------------------------------------------+-------------
                                               2GB   100% |   github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
         0     0% 99.88%        2GB 99.88%                | github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
                                               2GB   100% |   net/http.(*Request).ParseMultipartForm
----------------------------------------------------------+-------------
                                               2GB   100% |   io.CopyN (inline)
         0     0% 99.88%        2GB 99.88%                | io.Copy
                                               2GB   100% |   io.copyBuffer
----------------------------------------------------------+-------------
                                               2GB   100% |   mime/multipart.(*Reader).readForm
         0     0% 99.88%        2GB 99.88%                | io.CopyN
                                               2GB   100% |   io.Copy (inline)
----------------------------------------------------------+-------------
                                               2GB   100% |   io.Copy
         0     0% 99.88%        2GB 99.88%                | io.copyBuffer
                                               2GB   100% |   bytes.(*Buffer).ReadFrom
----------------------------------------------------------+-------------
                                               2GB   100% |   net/http.(*Request).ParseMultipartForm (inline)
         0     0% 99.88%        2GB 99.88%                | mime/multipart.(*Reader).ReadForm
                                               2GB   100% |   mime/multipart.(*Reader).readForm
----------------------------------------------------------+-------------
                                               2GB   100% |   mime/multipart.(*Reader).ReadForm
         0     0% 99.88%        2GB 99.88%                | mime/multipart.(*Reader).readForm
                                               2GB   100% |   io.CopyN
----------------------------------------------------------+-------------
                                               2GB   100% |   github.com/99designs/gqlgen/graphql/handler/transport.MultipartForm.Do
         0     0% 99.88%        2GB 99.88%                | net/http.(*Request).ParseMultipartForm
                                               2GB   100% |   mime/multipart.(*Reader).ReadForm (inline)
----------------------------------------------------------+-------------
                                               2GB   100% |   net/http.serverHandler.ServeHTTP
         0     0% 99.88%        2GB   100%                | net/http.(*ServeMux).ServeHTTP
                                               2GB 99.90% |   github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP
----------------------------------------------------------+-------------
         0     0% 99.88%        2GB   100%                | net/http.(*conn).serve
                                               2GB   100% |   net/http.serverHandler.ServeHTTP
----------------------------------------------------------+-------------
                                               2GB   100% |   net/http.(*conn).serve
         0     0% 99.88%        2GB   100%                | net/http.serverHandler.ServeHTTP
                                               2GB   100% |   net/http.(*ServeMux).ServeHTTP
----------------------------------------------------------+-------------

Noted: I tested with 1gb file

**Comment by RichardLindhout** [comment]
Maybe for big files GraphQL is not really an option but I'm not sure how well it is implemented in the spec itself. Are you using ioutil.ReadAll or file.Open?

If you are using file maybe you forget do defer file.Close() if your server code is diffent maybe share something.

**Comment by RichardLindhout** [comment]
I'm curious, I just implemented the graphql upload but I don't have the use-case of very big files a.t.m.

**Comment by arkhvoid** [comment]
I have changed line 67 of [/graphql/handler/transport/http_form.go](https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_form.go)
from
`if err = r.ParseMultipartForm(f.maxUploadSize()); err != nil {`
to
`if err = r.ParseMultipartForm(f.maxMemory()); err != nil {`
and it fixed to me

If I understand correctly, ` func (r *Request) ParseMultipartForm(maxMemory int64) error` should pass the max memory as argument instead of max request body size.

Can you help me to check whether I'm doing something wrong with this?

Again, thanks for your reply.

**Comment by lwc** [comment]
fixed via #1246
