### ISSUE TITLE
Ability to omit nil/empty fields from response

### ISSUE THREAD

**Issue by bhaskarsaraogi** [99designs/gqlgen#1194]
### What happened?
Nil/empty fields gets returned in json response as null

### What did you expect?
To skip the fields from response and not increase the response size unnecessarily 

If gql marshaler, starts honouring `omitempty` tags on generated models that should be enough

As that would give me the flexibility to decide which fields to omit, can have a custom modelgen to decide which fields I want omitempty to be added(so that fields which have actually value as 0 or "" doesn't get skipped as well)

**Comment by frederikhors** [comment]
Please wait, stale.

**Comment by frederikhors** [comment]
@bhaskarsaraogi did you find a solution?

**Comment by talgat-ruby** [comment]
@frederikhors, @bhaskarsaraogi https://github.com/99designs/gqlgen/discussions/1943#discussioncomment-2110714
