### ISSUE TITLE
Incorrect handling of Float64: NaN, +Inf and -Inf

### ISSUE THREAD

**Issue by adrianduke** [99designs/gqlgen#1195]
### What happened?
I encoded a `float64` that was set to `math.Inf(1)`, the outputted JSON is invalid:

```json
{
  "someKey": +Inf,
}
```

### What did you expect?
As per Go's `json.Marshal()` I'd expect an error that I can't encode `+Inf`, `-Inf` or `NaN`:

- https://play.golang.org/p/3V_qBPlAeR-
- https://golang.org/src/encoding/json/encode.go?s=17629:17751#L573

JSON doesn't support infinity or nan, see:

- https://www.json.org/
- https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

### Minimal graphql.schema and models to reproduce

```graphql
type FloatExample {
  myFloat: Float
}
```

```go
func NewFloatExample(f float64) *FloatExample {
  return &FloatExample{
    MyFloat: f,
  }
}

type FloatExample struct {
  MyFloat float64
}

NewFloatExample(math.Inf(1))
NewFloatExample(math.Inf(-1))
NewFloatExample(math.NaN())
```

set `myFloat` to either `math.Inf(1)`, `math.Inf(-1)` or `math.NaN()`.

### versions
 - `gqlgen version`? **v0.10.1**
 - `go version`? **go1.13.4**
 - dep or go modules? **go modules**

**Comment by frederikhors** [comment]
Nope.

**Comment by frederikhors** [comment]
No
