### ISSUE TITLE
Mapping between inconsistent Go and GraphQL enums does not fail at `gqlgen generate`

### ISSUE THREAD

**Issue by kkom** [99designs/gqlgen#1199]
### What happened?

The `gqlgen generate` step succeeded, despite the mapped Go "enum" not having the fields declared in the GraphQL schema.

Passing a value of that enum subsequently failed at runtime:

```
"message": "Expected type FooGraphQL!, found a. Did you mean the enum value aa?",
```

### What did you expect?

I expected `gqlgen generate` to fail with an error message.

### Minimal graphql.schema and models to reproduce

relevant bits below

existing Go type:

```
// FooGo is a Go enum.
type FooGo string

// FooGo values.
const (
	FooGoA FooGo = "a"
	FooGoB FooGo = "b"
)

func (s FooGo) String() string {
	return string(s)
}

// FooGoValidator is a validator
func FooGoValidator(s FooGo) error {
	switch s {
	case FooGoA, FooGoB:
		return nil
	default:
		return fmt.Errorf("invalid enum value for foogo field: %q", s)
	}
}
```

relevant `gqlgen.yml` part:

```
models:
  FooGraphQL:
    model:
      - api/enums.FooGo
```

relevant `schema.graphqls` part:

```
enum FooGraphQL {
  aa
  bb
}
```

### versions
 - `gqlgen version`? `v0.11.3`
 - `go version`? `1.14`
 - dep or go modules? enums are generated using `github.com/facebookincubator/ent v0.2.1`

**Comment by frederikhors** [comment]
Nope.
