### ISSUE TITLE
Vulnerability in websocket library dependency

### ISSUE THREAD

**Issue by jamesjwarren** [99designs/gqlgen#1201]
### What happened?

This module is using an outdated version of the `github.com/gorilla/websocket` module which has a known vulnerability. Running [nancy](https://github.com/sonatype-nexus-community/nancy) reports the following vulnerability from the OSS index:

> pkg:golang/github.com/gorilla/websocket@1.2.0  [Vulnerable]   1 known vulnerabilities affecting installed version
>
> CWE-190: Integer Overflow or Wraparound
The software performs a calculation that can produce an integer overflow or wraparound, when the logic assumes that the resulting value will always be larger than the original value. This can introduce other weaknesses when the calculation is used for resource management or execution control.
>
> ID:5f259e63-3efb-4c47-b593-d175dca716b0
> Details:https://ossindex.sonatype.org/vuln/5f259e63-3efb-4c47-b593-d175dca716b0

### What did you expect?

No known vulnerabilities in dependencies.

### versions
 - `gqlgen version` v0.11.3
 - `go version` 1.14.3
 - go modules

**Comment by mtibben** [comment]
Fixed in #1207
