### ISSUE TITLE
Null input for slice should convert to nil rather than a empty slice 

### ISSUE THREAD

**Issue by NateScarlet** [99designs/gqlgen#1203]
### What happened?

gqlgen always make a slice if field is set, even it set to null.

https://github.com/99designs/gqlgen/blob/0eef2fe2cf5123990844a6c2bbb2418b044df1e6/codegen/type.gotpl#L20-L27

https://github.com/99designs/gqlgen/issues/1023 mentioned this as a question, but i believe this is a bug.

### What did you expect?

got nil for fields that set to null.

### Minimal graphql.schema and models to reproduce

```gql
type Item {
  name: String!
}

type Query{
   items(name: [String!]): [Item!]
}
```
```gql
query {
  items(name: null) {
    name  
  }
}
```

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? 1.14
 - dep or go modules? go modules

**Comment by lwc** [comment]
Fixed via: https://github.com/99designs/gqlgen/pull/1242
