### ISSUE TITLE
Error while running gqlgen

### ISSUE THREAD

**Issue by OlegMoshkovich** [99designs/gqlgen#1211]
### What happened?
When I run  gqlgen, previously generated files are deleted, then I get an error
internal error: nil Pkg importing "context" from "gitlab.com/outerlabs/panorama/data/presenter"

I tried to find the answer to this error but cannot find anything of use. 
Can you please help?
### What did you expect?
I expected the files to be regenerated.

### Minimal graphql.schema and models to reproduce
type Panel {
  id: String!
  frame: Frame!
  edge: Edge
  isVertical: Boolean!
  isActive: Boolean!
  isRoot: Boolean!
  material: Material
  materialProduct: String
}

### versions
 - `gqlgen version` - 0.10.02? 
 - `go version` - go1.14.1?
 - dep or go modules?

**Comment by Lilahamstern** [comment]
When you run the gqlgen. If an error comes up when it tries to validate the code the generated file wont be created.

Hard to say what problem you have, but I guess it have todo with import conflict of context or some other import of package `gitlab.com/outerlabs/panorama/data/presenter`
