### ISSUE TITLE
How to receive changes from other services?

### ISSUE THREAD

**Issue by zhivulinal** [99designs/gqlgen#1216]
I want to use a web socket to modify data on a site. This data comes from other services. But I can’t understand how to do this.

**Comment by ddouglas** [comment]
Right now I am porting a legacy php site to Go using VueJS and Golang. There is one page on the legacy site that is updated every few seconds by just making an HTTP Request every 2 or 3 seconds. When I port this page, I am going to have a cron do the dirty work in the background and push the changes to a Redis PubSub. In GQLGen, I am going to be listening for messages on that PubSub and when I get a new message, I'll push it down the subscription socket. I don't have an code for you, but this is one way of doing it across services. Hope this helps.

**Comment by ddouglas** [comment]
Here is the legacy site and page for reference

https://zkillboard.com/ztop/

**Comment by lwc** [comment]
gqlgen is only responsible for the subscription-websocket handling, getting data into your resolvers is up to you, and could come from many sources, such as grpc, redis pubsub, aws services such as sqs, sns, eventbridge etc.

As @ddouglas mentions, even a polling loop making http calls in your gqlgen server would work - we're successfully running many subscriptions this way.
