### ISSUE TITLE
Type as field in a model, what to do?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1219]
If I have a model like this:

```go
type Player struct {
  Kind  PlayerType
}

type PlayerType int

const (
  Zombie PlayerType = iota
  Human
  Dog
)
```

and a schema like this:

```graphql
type Player {
  kind: Int!
}
```

it generates method in resolver for `Kind`:

```go
func (r *playerResolver) Kind(ctx context.Context, obj *Player) (int, error) {
  panic(fmt.Errorf("not implemented"))
}
```

but `PlayerType` is just a new type based on `int`.

How to fix this?

I need to write something in `config.yml`?

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? go1.14.3 windows/amd64
 - dep or go modules? go mod

**Comment by jufemaiz** [comment]
I think I can jump in on this (and happy to be told that this isn't quite correct).

```go
func (r *playerResolver) Kind(ctx context.Context, obj *Player) (int, error) {
  return int(obj.Kind), nil
}
```

Because `PlayerType` is a specific type based on `int` it still needs to be cast as one.

**Comment by lwc** [comment]
One solution would be to create a scalar type on the graphql side and then bind that to your go type.

see https://github.com/99designs/gqlgen/tree/master/example/scalars for examples of this.

**Comment by jufemaiz** [comment]
That's probably a neater solution right there @lwc!

**Comment by frederikhors** [comment]
Thanks for your answers.
