### ISSUE TITLE
An error in  [go run github.com/99designs/gqlgen generate ]

### ISSUE THREAD

**Issue by HenryStreeter** [99designs/gqlgen#1220]
### What happened?
when I go run github.com/99designs/gqlgen generate ， Tip me : 
validation failed: packages.Load: -: package XXX/graph/model is not in GOROOT (C:\Go\src\XXX\graph\model)

### What did you expect?
what should I do ? I don`t know how to solve it
### versions
 - `gqlgen version`?   v0.11.3
 - `go version`?  1.14
 - dep or go modules? go modules

**Comment by HenryStreeter** [comment]
I solve it...    
  - graphqls/*.graphql
The right is    - graphqls/*.graphqls

**Comment by Igorpollo** [comment]
same error here, help...
This only created the graph/schena.graphqls
