### ISSUE TITLE
Cannot exec the init from the get started

### ISSUE THREAD

**Issue by flowHater** [99designs/gqlgen#1222]
### What happened?
When I'm running the `go run github.com/99designs/gqlgen init` line takken from the get started. I got an error
```
failed to load schema: exec and model define the same import path () with different package names (generated vs model)
```

### What did you expect?
That can run without error.

### Minimal graphql.schema and models to reproduce
Just follow the get started.

### versions
 - `gqlgen version`? the last `v.0.11.3`
 - `go version`? `go version go1.14.4 linux/amd64`
 - dep or go modules? go modules

I tested inside a clean image docker, and it works. It seems to be linked to my local setup. But I'm often working with Go. And I never saw  this behavior.

It seems to be the `generate` command who failed. Because I got the same issue with the `generate` command.

I tried to delete my local files:
```
: 1592567686:0;sudo rm -rf ~/go/pkg/mod/github.com/99designs
: 1592567702:0;rm -rf gqlgen-todos
: 1592569853:0;sudo rm -rf pkg/mod/github.com/99designs
: 1592569914:0;sudo rm -r `find . | grep gql`
: 1592569853:0;sudo rm -rf pkg/mod/github.com/99designs
```

Several tries as you can see.
Nothing worked.

Btw, I have already tried your project with another setup in a previous version, and it's awesome.
Thanks for your work guys

**Comment by JonasDoe** [comment]
In my case the absence of a go.mod file caused that issue.

**Comment by samfolo** [comment]
Also could be because your project is using the GOPATH, in which case your files need to be in a `/src` directory.

This was my situation, working in a monorepo which does not use any explicit `go.mod` files; moving `myProject` to `myProject/src` fixed it.
