### ISSUE TITLE
Inherit/extend input type in output type

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1223]
In Go I can write this code:

```go
type Player struct {
	ID        int
	CreatedAt time.Time
	UpdatedAt time.Time
	Team      *Team
	City      *City
	PlayerInput
}

type PlayerInput struct {
	TeamID  int
	CityID  int
	Type    int
	Score   int64
	Info    *string
}
```

as you can see `Player` "extends" `PlayerInput`.

In my code I can have:

```go
var newPlayer Player
var newPlayerInput PlayerInput

newPlayer.PlayerInput = newPlayerInput
```

and this is good.

Now I'm trying to do the same with GraphQL but I don't know how to do.

I have this code:

```graphql
type Player {
    id: ID!
    createdAt: Time
    updatedAt: Time
    teamID: ID!
    cityID: ID
    type: Int!
    score: Int64!
    info: String
}

input PlayerInput {
    teamID: ID!
    cityID: ID
    type: Int!
    score: Int64!
    info: String
}
```

As you can see `PlayerInput` has the same fields of `Player`.

**Is there a way to avoid this fields duplication?**

It would be amazing to have something like:

```graphql
type Player {
    id: ID!
    createdAt: Time
    updatedAt: Time
    @inherit PlayerInput
}

input PlayerInput {
    teamID: ID!
    cityID: ID
    type: Int!
    score: Int64!
    info: String
}
```

_Am I brutally wrong?_

**Comment by frederikhors** [comment]
Wrong question.

**Comment by BatmanAoD** [comment]
What is the right question? I feel like there's a sensible request here (somehow generate a single model type for both `Foo` and `FooInput`), but it's sort of "inverted" by asking about a (nonexistent) GraphQL feature rather than a possible `gqlgen` feature. I can't find any existing issues that seem to ask for that feature, though.

**Comment by frederikhors** [comment]
> What is the right question?

In this case I'm the author of the question too. 😄

**Comment by BatmanAoD** [comment]
Yes, I noticed that, but did you address this duplication somehow?

**Comment by frederikhors** [comment]
I changed my code design.
