### ISSUE TITLE
Pass fields collection from context to Dataloader 

### ISSUE THREAD

**Issue by mariosttass** [99designs/gqlgen#1225]
### What happened?
The target is to pass field collection context `GetOperationContext  ` into the Dataloader. In the resolvers we are passing the context into the retriever but it doesn't contain the the info that we need to get the fields of the query on that level. So I tried to change that on the Middleware layer but without hope. Do you know if there is a way to pass that context on the Dataloaders ?
FYI the error happen when I try to pass the field collection of the nested model in Dataloader, `panic missing operation context ` 
### What did you expect?
When I was passing the context in the resolver I was expecting that I will have all the info to get the fields and use  GetOperationContext  to get them and pass them in Dataloader.
### Minimal graphql.schema and models to reproduce
```query {
  rootQuery(
    name: ["Alex"]) {
    name
    email
    tel
    ProductsInfo{
      id
      name
      description
    }
  }
}
```
### versions
 - `gqlgen version`? 
     latest v0.11.3
 - `go version`?
     go version go1.14.2 linux/amd64

**Comment by 6d61746f** [comment]
I found a solution - not the cleanest, but it works for my use-case.
Idea is to init `Loaders` types in middleware without `fetch` func:
```
	ctx := context.WithValue(r.Context(), CtxThingByStuffIDLoaderKey, &ThingLoader{
			maxBatch: 1000,
			wait:     1 * time.Millisecond,
			fetch:    nil,
	})
	
	next.ServeHTTP(w, r.WithContext(ctx))
```

You can define function that takes `context.Context` and returns `fetch` func for loader:
```
func NewThingByStuffIDLoaderFetchFunc(ctx context.Context, svc ThingService) func(keys []string) ([][]*model.Thing, []error) {
	return func(keys []string) ([][]*model.Thing, []error) {
		resp, err := svc.FindThingsByStuffIDs(ctx, keys...)
                // mapping etc etc...
	}
}
```

Now in resolvers we have access to `graphql.OperationContext` through `context.Context` argument - this gives us opportunity to set `fetch` method with wanted `ctx` value:
```
	func (r *stuffResolver) Thing(ctx context.Context, obj *model.Stuff) ([]*model.Thing, error) {
		loader, _ := ctx.Value(CtxThingByStuffIDLoaderKey).(*ThingLoader)
		if loader.fetch == nil {
			loader.fetch = NewThingByStuffIDLoaderFetchFunc(ctx, r.ThingService)
		}

		return loader.Load(obj.ID)
	}  
```

If anybody thinks of any better solution please let me know.
