### ISSUE TITLE
Null doesn't propagate up to non-null list with field resolver

### ISSUE THREAD

**Issue by ktsymbal** [99designs/gqlgen#1230]
### What happened?

When a resolver of a non-null field in a type that is used in a null-null list of non-null elements returns null, null doesn't propagate up to the list, and then to `data`, but returns a null element in a list.

Example when `Image(ctx context.Context, obj *Post) (*Image, error)` returns `nil, fmt.Errorf("error message")`

```json
{
  "errors": [
    {
      "message": "error message",
      "path": [
        "users",
        0,
        "posts",
        0,
        "image"
      ]
    }
  ],
  "data": {
    "users": [
      {
        "name": "Nate",
        "posts": [
          null
        ]
      }
    ]
  }
}
```

### What did you expect?

According to [the spec](http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability), null should be propagated up to the first nullable field.

With this example:

```json
{
  "errors": [
    {
      "message": "error message",
      "path": [
        "users",
        0,
        "posts",
        0,
        "image"
      ]
    }
  ],
  "data": null
}
```

### Minimal graphql.schema and models to reproduce
```graphql
type User {
        name: String!
        posts: [Post!]!
}

type Post {
        title: String!
        image: Image! @goField(forceResolver: true)
}

type Image {
        name: String!
}

type Query {
        users: [User!]!
}

directive @goField(forceResolver: Boolean, name: String) on INPUT_FIELD_DEFINITION
    | FIELD_DEFINITION
```
### versions
 - `gqlgen version`? 
v0.11.3
 - `go version`?
v1.14.3
 - dep or go modules?
go modules

**Comment by bofia** [comment]
Not stale, seems like a open bug still
