### ISSUE TITLE
Update website documentation and add new Complexity Examples

### ISSUE THREAD

**Issue by mathbalduino** [99designs/gqlgen#1232]
### What happened?

The website documentation are out of sync with the code and I think that will be helpful to add some new examples on how to use the ComplexityLimit func (I'm struggling to use it)

How do I calculate the complexity using a function whose signature is `func(ctx context.Context, rc *graphql.OperationContext) int`? Should I iterate over the `rc.Operation.SelecionSet` and do the calculations based on that? Manually?

I don't want to use custom complexity using the fields in `Config{}.Complexity`. It doesnt make sense in my architecture (The GraphQL server belongs to one package, and shouldn't handle nothing specific to any resolver).

I'm using `FixedComplexityLimit`, but it not sufficient.

### What did you expect?

To be sync and have more examples.

Some easy way to calculate the complexity globally. Perhaps using something like this (from documentation):

```
func(childComplexity, count int) int {
        return count * childComplexity
    }
```

But for all field resolvers instead of one by one. Just an example

### versions
 - `gqlgen version`? 11.3

I already pointed it out in #1104, but I think it will be more appropriate to create an issue.

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
@mathbalduino please tell me if this is still an issue after reading https://gqlgen.com/reference/complexity/ and I'll re-open it.
