### ISSUE TITLE
Documentation fo introspection is outdated

### ISSUE THREAD

**Issue by andytruong** [99designs/gqlgen#1235]
### What happened?

It's outdated:

https://gqlgen.com/reference/introspection/

### What did you expect?

It's disabled by default, to enable it:

```go
schema := gql.NewExecutableSchema(cnf)
srv := handler.New(schema)
srv.Use(extension.Introspection{})
```

### versions
 - `gqlgen version`: v0.11.3
 - `go version`: go1.14.4
 - dep or go modules: go modules

**Comment by AienTech** [comment]
Hey there,
instead of using `handler.New()` which only creates a barebones gql server, you can use `handler.NewDefaultServer()` which also has introspection enabled by default

**Comment by frederikhors** [comment]
@andytruong can you write a PR instead?
