### ISSUE TITLE
Generate command fails in a strange way based on capitalization of "query" and "mutation"

### ISSUE THREAD

**Issue by ttt733** [99designs/gqlgen#1236]
### What happened?
On Windows 10, I followed the Getting Started tutorial with gqlgen init. I replaced the default schema contents with my own. After fixing a few validation errors, I reran the generate command and got errors such as the following:
```
PS C:\dev\gqlgallery> gqlgen generate
validation failed: packages.Load: C:\dev\gqlgallery\graph\generated\generated.go:7096:5: queryImplementors redeclared in this block
C:\dev\gqlgallery\graph\generated\generated.go:6435:5:  other declaration of queryImplementors
C:\dev\gqlgallery\graph\generated\generated.go:186:2: Query redeclared
C:\dev\gqlgallery\graph\generated\generated.go:102:2:   other declaration of Query
C:\dev\gqlgallery\graph\generated\generated.go:929:25: e.complexity.Query.GetUser undefined (type struct{} has no field or method GetUser)
```
After some poking around, I found that what was happening was that in my own schema file, I had `type query {...}` rather than `type Query{...}`. Changing to `Query` (capitalized) worked.

### What did you expect?
I think validation of the schema file should probably fail if it encounters `type query` (or `type mutation` for that matter) with a hint. I don't think lowercasing those types is within the standard.

### Minimal graphql.schema and models to reproduce
After running the init command, simply
```
type query {
  getSomeInt:Int!
}
```
and then `gqlgen generate` should fail.

### versions
 - `gqlgen version`?  v0.11.3
 - `go version`? go version go1.12.7 windows/amd64
 - dep or go modules? modules

**Comment by lwc** [comment]
If not provided, gqlgen (and most GraphQL servers I'm aware of) will provide a default schema definition along the lines of:

```graphql
schema {
  query: Query
  mutation: Mutation
}
```

https://graphql.org/learn/schema/#the-query-and-mutation-types

gqlgen is slightly permissive in the case of an undefined `type Query`, and will add an empty type if one is not found. This can be of use to extend an empty query with `extend type Query`.

[Names are case sensitive in GraphQL](https://spec.graphql.org/June2018/#sec-Names), so you're getting a default type query type added with no fields on it. The following schema definition should fix this issue:

```graphql
schema {
  query: query
  mutation: Mutation
}
```

I don't think validation should enforce the type names of the query, mutation and subscription types, although I do agree that the permissive defaults in gqlgen create a rough edge here. Open to suggestions to improve this.
