### ISSUE TITLE
Support default arguments in input types

### ISSUE THREAD

**Issue by ttt733** [99designs/gqlgen#1239]
### What happened?
Most sources I can find recommend using a single input object rather than multiple parameters. Let's say I have a query or mutation like this:
```
type Obj {
    id: Int!
    status: ObjStatus!
}

enum ObjStatus {
    CURRENT
    DELETED
    SUPERSCEDED
}

type Query {
    listObjs(input: ListObjsInput): ListObjsResponse
}

type ListObjsInput {
  status: [ObjStatus!]! = [CURRENT, SUPERSCEDED]
  ids: [Int!]
}

type ListObjsResponse {
  objs: [Obj!]
}
```
This will cause gqlgen to fail to generate.
```
failed to load schema: schema.graphql:6: Expected Name, found =
```

### What did you expect?
The GraphQL spec allows for the specification of default field values. Therefore, a system for storing them in gql would be nice.

### Minimal graphql.schema and models to reproduce
See above.

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? go version go1.14.4 linux/amd64
 - dep or go modules? go modules

**Comment by art1415926535** [comment]
```graphql
input ListObjsInput {
  status: [ObjStatus!]! = [CURRENT, SUPERSCEDED]
  ids: [Int!]
}
```

`type` -> `input`

**Comment by ttt733** [comment]
That indeed works - thanks!
