### ISSUE TITLE
Is it possible to cache the result of directives for permission checks?

### ISSUE THREAD

**Issue by maaft** [99designs/gqlgen#1241]
When I for example want to check if the user can query an object based on the owner of this object, I have to read from my database to check permissions.

If the same user now continues to query the same object (same context), I'd like to "instantly" return "Not authorized" instead of re-reading my database every time.

Any Idea how this can be achieved using gqlgen's directives?

**Comment by lwc** [comment]
This is something you probably want to do before/outside of directives themselves. 

Take a look at the [docs on authentication](https://gqlgen.com/recipes/authentication/ ) - they describe our typical approach for attaching the session & user to the request context before dispatching to the gqlgen handler.

Also, the [docs on dataloaders](https://gqlgen.com/reference/dataloaders/) describe how we minimise refetching the same resources over and over again as we resolve a GraphQL query.

**Comment by maaft** [comment]
Thank you very much for your fast answer.

Following the authentication example, the user is attached to the request context like:
```golang
user := getUserByID(db, userId)
```
which still does a DB access at every single request. I could of course fetch the user once (with the userId coming from the authorization token) and afterwards get the user from a memory cache instead (e.g. redis) (again, using the userId from the token). Would this be a good practice?

Also, while in this example the caching key is clear (userId), there might also more complex rules (owner checks, ...).
[Graphql-Shield](https://github.com/maticzav/graphql-shield) is a typescript middleware that offers all this functionality including caching permissions by defining simple rules.

I guess what I am really asking is, if there is something similar for gqlgen or if I have to manually program every single rule for my potentially large schema.

**Comment by ypopivniak** [comment]
@maaft I would propose you to use JWT token for your purposes. It fits with your needs. You can generate it during authentication procedure, add all necessary claims to the payload (`user_id`, `roles` as an array, e.g. `resource.my_mutation` or even `id.resource.my_mutation`) and sign it by a secret key. You won't need to use a cache at all. Just check the validity of the token and if it is valid you can believe it and use claims for checking permissions in your directive.

**Comment by frederikhors** [comment]
@maaft any news?

**Comment by maaft** [comment]
Hi! Sorry for the late answer. I ended up including all needed user details into the JWT. Works like a charm.
