### ISSUE TITLE
Fields tracing not working

### ISSUE THREAD

**Issue by art1415926535** [99designs/gqlgen#1244]
### What happened?

Tracing does not show field information.

![image](https://user-images.githubusercontent.com/5222234/87153050-7bd01d00-c2bf-11ea-8a2b-6faa7f92d367.png)

### What did you expect?

Tracing info for each field. 

### Minimal graphql.schema and models to reproduce
```graphql
type User {
  id: Int!
  username: String!
}
type Query {
  me: User
}
```

### versions
 - `gqlgen version` v0.11.3
 - `go version` 1.14
 - dep or go modules: go modules

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
@art1415926535 we're not using Playground anymore. Please tell me if this is still an issue with v0.16.0 and I'll re-open it.
