### ISSUE TITLE
Federation @key entity type error

### ISSUE THREAD

**Issue by amwill04** [99designs/gqlgen#1252]
Unsure if this issue is raised somewhere else - so apologies but couldnt see it.

### What happened?
Give the following `model`

```go
type Crash struct {
    CrashId *int `json:"crashId"`
}
```

and the corresponding `graphql` type

```graphql
type Crash @key(fields: "crashId") {
    crashId Int!
}
```
I will get the following error on generating 
```
cannot use id0 (variable of type *int) as int value in argument to ec.resolvers.Entity().FindCrashByCrashID
```

due to the generated `federated` file using `unmarshalNInt2ᚖint` and trying to pass in an `*int` to `FindCrashById` which will be generated expecting an `int`.

I can solve this by either removing the `pointer` from the model or removing the `non-nullable` from the `graphql` - neither of which would be ideal for me.

The only solution I found is to use `goField(forceResolve: true)` and then define the following

```go
    func (c *crashResolver) CrashID(ctx context.Context, obj *models.Crash) (int, error) {
	return *obj.CrashId, nil
}
```

This then correctly builds.

Is this correct? I cant find any documentation on `goField`

### What did you expect?
Correctly build without requiring an extra resolver.

### versions
 - `gqlgen version` `0.11.3` 
 - `go version` `1.14`
 - dep or go modules? `modules`

**Comment by frederikhors** [comment]
Nope

**Comment by frederikhors** [comment]
@amwill04 please tell me if this is still an issue with v0.16.0 and I'll re-open it.
