### ISSUE TITLE
Multiple requests for same struct but different selected fields gives incorrect error about mismatching arguments

### ISSUE THREAD

**Issue by ryanwmoore** [99designs/gqlgen#1272]
### What happened?

The following query returns an error:

```
query MyQuery($first: Int = 10, $after: ID = "2001") {
  hero {
    id
    friendsConnection(first: $first, after: $after) {
      totalCount
    }
    ...SomeFragment
  }
}
fragment SomeFragment on Character {
  friendsConnection(first: $first, after: $after) {
    pageInfo {
      hasNextPage
    }
  }
}
```

The returned error is:

```
{
  "error": {
    "errors": [
      {
        "message": "Fields \"friendsConnection\" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.",
        "locations": [
          {
            "line": 12,
            "column": 3
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED"
        }
      }
    ],
    "data": null
  }
}
```

### What did you expect?

A non-error response like:

```
{
  "data": {
    "hero": {
      "id": "2001",
      "friendsConnection": {
        "totalCount": 3,
        "pageInfo": {
          "hasNextPage": false
        }
      }
    }
  }
}
```

I think the error is invalid, since the arguments to friendsConnection *are* identical.

### Minimal graphql.schema and models to reproduce
See [Star Wars](https://github.com/99designs/gqlgen/tree/master/example/starwars) example in gqlgen repo. This query works as I expect when pasted into the textboxes at https://graphql.org/learn/queries/

### versions
 - `gqlgen version`? master head (39a12e0f1b6d9833f516f0271db0dbfa45c5ec45)
 - `go version`? go1.14.6 darwin/amd64 but I saw similar behavior in go1.14.7 on Linux
 - dep or go modules? gqlgen is using go modules

**Comment by frederikhors** [comment]
Nope

**Comment by jufemaiz** [comment]
Just hit this issue + created a PR to resolve the issue in vektah's package.
