### ISSUE TITLE
Federation __resolve_entities should be non-blocking (async)

### ISSUE THREAD

**Issue by malyusha** [99designs/gqlgen#1278]
### What happened?
I generated service with federation enabled and got some code, generated inside method `__resolve_entities`. Basically all it doest it's just fetching product by id (implemented `FindProductByID` method inside `entity.resolvers.go`). When i run service and using dataloader for products to load batch of products instead of fetching one by one, dataloader blocks each call of `FindProductByID` because generated `executionContext.__resolve_entities` method calls it synchronously for each of `representation`.

### What did you expect?
That `executionContext` runs `Find{Entity}By{Key}` in async mode.

### Minimal graphql.schema and models to reproduce
```
// inside products service
extend type Query {
    products: [Product!]
}

type Product implements Node @key(fields: "id") {
    id: ID!
    name: String!
}
```

```
// inside other service, extending products
extend type Product @key(fields: "id") {
    id: ID! @external
    testField: String!
}

// And make query 
query {
  products {
    id
    testField
    name
  }
}
```

### versions
 - `gqlgen version` v0.11.0
 - `go version` 1.14
 - dep or go modules - go modules

### What code is being generated inside `federation.go` now:
```
func (ec *executionContext) __resolve_entities(ctx context.Context, representations []map[string]interface{}) ([]fedruntime.Entity, error) {
	list := []fedruntime.Entity{}
	for _, rep := range representations {
		typeName, ok := rep["__typename"].(string)
		if !ok {
			return nil, errors.New("__typename must be an existing string")
		}
		switch typeName {

		case "Product":
			id0, err := ec.unmarshalNID2string(ctx, rep["id"])
			if err != nil {
				return nil, errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
			}

			entity, err := ec.resolvers.Entity().FindProductByID(ctx,
				id0)
			if err != nil {
				return nil, err
			}

			list = append(list, entity)

		default:
			return nil, errors.New("unknown type: " + typeName)
		}
	}
	return list, nil
}
```

### What i suggest:
```
func (ec *executionContext) __resolve_entities(ctx context.Context, representations []map[string]interface{}) ([]fedruntime.Entity, error) {
	var (
		wg         sync.WaitGroup
                list = []fedruntime.Entity{}
		errCh      = make(chan error)
		entitiesCh = make(chan fedruntime.Entity)
                done = make(chan bool)
		err  error
	)

	for _, rep := range representations {
		wg.Add(1)
		go func(rep map[string]interface{}) {
			defer wg.Done()
			typeName, ok := rep["__typename"].(string)
			if !ok {
				errCh <- errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
				return
			}
			switch typeName {

			case "Product":
				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
				if err != nil {
					errCh <- errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
					return
				}

				entity, err := ec.resolvers.Entity().FindProductByID(ctx,
					id0)
				if err != nil {
					errCh <- err
					return
				}

				entitiesCh <- entity

			default:
				errCh <- errors.New("unknown type: " + typeName)
			}
		}(rep)
	}

	go func() {
		wg.Wait()
		done <- true
	}()

	for {
		select {
		case err = <-errCh:
			return nil, err
		case e := <-entitiesCh:
			list = append(list, e)
		case <-done:
			return list, nil
		default:
		}
	}
}

```

**Comment by StevenACoffman** [comment]
@lwc I would really appreciate it if you could review #1285 
Thanks!

**Comment by mlaflamm** [comment]
Any chance this get officially merged soon? Without this we cannot use `dataloader` with entity resolver and in our case this make a huge performance gain. For the time being we use a fork (via a replace) but we would really appreciate this end up in the next official release.

**Comment by malyusha** [comment]
@mlaflamm you don't really need to fork whole repo in this case. Create entry point for gql generation that will replace federation plugin of this repo with yours, where the bug is fixed. You can use template that @StevenACoffman  proposed.
Just create binary with that codegen and use it instead of: 
instead of: `//go:generate github.com/99designs/gqlgen ...` 
use: `//go:generate your_binary_with_codegen`
