### ISSUE TITLE
Support query string paramete in POST request

### ISSUE THREAD

**Issue by taka011239** [99designs/gqlgen#128]
https://graphql.org/learn/serving-over-http/#post-request

Do you have any plan to support query string paramete in POST request ?

**Comment by vektah** [comment]
Not really, I worry a lot about csrf attacks and am tempted to remove get requests entirely or gate it being an opt in flag. What's the use case?

**Comment by yamitzky** [comment]
@vektah My use case is a compatibility w/ other GraphQL libraries. I migrated my GraphQL API from [python's graphene](https://github.com/graphql-python/graphene). Some of my clients use "query" w/ POST request.

I think that security problems should be prevented by other ways. Even if you remove GET feature, attackers can do CSRF attacks using POST requests. So, we have to prevent it by the CSRF token.

(Note that @taka011239 is my colleague :)

**Comment by vektah** [comment]
Happy to reopen this if it's providing value. Was just cleaning out old issues

**Comment by cayter** [comment]
@yamitzky @taka011239 Sorry if I ask a dumb question here. Wouldn't [CSRF be affecting GET request ](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) as well? I'd strongly recommend to avoid the use of GET request as [some of the browsers have URL length limitation](https://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be/33733386).
