### ISSUE TITLE
Getting started init : 'resolvergen: -: package go_graphql/graph is not in GOROOT'

### ISSUE THREAD

**Issue by syx309** [99designs/gqlgen#1286]
### What happened?
- I followed the getting started steps to make my first graphql project, but when i run 'go run github.com/99designs/gqlgen init' it outputs 'resolvergen: -: package go_graphql/graph is not in GOROOT'. I successfully created a project but the project is missing the resolver.go, schema.resolvers.go, and the server.go

### What did you expect?
I expected to get a graphql project with all the components including resolver.go, schema.resolvers.go, and the server.go

### versions
 - I use gqlgen version 0.12.1 => just tried it this morning 
 - I use go version of 1.14.6
 - Im quite new and i dont really understand the go modules yet but this is what mine looks like
![image](https://user-images.githubusercontent.com/58784396/90309767-882a4400-df15-11ea-81fd-352c263d5dc9.png)

**Comment by syx309** [comment]
if i run it inside my GOROOT folder it shows this response
![image](https://user-images.githubusercontent.com/58784396/90311116-0b519700-df22-11ea-9ee1-d2c87672a004.png)

**Comment by ChandanKuSingh** [comment]
Same problem for me

**Comment by ChandanKuSingh** [comment]
I worked for me now :
try using this combination. Update it in go.mod file and run "go mod tidy"	
github.com/99designs/gqlgen v0.11.3
github.com/vektah/gqlparser/v2 v2.0.1

But it took my 3-4 hours to resolve this.

**Comment by syx309** [comment]
> 
> 
> Try this, it worked for me now:
> try using this combination. Update it in go.mod file and run "go mod tidy"
> github.com/99designs/gqlgen v0.11.3
> github.com/vektah/gqlparser/v2 v2.0.1
> 
> But it took my 3-4 hours to resolve this.

Thanks, solved it for me, much appreciate it man

**Comment by syx309** [comment]
but can you do 'gqlgen generate' because for me, i cant seem to generate gqlgen commands

**Comment by conjohnerton** [comment]
I had this problem too. I appreciate your quick solution. Just wanted to try out gqlgen quickly.

**Comment by ChandanKuSingh** [comment]
goto graph -> cd graph
go run github.com/99designs/gqlgen generate

This is working for me

**Comment by syx309** [comment]
> go run github.com/99designs/gqlgen generate

apparently this doesn't work for me, i can check my version but i still can't generate, it returns nothing
![image](https://user-images.githubusercontent.com/58784396/90324927-29a9a800-df9f-11ea-877c-063b9aaa487a.png)

**Comment by syx309** [comment]
> 
> 
> > go run github.com/99designs/gqlgen generate
> 
> apparently this doesn't work for me, i can check my version but i still can't generate, it returns nothing
> ![image](https://user-images.githubusercontent.com/58784396/90324927-29a9a800-df9f-11ea-877c-063b9aaa487a.png)
> 
> if i execute 'go run gqlgen generate' it show output like this
> ![image](https://user-images.githubusercontent.com/58784396/90330540-a8bad280-dfd7-11ea-833b-0a2b455c45d3.png)

an update, mine worked now, I try deleting the schema.resolvers.go and then run "go run github.com/99designs/gqlgen generate" without the "". After the new schema.resolvers.go is built i can use generate by running the previous command
