### ISSUE TITLE
WrapErrorWithInputPath

### ISSUE THREAD

**Issue by lynntobing** [99designs/gqlgen#1287]
$ gqlgen

$ error:  WrapErrorWithInputPath not declared by package graphql

**Comment by genshen** [comment]
I have met the same error

**Comment by lwc** [comment]
Sounds like you have a different gqlgen command version from the library version.

We no longer recommend not installing gqlgen as a command, but instead using the same version pinned in your go.mod file via:
```
go run github.com/99designs/gqlgen
```

**Comment by bjwschaap** [comment]
Had the same issue. Turns out I was using an older version of `gqlgen` which I installed with `go install github.com/99designs/gqlgen`. So when you get this error either update the installed version by doing another `go install`, or (better) use the solution provided by @lwc above.
