### ISSUE TITLE
init only generate graph/schema.graphqls file

### ISSUE THREAD

**Issue by Igorpollo** [99designs/gqlgen#1296]
### What happened?
`go run github.com/99designs/gqlgen init ` is only creating the `graph/schema.graphqls`
![image](https://user-images.githubusercontent.com/4457845/90581704-45c96700-e1a2-11ea-9452-1e12adbee69e.png)

### What did you expect?
Generate all the files
### Minimal graphql.schema and models to reproduce
 no generated
### versions
 - `gqlgen version`? 12.2
 - `go version`? 1.14
 - dep or go modules? go modules

**Comment by lwc** [comment]
Modules are typically in the form of urls e.g. `github.com/Igorpollo/teste`. It's possible that just `teste` is confusing gqlgen.

Is `new-api` the containing directory or your git branch? If directory, it's also possible the mismatch between directory and branch is confusing gqlgen or even go itself.

**Comment by Igorpollo** [comment]
thanks for reply @lwc .
tryed to change the names... still the same.
![image](https://user-images.githubusercontent.com/4457845/90707278-a07bc500-e26d-11ea-813c-a69526df97bc.png)

**Comment by Igorpollo** [comment]
I found!!
There are a go mod outside this folder that I generated unintentionally.
Deleted them and all worked fine.
Thanks
