### ISSUE TITLE
How can insert a field with hooks?

### ISSUE THREAD

**Issue by xaoirse** [99designs/gqlgen#1301]
### What happened?
I want to add a field with hooks and i find out this way works. My problem is  `typ`
```GO
// Defining mutation function
func mutateHook(b *modelgen.ModelBuild) *modelgen.ModelBuild {
	var typ types.Type
	var cfg config.Config
	typ = types.NewNamed(
		types.NewTypeName(0, cfg.Model.Pkg(), "string", nil),
		nil,
		nil,
	)
	for _, model := range b.Models {
		model.Fields = append(model.Fields, &modelgen.Field{
			Description: "my string",
			Name:        "string",
			Type:        typ,
		})
	}
	return b
}
```
Is it the best way to difine `typ`? Or there is simpler way?
### What did you expect?
There isnt any document about how types library works. is there a simple way to do that?
### versions
 - `gqlgen version`? v0.12.1
 - `go version`? go1.15 linux/amd64
 - dep or go modules?

**Comment by xaoirse** [comment]
After a lot of search i found the solution:
	`typ = types.Typ[types.String].Underlying()`
This is the magic code that i was looking for.

**Comment by frederikhors** [comment]
@xaoirse can I ask you if you use the code from https://gqlgen.com/recipes/modelgen-hook/ is the generator generating resolvers files?

Thanks.

**Comment by xaoirse** [comment]
@frederikhors
Yes i use `mutateHook` to insert `gorm.Model`'s fields and it works.
But when we run  `go run github.com/99designs/gqlgen generate` it generate only resolver files and `model_gen.go` files not hooks.
hooks run when we start our program.
I have a simple test project with gqlgen:
[https://github.com/xaoirse/xgo](https://github.com/xaoirse/xgo )
