### ISSUE TITLE
Crash instead of diagnostic error when spelling model name wrong

### ISSUE THREAD

**Issue by jwatte** [99designs/gqlgen#1308]
### What happened?
I had spelled a model name wrong in gqlgen.yml, and gqlgen crashed with a null pointer dereference.

### What did you expect?
I expected an error similar to "could not find model type xxxxxx"

### Minimal graphql.schema and models to reproduce
Here's a patch that avoids the crash and returns an error, although it's probably not the best way to solve this problem:

    diff --git a/code/go/src/observe/vendor/github.com/99designs/gqlgen/codegen/field.go     
    b/code/go/src/observe/vendor/github.com/99designs/gqlgen/codegen/field.go
    index c12520b70..bccf18459 100644
    --- a/code/go/src/observe/vendor/github.com/99designs/gqlgen/codegen/field.go
    +++ b/code/go/src/observe/vendor/github.com/99designs/gqlgen/codegen/field.go
    @@ -67,6 +67,9 @@ func (b *builder) buildField(obj *Object, field *ast.FieldDefinition) (*Field, e
                    log.Println(err.Error())
            }
    
    +       if f.TypeReference == nil {
    +               return &f, fmt.Errorf("%d,%d: TypeReference is nil: %s: %s (%v)", f.Position.Line, f.Position.Column, field.Name, f.GoFieldName, f.GoFieldType)
    +       }
            if f.IsResolver && !f.TypeReference.IsPtr() && f.TypeReference.IsStruct() {
                    f.TypeReference = b.Binder.PointerTo(f.TypeReference)
            }

### versions
 - `gqlgen version`? 
v0.12.2

 - `go version`?
go1.14

 - dep or go modules?
go mod

**Comment by frederikhors** [comment]
@jwatte please tell me if this is still an issue with v0.16.0 and I'll re-open it.
