### ISSUE TITLE
[guidance request] gqlgen with nosql database

### ISSUE THREAD

**Issue by kockok** [99designs/gqlgen#1313]
### What happened?

I find it hard to integrate nosql database such as mongodb with gqlgen.

### What did you expect?

I expect a recipe to layout the best practices using gqlgen with mongodb.

### Minimal graphql.schema and models to reproduce
```
type User {
	id: ObjectID!
	email: String!
	username: String!
	name: String!
	group: Group!
}

type Group {
	id: ObjectID!
	admins: [User]!
	members: [User]!
	name: String!
}
```

From the above schema, I want the `User` to have a referenced relationship with the `Group`. Instead of just reference the `Group` type in the schema, should I add one more field to link up the relationship like below?

```
type User {
	id: ObjectID!
	email: String!
	username: String!
	name: String!
        **groupId: String!**
	group: Group!
}
```

**Comment by MattJBrowning** [comment]
What I ended up doing is something like this.

In your `gqlgen.yml` make sure you have the autobind model property set.
```
autobind:
  - "your/package/structure/models"
```

Create a package for all of your types that'll be used for serializing/deserializing from the database. In my case I just called it models.

You define some types like such:
```
type User struct {
	ID       primitive.ObjectID
	Email    string
	Username string
	Name     string
	GroupID  primitive.ObjectID
}

type Group struct {
	ID      primitive.ObjectID
	Admins  []primitive.ObjectID
	Members []primitive.ObjectID
	name    string
}
```

Then in your schema for gqlgen you'd write out:
```
type User {
	id: ObjectID!
	email: String!
	username: String!
	name: String!
	group: Group!
}

type Group {
	id: ObjectID!
	admins: [User]!
	members: [User]!
	name: String!
}
```
Once you have that setup, you should be able to regenerate and it'll create a resolver for group, admins, and members since the type in graphql won't match the type defined in the Go struct.

From there you can use whatever logic you want to use to make that reference.

**Comment by flintforge** [comment]
Here's an even more minimalist example 

`autobind` is set in the config file

The go structures
```
type User struct {
	id      ObjectID!
	groupID *ObjectId!  `json:"group" bson:"group"`
}

type Group struct {
	id    ObjectID!
	name  String!
}
```

and the graphQL schema
```
type User {
	id: ObjectID!
	group: Group
}

type Group {
	id: ObjectID!
	name: String!
}
```

Running the generation at this stage
`adding resolver method for User.group, nothing matched`

Now you could add
```
func (u *User) Group() *Group { // using u.Group as ID }
```
but this would return the entire record, not only the requested fields.

The proper way to go is to implement the `UserResolver` in the `schema.resolvers.go`

```
type userResolver struct{ *Resolver }

func (r *Resolver) User() generated.UserResolver {
	return &userResolver{r}
}

func (u *  userResolver) Group(ctx context.Context, obj *model.User) (*model.Group, error) {
	var fields = M_{}
	f := builders.CollectFields(ctx)
	for _, d := range f.Selections {
		fields[d.Name]=1
	}
	var s model.Group
	db.FindOne(db.Group,primitive.M{"_id":obj.Group},fields).Decode(&s)
	log.Debug(s)
	return &s,nil
}
```
Very likely this can get generated by a plugin.

Going to the api.Generate states
`Group is incompatible with *go.mongodb.org/mongo-driver/bson/primitive.ObjectID`. It's unclear, but it's only a warning.

Looks like the way to bring go+mongo+gqlgen to a 1.0.0 is still ahead

**Comment by ahmed-adly-khalil** [comment]
one important aspect here, that mongo driver can be configured to return any custom struct like what mentioned here: https://www.mongodb.com/blog/post/quick-start-golang--mongodb--modeling-documents-with-go-data-structures 
also, i found that creating a custom struct as @MattJBrowning mentioned and tagging each properties with both BSON & JSON counterparts works, something like this

```package entities

type Product struct {
	Upc   string `json:"upc" bson:"upc,omitempty"`
	Name  string `json:"name" bson:"name,omitempty"`
	Price int    `json:"price" bson:"price,omitempty"`
}

func (Product) IsEntity() {}
````

the nice thing here is that we can control separately how the data will appear in the JSON response and how it will be saved inside mongo in case that would be needed

**Comment by plxgwalker** [comment]
for those, who came to this issue and still do not understand why `autobind` parameter does not working (as I am) after enabling it properly
## Config
- if u want models from git repo, than use
```yml
autobind:
  - "github.com/your/desired/path/to/models"
```
- if u want models from your project
```yml
autobind:
  - yourFancyMainPackage.go/models
```
## Use

add type from your own models at the top of the file `schema.graphqls` (see `scalar`)

```graphql
scalar Id

type User {
  id: Id!
  ... ...
}
```

btw, I have this type of model

```go
package models

import "go.mongodb.org/mongo-driver/bson/primitive"

type User struct {
	Id       primitive.ObjectID `bson:"_id"`
        ...      ...
}
```

**Comment by amirhossein-shakeri** [comment]
# Integrating GraphQL ID with MongoDB Object ID(primitive.ObjectID)

I've spended over 5 hours on this and in case anyone might probably face something like this, Here's what I ended up with:

```go
// path/to/custom/models.go
package models

import (
	"fmt"
	"io"

	"github.com/99designs/gqlgen/graphql"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type ObjectID = primitive.ObjectID

func MarshalObjectID(id ObjectID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		fmt.Fprintf(w, "\"%s\"", id.Hex())
	})
}

func UnmarshalObjectID(v interface{}) (ObjectID, error) {
	str, ok := v.(string)
	if !ok {
		return primitive.NilObjectID, fmt.Errorf("ObjectID must be a string")
	}
	return primitive.ObjectIDFromHex(str)
}
func MarshalObjectIDScalar(id primitive.ObjectID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		fmt.Fprintf(w, "\"%s\"", id.Hex())
	})
}
```

Configure your `gqlgen.yml` file like below:
```yml
models:
  ID:
    model:
      - github.com/me/my-app/path/to/custom/models.ObjectID
```

And use the default `ID` in your `schema.gql` normally!

```gql
type Model {
  id: ID!
  createdAt: Time!
  updatedAt: Time!
  deletedAt: Time
}
```

Boom! It works seamlessly for me with a type alias.
