### ISSUE TITLE
follow-schema leaves resolver stubs

### ISSUE THREAD

**Issue by duckbrain** [99designs/gqlgen#1314]
### What happened?

When working with the `layout: follow-schema` option turned on, if I get over eager about running gqlgen, and add a new field name, `gqlgen`, rename it, and `gqlgen` again, I get stubs added for each name it has ever had added to the end of the file under the `!!! WARNING !!!` section.

It is a minor inconvenience to have to remove those resolver stubs manually.

### What did you expect?

The unimplemented resolvers are detected as such and removed.

I'd think that the resolver generator checks for method bodies that contain `panic("not implemented")` or `panic(fmt.Errorf("not implemented"))` after trimming whitespace. (The first one is what and older version of the generator produced.) If the body contains only that string, it is ignored after it reads the source code and will be regenerated if it's still in the schema, and removed it it's not. That would have a side effect of "updating" the stubs using the old string.

### versions
 - `gqlgen version`?  v0.11.3
 - `go version`? go version go1.15 linux/amd64
 - dep or go modules? modules

**Comment by frederikhors** [comment]
@duckbrain please tell me if this is still an issue with v0.16.0 and I'll re-open it.

**Comment by duckbrain** [comment]
This isn't implemented. It is just a convenience feature when prototyping and designing the API.
