### ISSUE TITLE
Feature request: add IsResolver in FieldContext

### ISSUE THREAD

**Issue by skaji** [99designs/gqlgen#1315]
### What happened?

Currently I'm working on implementing datadog apm tracing package for gqlgen
based on https://github.com/99designs/gqlgen-contrib/blob/master/gqlopentracing/tracer.go.

Then I want to trace not all fields, but just fields that have resolvers defined by ourselves.
So it is nice if gqlgen exposes such information in FieldContext.

### What did you expect?

I want FieldContext to have "IsResolver" attribute. I'm happy to create PR if you are OK.

```diff
diff --git codegen/field.gotpl codegen/field.gotpl
index 993625b7..e89d7420 100644
--- codegen/field.gotpl
+++ codegen/field.gotpl
@@ -16,6 +16,7 @@ func (ec *executionContext) _{{$object.Name}}_{{$field.Name}}(ctx context.Contex
 		Field: field,
 		Args:  nil,
 		IsMethod: {{or $field.IsMethod $field.IsResolver}},
+		IsResolver: {{ $field.IsResolver }},
 	}
 
 	ctx = graphql.WithFieldContext(ctx, fc)
diff --git graphql/context_field.go graphql/context_field.go
index 3c338504..8491ea2e 100644
--- graphql/context_field.go
+++ graphql/context_field.go
@@ -28,6 +28,8 @@ type FieldContext struct {
 	Result interface{}
 	// IsMethod indicates if the resolver is a method
 	IsMethod bool
+	// IsResolver indicates if the field has a user-specified resolver
+	IsResolver bool
 }
 
 type FieldStats struct {

```

### Minimal graphql.schema and models to reproduce

N/A

### versions
- `gqlgen version`?: v0.12.2
- `go version`?: 1.15
- dep or go modules?: go modules

**Comment by lwc** [comment]
Sounds great - 👍  from me 😄

**Comment by skaji** [comment]
@lwc I would really appreciate it if you could review #1316

**Comment by skaji** [comment]
@lwc Thank you!
