### ISSUE TITLE
automatically insert generated models from schema into a database

### ISSUE THREAD

**Issue by g14a** [99designs/gqlgen#1318]
### What happened?
Generated models structs from Schema being overwritten on changes 
### What did you expect?
Looking for a way to automatically insert generated models from Schema into a database.

If this is my Schema
```
type Role {
  id: String!
  name: String!
  desc: String!
  permissions: [String!]!
}
```
Upon gql gen it returns this 
```
type Role struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Desc        string   `json:"desc"`
	Permissions []string `json:"permissions"`
}
```
But now I want to insert this generated `Role` struct into a postgres database by adding `pg` tags just like `json` tags but those are overwritten upon the next `gql gen`
### versions
 - `gqlgen version` v0.12.2
 - `go version` go1.15 linux/amd64
 - dep or go modules -> go modules

**Comment by umeat** [comment]
Just my perspective, but I feel like it's unlikely that you actually want your GraphQL schema to map exactly to your database schema.

You're better off creating a database schema object and mapping between them, even if it's exactly the same as the GraphQL schema object at the moment. This little bit of "duplication" (it's not really duplication, they're different things) will likely save you a lot of time later, and gives you far greater flexibility.

**Comment by frederikhors** [comment]
> Just my perspective, but I feel like it's unlikely that you actually want your GraphQL schema to map exactly to your database schema.
> 
> You're better off creating a database schema object and mapping between them, even if it's exactly the same as the GraphQL schema object at the moment. This little bit of "duplication" (it's not really duplication, they're different things) will likely save you a lot of time later, and gives you far greater flexibility.

An example?

**Comment by riaan53** [comment]
Agree with @umeat . Otherwise you leak your internals on the API and couple them to your db model. Example if you change your API then you might have to run migrations on your DB and supporting multiple API version would be more difficult. Also theres probably some additional keys and userIDs thats not visible on your API but in your DB model.

**Comment by g14a** [comment]
> Just my perspective, but I feel like it's unlikely that you actually want your GraphQL schema to map exactly to your database schema.
> 
> You're better off creating a database schema object and mapping between them, even if it's exactly the same as the GraphQL schema object at the moment. This little bit of "duplication" (it's not really duplication, they're different things) will likely save you a lot of time later, and gives you far greater flexibility.

Thanks a lot for the detailed reply. Gonna close this issue.
