### ISSUE TITLE
library change

### ISSUE THREAD

**Issue by LucaPaterlini** [99designs/gqlgen#1320]
### What happened?
wrong library mentioned

### What did you expect?
the right one
https://github.com/graph-gophers/dataloader

**Comment by frederikhors** [comment]
Nope. I think https://github.com/vektah/dataloaden is the right one.

**Comment by lwc** [comment]
Yep - we're using https://github.com/vektah/dataloaden here at 99, but you are free to use any dataloader implementation you like, gqlgen won't mind 😄 

If you go with https://github.com/graph-gophers/dataloader and want to contribute docs on using it with gqlgen, we'd be open to a PR 👍
