### ISSUE TITLE
Re-export context if available

### ISSUE THREAD

**Issue by stevefan1999-personal** [99designs/gqlgen#1321]
### What happened?
I was using Fiber and gqlgen together by the http handler converter, but I noticed something.

https://github.com/99designs/gqlgen/blob/aa407b1f3553ac2aee1939fbe28c85ed5cbfcdf9/graphql/handler/server.go#L132

Here it overridden the supposedly top-most `*fasthttp.RequestCtx`. This is why there's seemingly no way to get the Fiber context so that I can validate my JWT if available. I don't know what to do then.

### What did you expect?
I just want to confirm this is either a design flaw/expected result, or just me being silly...

**Comment by mfcochauxlaberge** [comment]
I don't understand. You had `r` which is a `*http.Request` with a context (`context.Context`). What this line does is make a new identical `r` except that this time the context has a new value (operation trace).

How is that line overriding anything?

Could you show how you attempt to retrieve the Fiber context?

**Comment by mfcochauxlaberge** [comment]
"What happened?" => Show us your code and its output/behavior.
"What did you expect?" => Tell us what you think the correct output/behavior should be.

**Comment by stevefan1999-personal** [comment]
@mfcochauxlaberge yeah. I'm just not familiar with go http middlewares😅I don't know I could remediate this by wrapping the middleware by another middleware. Closing as just being silly.
