### ISSUE TITLE
adding db tag to generated models

### ISSUE THREAD

**Issue by kfirufk** [99designs/gqlgen#1327]
Hi
first of all thank you for this wonderful package.

I was wondering if it's possible to add a db tag besides the sql tag to the models_gen.go file that is being auto generated.
since I use sqlx I want to use these types directly to fetch the data from the database

**Comment by anton-yurchenko** [comment]
Subscribe to [PR-1173](https://github.com/99designs/gqlgen/pull/1173)

**Comment by kfirufk** [comment]
Since I wanted the json and DB tags to match, I was able to implement it with the modelgen hook https://gqlgen.com/recipes/modelgen-hook/

**Comment by frederikhors** [comment]
@kfirufk can you please close this? Thanks.

**Comment by frederikhors** [comment]
@kfirufk thanks for closing this.

A question: if you use the code from https://gqlgen.com/recipes/modelgen-hook/ is the generator generating resolvers files?

**Comment by kfirufk** [comment]
@frederikhors yeah.. so instead of using gqlgen command line tool, I generate it using a go script
