### ISSUE TITLE
Cannot add http headers to client

### ISSUE THREAD

**Issue by mg98** [99designs/gqlgen#1330]
PR https://github.com/99designs/gqlgen/pull/861 featured a way to add http headers across a whole client or per request. This does not work for me. I tried adding a header to the client like this:
```
authHeader := client.AddHeader("Authorization", fmt.Sprintf("Bearer %s", accessToken))
c = client.New(srv, authHeader)
```

There is no error or anything, the header just isn't added. I also tried adding the header in a request, as a parameter to `c.MustPost` and got the same result.

Since I am not the only one with this issue, see https://github.com/99designs/gqlgen/issues/857#issuecomment-643739880, I think this might be a bug with gqlgen?

### versions
 - `gqlgen version`? *0.11.3*
 - `go version`? *1.15.1*
 - dep or go modules? *go modules*

**Comment by lwc** [comment]
The client is pretty [well tested](https://github.com/99designs/gqlgen/blob/master/client/client_test.go#L42-L68) in this regard. What is `srv` in your code snippet above? 

You will need to run your middleware stack to move any headers you want to access in resolvers into context.

**Comment by mg98** [comment]
I see. Strange. Alright, when I have time, I will upgrade to the the latest version of gqlgen and inspect the issue again

----

> The client is pretty well tested in this regard. What is srv in your code snippet above?

```
var srv = handler.NewDefaultServer(generated.NewExecutableSchema(NewRootResolvers()))
var c = client.New(srv)
```

**Comment by mg98** [comment]
Ok, I'm on gqlgen 0.13.0 now. Nothing changed, but I noticed that `c.MustPost` does not actually send a HTTP request to my API which means it never passend my middleware, where I extend the context with the header value:

```
authHeader := r.Header.Get("Authorization")
ctx = context.WithValue(ctx, "authorization", authHeader)
return next(ctx)
```

This was the only way I found to be able to access the auth token from the headers in a graphql directive. Like this:
```
ctx.Value("authorization")
```

Is there a better way?

Because like this, I don't see a possibility to run my tests with a programmatic access token.

**Comment by lwc** [comment]
It looks like you need your auth middleware in your tests too:

```go
var srv = handler.NewDefaultServer(generated.NewExecutableSchema(NewRootResolvers()))
// I would expect to see your auth middleware wrap srv
var c = client.New(srv)
```

I would normally have a function that returns my fully decorated handler that I could then call from tests and in my server.

**Comment by mg98** [comment]
🤦  yeah of course. I'm sorry, I could have come up with this myself. Thank you very much!

**Comment by yashjain12yj** [comment]
@mg98 @lwc  Can you share, how can we add middleware?

**Comment by mg98** [comment]
@yashjain12yj, the code shared in https://github.com/99designs/gqlgen/issues/1330#issuecomment-697034992 should work, does it not?
