### ISSUE TITLE
enum of numbers fails to generate 

### ISSUE THREAD

**Issue by kaushikbiswas1984** [99designs/gqlgen#1331]
gqlgen is the latest.

enum like below is failing to generate.

enum PRODUCT_CLASS {
    0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
}

**Comment by art1415926535** [comment]
Enumeration value must start with any of `_`, `A-Z`, `a-z`

[spec](http://spec.graphql.org/June2018/#Name)

**Comment by kaushikbiswas1984** [comment]
Thanks.
