### ISSUE TITLE
How to implement gqlgen on non HTTP/WebSocket environment?

### ISSUE THREAD

**Issue by sitompul** [99designs/gqlgen#1332]
### What happened?
On github.com/graphql-go/graphql and github.com/graph-gophers/graphql-go i can easily modify the handler to handle non HTTP connection by adding the handler onto my preferred microservice protocol consumer (AMQP, Kafka  etc), since both of them just require params object or string to be passed on to the schema executor.
How can i achieve this in gqlgen?

### What did you expect?
Using gqlgen with any microservice protocol.

### Minimal graphql.schema and models to reproduce
```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

### versions
 - `gqlgen version`? 
**0.12.2**
 - `go version`?
**1.14**
 - dep or go modules?
**Modules**

**Comment by lwc** [comment]
The [executor](https://github.com/99designs/gqlgen/blob/master/graphql/executor/executor.go) is probably what you're looking for?

**Comment by sitompul** [comment]
@lwc yeah i think **Executor.CreateOperationContext** will do just fine
