### ISSUE TITLE
V0.12.0+ breaks with pointer to slices that worked in v0.11.3

### ISSUE THREAD

**Issue by ananyasaxena** [99designs/gqlgen#1333]
In v0.11.3 pointers to slices would call the custom Marshal and Unmarshal methods for each element in the slice

v0.12.2 Breaks this functionality and calls the custom Marshal and Unmarshal with the entire slice

here is a sample code to reproduce this issue 
https://github.com/ananyasaxena/gqlgen_err

It succeeds for v0.11.3 
In v0.12.2 we get the following error 
```
validation failed: packages.Load: /Users/ananya/gqltest/graphql_gen.go:1896:21: cannot convert tmp (variable of type string) to []item.Type
/Users/ananya/gqltest/graphql_gen.go:1904:38: cannot convert *v (variable of type []item.Type) to string
exit status 1
```

This issue seems to be reproducible from v0.12.0 onwards

**Comment by carldunham** [comment]
Still seeing this in 0.13.0

**Comment by carldunham** [comment]
Any update? The PR looks helpful...

**Comment by ravisastryk** [comment]
Can we get these changes into a new release with the latest bits?
