### ISSUE TITLE
validation error if no new models are generated

### ISSUE THREAD

**Issue by tobiges** [99designs/gqlgen#1335]
### What happened?
I specify a @goModel for every gql type I define. It always fails in the validation process because no gqlgen structs were generated.

> validation failed: packages.Load: -: no matching versions for query "latest"

### What did you expect?
No error.
### Minimal graphql.schema and models to reproduce
Just specify a go struct for every gqlgen type you define.
### versions
 - `gqlgen version`? 
v0.13.0
 - `go version`?
go version go1.15.2 linux/amd64
 - dep or go modules?
go modules

**Comment by cyrilzh** [comment]
#1197
