### ISSUE TITLE
Unable to generate code from schema on go < 1.14 (1.13 might work)

### ISSUE THREAD

**Issue by rbUUbr** [99designs/gqlgen#1343]
### What happened?
Was unable to perform:
`go get github.com/99designs/gqlgen`
with go version 1.12.9
saw an error:
`go1.12.9/global/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/error.go:21:5: undefined: errors.As`
### What did you expect?
Expected no errors from `gqlgen` library
### versions
 - `gqlgen version` 0.13.0
 - `go version` 1.12.9
 - go modules
Also I'm using gvm (https://github.com/moovweb/gvm) for go versioning

**Comment by lwc** [comment]
Since https://github.com/99designs/gqlgen/releases/tag/v0.13.0 we only support go 1.13 and upwards, this is in line with the supported versions of Go itself.
