### ISSUE TITLE
Stop processing large POST requests

### ISSUE THREAD

**Issue by ScottyFillups** [99designs/gqlgen#1362]
### What happened?

Hi, I'm wondering if there's a way to limit the number of bytes processed for a request body.

I found options such as `handler.UploadMaxSize`, but there doesn't seem to be anything limiting the POST transport: https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_post.go#L34

It would be nice to be able to limit the number of bytes read for the request body, like so: https://stackoverflow.com/questions/33766070/stop-processing-a-http-post-request-if-it-is-larger-than-x-size

**Comment by bofia** [comment]
You can do this with a relatively simple router middleware:
```go
func Middleware(maxBytes int64) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r.Body = http.MaxBytesReader(w, r.Body, maxBytes)
			next.ServeHTTP(w, r)
		})
	}
}

```
