### ISSUE TITLE
Migrate to GraphiQL from Playground

### ISSUE THREAD

**Issue by bofia** [99designs/gqlgen#1367]
### What happened?
Playground is being deprecated and combining with GraphiQL: https://github.com/graphql/graphql-playground/issues/1143

### What did you expect?
gqlgen should stay up-to-date with its IDE

### Minimal graphql.schema and models to reproduce
N/A

### versions
 - `gqlgen version`? 0.13.0
 - `go version`?
 - dep or go modules?

**Comment by Sonamp** [comment]
Is there any update or plan on the playground migration.

**Comment by jbowa** [comment]
+1

**Comment by spdrstar** [comment]
Checking on this. File upload would be nice

**Comment by Dysar** [comment]
Any updates?
