### ISSUE TITLE
Dataloaders cache in a subscribtion 

### ISSUE THREAD

**Issue by microo8** [99designs/gqlgen#1368]
### What happened?
The client is using a subscribtion to get the latest jobs to do.
The job object looks something like this:
```
type Job {
   arg1 String!
   arg2 String!
   subJob SubJob
}
```

and the struct and resolver for the Job:
```go
type Job struct {
  Arg1 string
  Arg2 string
  SubJobID int
}

type jobResolver struct{
  db *sql.DB
}

func (r *jobResolver) SubJob(ctx context.Context, obj *Job) (*SubJob, error) {
    return getSubJobDataloader(ctx).Load(obj.SubJobID)
}
```

Every time the Job object is changed, or the SubJob object is changed, the server is sending the whole Job object to the client.

```go
func (s *subscribtion) Jobs(ctx context.Context, param string) (<-chan *Job, error) {
  ch := make(chan *Job, 10)
  go func() {
   jobIDChan := getJobChangeListener(ctx)
   for jobID := range jobIDChan {
        job, err := getJobDataloader(ctx).Load(jobID)
        if err != nil {
           log.Println("ERROR:", err)
           continue
        }
        ch <- job
   }
  }()
  return ch, nil
}
```

But when I send the new Job object, then the SubJob is loaded with a dataloader in jobResolver.SubJob, and it is the old version, because the dataloader uses a cache, and the cache is never cleared and because of the long running connection for the subscribtion, the dataloader is used over and over again.

### What did you expect?

Getting the up to date Job and SubJob object. Some kind of mechanism to clear the dataloader cache, or to forbit the use of cache for the dataloader when used in a subscribtion.

### Minimal graphql.schema and models to reproduce

```
query {
   allJobs: [Job]!
}

mutation {
   createJob(job: JobInput): Job
   updateJob(id: Int!, obj: JobInput): Job
   deleteJob(id: Int!): Boolean!
}

subscribtion {
   jobs(param: String!): [Job]!
}

type Job {
   arg1 String!
   arg2 String!
   subJob SubJob
}
```

### versions
 - `gqlgen version`?  v0.13.0
 - `go version`? go version go1.15.3 linux/amd64
 - dep or go modules? modules

**Comment by NateScarlet** [comment]
Maybe there is a `Clear` method on your dataloader?

Like https://github.com/vektah/dataloaden/blob/9d6b85cf15084a11c813eb0ee91c604b0e4a1de0/pkg/generator/template.go#L186

**Comment by wilhelmeek** [comment]
The above comment is correct. Depending on your use case you may need to invalidate the dataloader using `.Clear()`.
