### ISSUE TITLE
List input coercion not work when using variables

### ISSUE THREAD

**Issue by NateScarlet** [99designs/gqlgen#1369]
### What happened?

frontend code results `must be an array` error after i switch from apollo-server to gqlgen

![image](https://user-images.githubusercontent.com/21083014/96971515-cb251b00-1547-11eb-93e6-a045e85d6f86.png)

#244 added support for literal values but not variables

### What did you expect?

Pass single value as array variable should not error.

https://spec.graphql.org/June2018/#sec-Type-System.List

### Minimal graphql.schema and models to reproduce

schema:
```graphql
type Todo {
  name: String!
}

type Query {
  todos(name: [String!]): [Todo!]
}
```
query:
```grapqhl
query todos($name: [String!]) {
  name
}
```
variables:
```json
{"name": "foo"}
```

### versions
 - `gqlgen version`?: 0.13.0
 - `go version`?: 1.14
 - dep or go modules?: go modules

**Comment by NateScarlet** [comment]
https://github.com/vektah/gqlparser/blob/b778db6115bc4ae40c63fa4a9c2e9805344ce182/validator/vars_test.go#L154-L160

This is a upstream issue

**Comment by NateScarlet** [comment]
after upgrade gqlparser to v2.2.0

the error changed to `[]string is not a string` because `[]string` is not assignable to `[]interface{}`

need update
https://github.com/99designs/gqlgen/blob/3f68ea27a1a9fea2064caf877f7e24d00aa439e6/codegen/type.gotpl#L13-L17

**Comment by NateScarlet** [comment]
This seems fix the issue
```golang
func normalizeVariableValue(v interface{}) interface{} {
	var rv = reflect.ValueOf(v)
	switch rv.Type().Kind() {
	case reflect.Array:
		fallthrough
	case reflect.Slice:
		var ret = make([]interface{}, rv.Len())
		for i := range ret {
			ret[i] = rv.Index(i).Interface()
		}
		return ret
	}
	return v

}

// Issue1369Fix https://github.com/99designs/gqlgen/issues/1369
type Issue1369Fix struct{}

func (Issue1369Fix) ExtensionName() string {
	return "Issue1369Fix"
}
func (Issue1369Fix) Validate(schema graphql.ExecutableSchema) error {
	return nil
}

func (Issue1369Fix) MutateOperationContext(ctx context.Context, rc *graphql.OperationContext) *gqlerror.Error {
	for k, v := range rc.Variables {
		rc.Variables[k] = normalizeVariableValue(v)
	}
	return nil
}

var _ interface {
	graphql.OperationContextMutator
	graphql.HandlerExtension
} = Issue1369Fix{}
```

then `server.Use(Issue1369Fix{})`

**Comment by frederikhors** [comment]
@NateScarlet please tell me if this is still an issue with v0.16.0 and I'll re-open it.
