### ISSUE TITLE
Multiple import package use _ to import

### ISSUE THREAD

**Issue by zhangxiang958** [99designs/gqlgen#1380]
https://github.com/99designs/gqlgen/blob/3a31a752df764738b1f6e99408df3b169d514784/codegen/templates/import.go#L133

if i use Multiple import in plugin like:
```
{{ reserveImport "github/a" "_" }}
{{ reserveImport "github/b" "_" }}
```
it will return "ambient import collides on an alias" error，why not just ignore the "_" keyword ?

**Comment by frederikhors** [comment]
@zhangxiang958 please tell me if this is still an issue with v0.16.0 and I'll re-open it.
