### ISSUE TITLE
Generation of models fails with mismatch type error

### ISSUE THREAD

**Issue by MrDHat** [99designs/gqlgen#1385]
### What happened?
Generation of models failed with the following error:
```
# auth/graph/generated
graph/generated/generated.go:12217:9: cannot use &res (type *string) as type *[]string in return argument
graph/generated/generated.go:12224:31: cannot use *v (type []string) as type string in argument to graphql.MarshalString
```
### What did you expect?
Generation to succeed

### versions
 - `gqlgen version`? 
`0.13.0`
 - `go version`?
`go version go1.13.1 linux/amd64`
 - dep or go modules?
`go modules`

**Comment by MrDHat** [comment]
Realised that this error started coming after I updated gqlgen `v0.11.3` to `0.13.0`

**Comment by MrDHat** [comment]
Can anyone help out here please?

**Comment by mfcochauxlaberge** [comment]
Seeing some lines of code would be useful.

**Comment by frederikhors** [comment]
@MrDHat please tell me if this is still an issue with v0.16.0 and I'll re-open it.
