### ISSUE TITLE
Does not generate schema.resolvers.go file (Federation)

### ISSUE THREAD

**Issue by andrepinto** [99designs/gqlgen#1388]
### What happened?
Does not generate schema.resolvers.go file (Federation)

### What did you expect?
Create file  schema.resolvers.go when run ` go run github.com/99designs/gqlgen generate` and

graph/generate.go 

```
type ResolverRoot interface {
	Entity() EntityResolver
}
```

expected 

```
type ResolverRoot interface {
	Entity() EntityResolver,
        User() UserResolver
}
```

### Minimal graphql.schema and models to reproduce

```
type Account {
  body: String!
  author: User! @provides(fields: "username")
}


extend type User @key(fields: "id") {
  id: ID! @external
  accounts: [Account]
}
```

### versions
 - `gqlgen version`? 
     0.13.0
 - `go version`?
     1.15.1
 - dep or go modules?
    go mod

**Comment by MichaelJCompton** [comment]
Tracking on https://github.com/99designs/gqlgen/issues/1454

**Comment by jekjeki** [comment]
i have issue in "runtime error: invalid memory address or nil pointer dereference" when i build graphql with gorm and postgres
