### ISSUE TITLE
Codegen broken since v0.12 using external map scalar types

### ISSUE THREAD

**Issue by fredbi** [99designs/gqlgen#1391]
### What happened?

* I have a schema with imported scalar types.
* works fine with gqlgen =< v0.11.3
* breaks start with v0.12:
```
codegen: generating core failed: type.gotpl: template: type.gotpl:49:28: executing "type.gotpl" at <$type.Elem.GO>: nil pointer evaluating *config.TypeReference.GO
```

The faulty template code in `codegen/type.gotpl` is:
```
@@ -46,7 +46,21 @@
                                        return v.(map[string]interface{}), nil
                                {{- else if $type.IsMarshaler }}
                                        {{- if $type.IsNilable }}
-                                               var res = new({{ $type.Elem.GO | ref }})
```

Investigating further, the template fails when looping over my scalar types.

In my case, scalar types are maps, e.g. `map[string]interface{}`, `map[string]string`, `map[string]float64`.
This hits the case of a nullable type with no (known) element type (there is one, but it is not introspected, as only slices are introspected for the type of their element).

### What did you expect?
Successful codegen

### Minimal graphql.schema and models to reproduce
 (TODO)

### versions
 - `gqlgen version`? v0.12.x, v0.13.0, current master
 - `go version`? 1.15.3
 - dep or go modules? go modules

**Comment by fredbi** [comment]
Maybe a duplicate (or at least a special case) of #1293

**Comment by frederikhors** [comment]
@fredbi please tell me if this is still an issue and I'll re-open it.
