### ISSUE TITLE
[Doc]: How to return custom error type?

### ISSUE THREAD

**Issue by hsblhsn** [99designs/gqlgen#1397]
### What happened?
I want to show my user a special type of error message.

### What did you expect?
I want to return this to the end user.
```
{
  "error": {
    "title": "Permission denied",
    "message": "You are not allowed to access this.",
    "type": "Forbidden",
    "code": 32321,
    "request_id": "busvdh2-btmil6m45a-p90",
    "trace_id": "busvdh2-btmil6m45a-p9g"
  }
}
```

How to do this with `gqlgen`?

I am very new to `gqlgen`, so expecting an example code (minimal).

### versions
 - `gqlgen version`? 
v0.13.0-dev
 - `go version`?
go version go1.15.5 darwin/amd64
 - dep or go modules?
 go modules

**Comment by MichaelJCompton** [comment]
Answering this old question for posterity in case anyone else needs helps.

There's a section in the docs that talks about handling errors : https://gqlgen.com/reference/errors/

Also, as per the spec (https://spec.graphql.org/June2018/#sec-Errors), in general, GraphQL errors should be formatted with `message`, `locations` and `path`, with `extensions` used for any other app-specific data.  So the example error message in the question might look like

```
{
  "error": {
      "message": "You are not allowed to access this.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "title": "Permission denied",
        "type": "Forbidden",
        "code": 32321,
        "request_id": "busvdh2-btmil6m45a-p90",
        "trace_id": "busvdh2-btmil6m45a-p9g"
      }
  }
}
```

That's what will come out of gqlgen.  Which can be done either by creating an error in the resolver

```
graphql.AddError(ctx, &gqlerror.Error{ ... })
```

or by using the error presenter to set the extensions values from your custom error type (both options are in the linked doc).
