### ISSUE TITLE
Incompatible resolver function

### ISSUE THREAD

**Issue by mustafacol** [99designs/gqlgen#1407]
### What happened?
Resolver function does not return array of object(Question) even its return type []*prisma.Question 
### What did you expect?
Return array of object 
Triggered QuestionExecArray
### Minimal graphql.schema and models to reproduce
```
type User {
  id: ID! @id
  email: String! @unique
  password: String!
  phone:String!
  step:Int
  profile: Profile
  preference : Preference
  questions : [Question!]
  createdAt: DateTime! @createdAt
}
type Question @embedded{
  qid:          Int!
  forMe:        Int!
  forOther:     Int!
  importance:   Int!
}
```
### versions
 - `gqlgen version`?  v0.13.0
 - `go version`? go1.15.5 windows/amd64
 - dep or go modules? Prisma CLI version: prisma/1.34.10 (windows-x64) node-v14.15.1 Prisma server version: 1.34.10

**Comment by frederikhors** [comment]
Please format your code using: ```go.

Can this help you? https://github.com/99designs/gqlgen/pull/874

If yes please close this issue.

**Comment by mustafacol** [comment]
It still does not work for @embedded

**Comment by mustafacol** [comment]
Sorry but does not work
