### ISSUE TITLE
GRPC status code inaccessible in error presenter

### ISSUE THREAD

**Issue by karthikraobr** [99designs/gqlgen#1411]
### What happened?
The `status.FromError` method from the `grpc` package doesn't return a valid status code (always returns the default value of 0) in a custom error presenter. The method works as advertised in the resolver where the error was created, but as soon as it is received in the custom error presenter, the status information seems to be stripped. Is this because of the wrapping of error messages before it is passed to the error presenter newly introduced in v0.13.0?

### What did you expect?
The `grpc` status codes should be preserved and passed on the custom error presenter.

### versions
 - `gqlgen version`? 
v0.13.0
 - `go version`?
v1.15.2
 - dep or go modules?
modules

I would be happy to create a PR (would need some pointers though :)) if this issue is accepted.

**Comment by gyqsophila** [comment]
meet the same issue, can't reslove err by `ststus.FromError()`

**Comment by gyqsophila** [comment]
hello i want tell you i found how to resolve this issue:
``` go
err := graphql.DefaultErrorPresenter(ctx, e)
if status, ok := status.FromError(err.Unwrap()); ok {
        return &gqlerror.Error{
	        Path:    graphql.GetFieldContext(ctx).Path(),
	        Message: status.Message(),
	        Extensions: map[string]interface{}{
		        "code": uint32(status.Code()),
	        },
        }
}

```

**Comment by wilhelmeek** [comment]
Closing this out as it appears that we've found a solution 😄
