### ISSUE TITLE
Autobind config is not honored if I use modelgen example, why?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1423]
### What happened?

I'm trying to use the amazing hint by @AienTech here: https://github.com/99designs/gqlgen/issues/463#issuecomment-591646419 and using `models.go` from https://github.com/99designs/gqlgen/tree/master/plugin/modelgen with `autobind` in `gqlgen.yml` generated the types I already have in my packages.

### What did you expect?

Gqlgen with modelgen `models.go` does not generate models already in packages declared in `gqlgen.yml` > `autobind` config prop.

### versions
 - `gqlgen version`? 0.13.0
 - `go version`? 1.15.6
 - dep or go modules? go mod

**Comment by novikov1337danil** [comment]
Did you find a solution to the problem? 
Or maybe you found another way to specify additional tags in the generated structures?

**Comment by Virinchi2595** [comment]
any update on this?
