### ISSUE TITLE
Introspection query does not have stable sort order of fields and types

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1426]
### What happened?

Introspection query does not have stable sort order of fields and types

### versions
 - `gqlgen version`? 0.13.0

**Comment by pietdevries94** [comment]
We use the introspection to generate types on the frontend, but because the introspection is unstable, the generated code is also unstable, which creates false merge/rebase conflicts.

**Comment by nyergler** [comment]
@frederikhors Any chance you can share said script? This makes the life with gqlgen pretty painful.

**Comment by duckbrain** [comment]
@nyergler; here is a plugin we wrote that does it by wrapping each field with middleware and sorts the results if it's an introspection field.

 https://pkg.go.dev/github.com/ec2-software/gqlgen-introspect-filter#SortPlugin

**Comment by nyergler** [comment]
Thanks for the pointer, @duckbrain; I have a PR open to make the ordering stable, but a plugin may wind up being more straight-forward for tracking upstream.
