### ISSUE TITLE
implement multiple files

### ISSUE THREAD

**Issue by alihossein** [99designs/gqlgen#1427]
### What happened?

thanks for this package. 

is there any solution for multiple resolvers files?

### What did you expect?
for example, I have two types (user and post) :
instead of `query.resolvers.go` I want to have 2 files named : 

1. user.resolvers.go
2. post.resolvers.go

and in these files, I write my logic code.
### Minimal graphql.schema and models to reproduce
   
 ```
 type user struct {
	ID          int   
	name     string 
}
```
```
type post struct {
	ID          int   
	title     string 
}
```

### versions
 - `gqlgen version`?  v0.13.0

 - `go version`? go version go1.15.6 linux/amd64
 - dep or go modules?  go modules

**Comment by diep-it-dn** [comment]
Example gqlgen.xml config part: 
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - graph/graphql/*.graphql

# Where should the generated server code go?
exec:
  filename: graph/generated/generated.go
  package: generated

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: graph/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graph/resolver
  package: resolver

-----
Then in ./graph/graphql/user.graphql file, you can define like this:
extend type Query {
  currentUser: User! @isLoggedIn
  ...
}
extend type Mutation {
...
}

**Comment by alihossein** [comment]
@diep-it-dn thanks for your answer. but I did not understand your mean. I am sorry.

I need 2 files (instead of `query.resolvers.go` ) to write my logic. 

actually, I write all logic in one file (query.resolvers.go) and this file became very long.

**Comment by diep-it-dn** [comment]
Hi @alihossein 
After you configured as I commented above, you can rerun the command:
$go run github.com/99designs/gqlgen generate
it will create the resolver files in the folder: ./graph/resolver

If in ./graph/graphql folder has 2 files: user.graphql, post.graphql => output 2files: user.resolvers.go, post.resolvers.go
Then you can move the logic code in query.resolvers.go to these resolvers and delete query.resolvers.go

About @isLoggedIn: Just a sample directive. We can configure the directive to check permissions... You can read more about it here: https://gqlgen.com/reference/directives/

**Comment by alihossein** [comment]
wow. excellent @diep-it-dn  . 

it's worked for me.

**Comment by clshu** [comment]
It works great for me too. Thanks.

**Comment by adrianescat** [comment]
Hello! this solution is not working for my 100%

I can separate resolvers and graphqls files now, but when I want to serve the server:

```go
srv := handler.NewDefaultServer(graph.NewExecutableSchema(graph.Config{Resolvers: &graph.Resolver{
  ...
}}))
```

It can't resolve `&graph.Resolver` : _Unresolved type 'Resolver'_

I'm importing:

`graph "my.pkg.com/graph/generated"`

What am I missing?

**Comment by argatu** [comment]
@adrianescat The resolvers now are in the resolver package but you are using the old graph package.

Change the code to this and it should work.
`srv := handler.NewDefaultServer(resolver.NewExecutableSchema(resolver.Config{Resolvers: &resolver.Resolver{
  ...
}}))`

**Comment by MuhammadSaadQadeer** [comment]
Is there anything else that has to be updated, because I have tried this and it  doesn't work, the `resolver` does not have `NewExecutableSchema` option on it

**Comment by MuhammadSaadQadeer** [comment]
So this worked for me 

`srv := handler.NewDefaultServer(src.NewExecutableSchema(src.Config{Resolvers: &resolver.Resolver{
		DB: db,
	}}))`
	
you only have to update the resolver not the entire thing

**Comment by hwoodall30** [comment]
@diep-it-dn 

I have everything set up like you mentioned above, and everything is working as expected besides the generated resolvers. Would you mind trying to help me out with that?

So basically what I am running into is I have a `typeDefs` folder that has:
1. todo.graphql
2. user.graphql

I want to then generate a `resolvers` folder that has:
1. todo.resolvers.go
2. user.resolvers.go

The issue I am now running into is that every time I regenerate the code, this piece of code is added to the todo.resolvers.go, but I have manually moved it into the resolver.go

```
// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
```

My resolver.go file:

```
package resolvers

//go:generate go run github.com/99designs/gqlgen generate

import (
	"github.com/hunter-woodall/xgen-gql/graph/generated"
	"github.com/hunter-woodall/xgen-gql/graph/model"
)

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require here.

type Resolver struct {
	todoList []*model.Todo
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
```

Is there any way to prevent this code from being added so that every time I regenerate, I don't have to remove this?

**Comment by dratner** [comment]
I'm having that issue as well ... I'm actively developing the app and adding and tweaking models all the time. Every time I regenerate it makes new stubs for the code I already moved to model-specific resolver files. Did you ever find an answer to this?
