### ISSUE TITLE
Scalar Timestamp converts to string

### ISSUE THREAD

**Issue by hyperxpizza** [99designs/gqlgen#1428]
### What happened?
gqlgen for some reason converts Timestamp scalar to string instead of time.Time

schema.graphqls
```
scalar Timestamp

type Test {
  time: Timestamp!
}
```

then run: 
```bash
go run github.com/99designs/gqlgen generate
```

output models_gen.go :
```
package model

type Test struct {
	Time string `json:"time"`
}
```

Is there any way to solve this?

### versions
 - `gqlgen version`?  v0.13.0
 - `go version`? go version go1.15.6 linux/amd64

**Comment by diep-it-dn** [comment]
Hi, you can try to use: `scalar Time` instead of `scalar Timestamp`

**Comment by frederikhors** [comment]
@hyperxpizza if @diep-it-dn's hint works please close this issue.

**Comment by hyperxpizza** [comment]
i

**Comment by dotsinspace** [comment]
Where can i find cusom scalars like we used to have in node.js...it will be much for easy to handle these scalars.
