### ISSUE TITLE
gqlgen not generate graph/schema.resolvers.go for reviews server in the federation example

### ISSUE THREAD

**Issue by guichuan2018** [99designs/gqlgen#1429]
### What happened?
 
Wanted to recreate the federation example following the steps described at https://gqlgen.com/recipes/federation/. (The steps are not very clear though)

However, the following go run command did not generate graph/schema.resolvers.go for the reviews server after running "go run github.com/99designs/gqlgen"

Note: the file schema.resolvers.go does be listed in the official example repo though. That is, github.com/99designs/gqlgen@v0.13.0/example/federation/reviews/graph/schema.resolvers.go

### What did you expect?
graph/schema.resolvers.go is expected to be generated for reviews service. However, it was not generated.

### Minimal graphql.schema and models to reproduce

type Review {
    body: String!
    author: User! @provides(fields: "username")
    product: Product!
}

extend type User @key(fields: "id") {
    id: ID! @external
    reviews: [Review]
}

extend type Product @key(fields: "upc") {
    upc: String! @external
    reviews: [Review]
}

### versions
 - `gqlgen version`? 
  v0.13.0

 - `go version`?
 go version go1.15.5 linux/amd64

 - dep or go modules?

**Comment by vectorhacker** [comment]
@guichuan2018 I've had this issue as well and it rises from the problem that gqlgen does not also generate the _Service and _service: Service! type and fields in the graphql schema. Adding them to the schema manually seems to fix this as the resolver is generated correctly this way.

Just adding those to the schema for your service and enabling federation will enable it to work properly

**Comment by r0busta** [comment]
Same issue here. And unfortunately, @vectorhacker solution doesn't fix the issue, as the `_Service` type is, in fact, injected during the code generation and defining `_Service` again causes the following error `failed to load schema: federation/entity.graphql:13: Cannot redeclare type _Service.exit status 1`.

**Comment by r0busta** [comment]
Just FYI, I solved this by replacing the 99designs federation solution with schema stitching https://www.graphql-tools.com/docs/stitch-combining-schemas

Works like a breeze, and no need to use the federation directives bloat.

**Comment by lkasser1** [comment]
@r0busta FYI, schema stitching has a whole host of scalability problems, and was replaced by federation (which has much more loosely coupled models). I ran into the same issue you're having, but the workaround given [here](https://github.com/99designs/gqlgen/issues/1454) works for me.

**Comment by r0busta** [comment]
@lkasser1, yeah, I'm not sure about this. Every approach has pros and cons. Stitching, for example, is also a nice pattern as it enforces separation of concerns, and hence, it's greatly aligned with the concepts of good API design and microservice architecture.

**Comment by MichaelJCompton** [comment]
Closing for https://github.com/99designs/gqlgen/issues/1454.

Also adding more explanation to docs.
