### ISSUE TITLE
Will the graph-transport-ws subprotocol be implemented?

### ISSUE THREAD

**Issue by Restraint** [99designs/gqlgen#1430]
It seems like gqlgen is currently implementing the subprotocol defined here:
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

Seeing as how that package says it's no longer being actively maintained, I was wondering if there were any plans to move to the new subprotocol that they recommend?

https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

**Comment by glebselyukov** [comment]
Any updates?

**Comment by trey-wallis** [comment]
Hi, reopening this.

Do you guys have any plans to implement graph-ws?
