### ISSUE TITLE
Context not passed to child resolvers using subscriptions

### ISSUE THREAD

**Issue by bstanescu** [99designs/gqlgen#1433]
We are using authentication via an `authorization` token extracted from HTTP headers and via WebsocketInit. We store the token in the context in a key called `tknCtxKey`

### What happened?
The context passed to subsequent (child) resolvers are missing the values of the parent resolver context.
In our case, the field *Groups* is a child of *User* (a user can be part of many groups). Groups has its own resolver:
```yml
  User:
    fields:
      groups:
        resolver: true
```

If we query Users to return the Groups:
```gql
subscription {
  users {
    user {
      id
      groups {
        name
      }
    }
  }
}
```
We get the token in the Users resolver, but not in the Groups resolver:
```go
func (r *subscriptionResolver) Users(ctx context.Context) (<-chan []*model.User, error) {
  // ctx.Value(tknCtxKey) is available
...
}
func (r *userResolver) Groups(ctx context.Context, obj *model.User) ([]*model.Group, error) {
  // ctx.Value(tknCtxKey) is NOT available 😢 
}
```

Works as expected for simple queries (same _Groups_ function receives context):
```go
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
  // ctx.Value(tknCtxKey) is available
}
func (r *userResolver) Groups(ctx context.Context, obj *model.User) ([]*model.Group, error) {
  // ctx.Value(tknCtxKey) is available
}
```

### What did you expect?
Context to be propagated for subscriptions to resolvers

### Minimal graphql.schema and models to reproduce
```gql
type User {
  id: ID!
  groups: [Group!]
}
type Group {
  id: ID!
  name: String
}
type Subscription {
  users: [User!]
}
type Query {
  me: User
}
```
### versions
 - `gqlgen version`?
 github.com/99designs/gqlgen v0.13.0

 - `go version`?
 go version go1.14.3 darwin/amd64
 
 - dep or go modules?
go modules

**Comment by fpopa** [comment]
did you try fetching it via the context.Value function?

**Comment by maeglindeveloper** [comment]
Hi @vektah, @neelance , I have the same concern, is there any advice on this ? 
Thanks in advance :+1:

**Comment by maeglindeveloper** [comment]
@bstanescu, since you closed the issue, how did you solve that problem ?
