### ISSUE TITLE
request response logs

### ISSUE THREAD

**Issue by araufdogan** [99designs/gqlgen#1442]
Hello, I want to add request and response logs to my gqlgen server. How can I get the raw response? Here is my simple function;

```

h.AroundResponses(func(ctx context.Context, next gqlGraphql.ResponseHandler) *gqlGraphql.Response  {

	req := gqlGraphql.GetOperationContext(ctx)
	fmt.Println(req.Operation.Operation)
	fmt.Println(req.OperationName)
	fmt.Println(req.Stats.OperationStart)
	fmt.Println(req.RawQuery)
	fmt.Println(req.Variables)

	go func(){
		for {
			select {
			case <- ctx.Done():
				// TODO get response
				// TODO calculate elapsed time
				return
			}
		}
	}()

	return next(ctx)
})

```
### versions
 - `gqlgen version`? v0.13.0
 - `go version`? go1.14
 - dep or go modules? go modules

**Comment by wilhelmeek** [comment]
@araufdogan you should be able to read off the return type on `next`. Not the same interceptor type, but this issue (https://github.com/99designs/gqlgen/issues/1637) might be helpful.
