### ISSUE TITLE
How to get all fields without specifying the field names in a query

### ISSUE THREAD

**Issue by deepakmagadi** [99designs/gqlgen#1461]
### What happened?
Hi i'm new to graphql i'm implementing it using golang with `gqlgen` package.  I have defined a schema which is having more than 30 fields. 
For example this is my query 
`query={model_list{id, name, email, phone, date ...........................}}`
To get all fields in a response I need to send all field names in graphql query. It would be difficult to pass entire schema fields. 

### What did you expect?
I wanted to know how get all field values defined in a  schema without passing the field names in  a query . 
For example 
`query={model_list}`
in above query im just passing schema name not any field names. so in this case I need to get all values. 
### versions
 - `gqlgen version : v0.13.0`? 
 - `go version : 1.15`?
 - dep or go modules?

**Comment by cyberhck** [comment]
You don't, in GQL, you ask for what you need, but your SDK might be able to offer all fields, but not with simple way, not possible.

**Comment by MichaelJCompton** [comment]
Yeah, that's right.  GraphQL is deliberate in not allowing you to query for the equivalent of `*`.  

If you are investigating a schema with some sort of GUI, then you can always save your common queries.    In your code, you'll get some sort of support from your editor to select the fields you require.

It's pretty normal to want to reach for something like this when you first bump into GraphQL.  As you use it more, you'll be likely to understand that your queries want particular fields to render, for example, and that the GraphQL way makes quite some sense.
