### ISSUE TITLE
Generate Getters for Interface Fields

### ISSUE THREAD

**Issue by maaft** [99designs/gqlgen#1469]
Currently, when you have a schema like this:
```
interface Foo {
  value: String!
}

type FooA {
  bla: String!
}

type FooB {
  blub: String!
}
```

The generated go file will look like this:
```golang
type Foo interface {
   IsFoo()
}

type FooA struct {
   Bla string
   Value string
}

func (f FooA) IsFoo() {}

type FooB struct {
   Blub string
   Value string
}

func (f FooB) IsFoo() {}

```

Additionally, it would be great to also generate getters for all interface fields. This makes using typeswitches obsolet when you're not interested in the underlying type.

```golang
type Foo interface {
   IsFoo()
   
   GetValue() string
}

type FooA struct {
   Bla string
   Value string
}

func (f FooA) IsFoo() {}

func (f FooA) GetValue() string {
   return f.Value
}

type FooB struct {
   Blub string
   Value string
}

func (f FooB) IsFoo() {}

func (f FooB) GetValue() string {
   return f.Value
}
```

**Comment by elversatile** [comment]
This change makes a ton of sense and would make coding against interfaces a lot simpler.

**Comment by iyinoluwaayoola** [comment]
Hit this issue today; this will make the generated interfaces actually useful.

**Comment by cpurta** [comment]
This really should be something that is supported. It is extremely cumbersome to get around this as there is really only 1 way to get the `Value` in the example. Create helper function for each field that is included in the common interface definition and that has to use type-switching as stated before:
```go
func GetValue(foo Foo) string {
    switch f := foo.(type) {
    case FooA:
        return f.Value
    case FooB:
        return f.Value
    }
    return ""
}
```
If a new field is added to the interface graphql schema another helper function will need to be added. These have to be implemented in helper packages and adds more complexity than is really needed as opposed to just generating the Getters.

**Comment by neptoess** [comment]
If anyone is still wanting this functionality, feel free to review #2314 and let me know if it matches your expectations
