### ISSUE TITLE
Getting started tutorial fix

### ISSUE THREAD

**Issue by adrianmoya** [99designs/gqlgen#1473]
### What happened?
At the end of the tutorial, under finishing touches, it suggests to add the go generate comment to `resolver.go`. 

### What did you expect?
I think it should be to `schema.resolvers.go` as this is the file that gets generated, the other one it's supposed to be manually edited.

I can open a PR with this little fix.

**Comment by MichaelJCompton** [comment]
Hi, thanks for the note.

Yes it could also go in `schema.resolvers.go`.  However `resolver.go` isn't regenerated by running gqlgen - it's a one time create from init.  So it's also fine to go in there and as that file is general setup / dependence injection / etc.  It does feel appropriate to put the comment for go generate there.  Either should be fine though.
