### ISSUE TITLE
how to serialization result of gqlgen by apache arrow ?

### ISSUE THREAD

**Issue by hunght3101** [99designs/gqlgen#1475]
### What did you expect?
i want serialization result of gqlgen by apache arrow
### Minimal graphql.schema and models to reproduce
now result format:
```
{
    "rows": [
        {
            "timestamp": "2021-03-01T09:00:00",
            "index": 100
        },
        {
            "timestamp": "2021-04-03T09:00:01",
            "index": 101
        }
    ]
}
```
expect json format:
```
{
    "rows": "XXXXXXXXX"
}
"XXXXXXXXX" :  Byte array converted from result of graphql by Apache Arrow
```
### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?

**Comment by imiskolee** [comment]
can not understand the expect json format from your example, can you try to explain more details ?

**Comment by hunght3101** [comment]
> can not understand the expect json format from your example, can you try to explain more details ?

Sorry, expect json format with value is byte array converted from result of graphql by Apache Arrow

**Comment by MichaelJCompton** [comment]
Hi, thanks for the question.  Sorry, I'm a little confused about what's being asked here.

I think you want your GraphQL server to output 

```
{
    "rows": "XXXXXXXXX"
}
```

Is that right?  If so, then you'll probably want something like a schema where `rows` is of type `String` and your resolver will be in charge of taking results and converting them to the right format.  If that's not right, please get back in touch with some more info and I'll see how I can help.

**Comment by hunght3101** [comment]
Thanks you for your help
I did it by used Scalar type custom.
