### ISSUE TITLE
[PROBLEM] EOF - error 

### ISSUE THREAD

**Issue by Dagetby** [99designs/gqlgen#1478]
### What happened?
Hi! 
We catch the EOF error at different times under different circumstances. It can happen several times in a day. I decided to replace the gorilla/websocket library with gobwas/ws after replacing websocket - this error became permanent.

It seems that this error is related to the incorrect closing of the connection.

This link partially described the problem
[link](https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi/17735392#17735392)

### What did you expect?
Work without errors. 

### Minimal graphql.schema and models to reproduce
The structure of the message that we read in the subscription

`operationMessage struct {
		Payload json.RawMessage json:"payload,omitempty"
		ID      string          json:"id,omitempty"
		Type    string          json:"type"
	}`

**Comment by wilhelmeek** [comment]
@Dagetby checking in. Has this problem persisted? Unfortunately there doesn't seem to be much to go on here, so any additional information would be handy.

**Comment by wilhelmeek** [comment]
Closing this out for now, but please open up another issue (preferably with some more info) if you're still experiencing this issue.
