### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by carldunham** [99designs/gqlgen#1482]
It seems like there has been very little attention to issues or merge requests here in the last several months. Just wondering if we should continue to invest energy here, or move on? Appreciate the volunteer nature of open source, but I thought this was sponsored by 99designs. Hope everyone is ok there.

**Comment by oreqizer** [comment]
I damn well hope this is not true — using this in production on a moderately large app 😕 I hope somebody will pick it up, the project is brilliant

**Comment by MichaelJCompton** [comment]
Hi, thanks for the question.

Things have been changing quickly at 99designs and lots of growing, so maybe there's a bit of a lull here - you can read the answer to a similar recent question https://github.com/99designs/gqlgen/issues/1386.

Safe to say it's not going anywhere - we use it everyday.

I'm new at 99designs, but really wanting to spend some of my time in here.  At least in the short term, I'll be fighting back the issues and PRs lists as much as I can.  

We're always happy for PRs, issues, comments and feature requests :-)
