### ISSUE TITLE
How to pass data from directives middleware to resolvers

### ISSUE THREAD

**Issue by appcypher** [99designs/gqlgen#1486]
### What happened?
I have managed to set up a validation directive and I would like to check for validation errors right before the resolver runs so that I can stop the operation from moving forward.

Right now, I'm trying to achieve that by injecting a `validationErrorExists` value into `ctx` so that I can use it later in a resolver function but the value is not getting added.

### What did you expect?
I expect to get injected value from `ctx` when retrieved with `ctx.Value` function.

### Minimal graphql.schema and models to reproduce
`user.graphqls`
```gql
directive @validate(rules: String) on INPUT_FIELD_DEFINITION

// ...

input UserInput {
  email: String! @validate(rules: "email")
  password: String! @validate(rules: "lt=5")
}

type Mutation {
  createUser(user: UserInput!): User!
}
```

`directives.go`
```go
func Validate(validate *validator.Validate) directiveFunc {
	return func(ctx context.Context, obj interface{}, next graphql.Resolver, rules *string) (interface{}, error) {
		fieldValue, err := next(ctx)
		if err != nil {
			return fieldValue, err
		}

		err = validate.Var(fieldValue, *rules)
		if err != nil {
			// Add error message to response.
			graphql.AddError(ctx, &gqlerror.Error{
				Path:    graphql.GetPathContext(ctx).Path(),
				Message: "input validation failed",
			})

			// Add information regarding the existence of a validation error.
			context.WithValue(ctx, validationErrorExists, true)
		}

		return fieldValue, nil
	}
}

func ValidationErrorExists(ctx context.Context) bool {
	val, ok := ctx.Value(validationErrorExists).(bool)
	fmt.Println(">> Value set:", ok) // PROBLEM: Returns false always
	return val
}
```

`user.resolvers.go`
```go
func (r *mutationResolver) CreateUser(ctx context.Context, user model.UserInput) (*model.User, error) {
	// Check for validation errors.
	if directives.ValidationErrorExists(ctx) {
	 	// PROBLEM: Not reaching here.
	}

	// ...
}
```

### versions
 - `gqlgen version`? 
     -  v0.13.0
 - `go version`?
     - 1.15.2
     
 - dep or go modules?
     - go modules

**Comment by lwc** [comment]
Unfortunately due to the immutable nature of `context.Context`, your `context.WithValue` is returning a new context that you're subsequently letting fall out of scope at the end of the directive.

To make this work you'd need to always wrap the context with a validation state carrying context on this line e.g:
```
fieldValue, err := next(validate.WrapContext(ctx))
```

Alternatively, you _may_ be able to use [`graphql.GetFieldErrors`](https://github.com/99designs/gqlgen/blob/master/graphql/context_response.go#L81) or a related function in that package to find the error you added via `graphql.AddError` in the directive, but I've never actually tried to do that, so YMMV 😀

**Comment by appcypher** [comment]
`graphql.GetFieldErrors` seems to always return an empty list in a resolver. `graphql.GetErrors` works but I would prefer not to iterate through the list of errors just to check if a validation error exist.

The context wrapping could have indeed worked but I ended up implementing a plugin that allows custom struct tags.

I will try the context wrapping thing if I need to pass data between directives and resolvers again in the future.
