### ISSUE TITLE
View the queried client fields so that resources can be saved

### ISSUE THREAD

**Issue by sneakykiwi** [99designs/gqlgen#1496]
Hello,

I am looking to find if there is a way to view queried fields. I have a subscription which conveys a huge amount of data which is not always needed to be calculated. I am looking to find a way to maybe cut down the resources used to retrieve the data needed for the frontend, I have been searching around but there is no issue for `gqlgen` similar to my problem. I would appreciate it a lot if someone knew how to do that

**Comment by MichaelJCompton** [comment]
I think what you are looking for is field collection : https://gqlgen.com/reference/field-collection/.

Please get back in touch if that isn't right.
