### ISSUE TITLE
Is it possible to seperate "gqlgen.yml" file into different files?

### ISSUE THREAD

**Issue by keyyangxie** [99designs/gqlgen#1499]

**Comment by MichaelJCompton** [comment]
Hi,

Is the gqlgen.yml file so big that you need to split it up?

The command itself only reads one file, but you might be able to make it part of either your build procedure or `go generate`.  

For example, if you are using `//go:generate go run github.com/99designs/gqlgen`, then you can always add more  `//go:generate ...` lines above that and concatenate multiple files into one there, so every time you generate, you rebuild the config file.

**Comment by lwc** [comment]
Have you seen [Inline config with directives](https://gqlgen.com/config/#inline-config-with-directives)? This approach allows for binding to happen in the schema itself, removing the need for a lengthy gqlgen.yml. Diffs much better too!
