### ISSUE TITLE
How to add schema type documentation?

### ISSUE THREAD

**Issue by neel1996** [99designs/gqlgen#1500]
I would like to add a detailed schema documentation for my GQL API setup using gqlgen. This is to give a short description for all the types present in the API. The sample is as follows

![image](https://user-images.githubusercontent.com/47709856/112790439-f8d53980-907c-11eb-9a1e-4cf3be484789.png)

Is there a way to achieve the same with gqlgen ?

**Comment by MichaelJCompton** [comment]
Hi, thanks for the question.  There's two types of things you can add to the schema: comments and descriptions.

Comments look like this:

```graphql
# this is a comment
type Atype {
  ...
}
```

That's just in the source and doesn't come out when introspecting the server.

Descriptions look like this:

```graphql
"""
A block description that could have multiple lines

like this
"""
type Atype {
  "a single line description"
  afield: Blaa
}
```

Those are the ones that you see in the schema in a GraphQL tool like in your screenshot.

All of those work in gqlgen.

Some examples from the GraphQL spec here : https://spec.graphql.org/June2018/#sec-Descriptions
