### ISSUE TITLE
Getting Started Documentation Clarity

### ISSUE THREAD

**Issue by bobbywilson0** [99designs/gqlgen#1506]
### What happened?

Following the 'Getting Started' guide, seeing error: `method CreateTodo already declared for type mutationResolver struct{*Resolver}`. I understand this is because `gqlgen generate` copies the `resolver.go` implementation to `schema.resolvers.go` but it's unclear why it would do this if the implementation exists in the same package. 

There is a StackOverflow [issue](https://stackoverflow.com/questions/60669166/golang-gqlgen-error-trying-to-import-model-into-resolver-go) that doesn't really explain why this is they way it is as well. 

### What did you expect?

I would expect that the generator would be able to generate code that didn't produce an error.

### Minimal graphql.schema and models to reproduce

The default generated schema. 

```
# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

### versions
 - `gqlgen version`? v0.13.0 
 - `go version`? go1.15.6 darwin/amd64
 - dep or go modules? go modules

### Additional Notes

I think that there is likely an easy explanation for the correct workflow when using `gqlgen generate` but it isn't immediately apparent on the 'Getting Started' example. For me personally it would help to understand the developer workflow for using gqlgen properly. I wouldn't think that the correct workflow is to update your code then regenerate, then go back and delete the duplicated code.

**Comment by MichaelJCompton** [comment]
Hi, thanks for the question.

Looks like this is the result of some unclear wording in the getting started guide and that you've added resolvers to `resolver.go`.  

The docs have been reworded on master to make it clearer to implement the resolvers in `graph/schema.resolvers.go`, rather than `resolver.go`.
