### ISSUE TITLE
Generated resolver ( unwanted ) for each field of a normal type ( like todo type in example )

### ISSUE THREAD

**Issue by Kliton** [99designs/gqlgen#1524]
### What happened?

Wrong resolvers generated for type

### What did you expect?
No resolver generated on type

### Minimal graphql.schema and models to reproduce

I have added this to one of my schemas
```
type Ruolo  {
    name: String!
    description: String!
}
```

When i run gqlgen generate i get the `Ruolo` type added to `ResolverRoot` near to query and mutation type.

```type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
	Ruolo() RuoloResolver
}
```

And then adds this to my `xxxxxxxxxx.resolver.go`

```

func (r *ruoloResolver) Name(ctx context.Context, obj *domain.Ruolo) (string, error) {
	panic(fmt.Errorf("not implemented"))
}

func (r *ruoloResolver) Description(ctx context.Context, obj *domain.Ruolo) (string, error) {
	panic(fmt.Errorf("not implemented"))
}

```

### versions
 - `gqlgen version` 0.13.0 
 - `go version` 1.16.3
 - dep or go modules: go mod

**Comment by loganbfisher** [comment]
@Kliton why was this closed can you tell me your solution I am having the same issues.
