### ISSUE TITLE
Outsource schema files and add project specific directives

### ISSUE THREAD

**Issue by dennishoffmann-edu** [99designs/gqlgen#1532]
### What happened?
I want to outsource specific schema files, that will be reused by other projects. 

### What did you expect?
I want to load that "remote" schema in a different project and be able to add directives(related to that specific project) to the fields ? I want to avoid that any other project that also implements that exact type, needs to write their own schema file. Is there a way to achieve that through the "gqlgen generate(gqlgen.yaml)"? 

Is there a best practice for that use case?

Thanks.

**Comment by baucosta** [comment]
I'm wanting the same thing!!!  Have you got it? It is bringing a lot work to me,  hahaha.
