### ISSUE TITLE
resolver for isRepeatable error

### ISSUE THREAD

**Issue by wayne-brush-optii** [99designs/gqlgen#1533]
### What happened?
I get this error when I run the scripts:
C:\Users\Work\optii\pkg\mod\github.com\99designs\gqlgen@v0.13.0\graphql\introspection\introspection.go:7 adding resolver method for __Directive.isRepeatable, nothing matched

### What did you expect?
Scripts to complete correctly.

### Minimal graphql.schema and models to reproduce
Not sure. Last time this happened, I waited a day or two and it started working again.

### versions
 - `gqlgen version`? from above, I'd guess v0.13.0
 - `go version`? v1.16.2
 - dep or go modules?

**Comment by mpieczaba** [comment]
@wayne-brush-optii I've also been getting this error with gqlparser v2.2.0 but when I've changed it to v2.1.0 my problem has disappeared :smiley:

**Comment by wayne-brush-optii** [comment]
@mpieczaba One of the devs on my team tried that with success as well.

**Comment by lwc** [comment]
Fixed in v0.14.0
