### ISSUE TITLE
0.14.0?

### ISSUE THREAD

**Issue by carldunham** [99designs/gqlgen#1534]
The last release was eight months ago, it looks like there has been a lot of great activity here, and some blocking bugs (for us) have been fixed.

Thanks!

**Comment by marwan-at-work** [comment]
Any luck here?

cc: @lwc @vektah 

Thanks!

**Comment by negz** [comment]
Throwing in my vote for a new release too. :) We're waiting on https://github.com/99designs/gqlgen/issues/1271, which looks like it didn't quite make it into the last release.

**Comment by negz** [comment]
I'm slightly concerned this project might no longer be maintained. I've raised https://github.com/99designs/gqlgen/issues/1571 hoping to get some clarity.
