### ISSUE TITLE
How to add functions on generated types?

### ISSUE THREAD

**Issue by DENKweit** [99designs/gqlgen#1556]
How can I add custom functions (e.g. `MarshalJSON`) on generated types?

**Comment by 1271** [comment]
Hi. Please, check your `gqlgen.yml` file.
Section `models`

**Comment by DENKweit** [comment]
Thank you very much, but I don't see how this could help me.

I need to generate new types based on the types that are present in the schema. `gqlgen.yml` requires a-priori knowledge about these types which I don't have.

And for these new types I need to also add functions.

**Comment by DENKweit** [comment]
I ended up writing my own MutateConfig plugin and used gotpl to generate a function conditionally:
```gotpl
	{{- if .IsOptionalInput }}
	func (m *{{ .Name|go }}) MarshalJSON() ([]byte, error) {
		return json.Marshal(m.Value)
	}
	{{- end }}
```
