### ISSUE TITLE
Cannot understand how to split schema.graphql

### ISSUE THREAD

**Issue by maxifom** [99designs/gqlgen#1559]
### What happened?
Cannot split schema.graphql to multiple files
### What did you expect?
Multiple *.resolvers.go files being generated
### Minimal graphql.schema and models to reproduce
https://github.com/maxifom/ent-graphql
### versions
 - `gqlgen version`? v0.13.1-0.20210415065809-5ad012e3d7be
 - `go version`? 1.16.5 linux/amd64
 - dep or go modules? go modules

Link to the Github Repo in the description. How can I achieve splitting schema.graphql and notes/notes.graphql to 2 separate *.resolvers.go files? As I researched code follow-schema must do it, but it doesn't. Or should I somehow extend query and mutation in notes.graphql?

**Comment by acelot** [comment]
Yes, it is possible to split the schema. Just place notes query into separate file:

`schema.graphql`
```gql
scalar Time

type Query

type Mutation
```

`notes.graphql`
```gql
extend type Query {
    notes: [Note!]!
    noteById(id: ID!): Note
}

extend type Mutation {
    createNote(input: CreateNotePayload!): Note!
    updateNote(id: ID!, input: UpdateNotePayload!): Note!
    deleteNote(id: ID!): DeleteNoteResponse
}
```

**Comment by maxifom** [comment]
> Yes, it is possible to split the schema. Just place notes query into separate file:
> 
> `schema.graphql`
> 
> ```graphql
> scalar Time
> 
> type Query
> 
> type Mutation
> ```
> 
> `notes.graphql`
> 
> ```graphql
> extend type Query {
>     notes: [Note!]!
>     noteById(id: ID!): Note
> }
> 
> extend type Mutation {
>     createNote(input: CreateNotePayload!): Note!
>     updateNote(id: ID!, input: UpdateNotePayload!): Note!
>     deleteNote(id: ID!): DeleteNoteResponse
> }
> ```

Thanks, I tried it with `type Query{}` with empty brackets and it didn't work. Guessed it wouldn't work without {}. Thanks a lot!
