### ISSUE TITLE
How to define type resolvers?

### ISSUE THREAD

**Issue by karanpratapsingh** [99designs/gqlgen#1561]
### What happened?

First of all, great project..tho I was bit confused on how can I add type resolvers. Let's say I want to add a resolver for `Person.option` similar to how I would do in graphql-js, here's a minimal example:

```js
const resolvers = {
  Person: {
     option: () => ....
   },
  Query: {...},
}
```

Sorry, I'm new to `gqlgen`, if this has an obvious answer 😅 

### Minimal graphql.schema and models to reproduce

`graph/schema.graphqls`

```gql
type Person {
  id: ID!
  name: String!
  option: Option!
}

type Option {
  id: ID!
  name: String!
}
```

`graph/model/model_gen.go`
```go
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Person struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Option  *Option   `json:"option"`
}

type Option struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
}
```

everything is pretty much from `go run github.com/99designs/gqlgen init`

### versions
 - `gqlgen version`? v0.13.0
 - `go version`? 1.15
 - dep or go modules?

**Comment by karanpratapsingh** [comment]
Got it! added this to yaml config and it worked!

```
models:
  Person:
    fields:
      option:
        resolver: true  
```

**Comment by wilhelmeek** [comment]
Hey @karanpratapsingh! Looks like you've managed to get the outcome you needed.

You can also achieve the same using custom models or directives. [Explained here](https://gqlgen.com/#how-do-i-prevent-fetching-child-objects-that-might-not-be-used).
