### ISSUE TITLE
Go generate is failing for v1.16.6

### ISSUE THREAD

**Issue by DONSA** [99designs/gqlgen#1573]
### What happened?
Go generate is failing for v1.16.6 after `go mod tidy`. I don't have this problem with older versions of go.

Using v1.16.6. is causing that `go mod tidy` deletes many indirect dependencies inside my `go.sum` despite those are being defined inside gqlgen `go.mod` file.

Example:
```
github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
-github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
github.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0
-github.com/vektah/dataloaden v0.2.1-0.20190515034641-a19b9a6e7c9e h1:+w0Zm/9gaWpEAyDlU1eKOuk5twTjAjuevXqcJJw8hrg=
github.com/vektah/dataloaden v0.2.1-0.20190515034641-a19b9a6e7c9e/go.mod h1:/HUdMve7rvxZma+2ZELQeNh88+003LL7Pf/CZ089j8U=
```

Then when I run `go generate ./...` is causing:
```
missing go.sum entry for module providing package github.com/vektah/dataloaden; to add:
	go mod download github.com/vektah/dataloaden
internal/dataloader/dataloader.go:1: running "go": exit status 1
/Users/nulop/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/internal/code/packages.go:7:2: missing go.sum entry for module providing package github.com/pkg/errors (imported by github.com/99designs/gqlgen/cmd); to add:
	go get github.com/99designs/gqlgen/cmd@v0.13.0
/Users/nulop/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/cmd/gen.go:9:2: missing go.sum entry for module providing package github.com/urfave/cli/v2 (imported by github.com/99designs/gqlgen/cmd); to add:
	go get github.com/99designs/gqlgen/cmd@v0.13.0
internal/graphql/resolver.go:1: running "go1.16.6": exit status 1
```

### What did you expect?
That go mod tidy doesn't remove indirect dependencies.

### Minimal graphql.schema and models to reproduce
Is not related to the schema.

### versions
 - `gqlgen v0.13.0`
 - `go v1.16.6`

**Comment by diep-it-dn** [comment]
Hi @DONSA 
You can refer to my repo to find the solution:
https://github.com/diep-it-dn/fullstack-go-angular

**Comment by DONSA** [comment]
This issue is related to go v1.16 since he's no longer trying to fix missing requirements automatically and therefore `go generate ./...` is failing.
Followed the [recommended](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) way to import tool dependencies and now it's working.
