### ISSUE TITLE
Cannot cast application specific errors in error presenter (v0.13.0)

### ISSUE THREAD

**Issue by hizzuu** [99designs/gqlgen#1576]
### What happened?
Cannot cast application specific errors in error presenter
It works in version v0.11.3, but not in version v0.13.0.

### What did you expect?
I was hoping to cast it into its own error here.
Can you tell me what to do?
```
// custom error
type AppError struct {
	err  error
	code codes.Code
}
```

cannot cast err to AppError
It works in version v0.11.3, but not in version v0.13.0.
```
// error presenter
return graphql.ErrorPresenterFunc(func(ctx context.Context, err error) *gqlerror.Error {
  if e, ok := err.(*AppError); ok {
     return e.Code, ok
  }
}
```

### versions
 - `gqlgen version`? 
  v0.13.0

 - `go version`? 
 v1.16

 - dep or go modules? 
 go mod

**Comment by bickyeric** [comment]
you should use `errors.As()` instead of type casting as shown on reference
https://gqlgen.com/reference/errors/#the-error-presenter
i hope can solve your issue

**Comment by lwc** [comment]
@bickyeric is correct, we changed error behaviour to make better use of new features in go 1.13. See: https://go.dev/blog/go1.13-errors
