### ISSUE TITLE
 Directive deprecated is not applicable on INPUT_FIELD_DEFINITION

### ISSUE THREAD

**Issue by vikusku** [99designs/gqlgen#1579]
Hi,

The title is pretty much self explanatory. When trying to generate code from schema that had @deprecated directive on the input fields I get this error. Is it a bug or expected behaviour? If it's not a bug what is the reason behind dropping @deprecated directive support on INPUT_FIELD_DEFINITION?

### Minimal graphql.schema and models to reproduce
```
schema {
    query: Query
}

type Query {
   getMenu(input: GetMenuInput!): Menu!
}

input GetMenuInput {
    menuID: ID @deprecated(reason: "Use `id`")
    id: ID
}

type Menu {
    id: ID!
    name: String!
}
```

### versions
 - `gqlgen version - v.0.12.*`
 - `go version - go1.16.6`
 - go modules

**Comment by milesich** [comment]
This library supports only `FIELD_DEFINITION` and `ENUM_VALUE` based on this declaration:

```
directive @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE
```

There is a [PR](https://github.com/vektah/gqlparser/pull/155) to change it.
