### ISSUE TITLE
client side property __typename not accepted by gqlgen server

### ISSUE THREAD

**Issue by umerm-work** [99designs/gqlgen#1585]
### What happened?
We are using [flutter](https://github.com/zino-app/graphql-flutter)  graphql library for graphql implementation . It automactically adds __typename in mutation query but gqlgen is giving validtion error on that. How to solve this issue?

### What did you expect?
I didn't expect __typename validation error.

```
OperationException(linkException: ServerException(originalException: null,
parsedResponse: Response(data: null,
errors: [
GraphQLError(message: unknownfield,
locations: null,
path: [
variable,
notifications,
__typename
],
extensions:

{ code: GRAPHQL_VALIDATION_FAILED }

)
],
context: Context(

{ ResponseExtensions: Instanceof'ResponseExtensions' }

))),
graphqlErrors: [

])

```
### Minimal graphql.schema and models to reproduce
```
type Mutation {
    createUser(input: CreateUserInput!):User!
}
input CreateUserInput {
    firstName: String!
    userId: String
    lastName: String!
    email: String!
    deviceToken: String!
    signupMethod: String!
    dob: DateTime!
    gender: String!
    countryCode: String!
    notifications:UserNotificationsInput
}
input UserNotificationsInput {
    pendingCashback:Boolean
    availableCashback:Boolean
    updatesAndOffers:Boolean
}
```

### versions
 - `gqlgen version`?  
 v0.13.0
 - `go version`? 
 go1.16.5 linux/amd64
 - dep or go modules? 
 go modules

**Comment by wilhelmeek** [comment]
I'm not sure if the spec explicitly defines this, but I don't believe `__typename` isn't a valid input argument.

It appears that the flutter lib you're using does implicitly also query for `__typename` along with any other fields. This absolutely is supported by `gqlgen`.

@umerm-work are you by any chance using a previously fetched entity as your input argument in this case? That would explain why you're seeing this error.

**Comment by wilhelmeek** [comment]
Gonna close this out for now since I believe gqlgen is functioning as expected here. Please open another ticket (preferably with some more info) if you haven't been able to get this to work.
