### ISSUE TITLE
Redundant call to graphql.WithOperationContext

### ISSUE THREAD

**Issue by AndrewWPhillips** [99designs/gqlgen#1592]
### What happened?

Stepping through the code and it seems that the same OperationContext is added twice to the active context.Context.  This happens just before the call to exec.DispatchOperation at:
https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_post.go#L51

then at the top of exec.DispathcOperation at:
https://github.com/99designs/gqlgen/blob/master/graphql/executor/executor.go#L90

### What did you expect?

I expected to see only one call to graphql.WithOperationContext(). I could be wrong but it seems there is a redundant call.

### versions
 - `gqlgen version`? v0.13.0
 - `go version`? go version go1.16.6 windows/amd64
 - dep or go modules? Go modules

**Comment by KunalSin9h** [comment]
@lwc close this issue, it its fixed.

**Comment by alexandear** [comment]
@StevenACoffman please close issue, it's fixed via #1641
