### ISSUE TITLE
Full Schema introspection and idl description generation

### ISSUE THREAD

**Issue by AlexandreBossard** [99designs/gqlgen#1593]
### What happened?

I've Tried to find a (documented way) to implement something like https://docs.github.com/en/graphql/guides/introduction-to-graphql#discovering-the-graphql-api.
 
TL;DR;
A GET request retrieves the whole schema introspection.
There is also a way to get the result in the idl format.

### What did you expect?

Is github api doing some magic here or is gqlgen missing this feature/documentation to implement it ?

### Minimal graphql.schema and models to reproduce
```
curl -H "Authorization: bearer <token api reader>"  https://api.github.com/graphql | jq
curl -H "Authorization: bearer <token api reader>"  https://api.github.com/graphql  -H 'Accept: application/vnd.github.v4.idl'
``` 
### versions
 - `gqlgen version` v0.13

**Comment by lwc** [comment]
Hey there. gqlgen supports [standard graphql introspection queries](https://github.com/99designs/gqlgen/blob/master/graphql/introspection/query.go). By the looks of it, github has added a few additional non-standard methods to fetch the schema.
