### ISSUE TITLE
federated GraphQL gateway spport

### ISSUE THREAD

**Issue by sumanthakannantha** [99designs/gqlgen#1596]
### What happened?

Does GQLGEN support federated GraphQL gateways like Bramble and nautilus?

https://movio.github.io/bramble/#/federation
https://gateway.nautilus.dev/

**Comment by suessflorian** [comment]
👋  - I work with both `graph-gophers` and `gqlgen` on a daily basis, they both are agnostic to what federation spec you use as long as you correctly configure which directives are listened to where. For `bramble` you will need to use the `@boundary` and `@namespace` directives when intending to federate portions of your schema. These directives will need to be locally defined via;

```
directive @boundary on OBJECT | FIELD_DEFINITION
directive @namespace on OBJECT
```

Naturally, `gqlgen` will interpret these and will prepare, what you can think of `middleware` resolvers. These will need to be implemented. But keeping in mind, as alluded to before, your service itself will not want to react to those directives, you will appropriately define them as passthrough middleware resolvers.

```
graph := generated.Config{
	Resolvers: resolver, // `resolver` being your resolver implementation
}

// ignore Bramble specific directives
graph.Directives.Namespace = func(ctx context.Context, obj interface{}, next graphql.Resolver) (interface{}, error) {
	return next(ctx)
}
graph.Directives.Boundary = func(ctx context.Context, obj interface{}, next graphql.Resolver) (interface{}, error) {
	return next(ctx)
}

server := handler.NewDefaultServer(
	generated.NewExecutableSchema(
		graph,
	),
)
```

So from a local POV, your server ignores those directives, only really being used to indicate to the implementor what parts of your schema will/will not be federated. It's still important to define the directives locally though as, when this service is federated, the schema provided to bramble will have those directives there, allowing bramble to correctly react to those directives when undergoing it's schema merging logic.

**Comment by lwc** [comment]
Thanks @suessflorian! I'm going to resolve this as answered 😄
