### ISSUE TITLE
CollectFields getting prefix path?

### ISSUE THREAD

**Issue by kim-hetrifi** [99designs/gqlgen#1609]
Is there some way to get the field path prefix before the current field resolver?

eg:

```
query {
  users {
    friends {
      posts {
        id
        description
      }
    }
  }
}
```
assuming the `posts` field is a forced field resolver, is there some way to use field collection to get the path the query took to get to the field? (eg in this case `["users", "friends"]` or `["users", "friends", "posts"]`)

**Comment by lwc** [comment]
Yep, it should be possible to get the path from context in a resolver. 

Take a look at https://github.com/99designs/gqlgen/blob/master/graphql/context_path.go#L69

**Comment by kim-hetrifi** [comment]
Perfect thank you very much, exactly what I was looking for.  Would probably be a nice addition to the field collector documentation.
