### ISSUE TITLE
Gqlgen Community Discord?

### ISSUE THREAD

**Issue by spdrstar** [99designs/gqlgen#1616]
Currently choosing Gqlgen for production and noticed it’s hard to find a great Golang / GraphQL community. Would the contributors of this project be interested in starting one?

**Comment by frederikhors** [comment]
https://discord.com/channels/831012771810377778

**Comment by frederikhors** [comment]
If it's ok with you close this issue.

**Comment by lwc** [comment]
Hey @spdrstar, we're actually just in the process of setting one up! Here's an invite link: https://discord.gg/DYEq3EMs4U

**Comment by ddevault** [comment]
Discord should *never* be used for open source projects. Don't put development discussions on the other side of a proprietary walled garden. Furthermore, Discord is not accessible on low-end hardware or with screen readers, which creates a class divide in the project. Discord is wholly unsuitable for FOSS projects.
