### ISSUE TITLE
[String] is not interpreted as nullable

### ISSUE THREAD

**Issue by tschwann** [99designs/gqlgen#1618]
Define schema:
```
type Post {
  delta: [String]
}
```
Run ```gqlgen generate``` and see the result of
```
type Post struct {
	Delta []*string `json:"delta"`
```
whereas it should be
```
type Post struct {
	Delta *[]*string `json:"delta"`
}
```
because GraphQL presumes everything is nullable by default unless you define something as non-nullable.

### versions
 - `gqlgen version` v0.13.0
 - `go version` 1.17
 - `dep or go modules` modules

**Comment by bickyeric** [comment]
AFAIK, `nil` can be assigned to slice type on golang and the default value of slice in golang is `nil` not empty slice. so technically `Delta []*string` is nullable and no need to use `Delta *[]*string`

**Comment by frederikhors** [comment]
I agree with @bickyeric. Please close this issue if you are ok with answer, @tschwann.

**Comment by tschwann** [comment]
Indeed. Thank you @bickyeric and @frederikhors.

**Comment by evanchaney** [comment]
> AFAIK, `nil` can be assigned to slice type on golang and the default value of slice in golang is `nil` not empty slice. so technically `Delta []*string` is nullable and no need to use `Delta *[]*string`

Maybe this has changed in Go? The zero-value of a slice appears to be an empty slice.

https://go.dev/play/p/t-aoE8LrGHR
