### ISSUE TITLE
Problem with `@deprecated` directive in input fields

### ISSUE THREAD

**Issue by VictorAssunc** [99designs/gqlgen#1636]
### What happened?
After upgrading gqlgen (`v0.13.0` -> `v0.14.0`), when trying to generate models, I got an error related to the `@deprecated` directive in input fields. I was checking and I'm not sure if it's a gqlgen or gqlparser bug (this second I don't think it's because they updated this directive in a [recent commit](https://github.com/vektah/gqlparser/commit/2deb65762a4f096566603a10fff2124c89b637c6)).

This error did not happen in the previous version (`v0.13.0`).
### What did you expect?
Generate models without problems

### Minimal graphql.schema and models to reproduce
```graphql
input NewUserInput {
  email: String!
  password: String!
  name: String @deprecated(reason: "No longer supported")
}
```
### versions
 - `gqlgen version`? v0.14.0
 - `go version`? go version go1.17 linux/amd64
 - dep or go modules? go mod

**Comment by bickyeric** [comment]
i try to debug this issue, i'm pretty sure this is gqlparser bug on this commit https://github.com/vektah/gqlparser/commit/375e4cf58bb5c5a8d3c0785b7fb6c501bb9167dd, [bug fix](https://github.com/vektah/gqlparser/pull/155) already merged but unfortunately not included on [gqlparser@v2.2.0](https://github.com/vektah/gqlparser/tree/v2.2.0) which is used on [gqlgen@0.14.0](https://github.com/99designs/gqlgen/blob/v0.14.0/go.mod#L26).

i hope gqlparser maintainer can create new release so we can add it into gqlgen v0.15.0 or gqlgen v.0.14.1

**Comment by britztopher** [comment]
This is definitely keeping me from updating as we use the deprecated directive all over our schema

**Comment by BatmanAoD** [comment]
Here's the request for a new release in `gqlparser`: https://github.com/vektah/gqlparser/issues/165

**Comment by macnibblet** [comment]
That issue has been open for a while, maybe we should fork the gqlparser into 99designs?

**Comment by StevenACoffman** [comment]
I cut a new release, but it appears not to be that easy as it looks like the very first merge after the v2.2.0 release causes problems in gqlgen generate.

**Comment by StevenACoffman** [comment]
Sorry this took so long. Should be good now!

**Comment by macnibblet** [comment]
Thank you sooo much!

**Comment by BatmanAoD** [comment]
This works! Thank you!

How soon do you expect a new release of `gqlgen` to be cut?

**Comment by imjma** [comment]
The error is not happening
But when I tested, there is no deprecated info in the schema or GraohpiQL documentation explorer.

**Comment by slightlytyler** [comment]
Yep it appears that the codegen supports this now but not the runtime introspection behavior

**Comment by StevenACoffman** [comment]
PRs welcome!

**Comment by carldunham** [comment]
fwiw, this is only supported in the working draft gql spec: https://spec.graphql.org/draft/#sec--deprecated.  The current spec only allows `@deprecated` on fields and enums. It may not play nicely with other tooling.
