### ISSUE TITLE
How does InterceptResponse work?

### ISSUE THREAD

**Issue by MetalRex101** [99designs/gqlgen#1637]
### What happened?
I'm running my GQL server with some tracer, which implements `ResponseInterceptor` interface. I'm calling Mutation method, which resolver returns error. Via debug, i see, that `InterceptResponse` method on my tracer is called before mutation method. And `graphql.GetErrors(ctx)` line gives me nil. Tracer also implements `InterceptField` method, which actually work correct: I see error from called mutation resolver. But i want to have correct single result for the whole call, not for particular field.

### What did you expect?
1. `graphql.GetErrors(ctx)` returns slice with 1 error, which was returned from mutation resolver.
2. Mutation resolver called before `InterceptResponse`

### Any documentation about interceptors
It would be also very kind if any straight forward documentation about all the interceptors with explained examples would be there. Right now i just don't really understand when `InterceptResponse` should be used.

#### Schema
Any scheme with at least 1 mutation

#### Tracer
```
type Tracer struct{}

var _ interface {
	graphql.ResponseInterceptor
	graphql.FieldInterceptor
} = GqlTracer{}

func (a Tracer) InterceptResponse(ctx context.Context, next graphql.ResponseHandler) *graphql.Response {
	fmt.Println(graphql.GetErrors(ctx))

	return next(ctx)
}

func (a Tracer) InterceptField(ctx context.Context, next graphql.Resolver) (interface{}, error) {
	res, err := next(ctx)
	
	fmt.Println(err)

	return res, err
}

func (a Tracer) ExtensionName() string {
	return "SomeExtension"
}

func (a Tracer) Validate(schema graphql.ExecutableSchema) error {
	return nil
}
```

### versions
 - `gqlgen version` - `v0.14.0`
 - `go version` - `go version go1.17.1 linux/amd64`
 - dep or go modules - modules

**Comment by wilhelmeek** [comment]
[This diagram](https://github.com/99designs/gqlgen/blob/master/graphql/handler.go#L37) is a good starting point when approaching interceptors. Generally speaking, the interceptors allow you to define behaviour before and after running the wrapped `next` function.

In your case, you need to check errors only after running `next`:
```go
srv.AroundResponses(func(ctx context.Context, next graphql.ResponseHandler) *graphql.Response {
  res := next(ctx)
  // res.Errors == graphql.GetErrors(ctx) == errors occured while evaluating resolvers
  return res
})
```

**Comment by MetalRex101** [comment]
Got it! Thank you!
