### ISSUE TITLE
GraphQL Voyager integration

### ISSUE THREAD

**Issue by yar00001** [99designs/gqlgen#1639]
Hello - I am wondering if there is any sample integration sample with [GraphQL Voyager](https://github.com/APIs-guru/graphql-voyager) out there. This could be a useful addition to make graphql structure more visible to clients.

**Comment by wilhelmeek** [comment]
@yar00001 `gqlgen` supports [introspection by default](https://gqlgen.com/reference/introspection), so tooling such as GraphQL Voyager should should work out of the box if you point it at your graph endpoint.

Is there anything specific you need [outside of their Usage documentation](https://github.com/APIs-guru/graphql-voyager#usage) that might be more helpful?

**Comment by yar00001** [comment]
Thank you, I wasn't aware of the introspection support.
