### ISSUE TITLE
[proposal] Pass context to scalar Marshal/Unmarshal

### ISSUE THREAD

**Issue by duckbrain** [99designs/gqlgen#1645]
### Proposal

Add an alternate interface for `Marshaller` and `Unmarshaller` that includes a context. 

```go
type ContextMarshaler interface {
	MarshalGQLContext(ctx context.Context, w io.Writer) error
}
type ContextUnmarshaler interface {
	UnmarshalGQLContext(ctx context.Context, v interface{}) error
}
```

The method names have changed, so types can implement the old and new interface simultaneously to support current and older versions of gqlgen. If that is done, the Context version is preferred.

The error response has been added to the Marshal function to satisfy #743 with a single signature change.

Additionally add a new form of an external Marshaller/Unmarshaller that uses a similar signature.

```go
func MarshalX(ctx context.Context, val T) error

func UnmarshalX(ctx context.Context, input interface{}) (T, error)
```

Since multiple external Marshal/Marshall functions for the same type can coexist with different names, there is no reason for a special prefix. The code generator can detect the updated signature and use it appropriately.

### Use Case

I want to define a scalar for various units that have regional-specific preferences. Since they will be utilizing `big.Float` I don't want to do unit conversions in the front-end. These types will be used in many places throughout the schema, so I'd like to do the formatting in the scalar type when doing the Marshal to a string.

To my knowledge, there is no way to `Marshal`/`Unmarshal` with an interface/custom type while passing it a context. This would allow me to pass the relevant context of which unit the scalar should format as. If I try to pass the context in a similar pattern as the automatically collected resolver methods, generates incorrect code.

```go
(r Radioactivity) MarshalGQL(ctx context.Context, w io.Writer)
// vs.
MarshalRadioactivity(ctx context.Context, r Radioactivity) graphql.Marshaler
```
yields unsatisfied interfaces or mistaking `context.Context` as the type being marshaled/unmarshaled respectively

**Comment by karthikeyanmanokaran** [comment]
UnmarshalGQLContext is not being called automatically. I searched on Google but couldn't find any clues. I also referred to the gqlgen documentation. Does UnmarshalGQLContext need to be called manually in the resolver?
