### ISSUE TITLE
struct tag help

### ISSUE THREAD

**Issue by chav-aniket** [99designs/gqlgen#1656]
### What happened?
- Need both json and bson tags in my model

### What did you expect?
- A guide on how to use the struct_tag field in the gqlgen.yml

I wasn't sure where else to put queries like this but yeah just needed help on using the struct_tag field in the yml, thank you!

**Comment by tprebs** [comment]
If you need to add an additional tag (bson) to your model you can do this using modelgen hooks. https://gqlgen.com/recipes/modelgen-hook/

Something similar to below should work as it will give matching json and bson tags

```go
func mutateHook(b *modelgen.ModelBuild) *modelgen.ModelBuild {
	for _, model := range b.Models {
		for _, field := range model.Fields {
			field.Tag += " " + strings.Replace(field.Tag,"json","bson",1)
		}
	}
	return b
}
```

e.g. 

```go
type SomeObject struct {
 UserName string `json:"userName" bson:"userName"`
}
```
