### ISSUE TITLE
How to setup hot reload for the GraphQL Server

### ISSUE THREAD

**Issue by ss-ravi** [99designs/gqlgen#1665]
While using the Playground, when I update the resolvers, they don't get updated in the actual running server.
I need to stop and restart the server for the changes to be reflected.

Is there a way to setup hot reload? I couldn't find in the documentation.

Thanks in advance

### versions
 - `gqlgen version`v0.14.0
 - `go version`go1.17.2 darwin/amd64

**Comment by CoreyWinkelmann** [comment]
@ss-ravi You would want to use something like [Air](https://github.com/cosmtrek/air) to accomplish the live reloading within your Go api.  I currently use Air within a docker container to live reload and it has worked fairly well for my projects.
