### ISSUE TITLE
Allow resolvers to be created once per request

### ISSUE THREAD

**Issue by jdoklovic** [99designs/gqlgen#1668]
### What happened?
Currently, each resolver struct is created for every method call on the resolver.
e.g. `return ec.resolvers.Mutation().UpdateSomeValue(...)` where `Mutation()` is a resolver struct with many methods.
This means a new Mutation struct is created for every method call and you can't share dependencies within the same resolver.

### What did you expect?
It would be better if there was a configuration that allowed us to specify that we want per-request resolvers, and then instead of the above code, the generated code would only create the resolver object once per request and then simply call methods on that same resolver struct as needed.

This would allow us to do per-request dependency injection on the resolver structs themselves instead of having to turn the golang context into a god object that holds everything and does poor man's dependency injection (which is a terrible anti-pattern)

### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?

**Comment by lwc** [comment]
Context should only be needed for request scoped stuff that exists outside the actual graph traversal, such as authentication. 
This is pretty much in line with other GraphQL servers, and other Go HTTP services.

The resolvers are intended to be DI containers that you wire up manually, [see the chat example](https://github.com/99designs/gqlgen/blob/master/example/chat/resolvers.go).
