### ISSUE TITLE
Proposal: Support the GraphQL Spec Updates

### ISSUE THREAD

**Issue by JonasDoe** [99designs/gqlgen#1678]
After three years, the GraphQL specification got an update: https://github.com/graphql/graphql-spec/releases/tag/October2021

Would be nice if these updates would be supported sometimes in the future.

**Comment by wilhelmeek** [comment]
@JonasDoe I've created 2 issues to address spec changes:

- https://github.com/99designs/gqlgen/issues/1687
- https://github.com/99designs/gqlgen/issues/1688

Is there anything else that was introduced that may also need to be implemented?

**Comment by JonasDoe** [comment]
@wilhelmeek I think [intermediate interfaces](https://dev.to/mikemarcacci/intermediate-interfaces-generic-utility-types-in-graphql-50e8) are missing yet, too.
I hope I didn't screw up when testing it, but I think at the moment the declaration of those intermediate interfaces (e.g. `interface AnimalEdge implements Edge {...}`) leads to `Unexpected Name "implements"`

**Comment by wilhelmeek** [comment]
@JonasDoe nope you're absolutely right! This needs both a parser change and a gqlgen change. I've opened issues here:
- https://github.com/99designs/gqlgen/issues/1690
- https://github.com/vektah/gqlparser/issues/166

**Comment by JonasDoe** [comment]
Awesome, thank you! If it makes sense to close this issue here, feel free to do so! :)

**Comment by wilhelmeek** [comment]
Thanks for raising @JonasDoe!
