### ISSUE TITLE
Question: Why the field type has a pointer if it's not required?

### ISSUE THREAD

**Issue by vine1993** [99designs/gqlgen#1683]
### What happened?
If I make any field non-required then became a pointer to the type.

### What did you expect?
I want to understand why the package behaves like that.

### Minimal graphql.schema and models to reproduce
```
type Profile {
    id: ID!
    name: String!
    email: String!
    userName: String!
}

input inputProfile {
    name: String
    email: String
    userName: String
}
```

The schemas generate this model:
```
package model

type Profile struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	UserName string `json:"userName"`
}

type InputProfile struct {
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	UserName *string `json:"userName"`
}

```

As you can see the input data it's not required, and everything it's a pointer now.

### versions
 - `gqlgen version: 0.14.0`
 - `go version: 1.17.2`

**Comment by wilhelmeek** [comment]
Using a pointer type allows for the representation of GraphQL's `null` in Go.

As you probably know, Go [uses zero values](https://tour.golang.org/basics/12). `string` makes it difficult to distinguish between `""` as a zero value (the client did not provide anything / provided `null`) or a provided `""`.

`*string` introduces the nil pointer as an additional value that can be used to indicate lack of value or `null`. 

Hopefully this clears things up!

**Comment by duckbrain** [comment]
@vine1993 If you don't care about the difference, you can copy/paste the model into a non-generated file and remove the pointers.

**Comment by vine1993** [comment]
@wilhelmeek that makes sense, thank you very much.
@duckbrain now that i understood why I think I should leave this way.

**Comment by jshnaidman** [comment]
I also didn't understand why this was the case by default. Perhaps adding this to the FAQ or even just a comment in the gqlgen.yml above struct_fields_always_pointers would be helpful.

**Comment by Genialngash** [comment]
`struct_fields_always_pointers: false
`

i have added the setting in the yaml file but still generates models with pointer

**Comment by Genialngash** [comment]
> @vine1993 If you don't care about the difference, you can copy/paste the model into a non-generated file and remove the pointers.

i have tried copying my models to a different file name but getting this error still
`interface conversion: interface {} is bool, not *bool`
