### ISSUE TITLE
Implement support for `@specifiedBy`

### ISSUE THREAD

**Issue by wilhelmeek** [99designs/gqlgen#1687]
As outlined in [this blog post](https://medium.com/@leeb/graphql-2021-868e07545b83) about the 2021 GraphQL spec, `@specifiedBy` can be used to communicate metadata around scalar types through introspection. 

Corresponding `gqlparser` issue: https://github.com/vektah/gqlparser/issues/167

**Comment by frederikhors** [comment]
I think this is fixed, right @Code-Hex?
