### ISSUE TITLE
`Mutation` and `Query` returns interface

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1689]
### What happened?

I just updated to [golangci-lint v1.43](https://github.com/golangci/golangci-lint/releases/tag/v1.43.0) today and I'm getting this warning from [ireturn](https://github.com/butuzov/ireturn):

![image](https://user-images.githubusercontent.com/41120635/140124577-16abe552-83d9-4f15-aaee-cd8c94899dde.png)

```
Mutation returns interface (project/internal/gqlgen.MutationResolver) (ireturn)
Query returns interface (project/internal/gqlgen.QueryResolver) (ireturn)
```
### What did you expect?

Maybe we should stop to return interface in that methods.

### Minimal graphql.schema and models to reproduce

- schema.graphql:

```graphql
type Query

type Mutation
```

### versions
 - `gqlgen version`? github.com/99designs/gqlgen v0.14.0
 - `go version`? go version go1.17.2 windows/amd64
 - dep or go modules? go.mod

**Comment by duckbrain** [comment]
It sounds like the linter is overly strict. Returning interfaces is perfectly valid when you're implementing another interface. (Which this is doing.) By changing the methods (and the interfaces they implement) to structs, you could no longer implement the Resolver interface with anything but the generated resolvers.

Source: Rob Pike mentions this as a problematic proverb https://github.com/go-proverbs/go-proverbs.github.io/issues/37#issuecomment-571345739

**Comment by martinscholz83** [comment]
Can is ask a question on this issue? Returning Interface I think it’s fine. But Query() and Mutation() always return a new pointer to their resolver implementation for every call. Wouldn’t that mean we would have a lot of objects which needs to be deleted by GC?
