### ISSUE TITLE
Question: Apollo federation 2

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [99designs/gqlgen#1695]
Hello, 
any plans to incorporate the fresh release of apollo federation 2? https://www.apollographql.com/docs/federation/v2/

https://www.youtube.com/watch?v=WcHYa39bUk8

Thanks a lot

**Comment by StevenACoffman** [comment]
@ahmed-adly-khalil Hi! Are there any specific changes that gqlgen does *not* already implement?  It seems to me like v2 changes the gateway and only relaxes the prior requirements on federated subgraphs.

**Comment by jakemhiller** [comment]
@StevenACoffman i think this will need to be addressed, [according to Apollo's federation 2 compatibility table](https://github.com/apollographql/apollo-federation-subgraph-compatibility) `gqlgen` is not compatible with the new federation spec.
