### ISSUE TITLE
Nested @requires generates incorrectly in generated federation file

### ISSUE THREAD

**Issue by CFitzgerald212** [99designs/gqlgen#1704]
### What happened?

I'm using the recently implemented nested @requires directives to try to pass through an id of a subtype to a field extension, and the generated file is not able to correctly unmarshall the nested id field, resulting in a null id being passed through.

### Schema 

```
extend type User @key(fields:"id"){
  id: ID! @external
  name: String!
  subType: SubType!
  extension: String @requires(fields:"subType {id }")
}

extend type SubType @key(fields:"id"){
  id: ID! @external
}
```

### Generated federation output

	
```
case "User":
	id0, err := ec.unmarshalNID2string(ctx, rep["id"])
	if err != nil {
		return errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
	}

	entity, err := ec.resolvers.Entity().FindUserByID(ctx,
		id0)
	if err != nil {
		return err
	}

	entity.SubType.ID, err = ec.unmarshalNID2string(ctx, rep["subTypeID"])
	if err != nil {
		return err
	}

	list[i] = entity
	return nil
```

### Expected generated output

```
case "User":
	id0, err := ec.unmarshalNID2string(ctx, rep["id"])
	if err != nil {
		return errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
	}

	entity, err := ec.resolvers.Entity().FindUserByID(ctx,
		id0)
	if err != nil {
		return err
	}

	entity.SubType.ID, err = ec.unmarshalNID2string(ctx, rep["subType"].(map[string]interface{})["id"])
	if err != nil {
		return err
	}

	list[i] = entity
	return nil
```

### What this does

When resolving User.extension, subType.ID = "null"

### versions
 - gqlgen: commit ed2d699, https://github.com/99designs/gqlgen/pull/1701
 - go: 1.16.3

**Comment by carldunham** [comment]
Not sure if this helps, but you may try marking `subType` with `@external`

**Comment by carldunham** [comment]
@CFitzgerald212 sorry about that. Just saw this myself, should have a tested fix soon.
