### ISSUE TITLE
Easier way to force generating resolvers for every single field of every single model?

### ISSUE THREAD

**Issue by elimist3** [99designs/gqlgen#1707]
I have a use case where I need to generate resolvers for every field of every model.

Currently there are two ways to force the generation of resolvers: either through `resolver: true` in each field of each model in the `gqlgen.yml`, or through specifying directives `@goField(forceResolver: true)` for every field in the graphql schema.

Is there a simpler way of accomplishing the above without having to manually specify that I need a resolver for every field? My project has dozens of entities with dozens of fields each and specifying by hand (even with autocomplete) gets a bit tedious. Maybe a single config entry under the `fields` key for each model? Or a custom model-level directive like `@goModel(forceFieldResolvers: true)` or something?

Would be happy to get some thoughts on whether there is an existing solution to this, or whether this is a common enough use case for me to make a PR out of.

**Comment by wilhelmeek** [comment]
Autobinding may be of use to you.

In your config:
```yml
# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - "github.com/your/app/graph/model"
```

If you declare structs and omit the fields you want resolvers generated for, `gqlgen` will generate resolvers for the missing fields for you.

**Comment by elimist3** [comment]
Ah, that's perfect. Cheers!
