### ISSUE TITLE
How to completely remove dataloaden from go.mod?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1715]
### What happened?

I removed `dataloaden` from my project ([because of this](https://github.com/99designs/gqlgen/issues/1714)) but I'm still having `dataloden` in my `go.mod` as an `indirect` dependency. **Why?**

```
go 1.17

require (
  ...
  github.com/99designs/gqlgen v0.14.0
  github.com/graph-gophers/dataloader/v6 v6.0.0
  github.com/vektah/gqlparser/v2 v2.2.0
  ...
)

require (
  ...
  github.com/vektah/dataloaden v0.2.1-0.20190515034641-a19b9a6e7c9e // indirect
  ...
)
```

[I searched in project for "dataloaden"](https://github.com/99designs/gqlgen/search?q=dataloaden) but nothing appears except for `example` dir. **Is this the problem?**

I also tried with:

`go mod why github.com/vektah/dataloaden`

in my project, which shows:

```
# github.com/vektah/dataloaden
myProject/lib/gqlgen
github.com/99designs/gqlgen
github.com/vektah/dataloaden
```

### What did you expect?

To remove it completely.

### versions
 - `gqlgen version` v0.14.0 
 - `go version` 1.17.3

**Comment by duckbrain** [comment]
From `go help packages`:

> Directory and file names that begin with "." or "_" are ignored
> by the go tool, as are directories named "testdata".

You could rename `example` to `_examples`. That _should_ get all of the Go tooling to ignore the whole directory. My testing on my machine indicates that the projects inside of `_examples` would still function normally if directly compiled. ie: `go install ./_examples/project-dir` works but `go install ./_examples/...` will have "matched no packages"

**Comment by frederikhors** [comment]
Thanks @duckbrain.
