### ISSUE TITLE
Can you please activate the Github Discussions tab in this project?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1722]
Can we please activate the [Github Discussions tab](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) in this project?

There are so many **questions** in the issues that could be moved there.

Having so many open issues:

1. can give the idea (especially if one does not know it) that the software is not very reliable;
1. makes it difficult to trace the real issues, perhaps very important [like this one](https://github.com/99designs/gqlgen/issues/518);
1. can free the mind and galvanize contributors more who can close issues in less time.

Thank you.

**Comment by frederikhors** [comment]
@StevenACoffman please, can you add the Discussions tabs? There are many many issues that are questions.

**Comment by StevenACoffman** [comment]
Done!

**Comment by frederikhors** [comment]
If you want I can take care of answering the questions and - in case - of moving them there. I'm available, no problem.

**Comment by StevenACoffman** [comment]
Yes please! That would be extremely helpful. I feel like I'm keeping up with PRs... but I find I have no OSS time left for responding to issues.
