### ISSUE TITLE
Default/builtin `goTag` directive requires implementation in `DirectiveRoot`

### ISSUE THREAD

**Issue by Giners** [99designs/gqlgen#1736]
### What happened?

I learned about the inline `goTag` directive from this documentation: https://github.com/99designs/gqlgen/blob/37a4e7eefa241dd7e5eeab7bbca56b1677d37daf/docs/content/config.md#inline-config-with-directives

After applying it to my schema, regenerating code, and running my GQL server my GQL client started reporting these errors:

```
Error: directive goTag is not implemented
```

Doing more research I found the following documentation about directives and the need to implement them: https://github.com/99designs/gqlgen/blob/8b9737179d3ba08405ab6422fb8c4883dd8e720c/docs/content/reference/directives.md#implement-the-directive

I was able to implement the directive on `DirectiveRoot` (`config.Directives`) as a no-op/pass through directive like so and eliminated the error:

```
resolver := resolver.CreateAndInitResolver()

config := server.Config{Resolvers: resolver}

config.Directives.GoTag = func(ctx context.Context, obj interface{}, next graphql.Resolver, key string, value *string) (res interface{}, err error) {
	// No-op/pass through directive
	return next(ctx)
}

graphql := handler.NewDefaultServer(server.NewExecutableSchema(config))
```

### What did you expect?

The aforementioned config documentation states (https://github.com/99designs/gqlgen/blob/37a4e7eefa241dd7e5eeab7bbca56b1677d37daf/docs/content/config.md#inline-config-with-directives):

> gqlgen ships with some builtin directives that make it a little easier to manage wiring.

It then lists the following builtin directives: `goModel`, `goField`, `goTag`

After reading the documentation I would expect any use of builtin directives to not require me to need to implement the directive on `DirectiveRoot` (`config.Directives`).

If an implementation is required then I would have expected:
* (Preferred :smile:) The Go code generation process to define it for more
* (Not Preferred :vomiting_face:) The documentation to state that I need to implement it with example

### Minimal graphql.schema and models to reproduce

`Schema`
```
directive @goTag(
    key: String!
    value: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

type Profile {
  email: String! @goTag(key: "validate", value: "required,email")
}

type Query {
  profile(email: String!): Profile!
}

type Mutation {
  createProfile(email: String!): Profile!
}
```

`Model`
```
type Profile struct {
	Email string `json:"email" validate:"required,email"`
}
```

Note the use of `validator` library/tags in conjunction with `goTag`: https://github.com/go-playground/validator

I wouldn't expect it to matter (i.e. you can change the key and value to `goTag` to anything and still get the same error.

### versions
 - `gqlgen version`? 
`github.com/99designs/gqlgen v0.14.1-0.20211122181954-4581fccdb67e`

I'm actually pinned to `master` at this commit: `https://github.com/99designs/gqlgen/commit/4581fccdb67e05937ba862bf601a18393731bccc`

 - `go version`?
```
$ go version
go version go1.17.3 linux/amd64
```
 
 - dep or go modules?

`go modules`

**Comment by tprebs** [comment]
Looks like its not automatically registered `goTag` to skip Runtime.  I will create a PR to fix this  but in the mean time you can add the below config to gqlgen.yml as a work around. This should stop the directive from being generated. 

```yml
directives:
  goTag:
    skip_runtime: true
```

**Comment by Giners** [comment]
Thank you so much @tprebs! :smile: :pray:
