### ISSUE TITLE
How to get the playground with graphiql version?

### ISSUE THREAD

**Issue by softshipper** [99designs/gqlgen#1764]
Hi all,

I would like to use the new GraphiQL playground that was merged with the commit https://github.com/99designs/gqlgen/pull/1751. 
When I do `go get github.com/99designs/gqlgen` it downloads the version `v0.14.0`. How to get current version of the gqlgen on my current go project?

Thanks

**Comment by giautm** [comment]
run `go get github.com/99designs/gqlgen@master`

**Comment by softshipper** [comment]
thanks a lot.
