### ISSUE TITLE
generating core failed: unable to load github.com/kelvin/gqlgen-todos/graph/model - make sure you're using an import path to a package that exists

### ISSUE THREAD

**Issue by kelvinink** [99designs/gqlgen#1765]
### What happened?
I encountered an issue when following the init instruction to init my example gqlgen project. When I ran `go run github.com/99designs/gqlgen init` it output an error message:

```
Creating gqlgen.yml
Creating graph/schema.graphqls
Creating server.go
Generating...
generating core failed: unable to load github.com/kelvin/gqlgen-todos/graph/model - make sure you're using an import path to a package that exists

Exec "go run ./server.go" to start GraphQL server
```

### What did you expect?
I expect it to generate the models, resolvers. But it didn't.

### versions
 - `gqlgen version`? 
 -  v0.15.0
 - `go version`?
 - go1.16.3
 - dep or go modules?

**Comment by yash492** [comment]
I'm, having the same issue

**Comment by ManWithA1000Names** [comment]
If you want to use v0.15.0, you can **for now** comment out the autobind option in the gqlgen.yml and it should work fine:
```yml
# ...
resolver:
# ...
  autobind:
    - "your module name/graph/model"
```
||
\\/
```yml
# ...
resolver:
# ...
#  autobind:
#    - "your module name/graph/model"
```

**Comment by ipfans** [comment]
Yes, You have some workarounds for this(choose the one you like):

1. comment the `autobind` section so you will not auto load the empty dir.
2. Touch a new empty go file in `graph/model` dir:

```
echo "package model" > graph/model/_tmp_gqlgen_init.go
```

3. Use `gqlgen` cli. I found use cli it works :)

```
go install github.com/99designs/gqlgen@latest
gqlgen init
```

**Comment by StevenACoffman** [comment]
Sorry folks! I would appreciate more code coverage around this area.

**Comment by domgolonka** [comment]
Seems the issue persists, but when I am commenting out autobind, the generate fails to find my custom models:

`modelgen: required package was not loaded: gitlab.com/domgolonka/api/scalars.UUIDmake: *** [generate] Error 1`

**Comment by ipfans** [comment]
@domgolonka Hi, have you tried the master branch yet?

**Comment by zachsmith1** [comment]
@ipfans and @StevenACoffman this is still an issue on 1.16 and on master. I was simply trying out the demo [here](https://www.howtographql.com/graphql-go/1-getting-started/) and it wouldn't work. 

Go version: 1.17

The workaround to comment out still works however I'm too naive with this library to understand the implications.

**Comment by honeywild** [comment]
what if I use a private code repo?

**Comment by StevenACoffman** [comment]
@honeywild should be fine! 

Also, I think the documentation has been corrected now @zachsmith1
