### ISSUE TITLE
gqlgen Getting started page wrong? 

### ISSUE THREAD

**Issue by fulviodenza** [99designs/gqlgen#1770]
Hi, I'm totally new to graphql, I found your getting started page and found this: 
![image](https://user-images.githubusercontent.com/9990423/149678538-e8a3865c-6f90-4154-adcd-5c60e755c0fc.png)
Is it possible that's wrong? Should UserID be User?

The page is at this link: https://gqlgen.com/getting-started/

**Comment by mfcochauxlaberge** [comment]
Yes, I think it should be `User User `json:"user"`.
