### ISSUE TITLE
Currently can't set headers to persist in graphiql

### ISSUE THREAD

**Issue by alexdibattista** [99designs/gqlgen#1776]
### What happened?
After adding a header to Graphiql and refreshing the page the header is removed from request headers section. Since we are using a auth header we can't load the documentation explorer which is helpful for local development.

### What did you expect?
The header to persist when refreshing the page.

### Minimal graphql.schema and models to reproduce
- not needed.

### versions
 - `gqlgen version  0.15.1` 
 - `go version 1.17.5`

It would be nice to have a way to set the prop [shouldPersistHeaders](https://graphiql-test.netlify.app/typedoc/modules/graphiql.html#graphiqlprops) with graphiql for development purposes.

**Comment by StevenACoffman** [comment]
So this is set in https://github.com/99designs/gqlgen/blob/master/graphql/playground/playground.go#L46

And I think it is something like this:
```
        React.createElement(GraphiQL, {
          fetcher: graphQLFetcher,
          headerEditorEnabled: true,
          shouldPersistHeaders: true
        }),
```

**Comment by StevenACoffman** [comment]
@alexdibattista Can you test if the PR #1856 works for you?

**Comment by alexdibattista** [comment]
@StevenACoffman Sorry, I missed your reply. I tested against master and it works. Thanks for the quick turnaround.
