### ISSUE TITLE
Current implementation of federation does not conform to the Apollo Federation subgraph specification

### ISSUE THREAD

**Issue by newerbie** [99designs/gqlgen#1834]
### What happened?
There are several issues in federation implementation according to the [Apollo Federation subgraph specification](https://www.apollographql.com/docs/federation/federation-spec):
1. When customizing root query type, _service is not generated in customized query struct. Then Apollo gateway cannot get service definition in subgraph.
2. If @key directive is not used in graphql schema, both _service and _entities are not generated.

### What did you expect?
1. _service is generated in customized query struct.
2. _service is generated in any case, while _entities is generated only when @key directive exists.

### Minimal graphql.schema and models to reproduce
```
schema {
    query: CustomQuery
}

type Hello {
  name: String!
}

type CustomQuery {
  hello: Hello!
}
```

### versions
 - `gqlgen version` 0.15.1
 - `go version` 1.17
 - dep or go modules? go modules

**Comment by ipfans** [comment]
@StevenACoffman Please review this and help us fix it.
