### ISSUE TITLE
provide typescript example

### ISSUE THREAD

**Issue by tmc** [99designs/gqlgen#184]
It would be nice to provide an example that uses apollo-cli's codegen:generate subcommand to generate typescript types.

**Comment by vektah** [comment]
We use it at 99designs, it works exactly [as documented by apollo](https://www.apollographql.com/docs/angular/features/developer-tooling.html#codegen). 

I don't really have the time to create one right now but if someone wanted to throw together an example I can link to that would be great :).

**Comment by gedw99** [comment]
What about other a golang client. Are we at a stage that we can generate a golang client from a graphql schema ?
