### ISSUE TITLE
generating core failed: unable to load example/graph/model in v0.16

### ISSUE THREAD

**Issue by aleybovich** [99designs/gqlgen#1860]
### What happened?
When using v0.15 and following the examples, everything worked.

After switching the new 0.16 release, when I run `go run github.com/99designs/gqlgen init` I get this error:

```
/api # go run github.com/99designs/gqlgen init
Creating gqlgen.yml
Creating graph/schema.graphqls
Creating server.go
Generating...
reloading module info
generating core failed: unable to load example/graph/model - make sure you're using an import path to a package that exists
```

and `server.go` is not generated.

### What did you expect?
No errors, server.go is generated

### Minimal graphql.schema and models to reproduce
N/A as the issue is happening before code generation

### versions
 - `gqlgen version`? 0.16.0
 - `go version`?  go version go1.16.13 linux/amd64
 - dep or go modules?

**Comment by frederikhors** [comment]
@StevenACoffman this is coming back several times.

Can we comment the `autobind` in https://gqlgen.com/config? People are copying and pasting that config when getting started.

**Comment by StevenACoffman** [comment]
I think that's fine, but if you could run through the steps and verify that that doesn't cause any different problems, I would feel better doing that. I kind of blew my OSS time budget for the week on the parser yesterday. 😞

**Comment by softshipper** [comment]
Hi all,
I have the same problem and I could not figure out why it happens. When I run `go run github.com/99designs/gqlgen generate` it shows the following error message:

```

go run github.com/99designs/gqlgen generate
reloading module info
generating core failed: unable to load calshare.io/service/graph/model - make sure you're using an import path to a package that exists
```

Would be great if someone can help.
[service.zip](https://github.com/99designs/gqlgen/files/7966753/service.zip)

**Comment by frederikhors** [comment]
@softshipper @aleybovich can you please comment out `autobind` in config and try again?

**Comment by frederikhors** [comment]
> I think that's fine, but if you could run through the steps and verify that that doesn't cause any different problems, I would feel better doing that. I kind of blew my OSS time budget for the week on the parser yesterday. 😞

I will in a few hours, @StevenACoffman.

**Comment by softshipper** [comment]
@frederikhors Thanks for your help. It works now. Why do we have to delete autobind?
