### ISSUE TITLE
Federation: requiring a field with a list of objects generates invalid code

### ISSUE THREAD

**Issue by arnemolland** [99designs/gqlgen#1861]
### What happened?
When extending a federated entity with a field of the array type containing object (not primitives/scalars) and adding a field that requires the array field, `gqlgen generate` generates invalid code. It looks like the execution context does not have any unmarshaler for the specific type. I'm not sure if this kind of relation is valid in GraphQL or if it's missing in gqlgen.

### What did you expect?
When extending a federated entity with a field of the array type containing object (not primitives/scalars) and adding a field that requires the array field, `gqlgen generate` generates valid code.

### Minimal graphql.schema and models to reproduce
```graphql
type Bar {
  id: Int!
}

extend type Foo @key(fields: "id") {
  id: Int!
  arr: [Bar!]! @external
  xyz: Int! @requires(fields: "arr")
}

```

### Logs
```
gofmt failed on federation.go: /Users/arne/dev/orgs/gameflow/backend/graph-template-go/graph/generated/federation.go:105:33: expected ')', found ',' (and 1 more errors)
validation failed: packages.Load: /Users/arne/dev/orgs/gameflow/backend/graph-template-go/graph/generated/federation.go:105:33: expected ')', found ','
/Users/arne/dev/orgs/gameflow/backend/graph-template-go/graph/generated/federation.go:105:35: expected ';', found rep
/Users/arne/dev/orgs/gameflow/backend/graph-template-go/graph/generated/federation.go:105:26: invalid operation: ec (variable of type *executionContext) is not an interface
```

### Invalid code
```go
entity.Arr, err = ec.(ctx, rep["arr"])
```

### versions
 - `gqlgen version`?  v0.14.0-dev
 - `go version`? go version go1.17.6 darwin/arm64
 - dep or go modules ? modules

**Comment by bpteam** [comment]
## Still actual for versions

- gqlgen version? v0.17.2
- go version? go version go1.17.6 darwin/arm64

**Comment by andriihrachov** [comment]
can confirm it doesnt work on v0.17.13

```
type BoostedSKU {
    sku: String!
    position: Int
    advertising_id: String!
}

type ProductsResponse @key(fields: "global_entity_id vendor_id category_uuid customer_id session_id", resolvable: false) {
    boosted_items: [BoostedSKU] @external
    items(limit: Int = 20, page: Int = 0): ProductCategoryItems @requires(fields: "boosted_items")
}```

**Comment by dariuszkuc** [comment]
fixed in https://github.com/99designs/gqlgen/pull/2884
