### ISSUE TITLE
Unable to init the project with go mod tidy v0.16.0

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#1873]
### Discussed in https://github.com/99designs/gqlgen/discussions/1854

<div type='discussions-op-text'>

<sup>Originally posted by **daviFrag** January 26, 2022</sup>
### What happened?
While i was reinitializing the go.mod file in my project go outputs this error:
````
go: found github.com/99designs/gqlgen/example/federation/accounts/graph/model in github.com/99designs/gqlgen/example v0.0.0-20220125191136-c161ab382547
go: found github.com/99designs/gqlgen/example/federation/products/graph/model in github.com/99designs/gqlgen/example v0.0.0-20220125191136-c161ab382547
go: found github.com/99designs/gqlgen/example/federation/reviews/graph/model in github.com/99designs/gqlgen/example v0.0.0-20220125191136-c161ab382547
go: github.com/99designs/gqlgen/example@v0.0.0-20220125191136-c161ab382547 requires
        github.com/99designs/gqlgen@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
````

### What did you expect?
If i manually install the gqlgen@v0.14.0 it works perfectly

### versions
 - `gqlgen version`? v0.16.0
 - `go version`? 1.16
 - dep or go modules? go modules
</div>

Additional comment by @daviFrag [here](https://github.com/99designs/gqlgen/discussions/1854#discussioncomment-2081800):

> The problem was issued is not about generation. I'm currently using gqlgen in a production backend setup as a federation (the autobind config is already commented out). The only way i can fix this importation issue is by creating a new go.mod file, then set manually the version v0.14.0 of gqlgen, run go mod tidy, and finally upgrade the version of gqlgen to v0.16.0. if i delete all the dirs in the go package 99design folder, run go mod init in the project and then go mod tidy, i face the problem again.
> 
> The real issue is generated when i try to use go mod tidy, in my go directory the importer creates two folders and that brakes the process: gqlgen->example@v0.0.0-20220125191136-c161ab382547 gqlgen@v0.16.0->all the folders of the project
> 
> `go: github.com/99designs/gqlgen/example@v0.0.0-20220130014535-a30b68de58cb requires github.com/99designs/gqlgen@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`

**Comment by ianling** [comment]
I can't reproduce this @frederikhors -- not sure if this is still an issue.

**Comment by frederikhors** [comment]
Ok. I'll close it.
