### ISSUE TITLE
Optional Any type should allow nil values

### ISSUE THREAD

**Issue by sugovsek** [99designs/gqlgen#1876]
### What happened?

When trying to use `Any` as an optional input parameter, if you omit it or pass in `null`, it panics:

```
interface conversion: interface is nil, not interface {}
```

The reason seems to be similar to the one in #799 - the relevant line in `generated.go`:

```
return ec.resolvers.Mutation().Set(rctx, args["key"].(string), args["value"].(interface{}))
```

The "value" arg should be checked for `nil` before the type assertion. If I make this change directly in the generated file, it works as expected.

### What did you expect?

Expected no error and the argument to be resolved to `nil`.

### Minimal graphql.schema and models to reproduce

```
mutation {
    set(key: String!, value: Any): Boolean
}

scalar Any
```

### versions
 - `gqlgen version`? v0.16.0
 - `go version`? 1.17
 - dep or go modules? go modules

**Comment by AdamJSoftware** [comment]
Any news on this? Any potential work arounds?

**Comment by sugovsek** [comment]
My current workaround is an ugly hack, basically editing the generated file to check the value:

```
var value interface{}
if args["value"] != nil {
    value = args["value"].(interface{})
}
return ec.resolvers.Mutation().SetValue(rctx, args["key"].(string), value)
```

I'm planning to dig into the templates and make a proper fix, but I'm not sure when since I'm pretty busy these days.
