### ISSUE TITLE
Return nil on null slice

### ISSUE THREAD

**Issue by rkeck** [99designs/gqlgen#1967]
### What happened?
When setting a nullable array (ex. contactInformation) to null or omitting it, i get an empty slice instead of nil.

### What did you expect?
To differentiate between setting an empty array "[]" or null, I expect to get a nil slice when "null-ing" a nullable GraphQL input field.

### Minimal graphql.schema and models to reproduce
GraphQL Spec:
```graphql
input ModifyContactInput {
  id: ID!
  contactInformation: [ContactInformationInput!] # can be null or "[]"
}

input ContactInformationInput {
  type: String!
  value: String!
}

type Mutation {
  modifyContact(input: ModifyContactInput!): Contact!
}
```

Generated models:
```go
type ModifyContactInput struct {
	ID                 string                    `json:"id"`
	ContactInformation []ContactInformationInput `json:"contactInformation"`
}

type ContactInformationInput struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

func (r *mutationResolver) ModifyContact(ctx context.Context, input models.ModifyContactInput) (*models.Contact, error) {
        log.Debug(input.ContactInformation) // is always []
	fields := graphql.CollectFieldsCtx(ctx, nil)
	return r.ContactService.ModifyContact(ctx, &input, fields)
}
```

### versions
 - `gqlgen version` v0.16.0
 - `go version` 1.17.3
 - dep or go modules? go modules

**Comment by 8tomat8** [comment]
Stumbled upon this today as well. From what I could find the reason is in this template
https://github.com/99designs/gqlgen/blob/44beadc1d037a0d46c799c85d88dc71a57f3938b/codegen/type.gotpl#L11-L24

This piece of code basically creates a new `res` slice, which in the case of `v == nil` will be translated into an empty list of elements.

Is it a bug and I create a PR or it was made on purpose?

**Comment by rkeck** [comment]
Nevermind, did a rookie mistake...
fmt and log just handle nil and empty slice the same by default and "return" []. So no problem with gqlgen here.
