### ISSUE TITLE
Request: support `extend` feature

### ISSUE THREAD

**Issue by vvakame** [99designs/gqlgen#200]
aka Extension.

our team's usecase is...

There is something I want to hide schema itself from users.
likes...

```graphql
# public!
type User {
    id: ID
    name: String
    point: Int @requiredLogin
}
```

```graphql
# confidential... What kind of information we have.
directive @hasRole on FIELD

enum Role {
    USER
    STAFF
    ADMIN
}

extend type User {
    creditScore: Int @hasRole(role: STAFF)
    loginHistories: [LoginHistory!]! @hasRole(role: ADMIN)
    relatedServices: [Service!]! @hasRole(role: ADMIN)
}
```

I am happy to have https://github.com/vektah/gqlgen/issues/6 , but I can handle without it.

**Comment by vektah** [comment]
[Type extensions](http://facebook.github.io/graphql/draft/#sec-Object-Extensions) will work with the new parser

Hiding stuff from the introspection api though sounds interesting, we will make sure to take it into account in the directive planning.

**Comment by vvakame** [comment]
yay! SchemaExtension also seems to be useful too.
