### ISSUE TITLE
Where is the CMD package github.com/99designs/gqlgen/cmd ?

### ISSUE THREAD

**Issue by khanakia** [99designs/gqlgen#2025]
### What happened?
`cmd` pkg does not exist anymore github.com/99designs/gqlgen/cmd  I am using cmd package for some custom work how do i get this package back ?
### Minimal graphql.schema and models to reproduce
```
type Image {
	url: String
  size: String
}
```
### versions
 - `go run github.com/99designs/gqlgen version` 0.17.0
 - `go version` go version go1.17.7 darwin/amd64

**Comment by frederikhors** [comment]
Oh my. @mtibben @StevenACoffman I think we're going to have tons of issues like this.

**Comment by mtibben** [comment]
Any api exposed by cmd was entirely accidental. And gqlgen api is unstable, we haven't hit v1.0.0. Feel free to PR any functionality your require here
