### ISSUE TITLE
gqlgen v0.17.1 and gqlparser v2.4.0 introduce "Variable is never used" error

### ISSUE THREAD

**Issue by skaji** [99designs/gqlgen#2028]
### What happened?

After upgrading gqlgen v0.17.1 and gqlparser v2.4.0,
a graphql query that has some fragments (which need variables) emits error:

```
Variable "$flag" is never used in operation "foo".
```

### What did you expect?

No error.

### Minimal graphql.schema and models to reproduce

Please look at 
https://github.com/skaji/gqlgen-quick-start/tree/gqlgen-v0.16.0
https://github.com/skaji/gqlgen-quick-start/tree/gqlgen-v0.17.1

The grapql query in question is

```graphql
query foo($flag: Boolean!) {
  ...bar
}
fragment bar on Query {
  __typename @include(if: $flag)
}
```
```
// variables
{"flag":true}
```

#### gqlgen-v0.16.0

With https://github.com/skaji/gqlgen-quick-start/tree/gqlgen-v0.16.0, the response of the graphql query is:

```json
{
  "data": {
    "__typename": "Query"
  }
}
```

This is expected.

#### gqlgen-v0.17.1

OTOH, with https://github.com/skaji/gqlgen-quick-start/tree/gqlgen-v0.17.1, the response of the graphql query is:

```json
{
  "errors": [
    {
      "message": "Variable \"$flag\" is never used in operation \"foo\".",
      "locations": [
        {
          "line": 1,
          "column": 11
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ],
  "data": null
}
```

This is unexpected.

### versions
 - `go run github.com/99designs/gqlgen version`? 0.17.1
 - `go version`? 1.17.7

**Comment by Code-Hex** [comment]
Exactly. We have to check directives too. I think this is a bug :bow:
https://spec.graphql.org/October2021/#sec--include

**Comment by skaji** [comment]
@Code-Hex Thanks for catching this up.
So which do you think this is a bug of gqlgen, or of gqlparser?

**Comment by Code-Hex** [comment]
@skaji this is caused by gqlparser

```go
if _, ok := parent.(*ast.FragmentSpread); !ok {
	w.walkDirectives(nextParentDef, it.Directives, ast.LocationField)
}
w.walkSelectionSet(nextParentDef, it, it.SelectionSet)
```

in walkSelectionSet method. I'm just working on it right now.

**Comment by Code-Hex** [comment]
@skaji I'm Sorry for the inconvenience. 
I sent PR https://github.com/vektah/gqlparser/pull/201
Maybe the maintainer will be merge and release a new version for this. Thanks

**Comment by skaji** [comment]
@Code-Hex @StevenACoffman Thanks!
