### ISSUE TITLE
GraphQL type "id" gets compiled to ID

### ISSUE THREAD

**Issue by Joelgullander** [99designs/gqlgen#2061]
### What happened?
If we type a graphql type as id, when we run the recompile the model gets rewritten to ID.

### What did you expect?
If named id, the result should be Id, not ID.

### Minimal graphql.schema and models to reproduce
```
type DeliverySlot {
  id: ID!
}
```

Gets converted to 

```
type DeliverySlot struct {
	ID                                   string   `json:"id"`
}
```

Expected Id.

### versions
 - `go run github.com/99designs/gqlgen version`?
 - `go version`?
 
 v0.17.1
 go version go1.17.1 darwin/amd64

**Comment by mpieczaba** [comment]
Actually, it is a [feature](https://github.com/99designs/gqlgen/blob/1f04d38a4441c5de6171400218b9dd25cebb3639/codegen/templates/templates.go#L447), not a bug.

**Comment by frederikhors** [comment]
Please tell me if we need to reopen this.
