### ISSUE TITLE
Missing files when using go mod vendor

### ISSUE THREAD

**Issue by lindlof** [99designs/gqlgen#2081]
### What happened?

When using `go mod vendor` to vendor dependencies some files are not included like everything in `graphql/introspection` directory.

This causes an error like:
```
reloading module info
reloading module info
reloading module info
merging type systems failed: unable to build object definition: unable to find type: github.com/99designs/gqlgen/graphql/introspection.EnumValue
```

Related to https://github.com/golang/go/issues/26366

### What did you expect?

All files required by `api.Generate` to be included in `vendor/github.com/99designs/gqlgen` directory

### Minimal graphql.schema and models to reproduce

Any schema

### versions
- `github.com/99designs/gqlgen v0.17.2`
- `go version go1.17.8 darwin/arm64`
- `go version go1.18 darwin/arm64`

**Comment by darrensapalo** [comment]
1. `gqlgen` depends on certain non-go related files.
2. [go mod vendor unfortunately does not include those files it requires when using `go mod vendor`](https://github.com/golang/go/issues/26366)

## Workaround

The following enabled me to run `go run github.com/99designs/gqlgen generate` to generate the models, etc.

1. Delete the vendorized dependencies `vendor/github.com/99designs/gqlgen`.
2. Clone this 99designs/gqlgen project into the directory `vendor/github.com/99designs`.
3. Run `go run github.com/99designs/gqlgen generate`.

**Caveats**

Not sure yet what the impact will be, when you attempt to do `go mod vendor` ... will the missing files be deleted? I am not sure yet (still experimenting... might post results here later).

**Comment by shyyawn** [comment]
Did this start happening with v0.17.2? I just upgraded my packages and this started happening.

**Comment by thesolution** [comment]
I had to `go get go get github.com/hashicorp/golang-lru` after executing the workaround.

versions
* `github.com/99designs/gqlgen v0.17.5`
* `go version 1.18 darwin/amd64`

**Comment by frederikhors** [comment]
@milesich [answer](https://github.com/99designs/gqlgen/issues/2081#issuecomment-1126099404) is the way to go. It has been said many times now.

**Comment by thesolution** [comment]
I feel like the documentation needs an update if this is the preferred method.  All projects at my job must be vendered.  I was able to unblock myself using this issue.

**Comment by frederikhors** [comment]
@thesolution can you PR?

**Comment by thesolution** [comment]
@frederikhors I haven't before.  Should I create an issue for a documentation update first or just put that info in the PR?

**Comment by frederikhors** [comment]
Create a PR. Someone on the team will consider whether to merge it.
