### ISSUE TITLE
Q: Can we add a prefix in the values of the generated JSON flags for each struct in schema?

### ISSUE THREAD

**Issue by droslean** [99designs/gqlgen#2086]
For example, let's say that we have this schema
```
type Person {
	id: ID!
	name: String! @id @search
	email: String
```
If we can somehow specify a prefix `MyPrefix.` for that struct then we can expect to generate:
```go
type Person struct {
	ID                        string                          `json:"MyPrefix.id"`
	Name                      string                          `json:"MyPrefix.name"`
	Email                     *string                         `json:"MyPrefix.email"`
}
```

Why do I need this?

I am using a dgraph as a database and unfortunately, their DQL is generating the schema using a prefix as predicates.

**Comment by frederikhors** [comment]
You already asked this.
