### ISSUE TITLE
Middleware does not pass the correct context

### ISSUE THREAD

**Issue by droslean** [99designs/gqlgen#2105]
Following the docs in 
https://github.com/99designs/gqlgen/blob/master/docs/content/recipes/authentication.md

```go
func Middleware() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := context.WithValue(r.Context(), userCtxKey, "whatever")
			r = r.WithContext(ctx)
			next.ServeHTTP(w, r)
		})
	}
}
```

Context in Middleware is: 
`&context.valueCtx{Context:(*context.valueCtx)(0xc000098900), key:(*users.contextKey)(0x18745c0), val:"whatever"}`

The context passed in queryResolver is different:
```go
func (r *queryResolver) GetPerson(ctx context.Context, name *string) (*model.Person, error) {
	fmt.Printf("Context: %#v", ctx)
}
```
`Context: &context.valueCtx{Context:(*context.valueCtx)(0xc000099470), key:"resolver_context", val:(*graphql.FieldContext)(0xc000096780)}`

### versions
github.com/99designs/gqlgen v0.17.2
go version go1.17.1 linux/amd64

**Comment by droslean** [comment]
@vektah Any ideas?

**Comment by frederikhors** [comment]
The context works very good for us. Please, create a SIMPLE repro and we can re-open this.
