### ISSUE TITLE
Federation v2 support

### ISSUE THREAD

**Issue by superbeeny** [99designs/gqlgen#2114]
Previous issue was closed

We've also found this as gqlgen does not handle the @shareable directive which is a key component of federation 2.

@StevenACoffman i think this will need to be addressed, [according to Apollo's federation 2 compatibility table](https://github.com/apollographql/apollo-federation-subgraph-compatibility) `gqlgen` is not compatible with the new federation spec.

_Originally posted by @jakemhiller in https://github.com/99designs/gqlgen/issues/1695#issuecomment-1098277141_

**Comment by shellfu** [comment]
This has also been a blocker for us to move to federation 2. I would love to see this implemented!!

**Comment by frederikhors** [comment]
Can you both PR?

**Comment by lleadbet** [comment]
@superbeeny - it was just merged, but likely needs a new version cut; @StevenACoffman can speak to next release timing

**Comment by StevenACoffman** [comment]
Hi. I would appreciate it if you pinned to the latest commit and then ran the [Apollo Federation tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility):
```
go get -d github.com/99designs/gqlgen@2a2a3dcb67c7d713e41476eac47e20ab0e21fba7
```

**Comment by lleadbet** [comment]
Ran the tests and will get the updated version in the Apollo tests, but the updated results are:

| Language | Library | Federation 1 Support | Federation 2 Support |
| --- | --- | --- | --- |
| Go | [gqlgen](https://gqlgen.com) | <table><tr><th>_service</th><td>✅</td></tr><tr><th>@key (single)</th><td>✅</td></tr><tr><th>@key (multi)</th><td>✅</td></tr><tr><th>@key (composite)</th><td>✅</td></tr><tr><th>@requires</th><td>✅</td></tr><tr><th>@provides</th><td>✅</td></tr><tr><th>@ftv1</th><td>❌</td></tr></table> | <table><tr><th>@link</th><td>✅</td></tr><tr><th>@shareable</th><td>✅</td></tr><tr><th>@tag</th><td>✅</td></tr><tr><th>@override</th><td>✅</td></tr><tr><th>@inaccessible</th><td>✅</td></tr></table> |

Fork: https://github.com/lleadbet/apollo-federation-subgraph-compatibility
PR: https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/87

**Comment by StevenACoffman** [comment]
I cut a new release, so @lleadbet if you would like to update your PR you no longer need to pin gqlgen to a specific commit.

**Comment by lleadbet** [comment]
Thanks! Just updated my PR and will get that in soon.

**Comment by StevenACoffman** [comment]
I think we are all good here then! Please open a new issue if you encounter any Federation 2 support issues!

**Comment by dennissetiawan** [comment]
does gqlgen support composite key in federation v1?

**Comment by StevenACoffman** [comment]
Yes. See above.

**Comment by dennissetiawan** [comment]
oops sorry. just want to make sure. got confused with apollo federation docs https://www.apollographql.com/docs/federation/v1/other-servers
turn out it is updated in the v2 for the federation v1
