### ISSUE TITLE
Why is schema.resolvers.go in .gitignore?

### ISSUE THREAD

**Issue by yay** [99designs/gqlgen#2116]
### What happened?

`.gitignore`'s contents:
```
...
# generated files
/graph/generated
/graph/schema.resolvers.go
/graph/model/models_gen.go
...
```
### What did you expect?

Not to see `/graph/schema.resolvers.go` in `.gitignore` because it's not only generated but also manually implemented according to the getting started guide: `Returning to graph/schema.resolvers.go, let’s implement the bodies of those automatically generated resolver functions.`

### Minimal graphql.schema and models to reproduce

N/A

### versions
 - `go run github.com/99designs/gqlgen version`: v0.17.2
 - `go version`: go1.18.1 darwin/arm64

**Comment by ianling** [comment]
gqlgen does not create a `.gitignore` file, I'm not sure where this could have come from.

**Comment by frederikhors** [comment]
@ianling answered, thank you.
