### ISSUE TITLE
Tag mapping

### ISSUE THREAD

**Issue by tkallioras** [99designs/gqlgen#212]
In every model for my database I have these 3 fields:

```
_id
_key
_rev
```

In order for the marshalling and unmarshalling to work correctly I need to place these three tags on each golang struct:

```
json:"_id"
json:"_key"
json:"_rev"

```

(_Note that these three properties are required by the database, so I cannot change the tags_)

When I autogenerate the **graphql type** the json tags are also autogenerated. The issue here is that the database variables start with underscore, and all types in Go that start with an underscore are not exported (thus I can't declare a field to start with an underscore, so as that I could have an autogenerated json tag starting with underscore)

Is there any way to bypass this issue? In case there isn't, would it be possible to have an entry in the configuration file, where we could map certain fields with certain tags (and have the rest autogenerated)?

**GraphQL type:**

```
type User {
  id: ID!
  key: ID!
  rev: String!
}
```

**Autogenerated Go struct:**

```
type User struct {
	ID          string     `json:"id"`
	Key         string     `json:"key"`
	Rev         string     `json:"rev"`
}
```

**Comment by vektah** [comment]
Model generation isn't really set up to cover every use case. If you want something unusual you'll have to build the models yourself and reference them in the config.

At some point in the future the templates might be configurable, but for now there are other features that have a higher priority (and have less conflicting requirements from different people)

**Comment by tkallioras** [comment]
Yes I figured, however we use a couple of models with more than a hundred fields, and we will then have to manually keep them in sync with the GraphQL models (which have the same number of fields) and the error margin increases this way (that's why we found the autogenerate feature really nice).

We may try to provide a PR. Maybe an extra field in the config yaml file named `GlobalTagMapping`. It may be fairly simple to provide some field names that require different tags across the whole project and have object generation take that into consideration.

**Comment by vvakame** [comment]
Is this Issue over?

**Comment by domsn** [comment]
@vvakame You can use [inline-config-with-directives](https://gqlgen.com/config/#inline-config-with-directives), fox example:

```
type User {
  _id: String! @goField(name: "id")
}

# regenerate using below command
# go generate ./...
# and you will see the generated code

type User struct {
    ID       string  `json:"_id"`
}

```
