### ISSUE TITLE
Using query string as span name of opentracing is hard to see

### ISSUE THREAD

**Issue by yamitzky** [99designs/gqlgen#215]
I am using opentracing feature with Jaeger.

Because query string can be longer as GraphQL schema grows, span name can be very long.

I found it on Jaeger's UI, but similar issues may occur on other opentracing UIs.

How do you think to use more shorter name?

### Actual Behavior

![image](https://user-images.githubusercontent.com/623449/43057841-75a614aa-8e7f-11e8-92b2-1197b4b936a5.png)

Notice: It occupies my 13-inch Macbook Pro's screen!

**Comment by vektah** [comment]
I'm not sure how to make this better, operation name is user specified and would let tricky people manipulate your stats in weird ways.

Open to suggestions!
