### ISSUE TITLE
Support of Apollo Tracing?

### ISSUE THREAD

**Issue by dtrinh50** [99designs/gqlgen#219]
Hi, are there any plans to support Apollo Tracing? Not sure if it would belong in this library, but just wanted to check.

**Comment by ermik** [comment]
@dtrinh50 I think one can implement the tracing spec by using context and number of middlewares that would collect the necessary data, then just adding an additional field `extensions` to the response payload. Look at the [dataloader](https://gqlgen.com/reference/dataloaders/#dataloader) example using context.
