### ISSUE TITLE
automatic use of "embed" package generates the wrong path on windows

### ISSUE THREAD

**Issue by vikstrous** [99designs/gqlgen#2190]
### What happened?
https://github.com/99designs/gqlgen/pull/2119 caused a regression on windows because it generates file paths in an OS-dependent way while it should always use `/`. See docs for "embed":

> The path separator is a forward slash, even on Windows systems. 

- https://pkg.go.dev/embed

### What did you expect?
gqlgen should generate correct paths on windows

### Minimal graphql.schema and models to reproduce
omitted... too long to include.. I'll just make the PR fixing it.

### versions
 - `go run github.com/99designs/gqlgen version`?  0.17.7
 - `go version`? 1.18

**Comment by frederikhors** [comment]
@StevenACoffman can you please release this?
