### ISSUE TITLE
Missing complete event for successful query/mutation over websocket

### ISSUE THREAD

**Issue by alexdavid** [99designs/gqlgen#2215]
### What happened?
Prior to v0.17.6 when completing a GraphQL query/mutation over websocket the server would respond with a `complete` message, however after 0.17.6 this message now isn't sent. According to https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#complete a complete message should be sent by the server when `the requested operation execution has completed` which I think would imply that it should be sent after a successful query/mutation response. Is this correct? If not, is it the responsibility of the client to send a `complete` after receiving the `next` event for a query/mutation?

### What did you expect?
The example client promise usage at https://github.com/enisdenjo/graphql-ws works only if the backend sends a complete message on successful query/mutation which it has been doing prior to v0.17.6. If this is not the intended workflow then the example implementation on that repo is wrong.

**Comment by frederikhors** [comment]
Can you identify which of the latest commits changed something?

**Comment by alexdavid** [comment]
Yes, I'll bisect this today and get back to you

**Comment by alexdavid** [comment]
I bisected this and found that the problem commit was eef7bfaad1b524f9e2fc0c1150fdb321c276069e which was actually reverted a few hours after I opened this issue in 6855b7290cab62a1fc6a26a2b633e0b5bbf248da! So testing against latest master has this fixed. Thank you for the quick fix :smile:!
