### ISSUE TITLE
Improve GraphQL http handler

### ISSUE THREAD

**Issue by salmana1** [99designs/gqlgen#223]
First off, this library has come far within few months so kudos to everyone who has contributed to this project. Thank you for your hard work!

This is s feature/enhancement suggestion. We are switching from `graph-gophers/graphql-go` and would like to use the out of the box http handler: `handler.GraphQL` instead of using our own. We have certain features in ours which would be great to have in `handler.GraphQL`.  Here is a list of few things that could be improved

1. Option to add custom CORS header, maybe use `github.com/rs/cors`
2. Handle batch requests i.e., an array of grapql requests. This would be very useful when using Apollo on client side
3. Use http status `BadRequest` instead of `StatusUnprocessableEntity`; `BadRequest` is more common and understood by everyone
4. Middleware to handle CSRF token
5. Middleware to handle authentication & authorization

I would be happy to submit a PR

**Comment by vektah** [comment]
Most of this comes down to middleware, and the graphql handler is a standard http handler so you should be able to bring your own.
 - rs/cors for cors
 - gorilla sessions for sessions
 - gorilla csrf for csrf
 - Authentication almost always needs to be handled in app, but maybe your looking for something like open

Maybe what's needed here are some good examples?

Batch requests and changing the status should be pretty straightforward though.

**Comment by ermik** [comment]
Looking at this now and I am eager to agree with a couple of comments. In JS community one goes to [`artsy/metaphysics`](https://github.com/artsy/metaphysics/) and learns how to build a GraphQL API. In go world there is a lot of helpful examples that usually accomplish this task, one that comes to mind is [`addsvc`](https://github.com/go-kit/kit/tree/master/examples/addsvc) that runs through the features of `go-kit`. Perhaps an example repo with plenty of comments will use as a guide to building not just better GraphQL services, but better APIs in general.

**Comment by salmana1** [comment]
@vektah, 

I was trying to say that if we add some more common hooks similar to `ResolverMiddleware etc` , it will resolve all these. As I said, I would be happy to create a PR. However, I understand if you think additional middlewares should be handled by using a library like gorilla.

**Comment by marpaia** [comment]
On one hand, I really like the consistency of using the `net/http` APIs to chain HTTP middleware, but I think some of the bullets that @salmana1 enumerates would be nice to have in the core API here. Salman, do you have any code examples of how one would use these middlewares, from an API users perspective?

**Comment by vektah** [comment]
I've started adding [docs](https://gqlgen.com/recipes/authentication/) to address these.

**Comment by mathewbyrne** [comment]
Closing, we have no plans to support additional HTTP features that are done much better by other libraries.  Feel free to open up another issue if you think there are use-cases we could better document.
