### ISSUE TITLE
WebsocketInitFunc sample recipe seems outdated

### ISSUE THREAD

**Issue by SebLKMa** [99designs/gqlgen#2243]
### Sample recipe codes using `WebsocketInitFunc` from below seems to be outdated with build errors.
https://github.com/99designs/gqlgen/blob/master/docs/content/recipes/authentication.md. 
https://github.com/99designs/gqlgen/blob/master/docs/content/recipes/authentication.md#websockets. 
```go
func main() {
	router := chi.NewRouter()
	router.Use(auth.Middleware(db))
	router.Handle("/", handler.Playground("Starwars", "/query"))
	router.Handle("/query",
		handler.GraphQL(starwars.NewExecutableSchema(starwars.NewResolver())),
		WebsocketInitFunc(func(ctx context.Context, initPayload InitPayload) (context.Context, error) {
                         ...
			return userCtx, nil
		}))
	)
	err := http.ListenAndServe(":8080", router)
	if err != nil {
		panic(err)
	}
}
```

### Fix by using handler.Server.AddTransport(..., InitFunc,...)
```go
	srv := handler.New(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{
		...,
	}}))
	srv.AddTransport(transport.POST{})
	srv.AddTransport(transport.Websocket{
		KeepAlivePingInterval: 10 * time.Second,
		Upgrader: websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				return true
			},
		},
		InitFunc: func(ctx context.Context, initPayload transport.InitPayload) (context.Context, error) {
			return yourImplFunc(ctx, initPayload)
		},
	})
```

### Minimal graphql.schema and models to reproduce
N.A.

### versions
 - gqlgen version v0.17.10
 - go version go1.18.2 linux/amd64

Perhaps documentation needs to be updated.

**Comment by tmc** [comment]
@SebLKMa Can you open a PR to reflect these suggestions?

**Comment by SebLKMa** [comment]
sure, will attempt to do it this week

**Comment by rootkea** [comment]
It seems we can't use `handler.NewDefaultServer()` and then add websocket transport with `InitFunc`. i.e. In above recipe one can't use `handler.NewDefaultServer` instead of `handler.New` or am I missing something?

Is there any way to use `handler.NewDefaultServer` and also specify the `InitFunc` for websocket transport?

Thanks!

**Comment by SebLKMa** [comment]
The `handler.NewDefaultServer()` has [already added a Websocket transport](https://github.com/99designs/gqlgen/blob/master/graphql/handler/server.go) but without any `InitFunc` to its array of transports.
Currently, I am not aware if there is documented function to specify an `InitFunc` for an existing Websocket transport.
Hence, using `New` instead of `NewDefaultServer` in order to have control over defining transports.
HTH
