### ISSUE TITLE
Embed templates into source

### ISSUE THREAD

**Issue by clayne11** [99designs/gqlgen#2260]
### What happened?
Using this library with Bazel is currently challenging for a number of reasons. One is the usage of `packages.Load`. The other is that the template files are not included in the binary.

`genqlient` recently made [this change](https://github.com/Khan/genqlient/pull/180) and not only is the API much nicer, it is much easier to consume with Bazel.

Are you open to a similar PR for `gqlgen`?

**Comment by frederikhors** [comment]
Please PR. Thanks.
