### ISSUE TITLE
Test client throws an error when trying to deserialize a Time scalar field

### ISSUE THREAD

**Issue by dball** [99designs/gqlgen#2265]
### What happened?

The test client throws an error when trying to deserialize a Time scalar field, e.g.:

```
		var resp struct {
			ActionCreate model.ActionCreatePayload
		}
		require.NoError(t, client.Post(query, &resp))
```

```
--- FAIL: Test_Actions (0.01s)
    --- FAIL: Test_Actions/create_action (0.00s)
        /Users/donald.ball/src/go/internal/gateway/test/actions_test.go:51: 
            	Error Trace:	actions_test.go:51
            	Error:      	Received unexpected error:
            	            	1 error(s) decoding:
            	            	
            	            	* 'ActionCreate.action.expirationTime' expected a map, got 'string'
            	Test:       	Test_Actions/create_action
```

### What did you expect?

I expected this to not raise an error  and for the `Time` field to contain a `time.Time` instance.

Moreover, it does not seem possible to provide a custom pair of marshal functions for this magic scalar type, so there are no apparent workarounds possible.

### Minimal graphql.schema and models to reproduce

```
type TestType {
  now Time
}
```

Using this with the gqlgen test client breaks any response that contains the `now` field.

### versions
 - `go run github.com/99designs/gqlgen version`?
 
 `v0.14.0-dev`

 - `go version`?

`go version go1.18.1 darwin/amd64`

**Comment by frederikhors** [comment]
Please update the version and if the issue persists I will reopen.
