### ISSUE TITLE
The Changelog is a joke

### ISSUE THREAD

**Issue by oofdog** [99designs/gqlgen#2282]
Let me start by saying this is a great package, much better than the alternatives IMO and have enjoyed using it all throughout.

You see, I hadn't used it in a while (0.13 to be exact) so when I got back into recently, I figured I'd look at the changelog to see what's new and if there were any breaking changes should I want to upgrade my old code.

You can imagine the look on my face when I opened it up and saw this
![image](https://user-images.githubusercontent.com/46097282/178118064-4663f2da-adeb-42af-9686-3c398f612c33.png)

The thing is, a changelog should tell a story. It should give users (new and returning) an organized summary of the project's developments, and most importantly, any breaking changes between versions. Instead, what I'm seeing here are git commit messages (for all I know).

For reference, here's graphql-ruby's changelog
![image](https://user-images.githubusercontent.com/46097282/178118235-cb08dc69-cb10-4160-b187-71807f3f4fd0.png)

and React's

![image](https://user-images.githubusercontent.com/46097282/178118244-54ea21a8-5cec-4d62-9e8a-d3117494f539.png)

and Bun's

![image](https://user-images.githubusercontent.com/46097282/178118276-27e4f515-8913-400e-9374-92617280bed7.png)

Seeing a difference? Git commit messages aren't meant to be substitutes for changelog updates. As consumers of this package, we're not going to dig into each commit to figure out, for ourselves, what the bug fixes, new features and breaking changes are. As maintainers you should be doing that.

**Comment by frederikhors** [comment]
You're right. And we already know we need to improve this. Can you contribute in any way?

**Comment by oofdog** [comment]
> You're right. And we already know we need to improve this. Can you contribute in any way?

How can I? I'm not a maintainer of this project and I know next to nothing about its internals, history, etc. Only the people that have worked on it can do it.

I'm glad you guys are aware, to say the least.

**Comment by frederikhors** [comment]
I meant that you can propose and set up a way to get those changelogs so we don't have to spend time thinking about how to do it.

And you can also propose PR.

For those who maintain it is easier and faster to accept than to think.

**Comment by oofdog** [comment]
> I meant that you can propose and set up a way to get those changelogs so we don't have to spend time thinking about how to do it.

What do you mean? LIke a template? Here you go

```
# <<release version>>

### Breaking changes
-
-

### Deprecations
-
-

### New features
-
-

### Bug fixes
-
-
```

**Comment by frederikhors** [comment]
That's not what I meant.

Anyway thanks for the proposal, I'm sure the maintainers will do something to improve the CHANGELOG.

**Comment by oofdog** [comment]
> That's not what I meant.

Can you explain what you meant then? Are you asking for a way to automate getting the changelog? I'm not sure..

**Comment by oofdog** [comment]
@frederikhors Here's a guideline https://keepachangelog.com/en/1.0.0/

**Comment by oofdog** [comment]
Also, I'm not sure why you marked this issue as closed when it hasn't been resolved yet.

**Comment by cyberhck** [comment]
Hello maintainers,
I can take care of setting up a process for changelog if you would accept my PR, here's my idea:
- Add a status check that enforces semantic-commit-message format.
- Setup [semantic release](https://semantic-release.gitbook.io/semantic-release) to do the release management
- Get rid of existing release management.

This way, anytime something's merged if it's either a `feat`ure or a bug `fix`, gqlgen would automatically release.
We can discuss more if you'd like a slightly different scenario like releasing on a schedule and release candidates / previews etc.

**Comment by cyberhck** [comment]
@frederikhors
