### ISSUE TITLE
Generator doesn't handle type aliases, but gqlgen doesn't handle type definitions.

### ISSUE THREAD

**Issue by psigen** [99designs/gqlgen#2283]
### What happened?

I have a type declared in another go module that I would like gqlgen to serialize and deserialize.  It also has another set of serdes for another package, so I cannot declare it in my gqlgen models code.

I have found that during code generation time, I need to use a type declaration _embedding_ the other type, and then during compilation, I need to switch this back to an _alias_ to get the correct type for runtime usage.

This is the specific error I get if I use a type alias:
```
gofmt failed on models_gen.go: /home/pras/example/graph/model/models_gen.go:56:22: expected ';', found 'type' (and 62 more errors)
```

And inspecting fields using the type in `models_gen.go`, I see the following:
```
ID invalid type `json:"id" bson:"_id"`
```

### What did you expect?

I expect that using a type alias should not cause problems during the generation step.

### Minimal graphql.schema and models to reproduce

```golang
type ExampleDoc {
  id: UUID!
}
```

```golang
// Implements a bidirectional conversion for UUIDs between mongo and gqlgen.
package model

import (
	"errors"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/example/services"
)

// This will fail on the code generation step but works fine at runtime.
type BsonUUID = services.BsonUUID

// This works in the code generation step but because the type does not match anymore, other non-gqlgen serdes functions fail.
// type BsonUUID services.BsonUUID

// MarshalUUID allows uuid to be marshalled by graphql
func MarshalUUID(id BsonUUID) graphql.Marshaler {
	return graphql.MarshalString(id.String())
}

// UnmarshalUUID allows uuid to be unmarshalled by graphql
func UnmarshalUUID(v interface{}) (BsonUUID, error) {

	idAsString, ok := v.(string)
	if !ok {
		return BsonUUID{}, errors.New("id should be a valid UUID")
	}

	id, err := uuid.Parse(idAsString)
	if err != nil {
		return BsonUUID{}, errors.New("id was not parsable")
	}

	return BsonUUID{UUID: id}, nil
}
```

```golang
package services

import (
	"github.com/google/uuid"
)

type BsonUUID struct {
	uuid.UUID
}

// Serdes used by MongoDB down here.
// [...]
```

### versions
 - `go run github.com/99designs/gqlgen version`? `v0.17.12`
 - `go version`? `go version go1.18.3 linux/amd64`

**Comment by frederikhors** [comment]
I think you're missing the config.yml setting for your `"github.com/example/services.BsonUUID"`.

Please read https://gqlgen.com/config/ and let me know if this works and need to be reopened:

```yml
models:
  UUID:
    model:
      - github.com/example/services.BsonUUID
```

**Comment by psigen** [comment]
So I already had the following in my `gqlgen.yml`
```
models:
  UUID:
    model:
      - github.com/example/graph/model.UUID
```

I would have thought that this would resolve using the type alias to `github.com/example/services.BsonUUID`.  Is that not expected to work?  I was trying to avoid having this path hard-coded in multiple places outside of the alias.

**Comment by amirhossein-shakeri** [comment]
I used type aliases to override default gql id with MongoDB primitive object id [here in this issue](https://github.com/99designs/gqlgen/issues/1313#issuecomment-2225271612) and it works for me this way.
