### ISSUE TITLE
graphql.ErrorOnPath discards error wrapping around *gqlerror.Error

### ISSUE THREAD

**Issue by andrejgou** [99designs/gqlgen#2286]
### What happened?
Any errors wrapped around an instance of `*gqlerror.Error` will be discarded when `graphql.ErrorOnPath` is called because of this block:
https://github.com/99designs/gqlgen/blob/fb13091df76b47b936224336fe19b15fe310b41d/graphql/error.go#L25-L29

Our application uses a custom error presenter to retrieve and log supplemental information annotated on errors in application code or through GraphQL directives using error wrappers, e.g. errors.WithMessage
https://pkg.go.dev/github.com/pkg/errors#WithMessage

Because the error passed to the error presenter is first processed with `ErrorOnPath`
https://github.com/99designs/gqlgen/blob/fb13091df76b47b936224336fe19b15fe310b41d/graphql/context_response.go#L48

we will lose any annotated information wrapped around the original `*gqlerror.Error` since the error wrappers have been discarded.

See a minimal example to reproduce in a golang playground:
https://go.dev/play/p/TzCt0-D-LRU

```
err := &gqlerror.Errorf("innermost")
// error annotation in application code or directive
wrappedErr := errors.WithMessage(err, "wrapped message")
// called on input to errorPresenter
strippedErr := graphql.ErrorOnPath(context.Background(), wrappedErr)

fmt.Printf("expect:\t\"%v\"\n", wrappedErr.Error())
fmt.Printf("actual:\t\"%v\"\n", strippedErr.Error())
```
yields
```
expect:	"wrapped message: input: innermost"
actual:	"input: innermost"
```

### What did you expect?
The above code snippet should instead output
```
expect:	"wrapped message: input: innermost"
actual:	"wrapped message: input: innermost"
```

### Minimal graphql.schema and models to reproduce
No schema/model needed. See reproduction:
https://go.dev/play/p/TzCt0-D-LRU

### versions
 - `go run github.com/99designs/gqlgen version`? Any version at 0.13.0 or above since it includes [this commit](https://github.com/99designs/gqlgen/commit/e821b97bfbb922589c9eea649f0415ec3454e446#diff-9523e7990be11a20f1b4573da0d562d3c3dbf58a6f22763e4c6387d6a9b4bd50)
 - `go version`? Any go version

**Comment by frederikhors** [comment]
Can you PR a fix?
