### ISSUE TITLE
gqlgen incorrectly extracts module name from go.mod

### ISSUE THREAD

**Issue by mobiletoly** [99designs/gqlgen#2298]
Costed me few hours today.

I was building a template (example) project for my team, so they could copy it, replace module name to what they need, fix few imports and run it.

While I was building it I was running `go run github.com/99designs/gqlgen generate --verbose --config ./graph/gqlgen.yml` to generate code from my schema and was getting this error:

```
reloading module info
reloading module info
merging type systems failed: unable to build input definition: unable to find type: name/internal/core/model.CalcInput
exit status 1
```

I was really puzzled where this "name" comes from in front of "internal/...". Ended up being that first few lines in my go.mod were

```
// TODO change module name
module some.repository.storage.com/some-repo/go-sample-service

go 1.18

require (
	github.com/99designs/gqlgen v0.17.13
...
```

so looks like gqlgen saw the word "module" and word "name" in comment and thought that "name" is actually a module name. I guess fix could be to ignore first lines if they are comments. Luckily go.mod syntax supports only `//` style comments, so no parsing of `/* ... */` is needed.

**Comment by frederikhors** [comment]
Can you PR please?

**Comment by mobiletoly** [comment]
Sure. Done:

https://github.com/99designs/gqlgen/pull/2299

**Comment by StevenACoffman** [comment]
Sorry for the inconvenience, but Thanks so much for the PR!

**Comment by mobiletoly** [comment]
thank you for such a great tool (gqlgen), really helps me a lot
