### ISSUE TITLE
Can't use OBJECT type as key in federation

### ISSUE THREAD

**Issue by tamas-zolcsak** [99designs/gqlgen#2319]
### Description
I have a type and its key is another object, but when I try to run generate it throws this error:
`failed to load schema: federation/entity.graphql:8: cannot use Test! as argument test because OBJECT is not a valid input type
`

### Example
```
type Test {
  sku: String
}

type TestKey @key(fields: "test") {
  test: Test!
}
```

The error above is thrown for this example when running: `go run github.com/99designs/gqlgen`

### versions
 - `go run github.com/99designs/gqlgen version v0.17.13`
 - `go version 1.18`

**Comment by frederikhors** [comment]
Read the error, that type must be input.

**Comment by tamas-zolcsak** [comment]
Thanks for the answer @frederikhors . But as you see in my example `Test` can't be an input because it's used as a field in `TestKey` type.

**Comment by frederikhors** [comment]
Sorry. I'll wait with you for authoritative answer.

**Comment by dariuszkuc** [comment]
Field set has to be a valid selection set. `test` field is an object so you have to select some fields on it.

Correct schema should be

```graphql
type Test {
  sku: String
}

type TestKey @key(fields: "test { sku } ") {
  test: Test!
}
```
