### ISSUE TITLE
`not implemented` could be a bit more descriptive

### ISSUE THREAD

**Issue by lintaba** [99designs/gqlgen#2327]
### What happened?
generated a lot of resolvers

### What did you expect?
finding the not implemented stubs to be easy, however its quite tricky.

I've made a PR that addresses the issue, let's see if its something useful, or if it breaks everyone's workflows :)

**Comment by lintaba** [comment]
(note: I'm not able to add the `proposal` label to the issue.)

**Comment by StevenACoffman** [comment]
Merged, so thanks!
