### ISSUE TITLE
BUG: Panic when trying to return a struct that implements the desired interface

### ISSUE THREAD

**Issue by droslean** [99designs/gqlgen#2360]
### What happened?

```go
func (r *queryResolver) QueryMyInterface(ctx context.Context, filter *model.MyInterfaceFilter, order *model.MyInterfaceOrder, first *int, offset *int) ([]model.MyInterface, error) {

  var ifaces []model.MyInterface
  
  ifaces = append(ifaces, Test{.....})
 // Test implements the `model.MyInterface`
......
.....
  
 return ifaces --> That panics with error `unexpected type Test` when we call the `QueryMyInterface` operation
```

### What did you expect?
I expect no errors.

### versions
 - `go run github.com/99designs/gqlgen version`?
 v0.17.16
 - `go version`?
go version go1.18.1 linux/amd64

/cc @vektah @neelance 

Am I doing something wrong here?

**Comment by jakezhu9** [comment]
Maybe you forgot to add `type Test implements MyInterface{ ... }` to your schema ?

**Comment by droslean** [comment]
@jakezhu9 I didn't forget it. My schema is correct. The problem is that the generated code doesn't understand that the struct is implementing the interface and it panics because it is checking the type only.

**Comment by droslean** [comment]
This is happening in the generated `executionContext` method for my MyInterface Interface.

Also, the `Test` struct is new that I use only to marshal the object. The generated code should check that too. Right now it only checks the types from my schema that implements that Interface. Nothing else. This is a bug 100%

**Comment by droslean** [comment]
@vektah Can you help? This seems to be a flow in the design of the tool.

**Comment by StevenACoffman** [comment]
Can you make a GitHub repository that will reproduce the problem?

**Comment by droslean** [comment]
@StevenACoffman I created https://github.com/droslean/99designs-gqlgen-2360

The problem is https://github.com/droslean/99designs-gqlgen-2360/blob/main/graph/generated/generated.go#L2786-L2814

Also, check my comment in https://github.com/droslean/99designs-gqlgen-2360/blob/main/graph/schema.resolvers.go#L21-L29

**Comment by droslean** [comment]
@StevenACoffman This issue still stands.
