### ISSUE TITLE
[BUG] Pagination on nested predicates is broken

### ISSUE THREAD

**Issue by droslean** [99designs/gqlgen#2395]
### What happened?

I created a repository to replicate the issue. Check https://github.com/droslean/99designs-gqlgen-filter

Query
```graphql
query {
  queryBug {
    name
    products (first: 1) {
      name
    }
  }
}
```

returns
```json
{
  "data": {
    "queryBug": [
      {
        "name": "Test BUG",
        "products": [
          {
            "name": "product-1"
          },
          {
            "name": "product-2"
          },
          {
            "name": "product-3"
          },
          {
            "name": "product-4"
          }
        ]
      }
    ]
  }
}
```

instead of
```json
{
  "data": {
    "queryBug": [
      {
        "name": "Test BUG",
        "products": [
          {
            "name": "product-1"
          }
        ]
      }
    ]
  }
}
```

### versions
 - `go run github.com/99designs/gqlgen version`?
 `v17.0.20`
 - `go version`?
 `go version go1.18.1 linux/amd64`

**Comment by droslean** [comment]
cc @StevenACoffman

**Comment by holy-func** [comment]
https://github.com/droslean/99designs-gqlgen-filter/blob/0f91678310879817fcf8f3707e285949b8d68416/graph/schema.resolvers.go#L16

**Comment by holy-func** [comment]
![image](https://user-images.githubusercontent.com/73243192/197435924-16516086-2779-4418-a095-e620a378f156.png)
may be you forget this?

**Comment by droslean** [comment]
@holy-func What do you mean?

**Comment by holy-func** [comment]
what the graph code query return depends on resolvers, above are why one expected but got four

**Comment by droslean** [comment]
@holy-func Can you be more descriptive because I don't understand what do you mean.

**Comment by droslean** [comment]
@chaitanyamaili  @chaitanyapantheor  Can someone take a look? This is a big blocker and it seems like a BUG.

**Comment by droslean** [comment]
@jclyons52 Can you please take a look? This is a big blocker.

**Comment by droslean** [comment]
@StevenACoffman cc

**Comment by jclyons52** [comment]
This doesn't seem like a bug. There is nothing in the generated code that will limit the number of return values simply because the query has a "first" argument. Your resolver needs to implement that logic.

**Comment by droslean** [comment]
@jclyons52 This is impossible to be done in the resolver since the resolver doesn't know where the pagination goes. The generator.

**Comment by droslean** [comment]
@mtibben @StevenACoffman @jclyons52 friendly reminder. This is a big blocker.

**Comment by giautm** [comment]
This isn't a bug. The resolve should handle the pagination. If you model already have that field, and you want to custom it to support pagination. try add `@goField(forceResolver: true)` on the field
```graphql
type Bug {
	id: ID!
	name: String!
	products(filter: ProductFilter, order: ProductOrder, first: Int, offset: Int): [Product!] @goField(forceResolver: true)

}
```

**Comment by droslean** [comment]
@giautm How the resolver will know the pagination args? The `first *int, offset *int` belongs to the `queryBug`. The problem in question is NOT there.

The problem here is that when the graphQL query tries to paginate a nested field.

**Comment by giautm** [comment]
```
query {
  queryBug {
    name
    products (first: 1) {
      name
    }
  }
}
```
You are passing the argument for products, not `queryBug`. What do you mean here?

**Comment by droslean** [comment]
Exactly. How the resolver will know the `first` argument for the products?

```
query {
  queryBug (first: 10) {
    name
    products (first: 1) {
      name
    }
  }
}
```

**Comment by giautm** [comment]
Are you reading my comment? I do an example for you here: https://github.com/droslean/99designs-gqlgen-filter/commit/b2bcf598a4742d78cbbb0d4fcd49d0860a4c9cbb#diff-e0a4909f568588675db7c5cfb3aa4175267381ba017bc73e85f980bd3ed715ffR17

**Comment by droslean** [comment]
@giautm Thanks for the example. Do you mean that I will have to put `@goField(forceResolver: true)` to ALL of my schema in order to enable pagination to nested fields?

Also, how the new resolver will resolve the nested pagination? I want to `queryBug` and order the `products`.

**Comment by droslean** [comment]
@giautm Is there any way to automate this or manually injection of the `forceResolver: true` in the schema is needed?

**Comment by giautm** [comment]
If you need to know the first arg of the product, from the `queryBug`'s resolver. That advanced technique requires more work and you have to implement it with `GetOperationContext`. We also use this technique in EntGQL to parse the query for preload data. You can see [it here](https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/gql_collection.go#L452-L562)

However, I recommend you should split the query into two parts if you don't have experience with GQLGen runtime. It means, writing a resolver for products, that starts to load product items with the given bug's ID.

**Comment by droslean** [comment]
@giautm Adding a new resolver for each object is out of the question because of the N+1 query issue. [This](https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/gql_collection.go#L452-L562) doesn't look like a solution or even a workaround since there is no way for me to know the pagination arguments for a specific object since the user can add pagination in any of the objects. I am also surprised that the generator doesn't handle the pagination itself since it is already handling the response based on the user's requested fields.

**Comment by giautm** [comment]
GQLGen is a GQL framework. It means it doesn't know which kind of data you will be returning for the query. From SQL, or File, or another kind of data source.

You need to deeply understand about GQLGen's runtime to get the plan from GQL. And its argument via each level. Unfortunately, I can't tell you exactly how.

**Comment by droslean** [comment]
@giautm But it already does. GQLGen already can understand which field it should include in the response. I just don't get why you are skipping the pagination and obviously there is no solution to that.

**Comment by FlymeDllVa** [comment]
@droslean hi!

It seems to me that what you describe is not a bug, you should control the data that your resolvers return yourself

gqlgen knows nothing about relay pagination, let alone that you have not fully implemented it. The task of gqlgen is to recognize the GQL schema and provide you with ready-to-implement `resolver` functions. By default, gqlgen tries to generate new types that have no binding in golang struct via `gomodel` or via `models` in `gqlgen.yml`. This way, all models that you declared in the GQL schema but did not bind to golang struct will be considered to be able to be loaded 1 time.
Suppose
```graphql
type User {
    id: String
    role: Role
}

type Role {
    id: String
    description: String
}
```
A resolver will be generated for the User, which will expect you to load the full User along with the Role. If Role is in another microservice and you need to load it additionally, you add resolver `@goField(forceResolver: true)` to the required field and then gqlgen will create additional resolver in which you can load additional data for this user (more effective to do for N+1, https://gqlgen.com/reference/dataloaders/). The new scheme will look like this
```graphql
type User {
    id: String
    role: Role @goField(forceResolver: true)
}

type Role {
    id: String
    description: String
}
```

A more beautiful option, perhaps in your case, is to use 'goModel` to bind SQL schema to golang struct. Change the GQL schema to this state
```graphql
type User @goModel(model: "github.com/project/users-service/models.User") {
    id: String
    role: Role
}

type Role @goModel(model: "github.com/project/roles-service/models.Role") {
    id: String
    description: String
}
```

If your structure looks like this, gqlgen will not generate a resolver for Role
```golang
type User struct {
	ID   string
	Role roles_service_models.Role
}
```
and if so, then gqlgen will not know about the role field in golang struct, although the scheme requires it and because of this it will generate a resolver
```golang
type User struct {
	ID   string
}
```

I hope that after this it will become clearer how you can use gqlgen 🦄

**Comment by droslean** [comment]
@FlymeDllVa Thanks a lot for the explanation but still that doesn't make any much difference. I have tried the `@goField(forceResolver: true)` way but this is even worst since that resolver will end up making `N^N` calls against the database, and if there is another object that needs to be expanded we are ending up with `N^N^N` calls. I figured out a workaround to expand the 2nd type from the first call and made my resolver extract the data from the JSON response (which is not stable).

Also, can you elaborate more on the `goModel` directive?
