### ISSUE TITLE
Option to disable comment generation

### ISSUE THREAD

**Issue by arnemolland** [99designs/gqlgen#2413]
### What happened?
When upgrading from gqlgen v0.17.15 to v0.17.20, `gqlgen generate` started generating comments. In our case, these are useless and add nothing but noise, so I would they can be disabled by config. AFAIK this change was introduced in #2263.

### What did you expect?
I would expect the option to disable comment generation.

### Minimal graphql.schema and models to reproduce
```graphql
type Foo {
 bar: Int!
}
```

### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.20
 - `go version` go1.19.2

**Comment by StevenACoffman** [comment]
A PR would be welcome!

**Comment by hexnaught** [comment]
@arnemolland cc @StevenACoffman 

I have opened a PR for this, hope this is acceptable!
