### ISSUE TITLE
Unwanted Resolvers are being Generated

### ISSUE THREAD

**Issue by Hrishikesh-Thakkar** [99designs/gqlgen#2414]
### What happened?
I am trying to generate resolvers for specific fields mentioning it like so below:
  ModelA:
    fields:
      fieldA:
        resolver: true
 However in schema.resolvers.go I am seeing resolvers for every field in the Model and I don't want that.
### What did you expect?
I expected a singular resolver for the given field FieldA instead I am seeing a whole list of them.
    
### versions
 - v0.17.20?
 - go version go1.19.1 darwin/arm64

**Comment by silicon-ninja** [comment]
Hey @Hrishikesh-Thakkar, all the revolvers gqlgen generates for you depends on the schema. you mind sharing and example of your .graphqls schema and then the gqlgen.yml ?

**Comment by Hrishikesh-Thakkar** [comment]
Hi @silicon-ninja this is resolved now, I had not declared the schema correctly. I feel it should be mentioned somewhere that resolvers are created two ways

1. When explicitly set in the gqlgen.yml
2. When the schema/models are defined in a way that it cannot be resolved internally.

Reason being I spent a lot of time working on the Yaml script because all roads let to that point. And turned out the culprit was the schemas and models.
Thanks for your help
