### ISSUE TITLE
Named return values in resolvers

### ISSUE THREAD

**Issue by lorenzo-sercanto** [99designs/gqlgen#2417]
### What happened?
Return values are not named by default and they also cannot be named manually, as stated in issue #1927.
```go
func (r *Resolver) FunctionName(ctx context.Context, input *model.something) (*model.somethingElse, error) {
```

### What did you expect?
Return values to be named possibly via the `gqlgen.yml` (by default they should be named like `output` and `err`).
It would allow the use of `defer` inside the resolver funcions allowing the use for a comprehensive external logging of the inputs, outputs and errors from the resolver function itself.
```go
func (r *Resolver) FunctionName(ctx context.Context, input *model.something) (output *model.somethingElse, err error) {
```

### Minimal graphql.schema and models to reproduce
Any

### versions
 - `gqlgen version` v0.17.16
 - `go version` 1.19

**Comment by dtrckd** [comment]
Please could you point me where the name of the value to return are defined (in the code) ?
Many thanks.
