### ISSUE TITLE
Error handling for malformed body

### ISSUE THREAD

**Issue by koniuszy** [99designs/gqlgen#2430]
### What happened?
I cannot intercept the error using [the hooks](https://gqlgen.com/reference/errors/). I always get:
```
{"errors":[{"message":"json body could not be decoded: json: cannot unmarshal array into Go value of type graphql.RawParams"}],"data":null}
```

### What did you expect?
Possibility to overwrite the error. I want to return `Internal server error` or `wrong body/query error` instead of revealing the genuine error.

### Minimal graphql.schema and models to reproduce
any will work,  your request needs to include invalid json, not matching graphql.RawParams, for example:
`--data-raw '[]'`

### versions
 - `go run github.com/99designs/gqlgen version`? **0.17.20**
 - `go version`?: **1.19**

**Comment by StevenACoffman** [comment]
Can you make a small repository that reproduces your problem?
```
package bar

import (
	"context"
	"errors"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
)

func main() {
	server := handler.NewDefaultServer(MakeExecutableSchema(resolvers))
	server.SetErrorPresenter(func(ctx context.Context, e error) *gqlerror.Error {
		err := graphql.DefaultErrorPresenter(ctx, e)

		var myErr *MyError
		if errors.As(e, &myErr) {
			err.Message = "Eeek!"
		}

		return err
	})
}
```

**Comment by koniuszy** [comment]
@StevenACoffman 
I literally followed your `Quick start` guide. Launched the server and hit the server with
```shell
$ curl --compressed -i 'http://localhost:8080/query' -X POST -H 'Content-Type: application/json' --data-raw '[]'
```

Repo is here:
https://github.com/koniuszy/basic-gqlgen-example

**Comment by StevenACoffman** [comment]
Thanks for your help!
