### ISSUE TITLE
How to disable `DO NOT EDIT` message in generated code?

### ISSUE THREAD

**Issue by hsblhsn** [99designs/gqlgen#2450]
### What happened?

I am getting the message added in every resolver file generated by gqlgen.

```go
// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.
```

This is causing my IDE (GoLand) to think that it's a genrated file and should not be edited. GitHub also disabled diff view for those files by default.

Is there any way to disable the addition of the message in my generated code?

### What did you expect?

I expect it to behave like as it previously did. Remove the `DO NOT EDIT` section from the message.

### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.21
 - `go version`? 1.19

**Comment by StevenACoffman** [comment]
Resolved in #2454
