### ISSUE TITLE
[Question] Custom Error struct

### ISSUE THREAD

**Issue by DarkRyuk12345** [99designs/gqlgen#2477]
Well, suppose i have a struct called `Error` which has the following properties: `msg string` and `id int` 

Now when returning a error, i want to be able to return the Error struct, So, i can convert the error id into a response at the frontend. Is this possible? Since returning a error struct can allow us to have extra properties that can be accessed by the frontend for more precise error handling. 

Thanks, that's all.

**Comment by atzedus** [comment]
Not sure, that i understand you exactly, but maybe you search for gqlerror.Error type that you can safely return from resolvers and fully customize it before. GraphQL has strict schema protocol for returns errors and gqlerror.Error follows it.

**Comment by DarkRyuk12345** [comment]
> Not sure, that i understand you exactly, but maybe you search for gqlerror.Error type that you can safely return from resolvers and fully customize it before. GraphQL has strict schema protocol for returns errors and gqlerror.Error follows it.

That is exactly what I was looking for, thank you!
