### ISSUE TITLE
@goTag do not override existing tag

### ISSUE THREAD

**Issue by valllabh** [99designs/gqlgen#2514]
`@goTag` do not override existing tag

Ideally it should override existing tag. sole purpose of the directive is to give control to user.
Looks

![image](https://user-images.githubusercontent.com/1380940/213923043-e0cc60f3-bc39-4351-8b53-dd846737d32d.png)

![image](https://user-images.githubusercontent.com/1380940/213922962-5d75019c-fcb2-411e-b09e-fe17df048531.png)

`GoTagFieldHook` just appends new tags

https://github.com/99designs/gqlgen/blob/866187fd2510121d1b5f0d0636c8d37d80191c91/plugin/modelgen/models.go#L415

**Comment by StevenACoffman** [comment]
Thanks for reporting this!
