### ISSUE TITLE
Invalid Federation 2 specs defined

### ISSUE THREAD

**Issue by benkraus** [99designs/gqlgen#2546]
### What happened?
I attempted to run gqlgen on a schema that had `@external` defined on an Object. For example:

```
type Foo @external { }
```

However, when running gqlgen I got an error: `Directive external is not applicable on OBJECT.`

### What did you expect?

The specs for v2 indicate that it is allowed on objects: https://www.apollographql.com/docs/federation/subgraph-spec/. `directive @external on FIELD_DEFINITION | OBJECT` A dig through the source of gqlgen resulted in this: https://github.com/99designs/gqlgen/blob/db1e3b81e71adcbad5143cf4b91fb402bb7ceba6/plugin/federation/federation.go#L93

Is this all that's needed to be updated?

### Minimal graphql.schema and models to reproduce
See above

### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.24
 - `go version`? 1.19.4

**Comment by dariuszkuc** [comment]
Hello 👋 
FYI `@external` was originally (Federation v1) only applicable on `FIELD_DEFINITION`.
Federation v2 relaxed directive definition to also allow applying it on `OBJECT` (which has the same effect as making all the object fields as `@external`).
