### ISSUE TITLE
Support for @live queries

### ISSUE THREAD

**Issue by svanharmelen** [99designs/gqlgen#2552]
Hi 👋🏻 We've just finished implementing a GraphQL server using `gqlgen` and I must admit it was pretty straight forward and the available docs helped us out perfectly. So big thanks for all the work that has gone into that and making things as easy and clear as possible!

So the server is ready to be used and we started hooking it up with the frontend and pretty quickly we got into some discussions about how to best keep the frontend updated when state (entities) in the backend have changed.

After a few chats and some reading we stumbled upon https://the-guild.dev/blog/subscriptions-and-live-queries-real-time-with-graphql (among a few other similar posts) and came to the conclusion that using live queries (using the `@live` directive) would probably be the most effective way to achieve our goal.

So I started looking for some guidelines or pointers/suggestion on how we could add this functionality to our `gqlgen` based server, but is seems not as straight forward as we hoped for 😅 I'm OK with diving into it and trying to add any missing pieces, but it would be great to have some upfront discussion about where/what to look at and how to go about this.

For starters, is it something that should be in the `gqlgen` package, or should it "just" be a custom directive? And if so, what (from a high level) should that directive look like, what should it do (again high level)?

I know I'm probably asking for a lot, but if anyone has time to give us some feedback and/or pointers around this one, that would be awesome and would be very much appreciated!

_EDIT: This also explained a lot, but it's mainly based on the [thunder](https://github.com/samsarahq/thunder) package which has a very different philosophy: https://www.youtube.com/watch?v=g-asVW9JFPw_

**Comment by kluzzebass** [comment]
Sounds like you're looking for GraphQL subscriptions: https://gqlgen.com/recipes/subscriptions/

**Comment by svanharmelen** [comment]
Anyone any pointers or ideas?

**Comment by svanharmelen** [comment]
I guess I'll have to figure this one out myself... 😏

**Comment by comerc** [comment]
@svanharmelen were you able to implement @live directive?
