### ISSUE TITLE
Add Example Tests

### ISSUE THREAD

**Issue by andrewmunro** [99designs/gqlgen#256]
Just noticed that the documentation for [error handling found here](https://gqlgen.com/reference/errors/) is out of date (`graphql.Error` has been replaced by `gqlerror.Error`).

This could be prevented by having [Example Tests](https://golang.org/pkg/testing/#hdr-Examples) that will fail should there be any breaking changes in the API.

**Comment by vektah** [comment]
Example tests are really hard to do with codegen. I've thought many times about taking the idea and applying it to a more generic doc site generator that can run codegen commands but it would be a lot of work, detracting from what needs to be done.
