### ISSUE TITLE
Adding an on-close callback for websockets.

### ISSUE THREAD

**Issue by szgupta** [99designs/gqlgen#2604]
### Proposed feature
I'd like the ability to register a callback so that I can add some teardown logic when a subscription (really, the underlying websocket) is closed. This would be very similar to the [`WebsocketInitFunc`](https://github.com/99designs/gqlgen/blob/a1a6f231d8756567e4346897733b123ceb905edf/graphql/handler/transport/websocket.go#L46) and [`WebsocketErrorFunc`](https://github.com/99designs/gqlgen/blob/a1a6f231d8756567e4346897733b123ceb905edf/graphql/handler/transport/websocket.go#L47). Currently, the only way to do this would be to set up a goroutine that blocks on `ctx.Done()` (or something along the lines).

I'm happy to send a PR for this if you agree with the use-case. It should be something along the lines of [this](https://github.com/szgupta/gqlgen/commit/80df2e64879a4c06f39327b461dd90999d4a8210) (missing tests).

**Comment by szgupta** [comment]
@StevenACoffman any reservations against something like this? Or should I just submit a PR?

**Comment by StevenACoffman** [comment]
That seems great to me, as long as it is only invoked `if c.CloseFunc != nil` (or make the default CloseFunc is a no-op) so it is optional and backwards compatible.

**Comment by szgupta** [comment]
@StevenACoffman just sent a PR!

**Comment by gdejong** [comment]
The `CloseFunc` gets called twice when a connection is stopped in the [Playground](https://github.com/99designs/gqlgen/blob/master/graphql/playground/playground.go). 
The first `closeCode` is `1006 (abnormal closure)` and the second `closeCode` is `1000 (normal)`.
Is that expected behaviour?

**Comment by StevenACoffman** [comment]
I don't think so, but if you can find a source for the abnormal closure and fix it, PRs are welcome.
