### ISSUE TITLE
subscription didn't work with authorization header

### ISSUE THREAD

**Issue by lynic** [99designs/gqlgen#261]
I wrap a authorization handler to authentication user, it works with query and mutation, but fails at subscription. I try with Playground included in this repo.
After I remove authorization wrapper,  all works fine. Seems subscription in playground didn't send header to server.

### Expected Behaviour
subscription works.

### Actual Behavior
subscription failed

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:8828/graphql. Please check if the endpoint url is correct."
}
```

**Comment by lynic** [comment]
Well I found that this might be related to browser, with chrome 68.0 it works fine, but failed on chrome 63.0 and also failed on safari.

**Comment by vektah** [comment]
Was this in the playground? They have [a few open issues](https://github.com/prismagraphql/graphql-playground/search?q=request.credentials&type=Issues) regarding authentication.

**Comment by lynic** [comment]
Yes, this was in the playground. This looks like playground didn't send the headers on subscription request. Sounds like a playground problem.
