### ISSUE TITLE
Subscription documentation is confusing

### ISSUE THREAD

**Issue by szgupta** [99designs/gqlgen#2618]
### What happened?
I was reading over the subscription example and in [the example resolver](https://gqlgen.com/recipes/subscriptions/#implementing-your-resolver), there's the following comment:

> // The channel may have gotten closed due to the client disconnecting.
> // To not have our Goroutine block or panic, we do the send in a select block.
> // This will jump to the default case if the channel is closed. 

From what I can tell, the subscription resolver returns the receiver-end of the channel, which implies that gqlgen cannot actually close the channel. 

Am I missing something? When would the send here actually fail (i.e. enter the `default` case)? Wouldn't sending over a closed channel actually cause a panic (if it were the case that the channel could be closed at this point)?

Was this a non-blocking send because the channel was unbounded? If so, I think the `default` case which describes the channel as "closed" is confusing.

Thanks!

**Comment by szgupta** [comment]
cc @Unkn0wnCat since I believe you added these docs!

**Comment by Unkn0wnCat** [comment]
Yes, I wrote that part of the docs. I don't quite know what caused the routine to block anymore, but i remember when i tested it when i wrote the docs and when not handling the send-failure my test program crashed a few times. This may not be the case anymore, but I have not tried. 

I'll try to find out more about it in the source code later, as I'm not at my computer currently

Hope this helps! 😊

**Comment by szgupta** [comment]
Sounds good, thanks @Unkn0wnCat!

IIUC, the send can potentially block (if there isn't a ready receiver) which is when the `default` case would kick in. But I'm a little skeptical that the default case here actually indicates the channel was closed (if it was, attempting to send on it in the previous case would have panic'd) and also unsure how gqlgen can actually close the channel in library code if the resolver returns a receiver of the channel 🤔

**Comment by Unkn0wnCat** [comment]
I've not had the time yet, and I don't think I'll have the time over the next few days to test removing the `default`-case, as I'm going away for an extended weekend. If you want to you can test how the code does without the `default` case. If you do please check if a) the program gracefully handles disconnected clients, and b) the count of goroutines stays the same (to check if sending loops/routines are exiting properly)

I have to honestly say, I don't know what exactly happens anymore. I'm sorry about that, it's been a little while

**Comment by mokiat** [comment]
Hi, I was looking at the Subscription documentation and noticed a number of issues myself. Here are my findings:

1. Trying to send on a closed channel will panic (check [example](https://play.golang.com/p/nI4WHHbDiQM))

    Thankfully, the library does not appear to close the channel on connection termination. As such, a panic does not occur.

2. There is a timing problem with the proposed approach.

    The way it works right now is that it depends on the fact that there is someone to read off of the channel fast enough. The demo works just because there is a `time.Sleep(time.Second)`. Remove that and the goroutine would quit and the subscription will fail. In a real scenario, if there are multiple writes fast enough from the server but the client is slow, the proposed implementation would fail.


Something that should be more in line with Go conventions and which appears to work (with some limited testing on my part) is the following code:

```go
// CurrentTime is the resolver for the currentTime field.
func (r *subscriptionResolver) CurrentTime(ctx context.Context) (<-chan *model.Time, error) {
	ch := make(chan *model.Time)
	go func() {
		defer close(ch) // Make sure the graphql library is aware that we will not be sending anymore data so that it can cleanup on its end if needed.
		for {
			time.Sleep(1 * time.Second)
			currentTime := time.Now()
			t := &model.Time{
				UnixTime:  int(currentTime.Unix()),
				TimeStamp: currentTime.Format(time.RFC3339),
			}
			select {
			case ch <- t:
				// Our message went through, continue looping
			case <-ctx.Done(): 
				return // Connection is closed or some other cancellation.
			}
		}
	}()
	return ch, nil
}
```

In essence, we are relying on the `context.Context` to be cancelled once the connection is closed.

**Comment by StevenACoffman** [comment]
I think the improvements with #2677 have largely fixed this, but I'm always open to further PRs with further improvement!
