### ISSUE TITLE
request: Raise unimplemented error notification at more earlier timing

### ISSUE THREAD

**Issue by vvakame** [99designs/gqlgen#269]
### Expected Behaviour

We get error on code generation phase from schema.

### Actual Behavior

We got error on server execution phase. 😿 

### Minimal graphql.schema and models to reproduce

```
{
  "error": "Could not find possible implementing types for Node in schema. Check that schema.types is defined and is an array of all possible types in the schema."
}
```

```schema.graphql
interface Node {
  id: ID!
}

interface Connection {
  pageInfo: PageInfo
  edges: [Edge]
}

interface Edge {
  cursor: String
  node: Node!
}

type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

type TodoConnection implements Connection {
  pageInfo: PageInfo!
  edges: [TodoEdge]
  nodes: [Todo]
}

type TodoEdge implements Edge {
  cursor: String
  node: Todo! # Wow! Todo is not implemented Node interface!
}

# 👀
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

**Comment by vektah** [comment]
I think that error is coming from your client, not gqlgen?

Is there something in the spec that says an interface must have at least one implementing type? (I can't see anything)

**Comment by vvakame** [comment]
I think this error is not come from client.
wow, sorry my description is wrong... I edit it now, sorry...

My example schema contains an error.
`Edge.node` requires implements `Node` interface, and 'TodoEdge.node` has `Todo` type, but it is not implements `Node` interface. It is invalid on the spec.
so, gqlgen raise error correctly.
My requrest is about the timing of the error.
Now, gqlgen report the error at running the query on the server.
but I hope to get an error at execute gqlgen command on my local machine.

**Comment by vektah** [comment]
#335 should make this a compile time error
