### ISSUE TITLE
Quick start instructions fail

### ISSUE THREAD

**Issue by AndrewWPhillips** [99designs/gqlgen#2717]
### What happened?

Ran quick start instructions at gqlgen.com.    The last step produced this:

```sh
$ go run server.go
# github.com/hashicorp/golang-lru/v2/simplelru
XXX\github.com\hashicorp\golang-lru\v2@v2.0.3\simplelru\list.go:8:12: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
... too many errors
```

Note that I am running Go1.19 and go.mod is:

```
module example

go 1.19

require (
        github.com/99designs/gqlgen v0.17.35
        github.com/vektah/gqlparser/v2 v2.5.7
)

require (
        github.com/agnivade/levenshtein v1.1.1 // indirect
        github.com/cpuguy83/go-md2man/v2 v2.0.2 // indirect
        github.com/russross/blackfriday/v2 v2.1.0 // indirect
        github.com/urfave/cli/v2 v2.25.5 // indirect
        github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673 // indirect
        golang.org/x/mod v0.10.0 // indirect
        golang.org/x/sys v0.8.0 // indirect
        golang.org/x/text v0.9.0 // indirect
        golang.org/x/tools v0.9.3 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
)
```
### What did you expect?

2023/07/19 12:19:13 connect to http://localhost:8080/ for GraphQL playground

### Minimal graphql.schema and models to reproduce

default

### versions
$ go run github.com/99designs/gqlgen version
v0.17.35

$ go version
go version go1.19 windows/amd64

**Comment by UnAfraid** [comment]
Run `go mod tidy` and then `go run server.go` should work.

**Comment by rhzs** [comment]
> Run `go mod tidy` and then `go run server.go` should work.

Hi, 

I try to help a bit here. I use Go 1.20. I managed to run it with `go mod vendor`. This will create `vendor` folder. 

I have published a better Todo example app from GQLGen starter that separates the `mutation` and `query` logic. 
You can see it here https://github.com/rhzs/gqlgen-todos/

I hope it helps!

**Comment by StevenACoffman** [comment]
Sorry about that! `go mod tidy` should also fix it. We've updated the documentation, so I'm closing this.
