### ISSUE TITLE
Response returns null on a non-nullable type

### ISSUE THREAD

**Issue by tkallioras** [99designs/gqlgen#275]
I am a bit baffled by the way the framework deals with non-nullable types.

For example I have a mutation like that:

```
mutation SignUp($email: String!, $password: String!) {
  signUp(email: $email, password: $password) {
    success
  }
}
```
with the respective GraphQL schema:

`  signUp(email: String!, password: String!): Result!`

If I run this mutation through a client, in such a way that I get back an error (eg in this case I pass an empty email, which returns an error to the client):

```
{
	"data": {
		"signUp": null
	},
	"errors": [
		{
			"message": "Database error: email cannot be empty, message: email cannot be empty
			"path": [
				"signUp"
			]
		}
	]
}
```

_The issue is that the signUp field is not nullable, however the server responds with null._ In the beginning I believed it was a client issue, however after opening an issue in the [apollo-ios github repo](https://github.com/apollographql/apollo-ios/issues/342) it seems that there must be something off with the way the library handles nullability.

The issue is, that because the server nulls a non-nullable result, the client cannot handle correctly the error. Instead of getting back the correct error, it detects a null response (which should not be null) and reports the null value as the error.

**Comment by vektah** [comment]
http://facebook.github.io/graphql/June2018/#sec-Errors-and-Non-Nullability 

Looks like nulls should bubble up, and in this case data should be null.

**Comment by mikeifomin** [comment]
Faced with the same issue after update from 0.3 to 0.4.1 . All my schema now lack of a non nullable =(

**Comment by vektah** [comment]
@mikeifomin that's a separate issue that should be fixed on master
