### ISSUE TITLE
Logger middleware to log the information of HTTP requests

### ISSUE THREAD

**Issue by x80486** [99designs/gqlgen#2750]
Similarly to what `Echo` implemented as a [logger middleware](https://echo.labstack.com/docs/middleware/logger), is it possible to have something similar for `gqlgen`?

As it stands today, if no log statements are added to the resolvers, there is really no way to tell what's going on within the application. Additionally, this shouldn't add much latency to the overall performance.

**Comment by it512** [comment]
srv.Use(...)
