### ISSUE TITLE
Kubernetes Probes: liveness, readiness, and startup

### ISSUE THREAD

**Issue by x80486** [99designs/gqlgen#2758]
Not sure what's the best way to implement this within `gqlgen`, but it would be great to have a way to include this behavior as a built-in feature, considering the possibility to provide the algorithm to overwrite some behavior, particularly with _readiness_ and _startup_.

**Comment by UnAfraid** [comment]
You can always attach health endpoint on router of choice, it doesn't have to be gqlgen concern.
