### ISSUE TITLE
Improve interface to collect query fields from resolver 

### ISSUE THREAD

**Issue by oskanberg** [99designs/gqlgen#280]
Here's an example schema:

```graphql
interface Thing {
    name: String!
    permissions: [String]
}

type BigThing implements Thing {
    name: String!
    permissions: [String]
}

type SmallThing implements Thing {
    name: String!
    permissions: [String]
}

type Query {
    getThings(...) [Thing]
}
```

And queries:

```graphql
getThings(...) {
    name
}

or

getThings(...) {
    name
    permissions
}

or

getThings(...) {
    name
    ... on BigThing {
        permissions
    }
}
```

In the query resolver for getThings(...), I want to be able to change behaviour based on whether `permissions` was requested. In order to understand whether or not a given query has included the `permission` property, I need to collect the fields from all fragments and check them:

```golang
fields := graphql.CollectFieldsCtx(ctx, ["BigThing", "SmallThing"])
for _, field := range fields {
   if field.Name == "permissions" {
       // it was included
   }
}
```

Where `fields` may well include `"permissions"` several times, if there are conditional fragments in the query. If I need separate logic for each inherited type, I would need to do make the `CollectFieldsCtx` call multiple times.

@vektah suggested that this interface could be improved, in order to more easily collect the requested fields, regardless of type.

I'm fairly new to this, so I'm not sure how such a simplified interface would look. I would tentatively suggest that something like this might be helpful:

```golang
// returns a map of [type]bool to indicate whether the given property was requested on that type
func gqlgen.ResolverQueryHasProperty(ctx context.Context, property string) map[string]bool
```

Alternatively a new resolver interface method could be introduced that also accepts a method to check if a given property was accepted.

```golang
type RequestChecker func(subtype string, property string) bool

func QueryWithCheck_getThings(ctx context.Context, params ..., check RequestChecker) ([]*Thing, error) {
    requested := check("BigThing", "permissions")
    if requested {
        // permissions was requested on BigThings
    }
}
```

**Comment by thechriswalker** [comment]
I use this sort of functionality a lot, mostly to check the fields requested in order to make minimal database queries. 

Although it seems complex, a couple of simple utility functions cover the required functionality (including arbitrarily nested fragments/inline fragments) and I feel muddying the resolver API would be counter-productive. 
Maybe the functions themselves could be added to the library as available utilities, rather than imposed in the resolver API.

```go
// get the fields requested in a graphql query
// Useful for constructing SQL queries from the GraphQL query
func getFieldsRequested(ctx context.Context) []string {
	reqCtx := graphql.GetRequestContext(ctx)
	fieldSelections := graphql.GetResolverContext(ctx).Field.Selections
	return recurseSelectionSets(reqCtx, []string{}, fieldSelections)
}

// this get the same as above, but for use within the field resolver. So in the field resolver
// if we didn't get a field we can grab what was requested above and load it.
// Useful for lazy resolving data
// NB this will panic if there is no parent.
func getParentFieldsRequested(ctx context.Context) []string {
	reqCtx := graphql.GetRequestContext(ctx)
	fieldSelections := graphql.GetResolverContext(ctx).Parent.Field.Selections
	return recurseSelectionSets(reqCtx, []string{}, fieldSelections)
}

// loop through selection sets flattening out the field names from fragments,
// ignoring private fields
func recurseSelectionSets(reqCtx *graphql.RequestContext, fields []string, selection ast.SelectionSet) []string {
	for _, sel := range selection {
		switch sel := sel.(type) {
		case *ast.Field:
			// ignore private field names
			if !strings.HasPrefix(sel.Name, "__") {
				fields = append(fields, sel.Name)
			}
		case *ast.InlineFragment:
			fields = recurseSelectionSets(reqCtx, fields, sel.SelectionSet)
		case *ast.FragmentSpread:
			fragment := reqCtx.Doc.Fragments.ForName(sel.Name)
			fields = recurseSelectionSets(reqCtx, fields, fragment.SelectionSet)
		}
	}
	return fields
}
```
`getFieldsRequested` gets the fields requesting at the level, e.g. `{ thing { fieldA, fieldB } }` would return `[]string{"fieldA", "fieldB"}` if called in the `thing` resolver.

`getParentFieldsRequested` gets the fields requested at the previous level, using the same example as before, we would get `[]string{"fieldA", "fieldB"}` when run from the resolver for `fieldA` or `fieldB`.

**Comment by mathewbyrne** [comment]
@thechriswalker thanks for the input. As I think you noticed, we're currently thinking about this in #533.  It's a common feature and there are a couple of use-cases for it. Glad to have another though 👍

**Comment by RichardLindhout** [comment]
@thechriswalker See https://github.com/99designs/gqlgen/issues/746 for all requested fields an more higher level code.
