### ISSUE TITLE
[RFC] Allow pass directive variable value from variables

### ISSUE THREAD

**Issue by imiskolee** [99designs/gqlgen#286]
Allow pass directive variable value from variables

Hi,All:

When i trying to define the blow struct like:

```graphql
directive @hasPermission(userID:Int)

query {
findMyResource(userID:Int) @hasPermission($userID)
}
```

Currently, its can't to be work. I think is nice choice from shared variable.

**Comment by vektah** [comment]
Unless I'm missing something this isn't in the spec?

**Comment by imiskolee** [comment]
aslo request its on : https://github.com/facebook/graphql/issues/497
