### ISSUE TITLE
[Proposal] Add defer for field resolvers 

### ISSUE THREAD

**Issue by h-khodadadeh** [99designs/gqlgen#2860]
### What happened?
Running field resolver on tests with mock using github.com/stretchr/testify results in dead-lock,   if the called function is not defined. 

### What did you expect?
My test should run smoothly, no dead-lock.

### Minimal graphql.schema and models to reproduce
Create a type like below and define 
type Timeout {
    Name: String!
}

define a resolver on the field. If you have a resolver, a goroutine will be created to run the resolver. If inside this goroutine `runtime.Goexit()` is called , then we'll have a dead-lock. 
### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.41
 - `go version`?  go version go1.21.0 linux/amd64

### Long Version
I have a web server which has many types. Many of these types have resolver on their fields. If you takes a look at the code, you will see that https://github.com/99designs/gqlgen/blob/24ea195cebea095035caf4d23af7f3d75fd0a041/graphql/fieldset.go#L37-L57 
a wait group is defined and it will run resolver functions in a separate goroutine. Once all the resolver functions are finished, wait group allows the code for move forward. 

But Sometime Inside the resolver,I call a service which during a test a mock will be used.  When the mock doesn't know what to return, it calls `FailNow` function on `*testing.T` which in turn calls `runtime.Goexit()` and it will kill the goroutine. This means that `wg.Done()` is not called and the application gets stuck at `wg.Wait()`.  To fix this issue, I need to change:
 https://github.com/99designs/gqlgen/blob/24ea195cebea095035caf4d23af7f3d75fd0a041/graphql/fieldset.go#L48-L51
to 
```
                       go func(d delayedResult) {
                               defer wg.Done()
				m.Values[d.i] = d.f(ctx)
			}(d)
```
to make sure even if  `runtime.Goexit()`  is called, the test will exit instead of running forever.

**Comment by UnAfraid** [comment]
Nice catch, i've open up a PR to fix it https://github.com/99designs/gqlgen/pull/2861
