### ISSUE TITLE
Fail to upload file

### ISSUE THREAD

**Issue by KingWu** [99designs/gqlgen#2934]
### What happened?
Upgrade from 0.13.0 to 0.17.44 and go from 1.16 to 1.22

### What did you expect?
Can upload file previously,
but right now throw the following issue

```
{
	"errors": [
		{
			"message": "failed to parse multipart form"
		}
	],
	"data": null
}
```

The request body show follow

```
 POST /portal?lang=en_US HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/8.6.1
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Authorization: Bearer xxxxxxxxxx
> Accept: */*
> Content-Length: 3021

| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="operations"
| {"query":"mutation ($file: Upload!) .........
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="map"
| {"0":["variables.file"]}
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="0"; filename="logo.svg"
| Content-Type: image/svg+xml
| <svg width="110" height="44" viewBox="0 0 110 44" ............
| --X-INSOMNIA-BOUNDARY--
```

### versions
 - `go run github.com/99designs/gqlgen version`? 0.17.44
 - `go version`? 1.22

**Comment by KingWu** [comment]
Try different go version with gqlgen version

`gqlgen v0.17.33` with `go v1.18`  => No work
`gqlgen v0.17.10` with `go v1.16`  => No work
`gqlgen v0.17.0` with `go v1.16`  => No work
`gqlgen v0.16.0` with `go v1.16`  => No work

**Comment by KingWu** [comment]
`gqlgen v0.16.0` with `go v1.16` => Work

gqlgen upgrade to v0.17.x will cause upload fail issue

**Comment by UnAfraid** [comment]
Have you tried apollo upload link?

**Comment by KingWu** [comment]
i did't use apollo as my client. For gqlgen, after `0.17.0`, it assume the client is using apollo client?

**Comment by KingWu** [comment]
Any update for the issue?

**Comment by KingWu** [comment]
Finally, found that the middleware handle multipart, which has error

```
// Ensure the form is parsed correctly
		if r.Method == http.MethodPost || r.Method == http.MethodPut {
			if r.Header.Get("Content-Type") == "multipart/form-data" {
				if err := r.ParseMultipartForm(32 << 20); err != nil && err != http.ErrNotMultipart {
					http.Error(w, "Failed to parse multipart form", http.StatusBadRequest)
					return
				}
			} else {
				r.ParseForm()
			}
		} else {
			r.ParseForm()
		}
```
