### ISSUE TITLE
interface conversion: interface {} is []interface {}, not map[string]interface {}

### ISSUE THREAD

**Issue by voslartomas** [99designs/gqlgen#2958]
### What happened?

After recent upgrade to newest gqlgen we encounter this error, it seems like it is newly generated for inputs like this

```
GearboxCreateLayoutInput:
    model: "map[string]interface{}"
```

```
interface conversion: interface{} is []interface{} not map[string]interface {}
```

It seems related to changes in [2839](https://github.com/99designs/gqlgen/pull/2839) or https://github.com/99designs/gqlgen/pull/2830

### versions
 - `go run github.com/99designs/gqlgen version`?
 - `go version`?

**Comment by Ned-el-ch** [comment]
to clarify,
```graphql
input GearboxCreateLayoutInput {
  abc: String
  tiles: [TileInput]!
}

input TileInput {
  x: Int
  y: Int
}
```

```yaml
GearboxCreateLayoutInput:
    model: "map[string]interface{}"
TileInput:
    model: "map[string]interface{}"
```

The `tiles` field ends up assumed as a `map[string]interface{}` instead of a `[]interface{}`
```go
func (ec *executionContext) unmarshalInputGearboxLayoutTileInput(ctx context.Context, obj interface{}) (map[string]interface{}, error) {
	it := make(map[string]interface{}, len(obj.(map[string]interface{})))
	asMap := map[string]interface{}{}
	for k, v := range obj.(map[string]interface{}) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"x", "y"}
...
```
so we panic on the first line `it :=`

**Comment by voslartomas** [comment]
@endSly Hello, sorry to tag you in, but you might know if this issue is not tight to work you have done maybe?

**Comment by voslartomas** [comment]
It was after all bug in our application.
