### ISSUE TITLE
Unable to Install and Execute gqlgen v0.17.47

### ISSUE THREAD

**Issue by sekky0905** [99designs/gqlgen#3083]
### What happened?

While attempting to install and run gqlgen version v0.17.47, the following issues are encountered. These issues do not occur with version v0.17.46.

### What did you expect?

I expected that gqlgen version v0.17.47 would install and execute without errors, similar to how version v0.17.46 functions.

#### Problem 1

When running `go install github.com/99designs/gqlgen@latest`, the following error is encountered:

```
go: github.com/99designs/gqlgen@latest (in github.com/99designs/gqlgen@v0.17.47):
    The go.mod file for the module providing named packages contains one or
    more replace directives. It must not contain directives that would cause
    it to be interpreted differently than if it were the main module.
```

#### Problem 2

When running `go install github.com/99designs/gqlgen@v0.17.47` , the following error is encountered:

```
go: github.com/99designs/gqlgen@v0.17.47 (in github.com/99designs/gqlgen@v0.17.47):
    The go.mod file for the module providing named packages contains one or
    more replace directives. It must not contain directives that would cause
    it to be interpreted differently than if it were the main module.
```

#### Problem 3

When running `go run github.com/99designs/gqlgen@latest` , the following error is encountered:

```
go: github.com/99designs/gqlgen@latest (in github.com/99designs/gqlgen@v0.17.47):
    The go.mod file for the module providing named packages contains one or
    more replace directives. It must not contain directives that would cause
    it to be interpreted differently than if it were the main module.
```

#### Problem 4

When running `go run github.com/99designs/gqlgen@v0.17.47` , the following error is encountered:

```
go: github.com/99designs/gqlgen@v0.17.47 (in github.com/99designs/gqlgen@v0.17.47):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

#### Note

**These issues do not occur with version v0.17.46, where the same commands execute without any errors.**

### versions
 - `go run github.com/99designs/gqlgen version` : v0.17.47
 - `go version`: 1.22.2

**Comment by jasondborneman** [comment]
Still seeing this when installing `@latest`:

```
$ go install github.com/99designs/gqlgen@latest
go: github.com/99designs/gqlgen@latest (in github.com/99designs/gqlgen@v0.17.47):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

cc: @StevenACoffman

**Comment by An-LeMi** [comment]
I still got problem even though installing `@lastest` or `@v0.17.47`
```
go: github.com/99designs/gqlgen@latest (in github.com/99designs/gqlgen@v0.17.47):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```
cc: @StevenACoffman

**Comment by StevenACoffman** [comment]
@An-LeMi can you try `@v0.17.48`

**Comment by StevenACoffman** [comment]
@jasondborneman the work was done, but it needed a new release cut to include it in `@latest`

**Comment by An-LeMi** [comment]
It's working. Thanks for your support
