### ISSUE TITLE
Error on code generation

### ISSUE THREAD

**Issue by ankitpatial** [99designs/gqlgen#3222]
### What happened?
Moved go v1.22.6 to v1.23.0 and tried code generations

### What did you expect?
expecting to generate code successfully
but got following:-
panic: interface conversion: types.Type is *types.Alias, not *types.Named

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField(0x1402d611640, 0x140111ab830, 0x1401139b900)
         go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/field.go:147 +0xdc0
github.com/99designs/gqlgen/codegen.(*builder).buildField(0x1402d611640, 0x140111ab830, 0x140003dea00)
         go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/field.go:70 +0x314
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0x1402d611640, 0x140003cdba0)
        go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/object.go:78 +0x4fc
github.com/99designs/gqlgen/codegen.BuildData(0x140000f7688, {0x1402ae94600, 0x2, 0x2})
       go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/data.go:116 +0x2cc
github.com/99designs/gqlgen/api.Generate(0x140000f7688, {0x0, 0x0, 0x102d8a120?})
        go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/api/generate.go:97 +0x7bc
main.init.func2(0x140000bcd80?)
         go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:190 +0xa8
github.com/urfave/cli/v2.(*Command).Run(0x102d96d60, 0x140000bcd80, {0x1400008f180, 0x1, 0x1})
         go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/command.go:276 +0x600
github.com/urfave/cli/v2.(*Command).Run(0x14000134580, 0x140000bcc40, {0x14000092020, 0x2, 0x2})
         go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/command.go:269 +0x83c
github.com/urfave/cli/v2.(*App).RunContext(0x140000f2400, {0x102a37340, 0x102dcb5a0}, {0x14000092020, 0x2, 0x2})
         go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x51c
github.com/urfave/cli/v2.(*App).Run(...)
         go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
        go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:227 +0x200
exit status 2

### versions
 - `go run github.com/99designs/gqlgen version`?  v0.17.49
 - `go version`? go1.23.0

**Comment by abekoh** [comment]
I have encountered a similar issue. In my case, the error is as follows:

```
panic: unexpected type *types.Alias

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/templates.TypeIdentifier({0x1031a1310?, 0x14000120180?})
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/templates/templates.go:720 +0x280
github.com/99designs/gqlgen/codegen/config.(*TypeReference).UniquenessKey(0x140009ec850)
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/config/binder.go:295 +0x90
github.com/99designs/gqlgen/codegen.processType(0x140010facc0, 0x140009ec850)
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/type.go:18 +0x2c
github.com/99designs/gqlgen/codegen.(*builder).buildTypes(...)
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/type.go:12
github.com/99designs/gqlgen/codegen.BuildData(0x1400016d688, {0x1400026a1c0, 0x2, 0x2})
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/data.go:156 +0x780
github.com/99designs/gqlgen/api.Generate(0x1400016d688, {0x0, 0x0, 0x102d495b8?})
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/api/generate.go:97 +0x7bc
main.init.func2(0x14000120dc0?)
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:190 +0xa8
github.com/urfave/cli/v2.(*Command).Run(0x10350ed20, 0x14000120dc0, {0x14000119dd0, 0x3, 0x3})
        /Users/kotaro_abe/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x600
github.com/urfave/cli/v2.(*Command).Run(0x1400017e580, 0x14000120c80, {0x14000120040, 0x4, 0x4})
        /Users/kotaro_abe/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:269 +0x83c
github.com/urfave/cli/v2.(*App).RunContext(0x14000168400, {0x1031a32c0, 0x103543540}, {0x14000120040, 0x4, 0x4})
        /Users/kotaro_abe/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/kotaro_abe/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main()
        /Users/kotaro_abe/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:227 +0x200
exit status 2
```

versions
- `go run github.com/99designs/gqlgen version`? v0.17.49
- `go version`? go1.23.0

**Comment by abekoh** [comment]
In Go 1.23, the default value for GODEBUG gotypesalias was set to 1, causing `types.Alias` to be used during AST parsing. However, it seems that `types.Alias` is not supported in gqlgen, leading to errors.

https://go.dev/doc/go1.23#gotypespkggotypes
https://go.dev/doc/godebug#go-122

As a temporary workaround, I was able to resolve the issue by setting `GODEBUG=gotypesalias=0`.

**Comment by kriscoleman** [comment]
I am also experiencing this after updating to go 1.23.0 

```
panic: interface conversion: types.Type is *types.Alias, not *types.Named

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField(0x140080698a0, 0x14002d95dd0, 0x140012dc5a0)
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/field.go:147 +0xdc0
github.com/99designs/gqlgen/codegen.(*builder).buildField(0x140080698a0, 0x14002d95dd0, 0x14000483000)
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/field.go:70 +0x314
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0x140080698a0, 0x1400047a340)
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/object.go:78 +0x4fc
github.com/99designs/gqlgen/codegen.BuildData(0x14000151448, {0x140043deea0, 0x3, 0x3})
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/codegen/data.go:116 +0x2cc
github.com/99designs/gqlgen/api.Generate(0x14000151448, {0x0, 0x0, 0x1035ae100?})
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/api/generate.go:97 +0x7bc
main.init.func2(0x14000118c40?)
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:190 +0xa8
github.com/urfave/cli/v2.(*Command).Run(0x1400017e580, 0x14000118c40, {0x1400001e060, 0x1, 0x1})
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x600
github.com/urfave/cli/v2.(*App).RunContext(0x1400014c400, {0x103257500, 0x1035ef560}, {0x1400001e060, 0x1, 0x1})
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main()
        /Users/kriscoleman-testifysec/go/pkg/mod/github.com/99designs/gqlgen@v0.17.49/main.go:227 +0x200
exit status 2
gen.go:4: running "go": exit status 1
make: *** [generate] Error 1
```

**Comment by UnAfraid** [comment]
I've updated all my gqlgen projects to 1.23.0 and can't reproduce this issue.

**Comment by stefan-berkner-tilotech** [comment]
As I couldn't find any release policy: when do you intend to release/tag this fix?

**Comment by marvinwhite** [comment]
I use this merged version and I see problems with the generated code. In schema I use the `Any` scalar type and inside `github.com/99designs/gqlgen/internal/code/compare.go`  I hit the default error case:

```go
// CompatibleTypes isnt a strict comparison, it allows for pointer differences
func CompatibleTypes(expected, actual types.Type) error {
	.
	.
	default:
		return fmt.Errorf("missing support for %T", expected) // <- Hitting this line
	}

	return fmt.Errorf("type mismatch %T != %T", expected, actual)
}
```  

Which lead to false `Any is not compatible with *any` error message.

I just added:
```go
	case *types.Alias:
		if actual, ok := actual.(*types.Alias); ok {
			if err := CompatibleTypes(expected.Rhs(), actual.Rhs()); err != nil {
				return err
			}
			return nil
		}
```

which seem to fix the problem. I use the go1.23 so my local patch works but creating a compatible PR requires more changes  that's why I commented instead of PR.

**Comment by skyzyx** [comment]
I've been struggling with this for the past few days since updating to Go 1.23. I'm using `entgql` with Ent.

I was able to run `go run -mod=mod github.com/99designs/gqlgen generate --config ../gqlgen.yml` successfully after updating my autobind settings to include a more complete list of Ent schemas. (I'd forgotten to add the last few schema files I'd created.)

**Comment by skyzyx** [comment]
Ultimately, I ended up rolling back this project to Go 1.22.6, which more consistently solved the issue.

```bash
go get go@1.22.6
go1.22.6 download
go1.22.6 generate ./...
```

I already wrap everything up in a Makefile, so I just updated the definition of `$(GO)` to `GO=$(shell which go1.22.6)`.

I haven't tried 1.22.7 or 1.23.1 yet.

**Comment by ankitpatial** [comment]
For me easy fix was to use Go flag
```
GODEBUG=gotypesalias=0 go generate
```

**Comment by giautm** [comment]
Please try the master version of gqlgen and report any issues you guys found, thanks.
