### ISSUE TITLE
Bug with multipart order

### ISSUE THREAD

**Issue by kostiamol** [99designs/gqlgen#3244]
Almost each 10th request
```
curl localhost:8087/graphql\
            -H 'Content-Disposition: operations' \
            -H 'Cache-Control: no-cache' \
                 -F 'operations={ "query": "mutation ($file: Upload!) { uploadMyFile(file: $file) }", "variables": {}}' \
                 -F 'map={ "0": ["variables.file"] }' \
                 -F "0"=@arch.zip \
                 -H "Authorization: Bearer token"
```
                 
returns: 

`{"errors":[{"message":"first part must be operations"}],"data":null}%`

while debugging I found that the second part in these error cases was in the place of the first one - in my request first part is 'operations', not 'map' but I get in buffer of MultipartReader:
```
--------------------------k0quCW1U0Wsc9yMBqpKhiT
Content-Disposition: form-data; name="map"

{ "0": ["variables.file"] }
--------------------------k0quCW1U0Wsc9yMBqpKhiT
Content-Disposition: form-data; name="operations"

{ "query": "mutation ($file: Upload!) { uploadLP(file: $file) }", "variables": {}}
--------------------------k0quCW1U0Wsc9yMBqpKhiT
Content-Disposition: form-data; name="0"; filename="lps.zip"
Content-Type: application/octet-stream
```
because of this, the condition is failed
https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_form_multipart.go#L79

### versions
 - github.com/99designs/gqlgen version = 0.17.49
 - go version = 1.23.0

**Comment by kostiamol** [comment]
The issue was with gofiber: using flag `DisablePreParseMultipartForm: true` fixed the problem

**Comment by tamimdocxster** [comment]
@kostiamol THANK YOU
