### ISSUE TITLE
Ability to return the object even if the resolver returned an error

### ISSUE THREAD

**Issue by netixx** [99designs/gqlgen#3249]
I have a use case, where a resolver can return an error, but the object itself is non-nil and should be return to the user to view.

The server actually tries to enrich a IP by resolving it, but the resolution can fail, still we want to display the raw information to the user.

The following line prevents this kind of behaviour: https://github.com/99designs/gqlgen/blob/4c4be0aeaaad758e703724fe4a6575768017ac53/codegen/field.gotpl#L40

Could it be removed ? Does it impact something else that I am missing ?

**Comment by fearfate** [comment]
`graphql.AddError(ctx, err)` maybe what your want, it will both add the error and return the original result that you `return`

```
package resolver

import (
	"context"
	"github.com/99designs/gqlgen/graphql"
)

type Output struct {
	// Some fields
}

func (r *Resolver) Example(ctx context.Context, id string) (*Output , error) {
	res, err := Get(ctx, id)
	if err != nil {
		graphql.AddError(ctx, err)
	}
	return res
}
```

**Comment by netixx** [comment]
Works like a charm, thanks (just register the error with AddError and return res, nil at the end).

Thanks!!
