### ISSUE TITLE
error: directive entityResolver is not implemented

### ISSUE THREAD

**Issue by hboylan** [99designs/gqlgen#3267]
### What happened?

Trying to use the `@entityResolver(multi: true)` directive. The multi entity resolver is generated properly, but any requests to it yield a directive error.

### What did you expect?

Should be able to resolve multi entity.

### Minimal graphql.schema and models to reproduce

https://github.com/hboylan/gqlgen-multi-entity-resolver

**operation:**
```graphql
query Test {
  todos {
    id
  }
}
```

**response:**
```json
{
  "errors": [
    {
      "message": "directive entityResolver is not implemented",
      "path": [
        "todos"
      ]
    }
  ],
  "data": null
}
```

### versions
 - `go run github.com/99designs/gqlgen version`?
```
v0.17.49
```

 - `go version`?
 ```
go version go1.21.6 darwin/arm64
```

**Comment by StevenACoffman** [comment]
Yeah, that error is misleading! If you upgrade to v0.17.54 you can get a more reasonable stacktrace.
Either way, you just need to implement your resolvers. If you edit `graph/schema.resolvers.go` and implement the Todos:

```
// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todo := &model.Todo{
		ID:   "Something",
		Text: "Do something",
		Done: false,
		User: &model.User{
			ID:   "one",
			Name: "Bob",
		},
	}
	return []*model.Todo{todo}, nil
}
```
Then your query actually works!

**Comment by StevenACoffman** [comment]
@dericcain @wshirey @chiijlaw You all gave thumbs up, so I assume you are either encountering the same problem or working together. Does this explanation help you all?
