### ISSUE TITLE
Dataloaders broken since v0.17.50 and merge of #3203

### ISSUE THREAD

**Issue by Metamogul** [99designs/gqlgen#3285]
### What happened?
Merging #3203 introduced a new behavior where marshaling list types now does not run concurrently anymore. However this breaks the use of dataloaders (https://github.com/99designs/gqlgen/pull/3203#issuecomment-2350417342).

### What did you expect?
I discovered this new behavior accidentally when one of our pipelines failed and I started to debug the failing test. The service in question heavily relies on dataloaders, loosing them or changing our entire schema don't seem to be adequate solutions. The need to add the new directive everywhere to preserve the established concurrent behavior also introduces a lot of potential for accidentally breaking new or existing loaders. Finally I think this affects a lot more devs and I'd not expect such breaking changes in a big project.

### Minimal graphql.schema and models to reproduce
See linked comment above.

### versions
 &gt;= v0.17.50

### Possible resolution
I suggest reimplementing the change in such a way that the new behavior is opt-in, e.g. using a new `@Sequential` directive, instead of making the old behavior opt-in. This way the change would be non-breaking for current users of dataloaders.

**Comment by werjo-gridfuse** [comment]
I 100% agree with @Metamogul. 

If you look at the GraphQL spec [https://spec.graphql.org/October2021/#sec-Normal-and-Serial-Execution](url) it tells that parallel execution is considered the "normal" behaviour" except for mutations. Mutations must be executed sequential, because there may be side effects. 

I think graphqlgen should implement the spec by default and not putting default or "normal" behaviour behind some dorective or configuration.

**Comment by krupyansky** [comment]
@Metamogul @werjo-gridfuse @StevenACoffman I made fix

https://github.com/99designs/gqlgen/pull/3286

Please give me review

**Comment by StevenACoffman** [comment]
@Metamogul @werjo-gridfuse @krupyansky I reverted the #3203 and cut a new release v0.17.52 

I'm sorry for the fact that I missed this disruption. Please let me know how I can improve the dataloader test harness so this sort of disruption does not happen in the future.

If someone would like to make a completely opt-in change (like adding a `@sequential` directive for new behavior) or prove the change could be fixed and provide a huge performance benefit, I would be willing to consider that.

I have had a hard time understanding you @krupyansky and that is my fault for not knowing more languages than just English. However, if you have access to someone who can help you translate it might make collaboration smoother between us.

**Comment by StevenACoffman** [comment]
@Metamogul honestly, that is a great test that you could contribute. Have the dataloader supply different data than if it's not involved.
