### ISSUE TITLE
Subscriptions via Server-Sent Events

### ISSUE THREAD

**Issue by ssttevee** [99designs/gqlgen#329]
I've been working on a PR that adds SSE support for subscriptions, but I noticed that #317 mentions that GET requests should be blocked for subscriptions as well as mutations.

So, I'm wondering, since SSE requests use the GET verb, is this something that was previously decided to be not supported or something that was overlooked when that message was posted?

**Comment by Sach97** [comment]
@ssttevee do you plan to listen to Postgresql notifications over websockets like in this [example](http://coussej.github.io/2015/09/15/Listening-to-generic-JSON-notifications-from-PostgreSQL-in-Go/)?

**Comment by vektah** [comment]
@ssttevee Interesting, Is there a spec for SSE yet?

The http spec is pretty clear on not doing mutations in GET requests https://github.com/APIs-guru/graphql-over-http

**Comment by ssttevee** [comment]
@Sach97 I'm actually using it with events from an MQTT server.

@vektah afaik, there is not, however, I feel like SSE is actually an overall better fit for subscriptions over http(s) since its uni-directional nature matches how graphql subscriptions work. Additional, when combined with http2's multiplexing ability, the whole subscription id situation can be offloaded to the transport level while still using a single connection.

**Comment by gedw99** [comment]
IE and edge don't support SSE, according to the web site you linked to.

Are you aware of this ?

**Comment by vektah** [comment]
I'm going to close this until a standard is built around this. 

You should be able to write your own transport using whatever you like, and ditch the handler package.

**Comment by frederikhors** [comment]
@ssttevee any news on this?

**Comment by ssttevee** [comment]
@frederikhors I'm keeping patched version on my own fork, but I don't think a pr will be accepted

**Comment by frederikhors** [comment]
> @frederikhors I'm keeping patched version on my own fork, but I don't think a pr will be accepted

Maybe a good PR with good config options will...

**Comment by vektah** [comment]
Sorry if I've given off the wrong impression here. gqlgen is first and foremost open source software, if there is something people want, and it cant easily be implemented outside of core we should either make it possible to do or implement it internally.

My only concern is if there isn't a stable spec there isn't any interoperability. This is one of those I just don't know enough to make an informed decision, is https://github.com/CodeCommission/subscriptions-transport-sse the defacto standard? 

Are you implementing your own client code or is this something supported widely?

**Comment by frederikhors** [comment]
> Sorry if I've given off the wrong impression here.

@vektah no wrong impression to me. You're great. Gqlgen is great! Keep it up!

**Comment by pascoual** [comment]
**Server-Sent Events**
Latest Published Version (2015):
    http://www.w3.org/TR/eventsource/
Latest Editor's Draft (2020):
    http://w3c.github.io/eventsource/

**Comment by pascoual** [comment]
A transport layer example:
https://github.com/CodeCommission/subscriptions-transport-sse

Can be great to get it on gqlgen !
