### ISSUE TITLE
Bug found when generating schema including arrays of type Any

### ISSUE THREAD

**Issue by melanie-ewing** [99designs/gqlgen#3301]
### What happened?

We have a schema that uses an array of type Any as one of the field's types. Starting with `v0.17.48`, when we `go run github.com/99designs/gqlgen generate`, we encounter a breaking error that essentially adds an extra pointer when unmarshaling: <img width="404" alt="Screenshot 2024-09-25 at 3 12 48 PM" src="https://github.com/user-attachments/assets/ffb1543d-2298-4b13-ab9f-2f8afa7e71eb">

### What did you expect?

Code generation to continue to work even when including a type of `[Any]` in the schema

### Minimal graphql.schema and models to reproduce

```graphqls
scalar Any

type Broken {
   fakeField: [Any]!
}
```

### versions
 - `gqlgen >=v0.17.48`
 - `go v1.23.1`

**Comment by noamcohen97** [comment]
I suspect it's `gotypesalias` [change](https://go.dev/doc/go1.23#:~:text=By%20default%2C%20go/types%20now%20produces%20Alias%20type%20nodes%20for%20type%20aliases.%20This%20behavior%20can%20be%20controlled%20by%20the%20GODEBUG%20gotypesalias%20flag.%20Its%20default%20has%20changed%20from%200%20in%20Go%201.22%20to%201%20in%20Go%201.23) in 1.23 causing `IsNilable` to return a different value

**Comment by melanie-ewing** [comment]
`GODEBUG=gotypesalias=0` did fix the generation 🙏 Thanks for opening that PR!
