### ISSUE TITLE
Massive undocumented breaking change in v0.17.50

### ISSUE THREAD

**Issue by Vilsol** [99designs/gqlgen#3321]
I have hit a major issue due to this undocumented breaking change (https://github.com/99designs/gqlgen/pull/3243), which was introduced in a patch version bump.

This is how the `resolver.go` looked like before on version `v0.17.49`: https://github.com/satisfactorymodding/smr-api/blob/179d26156ff1bfc48119ab24ee8a4740d2a2a18b/gql/resolver.go

This is how it looks like after running the generator on version `v0.17.50`: https://gist.github.com/Vilsol/1d7ac5dabd75933604449e1d6faa3323

* It has not generated any imports for anything except for what it itself is using.
* It has blindly copied the code from within the resolver functions, disregarded the function argument names, therefore completely breaking code that used those variables.

Is there some config options I can change to make this work with newer versions? Or is my only possible path to not upgrade?

**Comment by JonasDoe** [comment]
Gotta agree, I don't really understand what the intention behind this change was. My situation isn't as dramatic, I just added some fields to the `Resolver` which I probably have to pass by `ctx` right now. But what's the gain of this? It feels like it only introduces new incompatibilities which little benefit.

**Comment by UnAfraid** [comment]
Yeah i feel you, behaviour altering changes should be behind configuration option usually opt-in

**Comment by StevenACoffman** [comment]
This was bad situation is actually both my mistake and my miscommunication combined, and I'm quite sorry.

There was originally a config option `enable_rewrite_for_single_file` in that PR  to opt-in to rewriting resolvers or to preserve existing resolver code even when the schema changed to no longer match.

I suggested that instead the config option be `rewrite` apply equally to both `single-file` and `follow-schema`. My intent was to reduce the growing divergence in the code that places all resolvers in a single file and the code that places the resolvers in a directory layout that matches the schema.

The person who did that PR was an intern under the supervision of another maintainer, and the maintainer and I had side conversations so I assumed that it had been more carefully vetted and I merged it based on that assessment, rather that doing my own.

That was a big mistake. Again, I'm sorry.

I'd welcome a PR to add a config option to at least opt-out of this rewrite behavior.

**Comment by JonasDoe** [comment]
Thanks for the response! If I find time, I can try to create a PR. But it might take a while, so if somebody is more into the topic and faster, I'll gladly yield it. ;)

**Comment by StevenACoffman** [comment]
This appears to illustrate the PR change before the config option was removed:
https://github.com/99designs/gqlgen/compare/1855758d8642404df9bbd80386cd9030ae96efa4...d7ffe0c5cf463e300deaff787d54118d2c0f1b19

**Comment by StevenACoffman** [comment]
I put up a draft PR for #3359, however I stumbled on a few tests, and ran out of time to fix things.
It's ready enough to get feedback from you all though.

**Comment by StevenACoffman** [comment]
Please see https://github.com/99designs/gqlgen/releases/tag/v0.17.56 and hopefully people can add `preserve_rewrite: true` to your gqlgen config and go back to how things were.

**Comment by budak7273** [comment]
For future readers, the config option is called [`preserve_resolver`](https://github.com/99designs/gqlgen/pull/3359/files#diff-aa75f766122d97a53f4018a5aea8c26e855451e1ff07b41ace40c25fffb87c0fR22) and not `preserve_rewrite` as [Steven's comment](https://github.com/99designs/gqlgen/issues/3321#issuecomment-2465953864) and the [release notes](https://github.com/99designs/gqlgen/releases/tag/v0.17.56) suggest
