### ISSUE TITLE
Graphql union type is generated to interface{}

### ISSUE THREAD

**Issue by Pokerkoffer** [99designs/gqlgen#333]
### Expected Behaviour
Union Type should get generated to type and not to generic interface.

### Actual Behavior
`graphql.schema`:
```graphql
{
  type User {
    id: ID!
    name: String
  }

type Error {
  messages: [String]!
}

union type GetUserResult = User | Error
}
```

gets generated by `$ gqlgen` to:
```golang
  type UserError interface{} // <-- 

type User struct {
	ID string `json:"id"`
	Name string `json:"name"`
}

type Error struct {
	messages []*String `json:"messages"`
}
```

### Minimal graphql.schema and models to reproduce
See above

**Comment by vektah** [comment]
What do you expected output to be? Something like this?

```go
type GetUserResult struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Messages []*String `json:"messages"`
}
or 
type GetUserResult struct {
	User
	Error  
}
```

The problem is unions aren't real types as far as executing the graph is concerned, it needs to go back to a User or an Error for field selection. What would this clean up in your code?

**Comment by lwc** [comment]
@Pokerkoffer what are you suggesting here? I was thinking that we should actually have a proper interface for the gql union & interface cases, e.g:

```graphql
type User {
  id: ID!
  name: String
}

type Error {
  messages: [String]!
}

union type UserResult = User | Error
}
```
should generate something along the lines of:

```go
type UserResult interface{
	IsUserResult()
} 

type User struct {
	ID string `json:"id"`
	Name string `json:"name"`
}
func (u *User) IsUserResult() {}

type Error struct {
	messages []*String `json:"messages"`
}
func (e *Error) IsUserResult() {}
```

This way we'd actually have compile-time saftey on unions and interfaces like we do with everything else.

**Comment by Pokerkoffer** [comment]
Yes, thats what i am suggesting, but currently union types are generated to interface{} by gqlgen.
That would be a neat feature. 
Nevertheless thank you for this tool, it helps me out a lot and makes developing graphql APIs with go very easy and fast!
