### ISSUE TITLE
Improve CreateOperationContext() in Executor by using sync.Pool.

### ISSUE THREAD

**Issue by lkeix** [99designs/gqlgen#3362]
### What happened?

This proposal improve to create opCtx by using sync.Pool.

Currently, opCtx is created new OperationContext below.
https://github.com/99designs/gqlgen/blob/232ef588190c0193c217fa0f3e3712ea2a490122/graphql/executor/executor.go#L50-L59
Runtime allocate memory of OperationContext struct per Request.
By using sync.Pool, optimize creation process of opCtx per request.

#### Benchmarks

I took benchmarks in my local machine.
My local machine spec is below.
```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
memory: 32 GB 2667 MHz DDR4
```

It seems improved allocations, response a little.
benchmarks are below.

**Before Improvement**

```
BenchmarkErrorReponse-16    	    2962	    345344 ns/op	   26555 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3524	    322943 ns/op	   26964 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3292	    372174 ns/op	   26667 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    2810	    463152 ns/op	   26886 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    2245	    852256 ns/op	   27207 B/op	     217 allocs/op
BenchmarkErrorReponse-16    	    2734	    792807 ns/op	   26696 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3432	    390218 ns/op	   26897 B/op	     216 allocs/op
```

**After Improvement**

```
BenchmarkErrorReponse-16    	    3891	    284122 ns/op	   26445 B/op	     215 allocs/op
BenchmarkErrorReponse-16    	    4354	    307598 ns/op	   27020 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3381	    334530 ns/op	   26702 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3170	    381134 ns/op	   26597 B/op	     215 allocs/op
BenchmarkErrorReponse-16    	    3129	    366953 ns/op	   26399 B/op	     215 allocs/op
BenchmarkErrorReponse-16    	    2784	    405820 ns/op	   26654 B/op	     216 allocs/op
BenchmarkErrorReponse-16    	    3093	    434934 ns/op	   26742 B/op	     216 allocs/op
```

#### Assumption of Change

1. Add pool field in Executor.
2. Create opCtx from pool in `CreateOperationContext` and put created opCtx to pool.

### Minimal graphql.schema and models to reproduce

I take benchmark gqlgen init schema, and return empty slice for Todos query.

### versions
 - `go run github.com/99designs/gqlgen version`?
　 - v0.17.55
 - `go version`?
     - go version go1.23.2 darwin/amd64

**Comment by StevenACoffman** [comment]
Can you put up a PR for this?

I'd like to try some benchmarks in more complicated setups.
