### ISSUE TITLE
Support for external PubSub Engine

### ISSUE THREAD

**Issue by Sach97** [99designs/gqlgen#337]
Hi guys, great project ! I was wondering if it could be possible to add support for external PubSub Engine more suitable fro production than In Memory, like apollo did with their [package](https://github.com/apollographql/graphql-subscriptions#pubsub-implementations) I started working on one but I'm still new to golang and it will take me some time to have a good working code for a PR. I started with Postgres with [listen/notify and go routines](http://coussej.github.io/2015/09/15/Listening-to-generic-JSON-notifications-from-PostgreSQL-in-Go/)). I know some people started working on graph-gophers/graphql-go subscription with that idea in mind like @matiasanaya with his [PR](https://github.com/graph-gophers/graphql-go/pull/203) or @mikeifomin with his [repo](https://github.com/mikeifomin/graphql-subscriptions-go-example).

**Comment by vektah** [comment]
The api apollo exposes (resolver functions that return asyncIterators) is functionally equivalent to the one gqlgen uses (resolver functions that return channels). 

The pubsub engine isn't specified at all by gqlgen, its up to you to bring your own. Use whatever makes sense for your stack.
