### ISSUE TITLE
Questions about nested queries with params, SQL query optimisation and slow performance with Dataloader

### ISSUE THREAD

**Issue by Daavidaviid** [99designs/gqlgen#341]
### Problem
I'm about to start using this library for a project for my company, but I'm not sure about two things..

### Questions

1. How would one write resolvers to query users with the last 5 posts for each users ?
```
query getUsers {
  users {
    id
    name
    posts(numberOfPosts: 5) {
      id
      title
      text
    }
  }
}
```

2. How would one write resolvers to query SQL database with only the specific columns ? Like in the gql query from above. In this case :
```
query getUsers {
  users {
    id
    name
    posts(numberOfPosts: 5) {
      id
      title
      text
    }
  }
}
```

One would not need to SELECT *, but SELECT user.id, user.name but also post.id, post.name, post.text.
I think we can get field from context but how could know which field is a scalar and which is not ?

Thanks in advance for answering my questions.

**Comment by mathewbyrne** [comment]
This is going to depend a little bit on how you're mapping to your `User` and `Post` models, but in general if in your schema you add an argument to a field, you will get given a resolver to implement.

```
type User {
    posts(numberOfPosts: Int!): [Post!]!
}
```

The above schema will generate a resolver interface that looks something like:

```
func (r *userResolver) Posts(ctx context.Context, u *User, numberOfPosts int) ([]Post, error) {
    // TODO retrieve numberOfPosts Posts for User from DB
}
```

For your second question, it depends on how you're fetching from your database in the resolver.  To get access to the set of collected fields, you can call `graphql.CollectFieldsCtx()` and inspect the returned `[]CollectedField` for the columns you require.

**Comment by Daavidaviid** [comment]
### And also a third question
3. I tried the Dataloader example as it is. And I get around `20ms` for the request duration with this simple query : 

```
query getCustomers {
  customers {
    id
    name
    orders {
      id
      date
      amount
      items {
        name
      }
    }
  }
}
```

Is this not too much, knowing that there is not a lot of data ?

**Comment by mathewbyrne** [comment]
It's difficult to say whether this is a long time or not without more information on the size of your dataset, how you've implemented your resolvers etc.  I would suggest doing some profiling to get a sense of where you're spending your time, ensuring you have your dataloader well configured etc.  We do have an [open tracing middleware](https://github.com/99designs/gqlgen/blob/master/opentracing/opentracing.go) that might be of use.

**Comment by Daavidaviid** [comment]
> This is going to depend a little bit on how you're mapping to your `User` and `Post` models, but in general if in your schema you add an argument to a field, you will get given a resolver to implement.
> 
> ```
> type User {
>     posts(numberOfPosts: Int!): [Post!]!
> }
> ```
> The above schema will generate a resolver interface that looks something like:
> 
> ```
> func (r *userResolver) Posts(ctx context.Context, u *User, numberOfPosts int) ([]Post, error) {
>     // TODO retrieve numberOfPosts Posts for User from DB
> }
> ```
> For your second question, it depends on how you're fetching from your database in the resolver. To get access to the set of collected fields, you can call `graphql.CollectFieldsCtx()` and inspect the returned `[]CollectedField` for the columns you require.

Hi, I just realized it doesn't work like that. The Posts resolver doesn't get generated, are you it is implemented yet ?

**Comment by VijayKrish93** [comment]
@Daavidaviid Is right , I have something similar to query using input variables and I dont see a resolver being generated . Although I could see some type generated related to the input variables

**Comment by rikkei-minh** [comment]
@mathewbyrne , i have got similar thing but gqlgen does not generate anything about the Post resolver as your comments. Please confirm this.

**Comment by thlcodes** [comment]
FYI: not ideal, but you can extract the data from the context, e.g. ctx.val.Field.Selections[0].Arguments[0].Value.Raw

**Comment by AdallomRoy** [comment]
@mathewbyrne is it possible to re-open this ticket? The generated code doesn't look like what you have specified, which means that we'd need to get the parameters from the execution context instead of it being auto-generated. Unless I'm missing something here.

**Comment by by-nelson** [comment]
To get the resolver then the `gqlgen.yml` config file must specify that you want a resolver for that type and field. So with the OP example we have:
```graphql
query getUsers {
  users {
    id
    name
    posts(numberOfPosts: 5) {
      id
      title
      text
    }
  }
}
```

Which I guess in the `schema.graphql` translates to something like this:
```graphql
type User {
  id: ID!
  name: String!
  posts(numberOfPosts: Int!): [Post!]!
}
...
```

So to get the User resolver that receives the amount of posts to include we have to modify the config file with:
```yaml
models:
  ID:
  ...
  User:
    fields:
      posts:
        resolver: true
```

## Reference
https://gqlgen.com/getting-started/#dont-eagerly-fetch-the-user
