### ISSUE TITLE
gqlgen generation failing for custom directives

### ISSUE THREAD

**Issue by KishorePav** [99designs/gqlgen#3412]
### What happened?
gqlgen is failing. observations are:
1.DirectiveRoot struct is not picking up a ValidateEmail function is defined.
2.A variable called builtInDirectiveValidateEmail in generated.go is not able to resolve directives.ValidateEmailDirective
3.Normally gqlgen picks up the imports but the issue here is that imports aren't getting resolved.

### What did you expect?
Successful gqlgen generation.

### Minimal graphql.schema and models to reproduce
directive @validateEmail on INPUT_FIELD_DEFINITION | FIELD_DEFINITION
...
email:  String! @validateEmail
...

### versions
 - `go run github.com/99designs/gqlgen version`? - v0.17.56
 - `go version`? - 1.22.5

**Comment by graham-iheart** [comment]
Is there any reason you wouldn't just use a custom scalar here instead of a directive? I know that doesn't solve this issue, but I know that custom scalars work as I was just using them lol, so maybe a workaround?

**Comment by Brookke** [comment]
Hey @KishorePav are you still seeing this issue with the latest version of gqlgen? I couldn't replicate it myself

**Comment by KishorePav** [comment]
hey @Brookke  and @graham-iheart 

as a workaround, I removed the the description of the directive from the yaml of the gqlgen and it worked. don't know why it wouldn't work with the desc in it.
