### ISSUE TITLE
GraphiQL Lint scalar type `Any` with error

### ISSUE THREAD

**Issue by fearfate** [99designs/gqlgen#3415]
### What happened?

when using `Any` type, the linter in `variable` of GraphiQL will lint with error, but the api can be called normally 

### What did you expect?

lint `Any` field properly when inputing array or object json type

### Minimal graphql.schema and models to reproduce
```
scalar Any

type Query {
    example(value: Any): Any
}
```
### versions
 - `go run github.com/99designs/gqlgen version`  -  `v0.17.57`
 - `go version` -  `1.23.3`

**Comment by StevenACoffman** [comment]
What is the specific linter message you see? I would also appreciate a PR that fixes this if you are able to contribute one!

**Comment by fearfate** [comment]
I think if it's possible to extend the graphiql library? The GraphQL official would never accept the Any scalar.

![cf54016a089347b6944deca877992a69](https://github.com/user-attachments/assets/f8ba1fa4-d748-495e-a9ce-68b1e6b6797a)

![image](https://github.com/user-attachments/assets/d6037164-ac7a-43b2-bedb-cfc8eb0cd815)

![image](https://github.com/user-attachments/assets/5350a403-0dde-46dc-96d2-591f228dbbe8)

**Comment by StevenACoffman** [comment]
Ohhhh, I see now. Thanks for clarifying. You didn't include your GraphQL schema, but GraphQL doesn't natively support an `Any` scalar type, so GraphiQL is trying to warn you about that.

So in your GraphQL schema file you need something like this SDL:
```graphql
scalar Any
```

For instance, a number of people end up with a JSON type for arbitrary data:
```graphql
scalar JSON
scalar JSONObject

type MyType {
  myValue: JSON
  myObject: JSONObject
}
```

And in your gqlgen you might to map those to something like the Go `graphql.Any` model or something like it.

In your JavaScript client, you then need to use https://github.com/taion/graphql-type-json or something like it.

**Comment by StevenACoffman** [comment]
The comment above it mentions everyone should make their own customized function, rather than use that example one.

You should add the transports you want to use, with customized, tuned values based on your observed workloads. Do you want more or less cache? Do you want longer or shorter timeouts?

If you don't want or need websockets/SSE/MultipartForm/etc. transports, leave them out of your server. 

https://github.com/99designs/gqlgen/blob/3d0c92aca2af716903a726c777339e273e246020/graphql/handler/server.go#L49-L68
```
// Currently, the server just picks the first available transport,
// so this example NewDefaultServer orders them, but it is just
// for demonstration purposes.
// You will likely want to tune and better configure Websocket transport
// since adding a new one (To configure it) doesn't have effect.
//
// Also SSE support is not in here at all!
// SSE when used over HTTP/1.1 (but not HTTP/2 or HTTP/3),
// SSE suffers from a severe limitation to the maximum number
// of open connections of 6 per browser. See:
// https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#sect1
//
func NewDefaultServer(es graphql.ExecutableSchema) *Server {
	srv := New(es)

	srv.AddTransport(transport.Websocket{
		KeepAlivePingInterval: 10 * time.Second,
	})
	srv.AddTransport(transport.Options{})
	srv.AddTransport(transport.GET{})
	srv.AddTransport(transport.POST{})
	srv.AddTransport(transport.MultipartForm{})

	srv.SetQueryCache(lru.New[*ast.QueryDocument](1000))

	srv.Use(extension.Introspection{})
	srv.Use(extension.AutomaticPersistedQuery{
		Cache: lru.New[string](100),
	})

	return srv
}
```
