### ISSUE TITLE
optional `Any` input lead to internal system error

### ISSUE THREAD

**Issue by fearfate** [99designs/gqlgen#3426]
### What happened?

when defined a query with optional `Any` argument, if not input a not null value, the server will panic

### What did you expect?

not need to input `Any` argument when define it as optional

### Minimal graphql.schema and models to reproduce
```
scalar Any

type Query {
  executeLang(lang: Lang!, statements: String!, context: Any): Any
}
```

![image](https://github.com/user-attachments/assets/30e8154c-52f7-4ea7-b711-90fda5a51f71)

### versions
 - `go run github.com/99designs/gqlgen version`? - `v0.17.58`
 - `go version`?  -  `1.23.3`

**Comment by StevenACoffman** [comment]
I think naming your graphql variable`context` is a bit problematic, as most of the Go resolvers already have that as an argument for request cancellation. Can you rename it and see if the problem persists?
