### ISSUE TITLE
[help] How to read HTTP headers in subscription context?

### ISSUE THREAD

**Issue by JulienBreux** [99designs/gqlgen#343]
Hello!

It's me again with a big thanks before.

My use case:

1. I've an header with `Authorization` key and `Bearer xxx.xxx.xxx` value
2. But my question is how to read in `ctx context.Context` of subscription to access to the value of header?

**Comment by JulienBreux** [comment]
```go
func (sr *subscriptionResolver) Updated(ctx context.Context) (<-chan model.ObjectReturned, error) {
   // ctx? to read Authorization header value?
}
```

**Comment by JulienBreux** [comment]
<img width="681" alt="screen shot 2018-09-14 at 12 47 29" src="https://user-images.githubusercontent.com/964330/45546143-b8927080-b81c-11e8-9365-a50e7841ccac.png">

With Apollo, for example. `Authorisation` is transmitted in the `connection_init` by `Payload`.
But in https://github.com/99designs/gqlgen/blob/master/handler/websocket.go#L82, the payload never handled at init.

```go
func (c *wsConnection) init() bool {
//...
	case connectionInitMsg:
		c.write(&operationMessage{Type: connectionAckMsg})
//...
}
```

How to read `Payload` at the initialisation of the WS ?

**Comment by JulienBreux** [comment]
Up! Do you have an idea?

We can't use authenticated `subscriptions` with `gqlgen`?

**Comment by JulienBreux** [comment]
Maybe the idea is to write the init Payload in the wsConnection? In `initPayload json.RawMessage`

**Comment by DenisNeustroev** [comment]
Maybe pass your token in extensions field, it should work the same for http and ws

**Comment by JulienBreux** [comment]
@DenisNeustroev how to?

**Comment by vektah** [comment]
You can use http headers and some middleware that puts data into context, same as query.

Unfortunately websocket init payloads aren't currently supported (PRs welcome)

**Comment by JulienBreux** [comment]
Thanks Adam, but this solution/recipe doesn't work.

The context between HTTP and WS seem different.
I can't retrieve my HTTP context in a subscription context :/

**Comment by vektah** [comment]
Closing in favour of #355
