### ISSUE TITLE
Query cache problem with long running instances

### ISSUE THREAD

**Issue by ssttevee** [99designs/gqlgen#344]
I've recently run into a problem with the LRU cache. After a few hours of the first hit of a unique query, the same query will start returning empty results (i.e. `{"data":{}}`).

I've traced it down to the cache from #318. Whenever I start getting empty results, the `SelectionSet` value always turns out to be `nil`. When I evict that particular query from cache, the query starts working properly again. I'm not sure how or why this happens, but if I had to guess, I would say there is something weird going on with the GC.

I am using `go version go1.11 windows/amd64`

**Comment by vektah** [comment]
@edsrzf any thoughts?

**Comment by edsrzf** [comment]
Pretty strange. Any advice on reproducing the issue? I can spend some time looking into it.

**Comment by vektah** [comment]
Unable to reproduce

**Comment by ssttevee** [comment]
Just to give this some closure, after revisiting this problem, it turns out that I had a middleware layer that was directly modifying the `QueryDocument` to block unauthorized users' access to certain fields.

So from starting the server until the first unauthorized user tries to access the same query, it would work normally. Every query after that would return the modified `QueryDocument`.
