### ISSUE TITLE
problem with error handler

### ISSUE THREAD

**Issue by mkrou** [99designs/gqlgen#345]
example from docs
```go
server := handler.GraphQL(MakeExecutableSchema(resolvers),
	handler.ErrorPresenter(
		func(ctx context.Context, e error) *gqlerror.Error {
			// any special logic you want to do here. This only
			// requirement is that it can be json encoded
			if myError, ok := e.(MyError) ; ok {
				return &gqlerror.Errorf("Eeek!")
			}

			return graphql.DefaultErrorPresenter(ctx, e)
		}
	),
)
```
1) gqlerror.Errorf already return a pointer
2) if return just a gqlerror.Errorf you get an error "must not be null"

**Comment by vektah** [comment]
Linked PR fixes (1)

(2) is more complicated, the returned error doesnt have a valid path, which is needed for the null bubbling behaviour defined in [6.4.4 Errors and Non-Nullability](http://facebook.github.io/graphql/June2018/#sec-Errors-and-Non-Nullability)

Docs have been updated.
