### ISSUE TITLE
Clean up the interfaces for dealing with authentication

### ISSUE THREAD

**Issue by vektah** [99designs/gqlgen#355]
https://github.com/99designs/gqlgen/pull/348 added websocket init payloads, but this means any auth context needs to be inside RequestMiddleware (not generic http middleware).

Conversely, RequestMiddleware doesn't have access to http cookies, so standard session auth can't happen inside.

Bit split brain, would be nice to polish this up before 1.0

**Comment by JulienBreux** [comment]
Any news about this issue?
