### ISSUE TITLE
gqlgen fail to find a field in a pointer embedded struct

### ISSUE THREAD

**Issue by MichaelMure** [99designs/gqlgen#356]
Simple case to reproduce:

```go
type OpBase struct {
	Author Person `json:"author"`
}

type SetTitleOperation struct {
	*OpBase
	Title string `json:"title"`
	Was   string `json:"was"`
}
```

```graphql
type SetTitleOperation implements Operation & Authored {
  author: Person!

  title: String!
  was: String!
}
```

When `OpBase` is embedded as value, gqlgen find the `Author` field. When `OpBase` is embedded as a pointer, gqlgen fail to do that and ask me to implement a resolver, which would simply be:

```go
func (setTitleOperationResolver) Author(ctx context.Context, obj *operations.SetTitleOperation) (bug.Person, error) {
	return obj.Author, nil
}
```

## Expected behavior

gqlgen find the field and generate the proper resolver by itself.

**Comment by MichaelMure** [comment]
If you need more details, the full code is here: https://github.com/MichaelMure/git-bug/tree/master/graphql

**Comment by MichaelMure** [comment]
I have another breakage that is probably related:

```
panic: unexpected type operations.AddCommentOperation
goroutine 1029 [running]:
github.com/MichaelMure/git-bug/graphql/graph.(*executionContext)._Operation(0xc420144650, 0x99a660, 0xc4202e0030, 0xc420175340, 0x7, 0x7, 0xc420390f10, 0x0, 0xc4201d3f48)
	/home/travis/gopath/src/github.com/MichaelMure/git-bug/graphql/graph/gen_graph.go:5530 +0x43d
github.com/MichaelMure/git-bug/graphql/graph.(*executionContext)._OperationConnection_nodes.func2.1(0xc420144650, 0x99a660, 0xc4202e0030, 0xc420151980, 0xc420175340, 0x7, 0x7, 0xc420390e00, 0x12, 0x20, ...)
	/home/travis/gopath/src/github.com/MichaelMure/git-bug/graphql/graph/gen_graph.go:3322 +0x90
github.com/MichaelMure/git-bug/graphql/graph.(*executionContext)._OperationConnection_nodes.func2(0x11)
	/home/travis/gopath/src/github.com/MichaelMure/git-bug/graphql/graph/gen_graph.go:3323 +0xb2
created by github.com/MichaelMure/git-bug/graphql/graph.(*executionContext)._OperationConnection_nodes
	/home/travis/gopath/src/github.com/MichaelMure/git-bug/graphql/graph/gen_graph.go:3328 +0x4e4
```

I added a test in my project that expose the problem: https://github.com/MichaelMure/git-bug/blob/master/tests/graphql_test.go

Once again, if I revert to using a value embedding for `OpBase`, everything is fine (except for the reason I change to use a pointer embedding of course).

Here is the diff of the generated code if that help: https://gist.github.com/MichaelMure/aa23d093f80c91002543192ffe5b0beb

**Comment by MichaelMure** [comment]
Digging further on the second breakage, in the generated code, I have this function:

```go
func (ec *executionContext) _Operation(ctx context.Context, sel ast.SelectionSet, obj *bug.Operation) graphql.Marshaler {
	switch obj := (*obj).(type) {
	case nil:
		return graphql.Null
	case *bug.CreateOperation:
		return ec._CreateOperation(ctx, sel, obj)
	case *bug.SetTitleOperation:
		return ec._SetTitleOperation(ctx, sel, obj)
	case *bug.AddCommentOperation:
		return ec._AddCommentOperation(ctx, sel, obj)
	case *bug.SetStatusOperation:
		return ec._SetStatusOperation(ctx, sel, obj)
	case *bug.LabelChangeOperation:
		return ec._LabelChangeOperation(ctx, sel, obj)
	default:
		panic(fmt.Errorf("unexpected type %T", obj))
	}
}
```
If I manually change it to this, it works fine.

```go
func (ec *executionContext) _Operation(ctx context.Context, sel ast.SelectionSet, obj *bug.Operation) graphql.Marshaler {
	switch obj := (*obj).(type) {
	case nil:
		return graphql.Null
	case bug.CreateOperation:
		return ec._CreateOperation(ctx, sel, &obj)
	case bug.SetTitleOperation:
		return ec._SetTitleOperation(ctx, sel, &obj)
	case bug.AddCommentOperation:
		return ec._AddCommentOperation(ctx, sel, &obj)
	case bug.SetStatusOperation:
		return ec._SetStatusOperation(ctx, sel, &obj)
	case bug.LabelChangeOperation:
		return ec._LabelChangeOperation(ctx, sel, &obj)
	default:
		panic(fmt.Errorf("unexpected type %T", obj))
	}
}
```

(If you wonder why `operations.AddCommentOperation` is now `bug.AddCommentOperation`, I moved them, nothing to see here).

So it's still a problem in the generated code, I'm not sure it's related to the first problem though.

**Comment by MichaelMure** [comment]
@mathewbyrne thank you for looking into that :+1: 

For the second issue, after some refactor, I'm no longer facing this problem (the bug still exist in gqlgen though). You can reproduce it by going back in time:

in https://github.com/MichaelMure/git-bug/commit/8af6f7d98f2fd98f85d6a17bcda49983c272cf48, I manually fixed the generated code. If you checkout the parent commit (8ab2f173e7e5b008d9a5c72d124e99fe0cd578ab), you will have the problem. You can run the `tests/graphql_test.go` test and you will see the crash.

**Comment by vektah** [comment]
I've tested the latest git-bug against master and it seems both issues are fixed, you will need to add a few signpost methods though.

**Comment by MichaelMure** [comment]
@vektah could you explain what you mean by "signpost method" ?

**Comment by vektah** [comment]
Hmm, yeah maybe that terminology isn't so common. 

In gqlgen we want our interfaces to act like graphql interfaces, not go ones. We don't care if a field is a method or a property, as long as its name and type match. This means our interfaces end up being empty, and there is no way to see whats satisfying it:
```
type Author interface {}
```

As of #335  we now generate a method that acts as a signpost, not providing any behavior but still giving some compile time safety over this contract, and enabling nice editor features like what implements this.
```
type Author interface {
    IsAuthor() // just a signpost
}
func (Commit) IsAuthor() {}
```

Take a look at #335

**Comment by MichaelMure** [comment]
Hoo, I see, that's neat. Thank you for taking the time.
