### ISSUE TITLE
Please add option to disable this error: gqlgen must be run from inside your $GOPATH

### ISSUE THREAD

**Issue by guiguan** [99designs/gqlgen#367]
If using go 1.11 modules, the src directory has to be outside `$GOPATH` by default. Please add an option in `gqlgen` to skip this check, so `gqlgen generate` can run outside `$GOPATH` after `go mod vendor` as a temp workaround for 1.11 modules.

Thanks for creating this great library!

**Comment by vektah** [comment]
It's not that simple, gqlgen heavily depends on the loader package which isn't compatible with go modules yet.

See #226 for more details

**Comment by guiguan** [comment]
@vektah I found that if I make a `vendor` copy of all my dependencies and symlink my repo outside `$GOPATH` to a directory inside `$GOPATH`, I can still use `gqlgen generate` to update my server under that symlinked directory without problem. So I thought, if there were an option to skip that check, I don't have to create that symlink. Am I on the right path?
