### ISSUE TITLE
add a Prisma example

### ISSUE THREAD

**Issue by ghost** [99designs/gqlgen#371]
i recently discovered prisma working with gqlgen.

Prisma is like an ORM and so handles all the communication with your database. It can work with sql, nosql, kv or other.
So it works with gqlgen, and code gens all the database communication code.

Here is the example using gqlgen:
https://github.com/prisma/prisma-examples/tree/master/go-graphql

Databases:
mysql: done
cockroachdb: https://github.com/prisma/prisma/issues/1705

**Comment by gedw99** [comment]
Because gqlgen does so much of the work for you, it makes me wonder if anyone has thought of adding codegen for the database layer also. ?
