### ISSUE TITLE
example/todo/schema.graphql failed at command $ gqlgen init at referencing to *User

### ISSUE THREAD

**Issue by mattdinhnguyen** [99designs/gqlgen#374]
$ gqlgen init
schema.graphql:20: Expected Name, found <Invalid>

@mathewbyrne How to work around this issue? Thanks. Matthew

**Comment by mathewbyrne** [comment]
I'm not sure exactly what you're attempting to do here.  If you've made a change to the schema in the todo example and want to regenerate, just run `gqlgen` without a subcommand.  The `init` subcommand is intended for bootstrapping where you have only a schema file and want to get started with a generated server.

Also I'm not sure about your error message, I would suggest make sure you're on the latest version of gqlgen.

**Comment by vektah** [comment]
Also https://gitter.im/gqlgen/Lobby is the best spot to find help.
