### ISSUE TITLE
Generation of deep param does not work 

### ISSUE THREAD

**Issue by fasibio** [99designs/gqlgen#378]
If i try to make deep Queries with param
Schema: 
```

type Query {}

type House {
  owner(id: String!): Boolean
}
type Mutation {
  house(id: String!): House
}



```

this generate: 
```
package data

type House struct {
	Owner *bool `json:"owner"`
}

```

there are missing ther ownerid func etc...

**Comment by mathewbyrne** [comment]
Generated models do not have any methods on them.  If you want these types of methods you should implement the model yourself and map it to your schema through [config](https://gqlgen.com/config/).
