### ISSUE TITLE
Resolver for creating multiple nested relation

### ISSUE THREAD

**Issue by podinacristi** [99designs/gqlgen#379]
I have two types: Model and FieldModel. Model has many FieldModel. I want to create a single Model and assign multiple fields in it.

My types, models and my resolver:
```
type Mutation {
     createModelWithFields(data:ModelCreateInput!): Model!
}

type Model{
    id: ID!
    name: String!
    fields: [FieldModel!]!
    status:Boolean
    createdAt: DateTime!
    updatedAt: DateTime!
}

type FieldModel{
    id: ID!
    name: String!
    fieldType: String!
    model: Model!
    createdAt: DateTime!
    updatedAt: DateTime!
}
input FieldModelCreateManyWithoutModelInput {
    create: [FieldModelCreateWithoutModelInput!]
    connect: [FieldModelWhereUniqueInput!]
}
```
and my resolver:

```
func (r *mutationResolver) CreateModelWithFields(ctx context.Context, data ModelCreateInput) (prisma.Model, error) {
	model,err:=r.Prisma.CreateModel(&prisma.ModelCreateInput{
		Name:&data.Name,
		Fields:&prisma.FieldModelCreateManyWithoutModelInput{
			Create:data.Fields
		},
	}).Exec()

	return model, err
}

```

The actual query is something like this and it works:
```
mutation {
  createModelWithFields(
    data: {
      name: "User"
      fields: {
        create: [
          { name: "name", fieldType: "String" }
          { name: "createdAt", fieldType: "DateTime!" }
        ]
      }
    }
  ) {
    id
    name
    fields {
      id
      name
      fieldType
    }
  }
}

```

How can i adapt  my resolver to do that, because  `Create` is `FieldModelCreateWithoutModelInput` and `data.Fields` is `FieldModelCreateManyWithoutModelInput` ?

**Comment by mathewbyrne** [comment]
Sorry but I'm not sure what you're asking here.  It looks like you've setup a mutation which is working for you, but you want to add a query resolver to get the same result?  Feel free to clarify.

**Comment by Sach97** [comment]
For the record, I posted a solution to @podinacristi issue [here](https://www.prisma.io/forum/t/prisma-golang-client-cannot-use-authors-type-string-as-type-string-in-field-value/4574)

**Comment by mathewbyrne** [comment]
Ah great, thanks @Sach97 👍
