### ISSUE TITLE
Support Schema Importing

### ISSUE THREAD

**Issue by Daavidaviid** [99designs/gqlgen#383]
### Expected Behaviour
In the `schema.graphql` file:
```
import mutations.graphql
import queries.graphql

...
```
### Actual Behavior
No possibility to import schema currently.

**Comment by mathewbyrne** [comment]
The [current GraphQL spec](https://facebook.github.io/graphql/June2018/) does not specify an importing feature yet.  We are interested, especially as [Prisma](https://github.com/prisma/graphql-import) and others are coming up with their own solutions for this.

As a workaround, some people have just been concatenating their schema files together before running gqlgen.

**Comment by vektah** [comment]
It might be enough to do some shell globbing in the short term:
```
schema: "*.graphql"
```

the parser supports multiple inputs concatenated and preserves path info.

**Comment by JulienBreux** [comment]
Good idea, but recursively?

`muts.graphql`
```
import sub-mut.graphql
```

**Comment by sandeepone** [comment]
Go generate bindata is helpful for that. We use separate file for each type and build all into single schema.

```
// Use `go generate` to pack all *.graphql files under this directory (and sub-directories) into
// a binary format.
//
//go:generate go-bindata -ignore=\.go -pkg=schema -o=bindata.go ./...
```

Code taken from here:
https://github.com/tonyghita/graphql-go-example/blob/master/schema/schema.go

**Comment by Daavidaviid** [comment]
Thanks that's perfect !
