### ISSUE TITLE
Why are subscription chans receive only?

### ISSUE THREAD

**Issue by 21stio** [99designs/gqlgen#391]
Hey, 

first of all, really nice implementation!

Now my issue:

I want to stream data from a streaming backend. I intuitively thought I'll just hand it over from one chan to another. Unfortunately, that doesn't work as I can't send data to it from within the function.

`invalid operation: rspCh <- rsp (send to receive-only type <-chan *schema.GetFilesResponse)`

Code

```golang
func (r *subscriptionResolver) WatchFiles(ctx context.Context, req *schema.GetFilesRequest) (rspCh <-chan *schema.GetFilesResponse, err error) {
    rspCh = make(chan *schema.GetFilesResponse)

    req0 := bridge.BridgeToGetFilesRequest(req)

    rsp0Ch, err := facade.WatchFiles(ctx, *req0)
    if err != nil {
        return
    }

    go func() {
        for {
            select {
            case rsp0, more := <- rsp0Ch:
                if !more {
                    return
                }

                rsp := bridge.BridgeFromGetFilesResponse(&rsp0)

                rspCh <- rsp
            case <-ctx.Done():
                return
            }
        }
    }()

    return
}
```

What's the reason for it being receive-only?  I mean, for pubsub it makes sense, but it's limited to that by the current signature.

**Comment by vektah** [comment]
I'm not sure I follow, you can always create and return a bidirectional channel in your resolver, the signature is just saying that we only gqlgen will only ever read from it. 

eg https://play.golang.org/p/DR7YwLfDEiE

**Comment by JulienBreux** [comment]
@21stio please close issue ;)

**Comment by JulienBreux** [comment]
@vektah sorry, I've GH cache Oo

**Comment by 21stio** [comment]
@vektah oh sorry, my bad... thanks for the lesson ;)
