### ISSUE TITLE
gqlgen command not found

### ISSUE THREAD

**Issue by krishna-prakash** [99designs/gqlgen#393]
Tried running gqlgen init after adding the packages as per docs
Expected to auto generate all the dependecy files for setting up graphql server
But i am unable to execute gqlgen command, gives me the following error 
" gqlgen command not found "

os: macos

**Comment by podinacristi** [comment]
if you use dep you should add gqlgen to your PATH

**Comment by weekaung** [comment]
Same problem here, generator not working. Krishna, have you been able to get it working by now?

**Comment by krishna-prakash** [comment]
@weekaung still facing the issue, unable to proceed after that. I kindly request authors to add a documentation which should help get started with gqlgen commands

**Comment by marhaupe** [comment]
@krishna-prakash @weekaung Is your $GOBIN (default ~/go/bin) in your $PATH?

**Comment by mathewbyrne** [comment]
Yes, there is an issue here between installing `gqlgen` globally, and having it in your `vendor` path.  There are a few issues that creep in, most notably version differences, and path issues.  We're going to look at improving the getting started documentation in a release soon.

**Comment by Nozgood** [comment]
> Yes, there is an issue here between installing `gqlgen` globally, and having it in your `vendor` path. There are a few issues that creep in, most notably version differences, and path issues. We're going to look at improving the getting started documentation in a release soon.

We are still waiting :(
