### ISSUE TITLE
cannot unmarshal !!seq into string when using multiple schema files

### ISSUE THREAD

**Issue by qhenkart** [99designs/gqlgen#394]
Following the example in https://github.com/99designs/gqlgen/blob/master/docs/content/config.md
for multiple schemas

### Expected Behaviour
should properly generate with multiple schema files

### Actual Behavior

```
unable to parse config: yaml: unmarshal errors:
  line 2: cannot unmarshal !!seq into string
```

### Minimal graphql.schema and models to reproduce
no contents necessary, the generator doesn't make it to the schema
min glqgen.yml file:
```
schema: 
 - schema/schema.graphql
 - schema/schema2.graphql
```

**Comment by vektah** [comment]
Sorry, that feature hasn't landed on a tagged release yet, you will need to point to master

**Comment by dehypnosis** [comment]
workaround..
```
gqlgen generate -v && sed -i '/ec.Tracer/d' ./schema/generated.go
```

**Comment by guiguan** [comment]
This error still exists in the latest master. Probably because I am using go modules and the vendor + symlink hack for `gqlgen`
