### ISSUE TITLE
Could not even run the generator

### ISSUE THREAD

**Issue by weekaung** [99designs/gqlgen#397]
### Expected Behaviour
Generate the code as documented
### Actual Behavior
Throws this exception ... gqlgen must be run from inside your $GOPATH
### Minimal graphql.schema and models to reproduce
Documentation could have been more specific as to how to go about doing it.

**Comment by mathewbyrne** [comment]
Yep, a few people have run into this now.  We are planning to update the getting started documentation soon, and make this clearer.  Thanks.

**Comment by aripalo** [comment]
This comment doesn't really help, sorry about that 😅 …but have to shout-out that I've been looking for this kind of "schema first" Golang package, just saw the Christopher Biscardi Gophercon UK 2018 talk and got really excited to try it! 

Unfortunately can't get passed the `gqlgen init` phase as seen on [getting started](https://gqlgen.com/getting-started/). Tried with Golang `1.8`/`1.9`/`1.10`.

Would appreciate if anyone has any ideas where to look or what to try for even a temporary fix while the documentation is being worked on!

**Comment by vektah** [comment]
Jump on gitter, it's the best spot to debug these kinds of issues
