### ISSUE TITLE
A strange resolver for the nested mutation

### ISSUE THREAD

**Issue by davidmz** [99designs/gqlgen#398]
I have the following schema (part of):
```
type Mutation {
  super: SuperAPI
}

type SuperAPI {
  createUser(input: CreateUserInput!): CreateUserPayload!
}
```
The generated types are:
```
type MutationResolver interface {
        // It is ok and expected
	Super(ctx context.Context) (*SuperAPI, error)
}
```
and (this is unexpected):
```
type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
	SuperAPI() SuperAPIResolver
}
```
When I call `mutation {  super {  createUser …`, both methods are executed in this order: MutationResolver.Super, ResolverRoot.SuperAPI.

Why gqlgen generated an additional method in the root resolver and why there are both executed?

**Comment by mathewbyrne** [comment]
This all seems correct to me.

Mutations are supposed to occur at the root of the `Mutation` type, so calling `mutation { super }` would call the mutation, and `SuperAPI` is the type returned.  Some users have tried namespacing Mutations but doing what you've done above, but that still requires using a type (in your case `SuperAPI`) and then just performing the mutation in the resolver.

Lastly, mutations are [supposed to be executed serially](https://facebook.github.io/graphql/June2018/#sec-Mutation), but responses will be resolved in parallel, so I would be careful trying to namespace like this.

**Comment by davidmz** [comment]
@mathewbyrne , thank you for the explanation!
