### ISSUE TITLE
Improve Getting Started Documentation

### ISSUE THREAD

**Issue by mathewbyrne** [99designs/gqlgen#408]
There are a lot of users getting stuck during the [getting started documentation](https://gqlgen.com/getting-started/) or shortly thereafter.  Some of the issues include:

1. User installs both gqlgen globally (and probably gets `master`), then installs gqlgen from dep.  So generated code is no sometimes not compatible depending on the state of master.

2. Users trying to execute `gqlgen` outside of their `GOPATH`.  We should at least make this clear that it's not currently possible and why.

3. User cannot find `gqlgen` binary — some people are struggling binding the binary, either they don't have it in their `PATH`, or have another configuration error.

We should address these issues and ensure that the described path does not easily run into any of them.

**Comment by hiucimon** [comment]
Can someone PLEASE tell me how to be "in the GO PATH"? I have tired everything I can think of and get the same message, and have searched until I am blue in the face and can not see a clear answer anywhere. I have tried setting GOPATH to various places, and tried CD'ing to where it seems to be and it never changes the results. gqlgen gets installing into ~/go/bin/ on the Ubuntu instance I have tried it on (also tried the same things on Mac).

**Comment by hiucimon** [comment]
OK, I figured it out. For anyone who needs to know, you have to be in the source directory of this code when you execute it.

**Comment by lowe1111** [comment]
@hiucimon what do u mean with this code? I cant get it running
