### ISSUE TITLE
If a type is named Subscription the codegen generates broken fields

### ISSUE THREAD

**Issue by slaskis** [99designs/gqlgen#414]
I'm looking into moving from apollo server in node to gqlgen in go and we have a legacy model named `Subscription`. Unfortunately the codegen in gqlgen seems to be confused by the name.

Tried in 0.6.0 and the current master (4bda3bc1291bdc0bc44e3057b5229d987eeecde2)

### Expected Behaviour

I expect it to generate the same as if its not named Subscription as long as it's not the one defined in the `schema{}`-scope.

### Actual Behavior

It seems to simply skip the word `Subscription` which results in broken go code and gives errors such as:

`expected type, found ',' (and 1 more errors)` because the return here is empty:

```go
type OtherResolver interface {
	Sub(ctx context.Context, obj *Other) (*, error)
}
```

and similar (```expected type, found `json:"sub"` ```) for the field in the generated model:

```go
type Other struct {
	Sub * `json:"sub"`
}
```

### Minimal graphql.schema and models to reproduce

```gql
type Subscription {
  id: ID!
}
type Other {
  sub: Subscription
}
type Query {
  other: Other
}
schema {
  query: Query
}
```

default models

**Comment by slaskis** [comment]
I think I've narrowed this down to a few lines in the parser:

https://github.com/vektah/gqlparser/blob/master/validator/schema.go#L128-L138

It defaults to use a type called `Subscription` if there are no other defined in the `schema {}`-block.

Not sure if this is something that can be removed without breaking things so it might be difficult to fix without a major version bump...

But I'm assuming if I set another subscription type in the schema block it will compile as expected (about to test that now...).

**Comment by slaskis** [comment]
Verified that adding `subscriptions: Nope` to the schema block lets it generate properly.

**Comment by vektah** [comment]
Some nice sleuthing work :+1:. We default to using type Subscription if it's there. Not sure how often it's used, maybe it's at it's most useful in examples? 

We could look at deprecating it with a warning for a few versions?
