### ISSUE TITLE
Facebook’s GraphQL gets its own open-source foundation

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#417]
https://techcrunch.com/2018/11/06/facebooks-graphql-gets-its-own-open-source-foundation

**Comment by vektah** [comment]
There was a little bit of discussion at the working group yesterday, an initial drafting of the notes are [here](https://docs.google.com/document/d/1juYKFdIl4Xxx3iAAo6lIu5Gm3vhLQCmAvKtsYKx4pMM/edit).
