### ISSUE TITLE
Using gorm (and gorm.Model in any type).

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#426]
I'm using **gorm** (https://github.com/jinzhu/gorm) and I need to have `gorm.Model` in almost all my types.

Any hint about how to generate this code below with `gqlgen` (not using the `gqlgen.yml` file and external `.go` models)?

```go
type User struct {
  gorm.Model
  Nickname *string `json:"nickname"`
}
```

`gorm.Model` automagically adds fields like `ID`, `CreatedAt`... and you know.

I can extend those models with something like this code:

```go
type User struct {
  Nickname *string `json:"nickname"`
}

type ExtendedUser struct {
  gorm.Model
  User
}
```

Could there be any loss in terms of performance?

Having first type User and second Extended one is a performance problem?

Obviously I'm asking this and my concerned because of hundreds of types I have!

**Comment by vektah** [comment]
This sounds like a good use case for plugins. Lets make sure the plugin system can modify codegen and smooth over these kind of integrations, without baking too much of it into core.

Right now I don't think there is a great solution for you, Maybe write a script to codegen all the models for you and generate the yaml you need?

**Comment by frederikhors** [comment]
No stale.

**Comment by frederikhors** [comment]
Nope, stale.

**Comment by frederikhors** [comment]
No stale.

**Comment by colachg** [comment]
I have met this too. I don't know how to do.

**Comment by vektah** [comment]
I know you've been patiently bumping this but I cant see gqlgen ever supporting gorm models directly.

If you want it you can copy the [modelgen plugin](https://github.com/99designs/gqlgen/tree/master/plugin/modelgen) out into your repo and modify its templates however you like.
