### ISSUE TITLE
When I open my projen with graphiql it shows my fields as depricated

### ISSUE THREAD

**Issue by AkezhanOb1** [99designs/gqlgen#436]
### Expected Behaviour
We have 2 graphql apis(python, golang) graphql shows pythons api correct but puts go's api  into deprecated
### Actual Behavior
Now my graph api is deprecated 
### Minimal graphql.schema and models to reproduce
`
type Pawn {
    id: Int!
    name: String!
}

input newPawn {
    name: String!
}

input changePawn {
    id: Int!
    name: String!
}

input deletePawn {
    id: Int!
}

input singlePawn {
    id: Int!
}`

**Comment by vektah** [comment]
What are you using client side?

**Comment by AkezhanOb1** [comment]
@vektah React JS, Apollo
