### ISSUE TITLE
Int handling incompatibility with graph-gophers

### ISSUE THREAD

**Issue by gracenoah** [99designs/gqlgen#442]
I'm migrating a large codebase from graph-gophers to gqlgen and I ran into a really frustrating incompatibility. gqlgen requires models/resolvers to handle graphql Int as `int` and graph-gophers requires resolvers to handle graphql Int as `int32`.

I don't know what the best way to reconcile the two is right now. I'll try forking graph-gophers for now because there's a simple proposed change in https://github.com/graph-gophers/graphql-go/issues/105 that would allow them to accept int.

Another option that might help others who are migrating might be to add a config option to gqlgen to use int32 instead of int.

Anyway, just posting some migration issues as I go through the process. I don't know if there's interest in fixing this.

**Comment by vektah** [comment]
You can copy out the int marshaller and change it to int32, then map it over the Int scalar in your config.

https://github.com/99designs/gqlgen/blob/master/graphql/int.go
https://gqlgen.com/reference/scalars/

**Comment by gracenoah** [comment]
Wow! That worked so much better than modifying graph-gophers and all the resolvers! Thanks for the tip!
