### ISSUE TITLE
optional arrays trigger numerous codegen bugs

### ISSUE THREAD

**Issue by gracenoah** [99designs/gqlgen#464]
### Expected Behaviour
Optional arrays generate valid go code in `generated.go` files

### Actual Behavior
Optional arrays often cause invalid go code to be generated.

### Minimal graphql.schema and models to reproduce
Sorry, I don't have an example schema, but I expect these issues to be easy to reproduce. We've run into them multiple times and switched the optional arrays to required arrays to work around the issue.

If the bugs prove difficult to find, I'll work on finding a minimal schema, but I suspect it won't be hard to guess what schemas produce invalid code with optional arrays.

**Comment by vektah** [comment]
Unable to reproduce, please reopen with some schema.
