### ISSUE TITLE
How to use this with AWS Lambda?

### ISSUE THREAD

**Issue by csterritt** [99designs/gqlgen#466]
Hey -- trying a straight server approach with gqlgen works really well, thanks!

But I'd like to set it up as an AWS Lambda service, to replace a REST service I have set up already.

However, I can't figure out how to take a query/mutation and run it.  [This article](https://medium.com/a-man-with-no-server/building-a-golang-graphql-api-on-aws-lambda-b5278b7afc8c) shows how to do it using `graphql-go`, but that's a different API.

Thanks!

**Comment by mathewbyrne** [comment]
We don't use gqlgen with Lamda internally, so not sure what's required to get it working sorry.  I would recommending asking in [our gitter channel](https://gitter.im/gqlgen/Lobby) to see if anyone has tried this before.

**Comment by sdalezman** [comment]
We're doing this with heavily trafficked services - we've implemented just like any other http handler, we use the proxy adapters from the aws labs to use golang http handlers.  

code is something akin to: 

``` golang
package main

import (
	"context"

	"github.com/aws/aws-lambda-go/lambdacontext"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-xray-sdk-go/xray"
	"github.com/awslabs/aws-lambda-go-api-proxy/gorillamux"
	"github.com/gorilla/mux"
)

func init() {
	// start the mux router
	r := mux.NewRouter()
	api.Routes(r) // routes just accepts a mux router to bind routes to and that's where our gqlgen handlers live
	// initialize the mux adapter so that we can use mux with lambda
	muxAdapter = gorillamux.New(r)
}

// Handler is a wrapper around lambda and mux so that we can continue to use mux via lambda
func Handler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	res, err := muxAdapter.Proxy(req)
	if err != nil {
		log.Println(err)
	}
	return res, err
}

func main() {
	lambda.Start(Handler)
}
```

**Comment by mathewbyrne** [comment]
Thanks @sdalezman .  I'm going to mark this issue closed, we might consider including this in a documentation recipe in the future.

**Comment by csterritt** [comment]
Thanks @sdalezman -- that works fine! Much appreciated.

**Comment by rayhaanq** [comment]
Hey there, is there a repo for this showing a fully working example?

**Comment by rayhaanq** [comment]
Hey there, is there a repo for this showing a fully working example? @sdalezman

**Comment by sdalezman** [comment]
@rayhaanq unfortunately i don't have one that I can publicly share and am pretty strapped for time these days. You can use the mux router generated above to bind to a gqlgen handler like you would if you were using mux and you can do the same thing with the playground handler. Hope that helps!

**Comment by ptimson** [comment]
> Hey there, is there a repo for this showing a fully working example? @sdalezman

A year on but this hopefully is a more complete version for ref. It combines the generated `server.go` file with 
```
package main

import (
	"context"
	"log"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/gorillamux"
	"github.com/gorilla/mux"

	"<yourRepo>/graph"
	"<yourRepo>/graph/generated"
)

var muxAdapter *gorillamux.GorillaMuxAdapter

func init() {
	r := mux.NewRouter()

	// From server.go
	schema := generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}})
	server := handler.NewDefaultServer(schema)
	r.Handle("/query", server)
	r.Handle("/", playground.Handler("GraphQL playground", "/query"))

	muxAdapter = gorillamux.New(r)
}

func Handler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	rsp, err := muxAdapter.Proxy(req)
	if err != nil {
		log.Println(err)
	}
	return rsp, err
}

func main() {
	lambda.Start(Handler)
}

```

**Comment by leventov** [comment]
@ptimson I failed to make the code like the above working (I use serverless framework). The response from the server is always `404 page not found`.

What worked for me (no Playground though):
```go
import (
	"context"
	"github.com/99designs/gqlgen/handler"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/handlerfunc"
	"<repo>/server" // includes everything that corresponds to "generated" and "graph" in ptimson's comment
	"log"
)

var apiGatewayAdapter *handlerfunc.HandlerFuncAdapter

func init() {
	schema := server.NewExecutableSchema(server.Config{Resolvers: &server.Resolver{}})
	gqlHandler := handler.GraphQL(schema)
	apiGatewayAdapter = handlerfunc.New(gqlHandler)
}

func Handler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	rsp, err := apiGatewayAdapter.ProxyWithContext(ctx, req)
	if err != nil {
		log.Println(err)
	}
	return rsp, err
}
```

**Comment by markbdaniels** [comment]
@leventov I was also getting a 404 with @ptimson solution but I managed to get it working by changing my serverless config - 

from:
    events:
      - http:
          path: graphql
          method: ANY

to:
    events:
      - http: ANY {proxy+}
      - http: ANY /


Just in case someone else runs into same issue...

**Comment by TileNguyen** [comment]
Hi all,
Anyone use the gqlgen to generate ( types/model ) schema of AWS Appsync?
I try to use it but got an error with Aws directive
"failed to load schema: graph/schema.graphql:747: Undefined directive aws_subscribe.exit status 1"

Should I use the gqlgen for Aws or not?
Thanks

**Comment by giopetris** [comment]
For any other beginning at golang struggling to get this working, here's a more complete version of @ptimson's solution:

`server.go`:
```
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/awslabs/aws-lambda-go-api-proxy/gorillamux"
	"<yourRepo>/graph"
	"<yourRepo>/graph/generated"
	"github.com/gorilla/mux"
)

var muxRouter *mux.Router

func init() {
	muxRouter = mux.NewRouter()

	schema := generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}})
	server := handler.NewDefaultServer(schema)
	muxRouter.Handle("/query", server)
	muxRouter.Handle("/", playground.Handler("GraphQL playground", "/query"))
}

func lambdaHandler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	muxAdapter := gorillamux.New(muxRouter)

	rsp, err := muxAdapter.Proxy(req)
	if err != nil {
		log.Println(err)
	}
	return rsp, err
}

func main() {
	isRunningAtLambda := strings.Contains(os.Getenv("AWS_EXECUTION_ENV"), "AWS_Lambda_")

	if isRunningAtLambda {
		lambda.Start(lambdaHandler)
	} else {
		defaultPort := "7010"
		port := os.Getenv("PORT")

		if port == "" {
			port = defaultPort
		}

		log.Printf("connect to http://localhost:%s/ for GraphQL playground", port)
		log.Fatal(http.ListenAndServe(":"+port, muxRouter))
	}
}
```

`serverless.yml`:
```
provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  graphql:
    handler: bin/server
    events:
      - http: ANY /{proxy+}
      - http: ANY /
```

`Makefile`:
```
build:
	env GOOS=linux go build -ldflags="-s -w" -o bin/server

clean:
	rm -rf ./bin

deploy: clean build
	sls deploy --verbose
```

**Comment by 3nvi** [comment]
> For any other beginning at golang struggling to get this working, here's a more complete version of @ptimson's solution:
> 
> `server.go`:
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"log"
> 	"net/http"
> 	"os"
> 	"strings"
> 
> 	"github.com/99designs/gqlgen/graphql/handler"
> 	"github.com/99designs/gqlgen/graphql/playground"
> 	"github.com/aws/aws-lambda-go/events"
> 	"github.com/aws/aws-lambda-go/lambda"
> 	"github.com/awslabs/aws-lambda-go-api-proxy/gorillamux"
> 	"<yourRepo>/graph"
> 	"<yourRepo>/graph/generated"
> 	"github.com/gorilla/mux"
> )
> 
> var muxRouter *mux.Router
> 
> func init() {
> 	muxRouter = mux.NewRouter()
> 
> 	schema := generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}})
> 	server := handler.NewDefaultServer(schema)
> 	muxRouter.Handle("/query", server)
> 	muxRouter.Handle("/", playground.Handler("GraphQL playground", "/query"))
> }
> 
> func lambdaHandler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
> 	muxAdapter := gorillamux.New(muxRouter)
> 
> 	rsp, err := muxAdapter.Proxy(req)
> 	if err != nil {
> 		log.Println(err)
> 	}
> 	return rsp, err
> }
> 
> func main() {
> 	isRunningAtLambda := strings.Contains(os.Getenv("AWS_EXECUTION_ENV"), "AWS_Lambda_")
> 
> 	if isRunningAtLambda {
> 		lambda.Start(lambdaHandler)
> 	} else {
> 		defaultPort := "7010"
> 		port := os.Getenv("PORT")
> 
> 		if port == "" {
> 			port = defaultPort
> 		}
> 
> 		log.Printf("connect to http://localhost:%s/ for GraphQL playground", port)
> 		log.Fatal(http.ListenAndServe(":"+port, muxRouter))
> 	}
> }
> ```
> 
> `serverless.yml`:
> 
> ```
> provider:
>   name: aws
>   runtime: go1.x
>   lambdaHashingVersion: 20201221
> 
> package:
>   patterns:
>     - "!./**"
>     - ./bin/**
> 
> functions:
>   graphql:
>     handler: bin/server
>     events:
>       - http: ANY /{proxy+}
>       - http: ANY /
> ```
> 
> `Makefile`:
> 
> ```
> build:
> 	env GOOS=linux go build -ldflags="-s -w" -o bin/server
> 
> clean:
> 	rm -rf ./bin
> 
> deploy: clean build
> 	sls deploy --verbose
> ```

Thanks  for that!

**Comment by tabvn** [comment]
i 'm going to implement also subscription for aws apigateway socket in this repo if someone  need join let's give me a hand.

https://github.com/thebaycity/aws-graphql

**Comment by mihir-mehta** [comment]
I am following this code snippet , but getting "Transport not supported" error 

Any help would be appreciated

**Comment by tabvn** [comment]
@mihir-mehta  it is depend on graphql subscription client. If you are using graphql-ws 

you need add this to header of AWS  Apigateway websocket

```

return events.APIGatewayProxyResponse{Headers: map[string]string{
		"Sec-WebSocket-Protocol": "graphql-transport-ws",
	}, StatusCode: http.StatusOK, Body: body}, nil
```


see what i implemented here. https://github.com/thebaycity/aws-graphql/blob/master/lambda/subscription/main.go

**Comment by ahummel25** [comment]
Using above Lambda examples, is it possible to communicate any handled errors from the resolver services back out to the lambda handler? Since the request gets proxied I'm not seeing an easy way to do this.

See my below solution using an env variable. It's a total hack and not a good solution at all, but I'm relying on a env variable of `CLIENT_ERROR` which I set upon encountering an error in my resolvers. Then I determine what to set the response status code to based off of that.

If I encounter an error in one of my resolvers, how do I communicate that to the handler and then set the response code appropriately?

```golang
func LambdaHandler(
	ctx context.Context,
	request events.APIGatewayProxyRequest,
) (events.APIGatewayProxyResponse, error) {
	var (
		apiGWResponse                events.APIGatewayProxyResponse
		err                          error
		switchableAPIGatewayResponse *core.SwitchableAPIGatewayResponse
	)
	// Ugly way of determining an appropriate response code
	os.Unsetenv("CLIENT_ERROR")
	if switchableAPIGatewayResponse, err = muxAdapter.ProxyWithContext(ctx, *core.NewSwitchableAPIGatewayRequestV1(&request)); err != nil {
		return apiGWResponse, err
	}

	apiGWResponse = *switchableAPIGatewayResponse.Version1()
	apiGWResponse.IsBase64Encoded = false
	apiGWResponse.StatusCode = http.StatusOK
	// Check for errors if this was a request to the /graphql endpoint
	if request.Path == "/graphql" {
		var gqlResponse graphqlResponse
		// Unmarshal GraphQL response and check for errors
		if err = json.Unmarshal([]byte(apiGWResponse.Body), &gqlResponse); err != nil {
			apiGWResponse.StatusCode = http.StatusInternalServerError
			return apiGWResponse, fmt.Errorf("error parsing response: %w", err)
		}
		// Assign a response code based on the existence of errors.
		// TODO: Find better way to do this by not determining it based on an env variable.
		// With the lanbda proxying we're doing, there doesn't appear to be a clean way to communicate
		// service errors back out to the handler and then to API Gateway. The context doesn't appear to remain
		// populated during the before and after points of proxying the request.
		if len(gqlResponse.Errors) > 0 {
			clientError := os.Getenv("CLIENT_ERROR")
			switch clientError {
			case service.BAD_REQUEST:
				apiGWResponse.StatusCode = http.StatusBadRequest
			case service.NOT_FOUND:
				apiGWResponse.StatusCode = http.StatusNotFound
			default:
				apiGWResponse.StatusCode = http.StatusInternalServerError
			}
		}
	}
	return apiGWResponse, nil
}
```
