### ISSUE TITLE
optional input arrays are not pointers

### ISSUE THREAD

**Issue by gracenoah** [99designs/gqlgen#468]
### Expected Behaviour
Optional input array types are pointers to arrays

```go
func (r *queryResolver) IsTheSkyBlueOnDays(ctx context.Context, filterDays *[]string) ([]bool, error) {
```

### Actual Behavior
Optional input array types are not pointers to arrays
```go
func (r *queryResolver) IsTheSkyBlueOnDays(ctx context.Context, filterDays []string) ([]bool, error) {
```

### Minimal graphql.schema and models to reproduce
```graphql
type Query {
  isTheSkyBlueOnDays(filterDays: [String!]): [Boolean!]!
}
```

This behaviour makes it very difficult to port a large codebase from graph-gophers because there input arrays HAVE to be pointers. I'm looking for some solution that would allow me to keep my resolvers as similar as possible. It's already very frustrating that in one library the arguments are a struct and in the other they are positional arguments. In one particularly bad case I had to write a page of type casts, pointer fixes and struct creations just for mapping 1 resolver's inputs.

To make the migration bearable and work around this I defined a bunch of functions of the form
```go
func stringList([]string)*[]string {
	if l == nil {
		return nil
	}
	return &l
}
```

**Comment by mathewbyrne** [comment]
While interoperability between libraries is fine, our main goal with resolver generation is to be idiomatic and optimise for developer experience.  To this end, slices do not resolve as pointers regardless of their nullability in the schema.

Since slices can be nil, and slice pointers are generally only used in use-cases involving modifying the slice directly, we this this is the correct behaviour.

We are looking at addressing some resolver type things for 0.8, but we do not currently expect this behaviour to change.

**Comment by gracenoah** [comment]
I understand and respect your choice. I still think it would be useful to be able to make the experience of porting large codebases from graph-gophers easier, whether that's by modifying graph-gophers or adding some compatibility flags to this library. That way the barrier to switching would be lower. Another way to lower the barrier is for me to provide a little writeup of the various incompatibilities to help the next person who has to do this. That might be easier to do for now. Let me know if you'd like that as a new page on the website or something like that.

**Comment by mathewbyrne** [comment]
Thanks for your understanding.

Internally we've only used `gqlgen` so we don't have much experience with the other frameworks, but I think migration guides would be a welcome addition to the docs.  If you have anything you'd like to share we'd gladly look at it and see whether it's a good fit for `gqlgen.com`
