### ISSUE TITLE
Get full path of field?

### ISSUE THREAD

**Issue by saward** [99designs/gqlgen#469]
Hi,

What's the best way to grab the full path of a field?  Currently I'm trying something like this:

```
func fullFieldList(rctx graphql.ResolverContext) []string {
	var fields []string
	if rctx.Field.Field == nil {
		return []string{}
	}

	field := rctx.Field.Alias

	if rctx.Parent != nil {
		fields = fullFieldList(*rctx.Parent)
	}

	fields = append(fields, field)

	return fields
}
```

However, this seems to terminate when I have nested functions.  E.g., client->edges->node->transactions->client->blah, then the blah field has something like node.transactions.client.blah, instead of client.edges.node.transactions.client.blah.

I may be remembering the details incorrectly, but the gist of it is that I would like to fetch the full path for some field, but the method I'm using above doesn't work.  Is this possible, and is there a recommended way?

The above function is being called from inside ResolverMiddleware().

Thanks

**Comment by mathewbyrne** [comment]
Is `func (r *ResolverContext) Path() []interface{}` not working for you?  If you think there's a bug would you mind putting together a minimal reproduce example?

**Comment by saward** [comment]
Thanks, that works.  The problem with it is I had not noticed it when I was looking through the source :)

**Comment by mathewbyrne** [comment]
Yeah, we need some better API docs.  We will hopefully address heading towards 1.0
