### ISSUE TITLE
How to partially resolve a struct?

### ISSUE THREAD

**Issue by cannium** [99designs/gqlgen#470]
Say I have a type and query like:
```graphql
type Example {
     a: String!
     b: String!
     c: String!
}

type Query{
    example(q: String!): Example
}
```

gqlgen would generate a resolver interface like 
```go
type QueryResolver interface {
	Example(ctx context.Context, q string) (*graphql_model.Example, error)
}
```

The problem is, maybe `a` is fetched from DB, `b` is fetched from a service, and `c` is fetched from another service, so I would not like to fetch `c` when a client only asks for `a` and `b`. I'd like to know what's the best practice to handle it?

**Comment by mathewbyrne** [comment]
@cannium you have two main options:

1. In your `Example` resolver, you can use `ResolverContext.CollectFieldsCtx` to get back a list of fields that were selected by the query.  You can use this to conditionally fetch parts of the model to return.

2. You can force `gqlgen` give you resolvers for your `a`, `b`, and `c` fields using [your `gqlgen.yml` configuration](https://gqlgen.com/config/).  Example:

    ```yml
    models:
      Example:
        fields:
          a:
            resolver: true
    ```

**Comment by cannium** [comment]
Thanks for your timely response! I'll try.

**Comment by cannium** [comment]
The signature of `CollectFieldsCtx` is
```go
func CollectFieldsCtx(ctx context.Context, satisfies []string) []CollectedField 
```
what does `satisfies` mean? Seems for my case `nil` is OK, but I wonder if I call it correctly...

**Comment by JulienBreux** [comment]
Thanks for this precious reply @mathewbyrne !

**Comment by cannium** [comment]
Is there's a simpler way to force all fields of a type to generate resolvers? 
Say I have two queries as below,
```graphql
type Query {
    animal(name: String!): Animal
    animals(zoo: String!): [Animal!]
}
```
I think I need to manually resolve every field of `Animal` so the resolver of `animals` could return a list correctly as required. Otherwise there would be repeated code in the resolvers of `animal` and `animals`.

**Comment by mathewbyrne** [comment]
The `satisfies` argument is used when getting collected fields whose query include fragments.  They will only collect fields from fragments who satisfy a type  passed through `satisfies []string`.  If you're not using fragments in your query, then passing `nil` is fine.  We are going to improve this interface before `1.0`.

One way you could "force" `gqlgen` to give you resolvers for all fields of a model, is to bind the type to an empty struct:

```graphql
type Animal {
    name: String!
    zoo: String!
}
```

```go
type Animal struct {}
```

```yml
models:
  Animal:
    model: "package.Animal"
```
Since `gqlgen` cannot resolve the field names to a field on your struct, it will generate a resolver interface for you to fulfil.

**Comment by willyyang** [comment]
Sorry for reviving a closed issue but can someone show me how to use `ResolverContext.CollectFieldsCtx` to get the fields that were selected by the query ? Thanks in advance.
