### ISSUE TITLE
Do not call panic inside generated functions which are run as goroutines

### ISSUE THREAD

**Issue by gabrielruiu** [99designs/gqlgen#472]
### Expected Behaviour
Generated functions which are called as goroutines should either not panic, should be caught by the panic recovery function injected as the `RecoverFunc` Option, or instead return an `error` object.
### Actual Behavior
There are use-cases where, due to unforseen causes, the generated code is faulty, and eventually leads to calling a `panic` inside a goroutine which doesn't have any panic recovery mechanism, and hence the whole application is killed. Will give an example at the end.
### Minimal graphql.schema and models to reproduce
It's enough to use the `starwars` schema in the `examples` directory.

### Further description
Unfortunately I cannot provide a reproducing example, but I will describe what happened using the `starwars` project as a reference.
In my case, the panic happened inside a goroutine which was trying to map an object to a `Marshaler`. This function is typically generated to identify which implementation of an interface is provided. 
In the generated code for the `starwars` schema, such a function can be seen [here](https://github.com/99designs/gqlgen/blob/master/example/starwars/generated.go#L4125), where the `Character` type is determined.

Because of some unknown reason, the generated function in my case, did not have a switch case for one of the struct objects, there was however a switch case for the pointer of such an object. Continuing on the `starwars` example, imagine that there was a missing switch case for the `Droid` type, but there was for `*Droid`.  

This eventually led to the `panic` and killed my entire app, from which there is no way to recover. This is obviously, **extremely bad**.

```
func (ec *executionContext) _Character(ctx context.Context, sel ast.SelectionSet, obj *Character) graphql.Marshaler {
	switch obj := (*obj).(type) {
	case nil:
		return graphql.Null
	case Human:
		return ec._Human(ctx, sel, &obj)
	case *Human:
		return ec._Human(ctx, sel, obj)
	/*case Droid:
		return ec._Droid(ctx, sel, &obj)*/   <--- commented out to simulate the fact that it was missing
	case *Droid:
		return ec._Droid(ctx, sel, obj)
	default:
		panic(fmt.Errorf("unexpected type %T", obj)) <--- obj is of type Droid, not *Droid, so execution arrived here
	}
}
```

I don't know why the switch case was missing but in the end it is, to a certain extent, irrelevant, because no library should expose such possibilities where the entire application is brought down. 

Such panics show up in many places of the generated code, and I don't know how many are executed inside unprotected goroutines.

The base issue is also described [here](https://github.com/golang/go/issues/20161).

**Comment by vektah** [comment]
This definitely should panic, it shouldn't be possible, and is pointing out an underlying codegen bug. It should of course not crash the app though.

Sounds like there is a panic handler missing somewhere.

**Comment by azavorotnii** [comment]
I found another case when panic happens in goroutine and not handled properly. Lets assume I need scalar type which will be int64 value (allowed by graphql spec).
I can define it like this:
```
type Size int64

func (y *Size) UnmarshalGQL(v interface{}) error {
	switch v := v.(type) {
	case int64:
		*y = Size(v)
	default:
		return errors.New("bad type")
	}
	return nil
}

func (y Size) MarshalGQL(w io.Writer) {
	n, err := w.Write([]byte(strconv.FormatInt(int64(y), 10)))
	if err != nil {
		log.Error(err)
	}
}
```

It works both as input and output values. But if I supply >64bit integer whole application terminates because of unhandled panic:
```
panic: strconv.ParseInt: parsing "102410241024111111024": value out of range

goroutine 6008 [running]:
stash.wdmv.wdc.com/restsdk/sdk/vendor/github.com/vektah/gqlparser/ast.arg2map(0x7d3f518, 0x1, 0x2, 0x8378360, 0x1, 0x2, 0x84e9540, 0x8570e40)
        /go/src/stash.wdmv.wdc.com/restsdk/sdk/vendor/github.com/vektah/gqlparser/ast/argmap.go:17 +0x21c
stash.wdmv.wdc.com/restsdk/sdk/vendor/github.com/vektah/gqlparser/ast.(*Field).ArgumentMap(0x8227d00, 0x84e9540, 0x83784f8)
        /go/src/stash.wdmv.wdc.com/restsdk/sdk/vendor/github.com/vektah/gqlparser/ast/selection.go:38 +0x54
stash.wdmv.wdc.com/restsdk/sdk/internal/httpserver/internal/graphql/schema.(*executionContext)._Query_fake(0x83784f8, 0x270cba0, 0x840a100, 0x8227d00, 0x7db5918, 0x1, 0x1, 0x0, 0x0)
...
```
It doesn't happen for `Int` scalars as they are not verified in go-routine, while scalars values are parsed in goroutines.  

@vektah could you confirm that merged fix solves this issue too?
