### ISSUE TITLE
Can't use a port different from 8080 for subscriptions

### ISSUE THREAD

**Issue by tommyblue** [99designs/gqlgen#477]
### Expected Behaviour

Users can `subscribe` and receive pushes also if the server runs on a port different from 8080

### Actual Behavior

It doesn't. Moving back to 8080 works.
I suspect I need to set some sort of configuration somewhere but I can't find where in any doc or example.

### Minimal graphql.schema and models to reproduce

```
scalar Time

type Event {
  id: String!
  type: String!
  createdAt: Time!
  status: String!
}

type ServiceState {
	name: String!
	service_id: String!
	state: String!
    last_state_updated: String!
    id: String!
    type: String!
}

type ChangeEvent {
    entry_id: String!
	entry_type: String!
	action: String!
	change: ServiceState!
}

type EventResponse {
    data_dog: [ServiceState!]!
    pager_duty: [ServiceState!]!
    sentry: [ServiceState!]!
}

type Query {
  events: EventResponse!
}

type Subscription {
  eventCreated: ChangeEvent!
}
```

This is how I run the server. `conf` comes from a configuration file and `conf.Address` is `0.0.0.0` while `conf.Port` is `8081`:

```
func Run(conf ServerConfiguration, ch chan graphql.ChangeEvent, state *graphql.GlobalState) {
	c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowCredentials: true,
	})

	http.Handle("/", http.FileServer(http.Dir(conf.StaticFolder)))
	http.Handle("/graphiql", handler.Playground("GraphQL playground", "/query"))
	http.Handle("/query", c.Handler(
		handler.GraphQL(graphql.NewExecutableSchema(graphql.Config{Resolvers: &graphql.Resolver{
			Comm:        ch,
			Subscribers: make(map[string]chan graphql.ChangeEvent),
			State:       state,
		}}),
			handler.WebsocketUpgrader(websocket.Upgrader{
				CheckOrigin: func(r *http.Request) bool {
					return true
				},
			}))),
	)
	log.Fatal(http.ListenAndServe(fmt.Sprintf("%s:%d", conf.Address, conf.Port), nil))
}
```

**Comment by cbenjemaa** [comment]
@tommyblue Can you share more information on how reproduce this bug. 
My IDE can't find this method for example `graphql.NewExecutableSchema`. graphql here come from this package `github.com/99designs/gqlgen/graphql`. Is it the right package but an older revision or what ? 
Thanks :)

**Comment by vektah** [comment]
The chat example is using 8085, and we run it on 443 in prod. I don't think there is a bug here.

Check have you checked where your client is connecting, eg https://github.com/99designs/gqlgen/blob/master/example/chat/src/index.js#L13?

**Comment by comerc** [comment]
Hoppscotch - the same bug, but Altair work fine.
