### ISSUE TITLE
Even a GET endpoint, please.

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#478]
I need to have also a `GET` endpoint (in addition to the `POST` one).

With `chi` I can use this code:

```go
gql := handler.GraphQL(graphql.NewExecutableSchema(graphql.Config{Resolvers: &graphql.Resolver{}}))

r.Get("/playground", handler.Playground("GQLGENGraphql", "/api"))
r.Get("/api", gql)
r.Post("/api", gql)
```

If I try query on the `POST` endpoint everything works good.

On the `GET` endpoint it gives `422 Unprocessable Entity`.

**Why? Some config?**

**Comment by andrewmunro** [comment]
When using the GET endpoint, you still need to pass a query for graphql to process. You do this by passing it in a querystring. E.G:

`curl myapi/api?query={things{thing}}`

The graphql playground uses the POST endpoint.
