### ISSUE TITLE
How to report error when subscription is interrupted

### ISSUE THREAD

**Issue by guiguan** [99designs/gqlgen#479]
### Expected Behaviour
There should be an error channel or a mechanism to allow the running goroutine in a subscription to report the error when the subscription event stream is interrupted or erred

### Actual Behavior
The user has to define a customized error field in their GraphQL schema to handle such error

What's the best practice here with `gqlgen`? Thanks!

**Comment by shotmk** [comment]
This one requires attention.. I am also struggling with it..
