### ISSUE TITLE
Handle concurrent mutations on same resource

### ISSUE THREAD

**Issue by Pokerkoffer** [99designs/gqlgen#480]
Hi,
i wonder how to solve the [Lost Update Problem](https://en.wikipedia.org/wiki/Write%E2%80%93write_conflict) in graphql or with this library.

For example, 2 users of a graphql API fetch a resource and then both change some field to different values and both run the mutation, the one that is processed first will be overwritten by the second one and get lost without notice.

Is there any specific method within this library (like E-Tag in rest) to solve this?
If not, how should this be done in the server's code?

Thanks for feedback!

**Comment by mathewbyrne** [comment]
gqlgen doesn't provide you anything specific to solve this, you'll need to handle this in your resolvers using your own logic.
