### ISSUE TITLE
Generated array field unmarshalling handles errors incorrectly for input types

### ISSUE THREAD

**Issue by trotterdylan** [99designs/gqlgen#487]
### Expected Behaviour

If any element in an array field fails to unmarshal in an input type, it should be reported to clients as an error.

### Actual Behavior

If an error occurs unmarshalling any of the array elements but the last, the error is ignored.

### Minimal graphql.schema and models to reproduce

```
input Foo {
    dateAnswers: [Date!]
}
```

And the generated code:

```
			it.DateAnswers = make([]model.Date, len(rawIf1))
			for idx1 := range rawIf1 {
				err = (&it.DateAnswers[idx1]).UnmarshalGQL(rawIf1[idx1])
			}
			if err != nil {
				return it, err
			}
```

The error check should be inside the loop, not done at the end.

**Comment by vektah** [comment]
Looks like this has already been fixed on next.
