### ISSUE TITLE
[Question] Using different go int types (int8, int16, int32...)

### ISSUE THREAD

**Issue by yaryabu** [99designs/gqlgen#489]
Hi!

I have a struct in my code, that looks something like this:
```go
type MiscInfo struct {
	Field1 int8
	Field2 int16
	Field3 int32
//and a lot more
}
```

I want to map it onto a schema that looks like this:
```graphql
type MiscInfo {
        field1: Int!
        field2: Int!
        field3: Int!
}
```

When I try to do it, I get all sorts of errors about type incompatibility. Am I correct to assume that this automatic type mapping is not supported right now and the only two possible ways around it is to define [custom scalar](https://gqlgen.com/reference/scalars/) for every single golang type(`int8` `int16`  `int32`  `int64` `uint` `uint8` `uint16` `uint32` `uint64` `byte` `rune` `float32`) and write schema with them or to just stop using golang type other than `int` altogether?

**Comment by yaryabu** [comment]
On second thought, I wouldn't really want automatic mapping if some mutation sends data which overflows int8

**Comment by frederikhors** [comment]
> On second thought, I wouldn't really want automatic mapping if some mutation sends data which overflows int8

Hi @yaryabu can I ask you to explain this better?

What if someone overflow `int` too?

I mean isn't this a validation phase responsibility and not a modeling one?
