### ISSUE TITLE
New Config

### ISSUE THREAD

**Issue by jney** [99designs/gqlgen#495]
I noticed in many examples there is [`New` function](https://github.com/99designs/gqlgen/blob/master/example/chat/resolvers.go#L29-L35) generated in `resolver.go`.
In mine no such function. Is normal, should i implement it myself?

**Comment by vektah** [comment]
resolver.go is just a starting point for you to write your code, it currently doesn't get regenerated because you need to write everything in there.

**Comment by jney** [comment]
ok thank you for explanation
