### ISSUE TITLE
function generated for only 2 fields

### ISSUE THREAD

**Issue by jney** [99designs/gqlgen#496]
in my schema i've got the following type:

```gql
type Item {
  id: ID!
  advertiser: String
  impressionPixels: [String]
  title: String
  url: String
}
```

and in `resolver.go` I've got generated function:

```go
type itemResolver struct{ *Resolver }

func (r *itemResolver) Advertiser(ctx context.Context, obj *storage.DynamicItem) (*string, error) {
	panic("not implemented")
}
func (r *itemResolver) ImpressionPixels(ctx context.Context, obj *storage.DynamicItem) ([]*string, error) {
	panic("not implemented")
}
```

Only for those 2 fields. Not the others. Is it the expected generated code?

**Comment by azavorotnii** [comment]
@jney you can control which fields need resolver methods with .yml file. I don't see example in documentation, but there is in "examples": https://github.com/99designs/gqlgen/blob/master/example/starwars/.gqlgen.yml
```
  Starship:
    fields:
      length:
        resolver: true
```

**Comment by vektah** [comment]
This is expected, everything that has fields on the DynamicItem will be mapped automatically. Its assumed whatever returned the DynamicItem already set the properties.

Resolvers will be added when gqlgen:
 - cant find the field
 - cant convert between the graphql and go types
 - a complex type is returned and its probably requires a join

**Comment by jney** [comment]
they are indeed complex types in the struct declaration, i missed that. thank you guys
