### ISSUE TITLE
Using an `input` type in a `Query` context generates invalid Go code

### ISSUE THREAD

**Issue by jwatte** [99designs/gqlgen#500]
### Expected Behaviour

Using an `input` type in `Query` context should work (so I don't have to define all types twice)

If that goes against allowed schema in GraphQL (does it?) then the gqlgen generator should generate an error, rather than generate invalid go code.

### Actual Behavior

When generating, I get a go compile error in generated.go that _Foo is not defined on executionContext.

/home/jwatte/observe/code/go/src/observe/meta/foo/generated.go:216:9: invalid operation: ec (variable of type *executionContext) has no field or method _Foo

### Minimal graphql.schema and models to reproduce

    input Foo {
        a: String!
    }
    schema {
        query: Query
    }
    type Query {
        foo: Foo!
    }

**Comment by mathewbyrne** [comment]
> If that goes against allowed schema in GraphQL (does it?)

Yes it does, an input type is a separate concept from an object type and cannot be used in the same contexts.  We could probably do a better job of communicating the actual error here before we generate code, however the issue might be in the parser as well.
