### ISSUE TITLE
`generate` takes long time on build

### ISSUE THREAD

**Issue by jney** [99designs/gqlgen#503]
Hi there, I just changed the way my project is built, and now instead of having 1000s of line of generated files versioned in my repo I build them using comment:

```go
//go:generate go run scripts/gqlgen.go -v
```

with command `go generate ./...`

I'm doing this `gqlgen` and other stuff like `bindata`. While `bindata` just takes a couple of seconds, `gqlgen` slow down my build by approximatively 1m20s. 
I was wondering if it was normal, or if there are way to optimise this?

Thank you

**Comment by vektah** [comment]
That sounds like a long time. A few ideas:

*How long does it take to compile without a cache? *
```bash
go clean -r  -cache <YOUR ROOT PACKAGE HERE>
time go build -o /dev/null <YOUR ROOT PACKAGE HERE>
go build -o /dev/null .  6.42s user 0.53s system 465% cpu 1.495 total
```
gqlgen ends up scanning all of the code referenced in gqlgen.yml, and recursivly all of the dependencies. We have plans to speed this up by using the AST and only recursing into packages we need, probably at the same time we do go modules.

*Are you using a recent version of go?*
`go run` before [version 1.10](https://golang.org/doc/go1.10#build) did not cache intermediate files.

*Are you using a virtual machine with a slow file system?*
gqlgen scans lots of files, if using docker you probably want to mark your volume mounts as `delegated`.

If all of that shows up nothing lets jump on gitter and get some profiling traces out.

**Comment by jney** [comment]
> How long does it take to compile without a cache?

The issue append on both locally and travis.

locally results:

```
       17.58 real        45.75 user         6.06 sys
```

> Are you using a recent version of go?

on local laptop: `go version go1.11.4 darwin/amd64`
on travis: it is run in a docker `golang:1.11`

> Are you using a virtual machine with a slow file system?

Docker maybe.

running `go generate` locally:

```
       11.84 real        26.65 user         5.91 sys
```

**Comment by mathewbyrne** [comment]
Those numbers don't seem too bad on a Mac laptop. That said our next release should improve things a fair bit with Go Modules support landing. I'm going to close this for now, but feel free to reopen if you're still having issues on the next release in the coming weeks.
