### ISSUE TITLE
[Feature Request] generate schema from json

### ISSUE THREAD

**Issue by FingerLiu** [99designs/gqlgen#504]
I have a lot of REST API which return json, and I'am using gqlgen to wrap them to serve as GraphQL server.
It would be great if gqlgen can guess the json and generate a draft of schema.graphql. I am trying to add a `inspect` command to gqlgen which works like `go run scripts/gqlgen.go  generate` (maybe something like `go run scripts/gqlgen.go  inspect`).

Any suggestions on how to implement this?

**Comment by mathewbyrne** [comment]
I think this is outside the scope of core `gqlgen`, but we are interested in having a REST plugin that would allow you to effortlessly stitch in REST endpoints into your graph.  We've been planning to add plugins API for a while now (#228) and will be addressing them specifically in an upcoming release. Once the API is in we will look at adding some [contrib packages](https://github.com/99designs/gqlgen-contrib) and/or asking the community to help build them out.

**Comment by FingerLiu** [comment]
Awesome!

**Comment by FingerLiu** [comment]
>  allow you to effortlessly stitch in REST endpoints into your graph

For now I didn not need to go that far.My usecase is just generate the types to save some coding time(some API has near a hundred fields which it quite pain to hard code them).
And I had make a very basic sketch [here](https://gist.github.com/FingerLiu/ecf7cbb600abe832b1cad162109444d7). It does parse json and genrate graphql schema for me.

> I think this is outside the scope of core gqlgen

I agree this is not the core of gqlgen, but using it would save a lot of time (like me ~). If you guys need it, I could do some effort to make it robust(read config etc.) and wrap it into a cmd like this.
```go
	app.Commands = []cli.Command{
		genCmd,
		initCmd,
		versionCmd,
                 inspectCmd
	}
```

Just let me know if you need it and I'm alway glad to help.

**Comment by FingerLiu** [comment]
For memo, I made a simple tool to generate graphql schema from json a few month ago -->

https://github.com/FingerLiu/json2graphql
