### ISSUE TITLE
Implement complexity as a plugin

### ISSUE THREAD

**Issue by mia0x75** [99designs/gqlgen#508]
schema:
```
type Query {
	posts(count: Int = 10): [Post!]!
}

type Post {
	title: String!
	text: String!
	related(count: Int = 10): [Post!]!
}
```
when depth limit equals to 2:
valid query:
```
{
	posts(count: 100) { # depth = 1
		related(count: 100) { # depth = 2
		}
	}
}
```

invalid query:
```
{
	posts(count: 100) { # depth = 1
		related(count: 100) { # depth = 2
			related(count: 100) { # depth = 3
				related(count: 100) { # depth = 4
					title
				}
			}
		}
	}
}
```

**Comment by mathewbyrne** [comment]
We have a [query complexity](https://gqlgen.com/reference/complexity/) feature that you can use to limit which queries are allowed to run.  The `handler.ComplexityLimit` option allows you to control the limit.

**Comment by qhenkart** [comment]
I strongly second this. It is the field depth that causes issues, not the field length.

**Comment by Kay-Zee** [comment]
Also interested in a depth based complexity limit as an option.

**Comment by vektah** [comment]
We want to pull query complexity out into a plugin which will at the very least means you can provide a custom implementation without forking. 

I don't think it's as simple as what you describe though in practice. While 
```
posts -> related posts -> related posts
```
Is too deep
```
Viewer -> user > name
```
Isn't

Complexity is meant to capture what is hard and make it multiplicitivly harder the deeper you go, in this case related posts should have a high complexity, so you can't go very deep, but user, viewer and name have low complexity so going deep is ok

**Comment by qhenkart** [comment]
@vektah that would be great! But in terms of your examples, if I were designing my own plugin, I would design it so all depth is considered equal. Which means both of your examples would be equally complex (and I would set the complexity number and model my subresolvers appropriately), I think the issue that folks are touching on is that 

```
posts -> related posts -> related posts
```
has the same complexity as 
```
Viewer -> user > name
```

and

```
Viewer -> user > name
``` 
has the same complexity as 
```
Viewer -> user > name
                             email
                             id
```

**Comment by qhenkart** [comment]
keeping this alive because it's an important feature despite it's marking as low priority
