### ISSUE TITLE
Support Directives on Input Types

### ISSUE THREAD

**Issue by sdalezman** [99designs/gqlgen#511]
### Expected Behaviour

When defining a graphql schema you should be able to define a directive on an entire input object or an input field

### Actual Behavior

Can't define any directive on a input field 

### Minimal graphql.schema and models to reproduce

```graphql
directive @hello on INPUT_OBJECT

type Query {
   repeatLogName(n: Name!): String
}

input Name {
   name: String!
}

extend input Name @hello
```

where the directive evaluates to the input from the logging example: 

``` golang
func InputLogging(ctx context.Context, obj interface{}, next graphql.Resolver) (res interface{}, err error) {
	rc := graphql.GetResolverContext(ctx)
	log.Printf("input object logging: %v, %s, %T, %+v", rc.Path(), rc.Field.Name, obj, obj)
	return next(ctx)
}
```

Input logging will never be called. I think this has to do with how FieldMiddleware calls directives, but this is only from a cursory glance at the generated code

**Comment by sdalezman** [comment]
@mathewbyrne the reason I thought it was supported was because in the example of the type system extension there's an `INPUT_OBJECT`: https://github.com/99designs/gqlgen/blob/master/example/type-system-extension/schemas/input-object-extension.graphql

Searching through the generated code it didn't seem to ever be called, but thought it might've been my lack of understanding the generated code entirely

I understand your comments about when/how it should be called. For us, adding in some sort of input property/input object directive would be great. It would allow us to not have to add function calls to ensure that a given user has permission to filter/query by various fields (from a security perspective that adds onus to a developer to ensure they remember to add those checks as well as the reviewer to ensure that they're obvious- we do that and have tests for those flows, but reducing the mental burden of rapidly iterating on api's is always a plus in my book). 

That way we can have a handful of types and know that they can always be used securely and reduce the exposure of surface areas

**Comment by sdalezman** [comment]
@vektah @mathewbyrne our team would be happy to tackle this issue. If you can provide a bit more design guidance so we don't go down the wrong rabbit whole. We were thinking that you can have two types of input directives: 

1. Input directive that's called before any resolvers are called
2. Input directive that's called after resolvers are called

Which I think would cover 80% of use cases directives for inputs. If your team agrees on that we'd be happy to start working on this (and save us a tremendous headache at the moment)

**Comment by mathewbyrne** [comment]
Hey @sdalezman, sorry it took a bit to get back to you.  We'd been keen to support Directive Middlewares on Input objects.  I think it would work more or less the same as fields, where when the argument is resolved for a given input type, the middleware stack is run.

Obviously these directives will have the same interface as other directives, and be supplied through the generated directive root.  

We'd be happy to give feedback on a proposal issue if you think the scope of the change warrants.  Please be sure to work against the `next` branch for this change.

**Comment by steebchen** [comment]
Somehow, my directive works on INPUT_FIELD_DEFINITION, but I'm not able to get its value or name:

```graphql
directive @can(action: Action!) on INPUT_FIELD_DEFINITION

type Mutation {
	register(payload: RegisterPayload!): AuthResult!
}

input RegisterPayload {
	email: String!
	password: String!
	referrer: String @can(action: Create)
}
```

allows me implement this directive function:

```golang
func can(
	ctx context.Context,
	obj interface{},
	next graphql.Resolver,
	action gqlgen.Action,
) (interface{}, error) {
	rc := graphql.GetResolverContext(ctx)
	log.Printf("field %s has value %#v", rc.Field.Name, obj)
}
```

prints `field register has value gqlgen.RegisterPayload{Email:"customer", Password:"", Name:(*string)(nil)}`

I would have expected to get `field referrer has value <nil>` (provided that referrer was set to "").

Is there currently a way to do that?

**Comment by swkumar** [comment]
hi @steebchen: were you able to get the value or name for the INPUT_FIELD_DEFINITION directive?

**Comment by steebchen** [comment]
I'm not working on the project anymore, but I don't think I was. I worked around it. not stale

**Comment by swkumar** [comment]
@steebchen : thanks for the response. May I ask what was your workaround for this? Thanks!

**Comment by steebchen** [comment]
Sorry, that was unclear: I just didn't use directives for my use case anymore :P

**Comment by stevenxie** [comment]
Hi, are there any updates on this issue?

**Comment by swkumar** [comment]
Looks like this will be worked on here: https://github.com/99designs/gqlgen/issues/1084
