### ISSUE TITLE
Finding fields to Resolve partial struct 

### ISSUE THREAD

**Issue by willyyang** [99designs/gqlgen#512]
If I have type and query as : 
```
type NestStruct {
	b: String!
	c: String!
	d: String!
}

type Example {
	a: NestStruct
}

type Query {
	example(q: String!): Example
}
```
```
query {
	example(q: "test") {
		a {
			b
			c
		}
	}
}
```

How do I determine which fields of `NestStruct` are queried? This is similar to https://github.com/99designs/gqlgen/issues/470 but I'm not sure how to get the `Field` of a nested struct.
I'm able to see which fields are queried in the top layer resolver via
```
rslvrContext := graphql.GetResolverContext(ctx)
fmt.Println(rslvrContext.Field)
```
Unable to see fields from the next layer down though.. I think I need to extract out the context of the layer resolving `NestStruct` ? Appreciate any help

**Comment by willyyang** [comment]
Similarly, https://github.com/99designs/gqlgen/blob/5c870a489da3eecd57b4152f0501b65cd682f4af/example/selection/selection.go is only 1 level deep.. I want to find the selected fields of the next layer but there's only one context

**Comment by shenjing023** [comment]
@willyyang , How did you solve this problem? Thanks.

**Comment by willyyang** [comment]
@shenjing023 I think you can add this in `gqlgen.yml`
```
models:
  NestStruct:
    model: NestStruct
```
and run `generate`

if you need more control over the fields on the resolver you can also add 
```
models:
  NestStruct:
    model: NestStruct
    fields:
      a:
        resolver: true
      b:
         resolver: true
```

**Comment by shenjing023** [comment]
@willyyang Thanks. But how to find the selected fields of the next layer. such as this code, it just one level deep
```go
a:=graphql.CollectFieldsCtx(ctx,nil)
for _,v:=range a{
	spew.Dump(v.Name)
}
```
