### ISSUE TITLE
generated.go is too large

### ISSUE THREAD

**Issue by FingerLiu** [99designs/gqlgen#517]
I added 5 models and 4 query in schema, after generate, the size of `generated.go` is over 7000 lines?
Is this too large? I am new to go and I do not know whether it will cause any problem since the file is going to be over 10000 lines?

Or is there a need to seprate generated .go to separated files?

**Comment by mathewbyrne** [comment]
Is there a more specific problem you're worried about? We haven't spent much effort optimising for line count in generated code since generally it's just not an issue.
