### ISSUE TITLE
Missing content type with invalid json as query

### ISSUE THREAD

**Issue by vektah** [99designs/gqlgen#519]
### Expected Behaviour
curl --header "Content-Type: application/json" --request POST --data 'fff' http://localhost:8080/graphql

should return Content-Type application/json

### Actual Behavior

Isn't setting the content type.

**Comment by Sonna** [comment]
Is it not being set within the GraphQL handler `ServeHTTP`?
https://github.com/99designs/gqlgen/blob/39216361225c6dc824331ad1a218c9c931cc0985/handler/graphql.go#L323

Or would you want the generated server template prefix with a response writer to fix the headers?

https://github.com/99designs/gqlgen/blob/39216361225c6dc824331ad1a218c9c931cc0985/codegen/templates/server.gotpl#L22

```gotpl
        http.With(func(i http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
		})
	}).Handle("/query", handler.GraphQL({{ lookupImport .ExecPackageName }}.NewExecutableSchema({{ lookupImport .ExecPackageName}}.Config{Resolvers: &{{ lookupImport .ResolverPackageName}}.Resolver{}})))
```
