### ISSUE TITLE
Model generated Names differ from Resolver responses when found in the commonInitialisms

### ISSUE THREAD

**Issue by enjoylife** [99designs/gqlgen#527]
### Expected Behaviour
_This is using the latest next branch._

Given the following schema.graphql

```
type Query {
    getApiInfo: ApiInfo!
}

type ApiInfo {
    version: String!
}
```
The generated files should be

```
// models.go
// Note the  `Api` => `API` conversion
type APIInfo struct {
	Version     string    `json:"version"`
}

// schema.go
type QueryResolver interface {
	GetAPIInfo(ctx context.Context) (gen.APIInfo, error)
}
```
### Actual Behavior
The schema resolver's return types are not converted the same.
```
type QueryResolver interface {
        // note how its gen.ApiInfo and not the gen.APIInfo as in the generated models
	GetAPIInfo(ctx context.Context) (gen.ApiInfo, error)
}
```
The schema fails to build and outputs logs such as

```
unable to bind ...  is not compatible with var  .../gen.ApiInfo: named type name differs, APIInfo != ApiInfo
```

When triaging this bug I looked around for places in which the conversion takes place and I came across the `commonInitialisms` in the templates.go. This is used within the `ToGo` func, so it seems during the model generation its used on the generated models, but not for the interface return types. I tried finding where it was used vs not, but as I'm not familiar with the codebase it was a little confusing. 

Hopefully someone such as @mathewbyrne with more context can identify where the discrepancy takes place

**Comment by mathewbyrne** [comment]
We suspect that this has been resolved in 0.9
