### ISSUE TITLE
Dataloader with string keys generation

### ISSUE THREAD

**Issue by freddy311082** [99designs/gqlgen#536]
Hi guys... I'm new using gqlgen and now I'm trying to use a middleware dataloader for loading many pieces from an specific user... for example:

if I have this schema:

```
type Piece {
  id: ID!
  name: String
}

type User {
  id: ID!
  username: String!
  pieces: [Piece]
}
```

so, when I use dataloader from command line for generating the UserLoader struct, I got this:

```
type UserLoader struct {
	// this method provides the data for the loader
	fetch func(keys []int) ([]*wwgql.User, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[int]*wwgql.User

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *userBatch

	// mutex to prevent races
	mu sync.Mutex
}
```

but I need that the **fetch** function to receive **keys []string** instead **keys []int**

Do I have to do it manually or is there any way to do it an automatic way?

Regards

**Comment by vektah** [comment]
`dataloaden -keys string wwgql.User`?
