### ISSUE TITLE
Getting Started Guide 'Todo' Example fails

### ISSUE THREAD

**Issue by IkiM0no** [99designs/gqlgen#549]
### Expected Behaviour
The 'getting started' example builds and runs without issues.
https://gqlgen.com/getting-started/

### Actual Behavior
The 'getting started' example fails to run with error:
```
$ go run scripts/gqlgen.go init
exec plan failed: query entry point missing
```

### Minimal graphql.schema and models to reproduce
```
type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
  name: String! # adding this fixes the issue
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

**Comment by mathewbyrne** [comment]
Just to clarify, is this on `master` or our `next` branch?

**Comment by mathewbyrne** [comment]
Going to close this, we're close to a release candidate for our next release and I just ran through the getting started guide without any issues.
