### ISSUE TITLE
`[String]` returns `[]` on nil instead of `null`

### ISSUE THREAD

**Issue by leebenson** [99designs/gqlgen#556]
### Expected Behaviour

Given this type:

```gql
type Test {
  test1: [String]
  test2: [String!]
  test3: [String]!
  test4: [String!]!
}
```

I'd expect returning `nil` in each resolver to produce:

```json
{
  "data": {
    "test": {
      "test1": null,
      "test2": null,
      "test3": [],
      "test4": []
    }
  }
}
```

### Actual Behavior

This is what's returned instead:

```json
{
  "data": {
    "test": {
      "test1": [],
      "test2": [],
      "test3": [],
      "test4": []
    }
  }
}
```

https://github.com/facebook/graphql/issues/171 for context.

Is this an error or by design? Thanks in advance.

**Comment by vektah** [comment]
Looks like a bug. Go treats nils like empty arrays so it would be an easy one to make.

**Comment by rodrigo-brito** [comment]
Same problem here! Any update about it? :disappointed:
