### ISSUE TITLE
Add GraphiQL Browser IDE

### ISSUE THREAD

**Issue by syssam** [99designs/gqlgen#557]
Can I add GraphiQL Browser IDE?

**Comment by mathewbyrne** [comment]
We have a [graphqli playground](https://github.com/99designs/gqlgen/blob/master/handler/playground.go) handler you can mount in your application.

**Comment by syssam** [comment]
I know, GQLGEN provide the browser IDE, but I want to use https://github.com/graphql/graphiql, not https://github.com/prisma/graphql-playground.
It just my personal requirement.
So, may I add a function to provide new browser IDE?

**Comment by vektah** [comment]
We don't force you to use playground, its a separate package, you can use what you want.

If you want to share the code, push it up in its own repo, or PR to https://github.com/99designs/gqlgen-contrib. It doesn't need to be in core.
