### ISSUE TITLE
Optional list of values not generated as pointer

### ISSUE THREAD

**Issue by jakubknejzlik** [99designs/gqlgen#558]
### Expected Behaviour
given schema should generate:
```
type Car struct {
	Name *string `json:"name"`
}

type Owner struct {
	Cars  *[]*Car `json:"cars"`
	Cars2 *[]Car  `json:"cars2"`
	Cars3 []*Car `json:"cars3"`
	Cars4 []Car  `json:"cars4"`
}
```
### Actual Behavior
but the generated are not pointers for `cars`/`cars2`:
```
type Car struct {
	Name *string `json:"name"`
}

type Owner struct {
	Cars  []*Car `json:"cars"`
	Cars2 []Car  `json:"cars2"`
	Cars3 []*Car `json:"cars3"`
	Cars4 []Car  `json:"cars4"`
}
```

### Minimal graphql.schema and models to reproduce
```
type Owner {
  cars: [Car]
  cars2: [Car!]
  cars3: [Car]!
  cars4: [Car!]!
}

type Car {
  name: String
}
```

**Comment by jakubknejzlik** [comment]
The more problematic in our case is for mutations where we use "patch" mutations for example:
```
input UpdateOwner {
   carIDs: [ID!]
}

type Mutation {
   UpdateOwner(id: ID!, input: UpdateOwner)
}
```

Normally we would check if input.carIDs and do the update if it's not nil (replace values for relation). Now we receive empty array so it's impossible to distinguish between "don't update" and "set to empty array".

**Comment by mathewbyrne** [comment]
So I don't think we want pointers to slices.  What we probably want to just do is to distinguish in the response between a `nil` slice and an empty slice, which is tracked in #556.

With regard to your second comment, take a look at #505 where we are discussing the difference between `null` values and values that are not set.

**Comment by jakubknejzlik** [comment]
Ok, thanks for clarification.
