### ISSUE TITLE
unpredictable field types for generated models

### ISSUE THREAD

**Issue by MShoaei** [99designs/gqlgen#559]
`models_gen.go` created in [todo example](https://github.com/99designs/gqlgen/tree/master/example/todo) has both pointer type fields and value fields. How does the generator decides what kind of field to generate?

in my example below, generated `models_gen.go` is like this:
```go
type NewBot struct {
	IP *string `json:"ip"`
}
```
 which has a pointer value field.

the question is **How can I change this or control the behavior**?

### Minimal graphql.schema and models to reproduce

```graphql
# schema.graphql
schema {
  query: Query
  mutation: Mutation
}

type Bot {
  id: ID!
  ip: String
}

input NewBot {
  ip: String
}

type Query {
  bots: [Bot!]!
  bot(id: ID!): Bot
}

type Mutation {
  createBot(input: NewBot!): Bot!
}
```

```go
// models.go

type Bot struct {
	ID string
	IP string
}
```

**Comment by MShoaei** [comment]
looks like changing this 
```graphql
input NewBot {
  ip: String
}
```
to this
```graphql
input NewBot {
  ip: String!
}
```
makes ip a value field! 🤔
Can someone explain the reason for that?

**Comment by JulienBreux** [comment]
`ip: String` is nillable, no required. `ip: String!` not.
