### ISSUE TITLE
gqlgen@next disrespects config file

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#560]
### Expected Behaviour
Running `go run gqlgen/cmd.go -c gqlgen/gqlgen.yml` on gqlgen@latest works fine.
When using with gomodules, installing `next` with `go get github.com/99designs/gqlgen@next` and running `go run gqlgen/cmd.go -c gqlgen/gqlgen.yml` it should work too.

### Actual Behavior
`$ go run gqlgen/cmd.go -c gqlgen/gqlgen.yml` 
`unable to open schema: open schema.graphql: no such file or directory`

### Minimal graphql.schema and models to reproduce
-

Extra note: I noticed When I put the gqlgen.yml in the root dir, it works, even though explicitly setting the config file to `gqlgen/gqlgen.yml`.

project structure:
```
main.go
prisma/
  schema.graphql
gqlgen/
  gqlgen.yml
```

If a separate repro repo is needed, let me know and I'll provide one

**Comment by lpy-neo** [comment]
Bug seems to exist in this file:
github.com/99designs/gqlgen@v0.4.5-0.20190218060022-51266b8f7ab0/cmd/gen.go
line: 23

if configFilename := ctx.String("gen"); configFilename != "" {

**Comment by steebchen** [comment]
@lpy-neo I already sent a PR and fixed another issue, just see the reference above :P
