### ISSUE TITLE
Schema without query - question

### ISSUE THREAD

**Issue by Sach97** [99designs/gqlgen#562]
> https://github.com/99designs/gqlgen/blob/5c870a489da3eecd57b4152f0501b65cd682f4af/codegen/build.go#L147-L149

Hi guys,
Gqlgen is throwing "query entry point missing" because my schema does'nt have any query type. Can we get rid of this check or gqlgen needs it at some point?

**Comment by mathewbyrne** [comment]
From the [spec](https://facebook.github.io/graphql/June2018/#sec-Schema):

> The query root operation type must be provided and must be an Object type.

So your schema isn't valid GraphQL. Only mutations and subscriptions are optional.  What's the use-case for having no query root?

**Comment by Sach97** [comment]
I didn't know that. I'm schema stitching my go-graphql auth server with hasura-graphql and I only have mutations for sign-up, login, verifyToken etc. Thank's for the response I'll just put a hello world query then

**Comment by mathewbyrne** [comment]
Does this work?

```
type Query {
}
```

**Comment by Sach97** [comment]
Nope. Error : `expected at least one definition, found }`. Neither `type Query` which throws `OBJECT must define one or more fields.`

**Comment by mathewbyrne** [comment]
Ah right, yeah I guess it's still just a normal GraphQL type and needs a field to make sense.  I think you'll have to define something then.

**Comment by iamolegga** [comment]
Same issue, faced with this while doing federation: so I only need to extend existing remote types, but I don't need to expose any root level query

`skip_root_query_length_validation`or something, wdyt ?
