### ISSUE TITLE
Why does Int map to int and float to float64?

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#566]
It seems a bit inconsistent to me that Int maps to int and Float to float64. What's the reason behind this?

Float→float64 seems to follow the GraphQL spec to be double precision, but Int→int does not because the GraphQL spec says it should be 32 bits.

Personally, I'd prefer both values to map to int and float respectively, without any specific precision for the sake of simplicity.

**Comment by vektah** [comment]
Go doesn't have a `float` type, only `float32` and `float64`. See https://tour.golang.org/basics/11

**Comment by steebchen** [comment]
oops x)
