### ISSUE TITLE
Bad type name conversion

### ISSUE THREAD

**Issue by giter** [99designs/gqlgen#577]
### Expected Behaviour

With latest release v0.8.0 

`
input ITicket {
    otype: String!
}
`

=>

`
type ITicket struct {
	Otype    string  `json:"otype"`
}
`

### Actual Behavior
`
input ITicket {
    otype: String!
}`

=>
`
type Iticket struct {
	Otype    string  `json:"otype"`
}`

**Comment by vektah** [comment]
Fixed by #579

**Comment by vvakame** [comment]
@vektah my change can't handling this issue... 😿 
because, `ITicket` will split into `["ITicket"]` and it doesn't have commonInitialisms prefix.

**Comment by giter** [comment]
I created a new PR but this may cause some commonInitialisms tests fail
