### ISSUE TITLE
vendor not works when go generate ./...

### ISSUE THREAD

**Issue by exfly** [99designs/gqlgen#578]
### env
➜  gqlgen-bugs git:(master) go version   
go version go1.11.1 darwin/amd64

➜  gqlgen-bugs git:(master) dep version                                      
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false

gqlgen version:
    vendor: v0.7.2
    $GOPATH:  master 1968a7bcfff5a640b4fb80aecc485d404bf596e3

### Expected Behaviour

`gqlgen v0.7.2`, we can write a script like:
```
// +build ignore

package main

import "github.com/99designs/gqlgen/cmd"

func main() {
    cmd.Execute()
}
```
head of resolver.go
```
//go:generate go run scripts/gqlgen.go -v
...
```

we want to `go generate ./...` on fixed version of `gqlgen`. But it seems that the vendor is not working in my project.

### Actual Behavior

go generate ./... with `$GOPATH/src/github.com/99.../gqlgen`

### Minimal graphql.schema and models to reproduce

I will reproduce it later.

**Comment by mathewbyrne** [comment]
I'm not sure what's actually failing here. What output are you getting when running `go generate ./...`?

Regardless, I think we're unlikely to spend a whole lot of time fixing `0.7.*` issues at this point.  If you look at `0.8` we have reintroduced the `gqlgen` binary now that Go Modules does a better job of running the correct version of a binary for your module.  I'd recommend looking into whether updating it possible for your project.

**Comment by exfly** [comment]
sorry, I'll reproduce it later~ @mathewbyrne

**Comment by sprhawk** [comment]
@mathewbyrne Hi I'm using gqlgen v0.11.3, same issue when I use `go mod vendor` to save vendor packages locally, use `//go:generate go run github.com/99designs/gqlgen` recommended from "[Get Started](https://gqlgen.com/getting-started/#finishing-touches)" will fail as

> package github.com/99designs/gqlgen: no Go files in {my package}/vendor/github.com/99designs/gqlgen
> graph/resolver.go:3: running "go": exit status 1

**Comment by akhiljain23** [comment]
As a workaround I did `rm -rf vendor` then ran `go run github.com/99designs/gqlgen generate` and then vendor again

**Comment by neurocome** [comment]
> go run github.com/99designs/gqlgen generate



> As a workaround I did `rm -rf vendor` then ran `go run github.com/99designs/gqlgen generate` and then vendor again

thanks mate
