### ISSUE TITLE
Non deterministic behaviour in gqlgen - Possible race?

### ISSUE THREAD

**Issue by janflyborg** [99designs/gqlgen#581]
### Expected Behaviour

I'm expecting `gqlgen init` to give me the same output every time I run it, but it seems to give me a different output from time to time. 

I am using the latest version installed with `go get -u github.com/99designs/gqlgen` as of today.

### Actual Behavior
I have my API in specific folder ($GOPATH/src/api) and run the following bash snippet:

`janf@lnxjanf:::~/go/src/api$ rm * ; cp ~/controllers/schema.graphql . ; gqlgen init`

That means that gqlgen runs in a folder that is empty, apart from a schema.graphql file.

If I run this snippet a few times. I will either get the following output:
```
panic: DateTime was not found

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField.func1(0xc000130ab0, 0xc0002256c8)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/codegen/field.go:81 +0xac
github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc0002256c8, 0xc00011f680, 0xc000130ab0, 0xac4de0, 0xc00029d5c0)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/codegen/field.go:168 +0xbd6
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc0002256c8, 0xc00011f680, 0xc0003aa8c0, 0x0, 0x3, 0xc0006a4d60)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/codegen/field.go:64 +0x31d
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc0002256c8, 0xc0005e43c0, 0x9e8d35, 0x6, 0x0)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/codegen/object.go:72 +0x4d4
github.com/99designs/gqlgen/codegen.BuildData(0xc0001f40c0, 0xac4e60, 0xc0001125b0, 0x0)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/codegen/data.go:76 +0x395
github.com/99designs/gqlgen/api.Generate(0xc0001f40c0, 0xc000093938, 0x1, 0x1, 0xc0001ee368, 0x6)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/api/generate.go:37 +0x250
github.com/99designs/gqlgen/cmd.GenerateGraphServer(0xc0001f40c0, 0xa01dee, 0x10)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/cmd/init.go:75 +0xad
github.com/99designs/gqlgen/cmd.glob..func2(0xc0001fc160)
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/cmd/init.go:70 +0xc9
github.com/urfave/cli.HandleAction(0x929e00, 0xa294f8, 0xc0001fc160, 0xc000110600, 0x0)
	/home/janf/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0x9e705c, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa1020a, 0x1b, 0x0, ...)
	/home/janf/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x92f
github.com/urfave/cli.(*App).Run(0xc0001f0000, 0xc0000a0020, 0x2, 0x2, 0x0, 0x0)
	/home/janf/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x69b
github.com/99designs/gqlgen/cmd.Execute()
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/cmd/root.go:40 +0x224
main.main()
	/home/janf/go/pkg/mod/github.com/99designs/gqlgen@v0.8.0/main.go:8 +0x20
```

or this output for a few different types:
```
merging failed: unable to build object definition: connectToCloudPayload not found in typemap
Exec "go run ./server/server.go" to start GraphQL server
```

So it doesn't behave in a deterministic way. I'm aware of the issues with scalars recently introduced (https://github.com/99designs/gqlgen/issues/575), but this is probably another problem.

### Minimal graphql.schema and models to reproduce

Sorry. I cannot share that.

**Comment by janflyborg** [comment]
Or is it maybe a map that is visited in random order?

**Comment by atomicleads** [comment]
I'm having same issue and can't share my schema as well. But 100% sure schema is working fine on prev version 0.7.2

**Comment by janflyborg** [comment]
Same thing here. This exact schema worked in the previous version.

**Comment by vektah** [comment]
Is this still happening in 0.8.1?  I think https://github.com/99designs/gqlgen/pull/589 and https://github.com/99designs/gqlgen/pull/588 fixed the underlying bugs.

**Comment by janflyborg** [comment]
Just tried with v0.8.1 and so far I have not been able to reproduce it, so it's probably solved.
Thanks for that.
