### ISSUE TITLE
Defining a schema with recursive types is not possible

### ISSUE THREAD

**Issue by janflyborg** [99designs/gqlgen#586]
### Expected Behaviour

If a define a schema like this (which is valid GraphQL) and run gqlgen:

```
schema {
    query: Query
}

type Query {
     a: A
}

type A {
    b: B!
}

type B {
    a: A!
}
```

I would expect gqlgen to generate types in models_gen.go that contained pointers to the types A and B (in order to not define a recursive type in Go). 

Instead I get the following output in the 0.7.2 release:

```
/home/janf/go/src/api/models_gen.go:5:6: illegal cycle in declaration of A
/home/janf/go/src/api/models_gen.go:5:6: 	A refers to
/home/janf/go/src/api/models_gen.go:9:6: 	B refers to
/home/janf/go/src/api/models_gen.go:5:6: 	A
validation failed: couldn't load packages due to errors: api

```
### Actual Behavior

The generated model looks like this:

```
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type A struct {
        B B `json:"b"`
}

type B struct {
        A A `json:"a"`
}
```
Which compiles with an error:
`./models_gen.go:9:6: invalid recursive type B`

A temporary solution would be to change the schema to contain a pointer like this.
```
type A {
    b: B # b is now nullable, which breaks the recursive type definition
}
```
But that would change the semantics and since this is a valid way to define schemas in GraphQL it would be a good thing if use cases like this was supported. Maybe with a schema directive?

AFAIK there is no problems with recursions for queries like these since the consumer who is writing the query decides at what depth the recursion should stop (when he selects the attributes to query for).
Since the query is finite, so is the result.

### Minimal graphql.schema and models to reproduce
Please see above

**Comment by atomicleads** [comment]
possible dup of #585
