### ISSUE TITLE
allow for custom implementations of the @deprecated directive

### ISSUE THREAD

**Issue by gracenoah** [99designs/gqlgen#587]
### Expected Behaviour

I expect to be able to write a directive middleware for @deprecated that logs a warning every time a deprecated field is accessed.

### Actual Behavior

There's nothing in `DirectiveRoot` for the @deprecated directive.

### Minimal graphql.schema and models to reproduce
```
{
  query: String! @deprecated(reason: "no reason")
}
```

**Comment by vektah** [comment]
related to #584

**Comment by mathewbyrne** [comment]
Yeah, this is the use-case I was discussing with @vektah yesterday.  It's a case of not marking deprecated as a builtin directive, which will output it in the `DirectiveRoot`.  I wonder if this is something we could expose through config?

**Comment by swkumar** [comment]
Can builtin directives now be accessed through `DirectiveRoot`?

**Comment by thumphries** [comment]
Apologies for commenting on a closed issue; just leaving a note for those finding this issue in the future...

To get `Deprecated` into your `DirectiveRoot` for customisation I had to first set `skip_runtime` to false, like so:

```yaml
directives:
  deprecated:
    skip_runtime: false
```

(as of gqlgen v0.11.3)

**Comment by grzn** [comment]
with v0.17.55, it doesn't work.

it adds generated code do call the directive: 
```
		directive1 := func(ctx context.Context) (interface{}, error) {
			reason, err := ec.unmarshalOString2ᚖstring(ctx, "Use tagsV2 instead")
			if err != nil {
				var zeroVal []string
				return zeroVal, err
			}
			if ec.directives.Deprecated == nil {
				var zeroVal []string
				return zeroVal, errors.New("directive deprecated is not implemented")
			}
			return ec.directives.Deprecated(ctx, obj, directive0, reason)
		}
```

but it doesn't add `Deprecated` to the DirectiveRoot, so the code doesn't compile.
