### ISSUE TITLE
Pass schema URL in gqlgen.yml file

### ISSUE THREAD

**Issue by wildlifehexagon** [99designs/gqlgen#598]
I would like to provide a URL to my GraphQL schema (i.e. a file hosted on GitHub) rather than a local path in my `gqlgen.yml` file. Do you have any plans to implement this?

Something like:
```
schema:
 - http://....
```

**Comment by mathewbyrne** [comment]
We could do this, but it does lead down a bit of a rabbit-hole, as users then want authentication mechanisms and different protocols.  I would also recommend committing the schema along with your gqlgen project, as you then have a record of what you generated against, and can easily reproduce in CI for example to validate that all changes have been generated.

**Comment by JulienBreux** [comment]
Please use `bash` :

```gen.sh
curl|wget ...

go generate ./...
```

No?

**Comment by mathewbyrne** [comment]
After some discussion we've decided this isn't the way we want to support remote schemas.  #5 tracks schema stitching.

**Comment by wildlifehexagon** [comment]
I ended up finding a workaround for this. I updated the `gqlgen.go` script to download our schema from GitHub first, then remove the temporary files after the main generate command executes. A little bit of extra work, but it accomplishes exactly what I was wanting to do.
