### ISSUE TITLE
Interface name cannot start with two uppercase characters

### ISSUE THREAD

**Issue by Dispersia** [99designs/gqlgen#601]
### Expected Behaviour
 Generates correctly
### Actual Behavior
 Get error in generated.go:

>  Impossible type switch case: *obj (type Ibar) cannot have dynamic type *Bar (wrong type for IsIbar method)
>            have IsIBar()
>            want IsIbar()

### Minimal graphql.schema and models to reproduce
```
type Query {
    bar(id: ID!): Bar
}

type Bar implements IBar {
    id: ID!
    someField: Int!
}

interface IBar {
    id: ID!
}
```

I see https://github.com/99designs/gqlgen/issues/583 which was closed, and I'm in 0.8.1 so should have it, but I get the above throw. I see the comment on the commit, but I don't know if that means this isn't something that's supported (go caseifier to name directly), as I am not aware of what caseifier does

**Comment by vektah** [comment]
I think this will be fixed in 0.8.2 by https://github.com/99designs/gqlgen/pull/591
