### ISSUE TITLE
Not fully filling an object with its interface silently breaks GraphQL Playground

### ISSUE THREAD

**Issue by Dispersia** [99designs/gqlgen#602]
### Expected Behaviour
 GraphQL Playground can resolve schema when there is an interface
### Actual Behavior
 GraphQL Playground spins forever, and never displays the available schema
### Minimal graphql.schema and models to reproduce
```
type Query {
    bar(id: ID!): Bar
}

type Bar implements BarInterface {
    someField: Int!
}

interface BarInterface {
    id: ID!
}
```

 I am not sure if this is a GraphQL Playground problem or a gqlgen problem with how it responds. If it is a GraphQL Playground problem, is there any known workarounds? I googled around but didn't see any fixes. Thanks

EDIT: After further testing, download GraphQL Playground from prisma, and the desktop client they provide both work, so this looks like its an issue with the default GraphQL Playground client that's served

EDIT 2: So, found the issue. If you don't add all fields from the interface (in this case id:ID!) then it silently fails. Later versions of GraphQL Playground still loads but throws javascript errors at you. Would it be useful for the generator to give a warning to let you know when you don't fully implement an interface?

Sidenote: is there a reason it uses a tagged older version of GraphQL Playground? Seems strange to use latest of this repos version, but not latest of theirs, I feel this goes against the general go mantra

**Comment by vektah** [comment]
Some great notes here :)

Looks like there is a bunch of missing validation - https://github.com/vektah/gqlparser/pull/97
