### ISSUE TITLE
Automatically Infer Existing Models from Pattern

### ISSUE THREAD

**Issue by abraithwaite** [99designs/gqlgen#621]
Hello!  Thanks for the great library!

Currently it's possible to specify existing models such that gqlgen does not generate it's own.  It would be nice if I could point gql to a package and if the same type exists in that package, use it.

Of course, an explicit declaration would override the inferred value.

Additionally, the config could be updated to allow for ignoring types if a pattern is found but you want to generate the type anyway.

Right now I find myself adding lines to the config for every model which I've already written (since I've got a lot of additional fields and tags on the model).

WDYT?

**Comment by vektah** [comment]
A module search path would reduce a lot of the wiring :+1:

**Comment by akashbdj** [comment]
Hi @vektah @mathewbyrne,
Thanks for the awesome library!

I'm also facing this problem of manually pointing to types in config file even though they are already present in the package. I'd love the enhancement that @abraithwaite mentioned. Has someone already started working on it?

@abraithwaite Did you find any workaround for it?

Thanks for your time,
Akash

**Comment by abraithwaite** [comment]
I didn't find a workaround.  The side project using this is on hold. :-)

**Comment by akashbdj** [comment]
Oh! mine is not a side project. 😩

When I run `gqlgen`, it suggests me that it found compatible types in the package but doesn't use it for some reason. It's already scanning the package. I hope this feature won't require a lot of changes.

<img width="1668" alt="Screen Shot 2019-06-04 at 9 40 03 PM" src="https://user-images.githubusercontent.com/7085282/58895391-69290300-8711-11e9-97be-c0e5a94d0ed6.png">

**Comment by malekjaroslav** [comment]
This would be great! I am using Prisma and have to wire every single model that is generated by it, the `.gqlgen.yml` is getting very long!
