### ISSUE TITLE
Connected time for subscriptions through playground

### ISSUE THREAD

**Issue by divya1c** [99designs/gqlgen#623]
Hi! I am trying to implement subscriptions on graphql, using gqlgen. I observed that subscriptions functionality works fine, but the connection between my playground and my server gets cut every ~30 seconds. Is this expected behaviour? Is there a config for defining this connection time? Thanks!

### Expected Behaviour
Web socket connection should persist between playground and server.

### Actual Behaviour
Connection keeps breaking off every ~30 seconds.

### Minimal graphql.schema and models to reproduce
Will make a reproducible example if this is not the expected behaviour.

**Comment by vektah** [comment]
Its not expected, there should even be keepalives maintaining the connection in 0.8+.

**Comment by vektah** [comment]
Feel free to reopen this if you track it down, we aren't seeing it on our severs.
