### ISSUE TITLE
Possible to use an interface type for input?

### ISSUE THREAD

**Issue by sdalezman** [99designs/gqlgen#625]
Not really sure if this is possible with gqlgen, but we have a filter type that we want to include in gqlgen to allow our front-end to pass in complex filtering behaviors

``` golang
type Filter struct {
	FieldName  string
	Expression FilterExpression
	Val        interface{}
	Filters    []Filter
}
```

This filter is embedded as a list in our graphql query which allows our front-end to express arbitrary complex query behaviors

``` graphql
input Filter {
    fieldName: String!
    expression: FilterExpression!
    val: [?? - type]
    filters: [Filter!]
}
```

but I'm not 100% sure how to get an `interface{}` type to map correctly. The interface is needed for our given use case bec the front-end can pass in a list of strings, number, dates, single numbers, booleans, null values etc. 

We've developed a work around by having a custom type to map the values, but it feels like a hacky abstraction. Was curious if it's possible to use an `interface{}` type in an input directly?

**Comment by mathewbyrne** [comment]
This is something that's been discussed as part of the GraphQL specification for a while, but currently is not possible. See https://github.com/facebook/graphql/issues/488 . There are a number of reasons why, including that there isn't an equivalent for `__typename` for inputs, so it can lead to ambiguous situations when trying to discriminate a type from the wire.

So until there's some resolution there we wont be adding it to gqlgen, and unfortunately you'll need a workaround.  I've seen a variety of solutions to this, depending on what the schema is trying to express, but none of them feel particularly great.  I think your mentioned solution sounds reasonable for the meantime.
