### ISSUE TITLE
Allow defining empty types

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#630]
Empty types should be allowed. I'm not sure if the GraphQL spec allows this, but I think it makes sense when you `extend` types. 

For example, when I have a complex schema and split my definitions into separate packages/files, I may want to do the following:

```graphql
# query/query.graphqls
type Query {} # not allowed :(
```

```graphql
# query/user/user.graphqls
extend type Query {
  user: User!
}

type User {
  name: String
}
```

The exact error message is `modelgen: query/query.graphqls:1: Cannot extend type Query because it does not exist.`

[graphql-js also allows empty types](https://github.com/graphql/graphql-js/issues/937).

**Comment by vektah** [comment]
From the [current](https://facebook.github.io/graphql/June2018/#sec-Objects) and [draft](https://facebook.github.io/graphql/draft/#sec-Objects) specs

> An Object type must define one or more fields.

That issue has no merged PRs and people saying that it *doesnt* work in graphql-js

Lets wait for https://github.com/facebook/graphql/issues/568. If you are championing this please have a read of the [graphql spec contribution guidelines](https://github.com/facebook/graphql/blob/master/CONTRIBUTING.md). I cant imagine much resistance to this, it should go through pretty quickly.

**Comment by steebchen** [comment]
Alright, makes sense

**Comment by steebchen** [comment]
Just as an addition if other users visit this issue: using `type Mutation` without the braces works. Didn't know about this until now!

**Comment by leventov** [comment]
@steebchen I still get an error:
```
OBJECT must define one or more fields.
```
gqlgen 0.11.3
