### ISSUE TITLE
Include files recursively

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#631]
I can include multiple schema files:

```yaml
schema:
  - "*.graphqls"
```

However, that doesn't work recursively.

When I spread my schema into multiple files, I currently have to import them as follows:

```yaml
schema:
  - "api/*.graphqls"
  - "api/query/*.graphqls"
  - "api/mutation/*.graphqls"
  - "api/mutation/auth/*.graphqls"
```

I would like to import them recursively:

```yaml
schema:
  - "api/**/*.graphqls"
```

It's also a simpler way to split the schema into multiple files instead of #6 in my opinion.

**Comment by vektah** [comment]
Sounds good to me, #6 is useful for different reasons (remapping types from remote schemas) but its a long way off.
