### ISSUE TITLE
Make DirectiveRoot an interface

### ISSUE THREAD

**Issue by robojones** [99designs/gqlgen#632]
### Expected
The **DirectiveRoot struct should be an interface** like the resolvers are.
Since the DirectiveRoot is currently generated as a struct, I need to implement all methods separately and pass them to the struct when constructing it.
This is a real pain because the output of gqlgen doesn't export their types.
I would create my own struct type, but that is not possible because DirectiveRoot is a struct.

I would expect the generated code to look like this:
```go
type DirectiveRoot interface {
  Foo (ctx context.Context, obj interface{}, next graphql.Resolver, bar *string) (res interface{}, err error)
}
```
### Actual Behaviour
```go
type DirectiveRoot struct {
  Foo func(ctx context.Context, obj interface{}, next graphql.Resolver, bar *string) (res interface{}, err error)
}
```
### Minimal graphql.schema and models to reproduce
```graphql
directive @foo(bar: String) on FIELD_DEFINITION | QUERY
```

**Comment by mathewbyrne** [comment]
From memory, the reason that it was made an struct instead of an interface was to avoid requiring an implementation for every directive if the directive is a no-op at runtime.

I can definitely see your point, and maybe it's the right way to go in a future release.  However I think we would also want a way for plugins to provide an implementation for a directive that would prevent it from being part of the `DirectiveRoot` interface (somewhat related to #587).

**Comment by robojones** [comment]
Even if it was an interface, it would be easy for plugins to provide an implementation.
```graphql
directive @foo(bar: String) on FIELD_DEFINITION | QUERY
directive @baz(something: String) on MUTATION
```
This schema would generate an interface like this:
```go
type DirectiveRoot interface {
  Foo (ctx context.Context, obj interface{}, next graphql.Resolver, bar *string) (res interface{}, err error)
  Baz (ctx context.Context, obj interface{}, next graphql.Resolver, something *string) (res interface{}, err error)
}
```

the `@baz` directive in this example could be implemented by a plugin like this:
```go
type BazPlugin struct {}
func (*BazPlugin) Baz (
  ctx context.Context,
  obj interface{},
  next graphql.Resolver,
  something *string
) (res interface{}, err error) {
  // ...
}
```
and my own `DirectiveRoot` implementation would look like this:
```go
type MyDirectiveRoot {
  *BazPlugin
}
func (*MyDirectiveRoot) Foo (
  ctx context.Context,
  obj interface{},
  next graphql.Resolver,
  bar *string
) (res interface{}, err error) {
 // ...
}
```
`MyDirectiveRoot` would satisfy the `DirectiveRoot` interface.

**Comment by mathewbyrne** [comment]
I don't think that is a suitable way for plugins to provide an implementation.  Ideally it wouldn't require you to implement yourself (even with embedding) and would simply not be included in the `DirectiveRoot` output.

**Comment by robojones** [comment]
You're right. It's much simpler when plugin implementations are not included in the DirectiveRoot.
