### ISSUE TITLE
Using complex types as query arguments fails

### ISSUE THREAD

**Issue by pwmcintyre** [99designs/gqlgen#636]
I'm having trouble finding this in the graphql docs, so maybe this is simply not a thing you can do in GraphQL?

### Expected Behaviour
```go
func (r *queryResolver) Search(ctx context.Context, filter Filter) (*graph.Results, error) {
	fmt.Fatalf("not implemented")
}
```

### Actual Behavior
`gofmt failed on generated.go: .../generated.go:754:24: expected ')', found ',' (and 1 more errors)`

### Minimal graphql.schema and models to reproduce
```graphql
schema {
  query: Query
}

type Query {
  search(filter: Filter!): Results
}

type Filter {
    text: String
    since: String
}

type Results {
    thing: String
}
```

**Comment by vektah** [comment]
you cant use a `type` as an argument, you need to use:
```
# NOTE input not type!
input Filter {
    text: String
    since: String
}
```

you're also running an old version of gqlparser, otherwise you would get a better error message.

```
dep ensure -update github.com/vektah/gqlparser
```
