### ISSUE TITLE
[0.8.2] gqlgen init error

### ISSUE THREAD

**Issue by sharkyze** [99designs/gqlgen#638]
### Actual Behavior
I was following the instructions in the getting started when I got the following error:
```
> go run github.com/99designs/gqlgen init                                                                                                                                                        
go: downloading github.com/99designs/gqlgen v0.8.2
go: extracting github.com/99designs/gqlgen v0.8.2
merging failed: required package was not loaded: github.com/99designs/gqlgen/graphql.Boolean
Exec "go run ./server/server.go" to start GraphQL server
```
The command only generated the following files:
- gqlgen.yml
- models_gen.go

I am using go1.12, go mod and gqlgen v0.82

### Expected Behaviour
for the command to run and generate the following files:
- gqlgen.yml
- generated.go
- models_gen.go
- resolver.go
- server/server.go

**Comment by mathewbyrne** [comment]
I'm unable to reproduce with the same setup you described:

```
$ go run github.com/99designs/gqlgen init
go: finding github.com/99designs/gqlgen v0.8.2
go: downloading github.com/99designs/gqlgen v0.8.2
go: extracting github.com/99designs/gqlgen v0.8.2
Exec "go run ./server/server.go" to start GraphQL server
```

**Comment by sharkyze** [comment]
thank you for your answer. Do you have any tips on how to debug this ?

I tried deleting all booleans from my schema and got the same error for strings:
```
$ go run github.com/99designs/gqlgen init                                                                                                                                                                 
merging failed: required package was not loaded: github.com/99designs/gqlgen/graphql.String
Exec "go run ./server/server.go" to start GraphQL server
```

Here is my god.mod
```
module gitlab.com/<company>/graphql

go 1.12

require (
	cloud.google.com/go v0.37.1
	github.com/99designs/gqlgen v0.8.2 // indirect
	github.com/gorilla/mux v1.6.1
	github.com/rs/cors v1.6.0
	github.com/sirupsen/logrus v1.4.0
)
```

**Comment by mathewbyrne** [comment]
Yeah you will probably run into this issue for all built-in types. 🤔 I'm not super familiar with Go Modules yet, so I'm not sure why your gqlgen require is listed as `indirect`, perhaps that is part of the problem here? @vektah any thoughts?

**Comment by sharkyze** [comment]
I tried removing the `indirect` manually and re ran `init` but still the same issue. I will try to investigate more on my side. I keep you posted if find the problem.

**Comment by sharkyze** [comment]
When creating a new folder and following the instructions in the getting started section everything works perfectly. But when trying to follow the getting started section with existing go code in the directory I still have the same error.

I am closing this issue since I now generate my code in am empty directory and then copy it to my project directory.

**Comment by rapthead** [comment]
I have same issue if project folder ends with ".go" e.g. "myproject.go"

**Comment by echorohit** [comment]
I am still facing this issue

`✘  ~/perpro/go-graphql-demo  go run github.com/99designs/gqlgen init
merging failed: required package was not loaded: github.com/99designs/gqlgen/graphql.Boolean
Exec "go run ./server/server.go" to start GraphQL server
 ~/perpro/go-graphql-demo  go mod init $GOPATH/github.com/echorohit/go-graphql-demo
go: creating new go.mod: module /Users/rohitchoudhary/go/github.com/echorohit/go-graphql-demo
 ~/perpro/go-graphql-demo  go run github.com/99designs/gqlgen init                 
merging failed: required package was not loaded: github.com/99designs/gqlgen/graphql.Boolean
Exec "go run ./server/server.go" to start GraphQL server
 ~/perpro/go-graphql-demo  `
