### ISSUE TITLE
Non nullable mutation

### ISSUE THREAD

**Issue by sdalezman** [99designs/gqlgen#641]
### Expected Behaviour

Non nullable mutations shouldn't be defined as pointers 

### Actual Behavior

Non nullable mutations are being defined as pointers in the mutation interface

### Minimal graphql.schema and models to reproduce

```graphql
type Mutation {
    team(input: TeamInput!): Team!
}

input TeamInput {
    name: String!
}

type Team {
    id: ID!
    name: String!
}

```
 produces the following generated resolver
``` golang
type MutationResolver interface {
	team(ctx context.Context, input TeamInput) (*Team, error)
}
```

I would have expected it to produce 
```golang
type MutationResolver interface {
	team(ctx context.Context, input TeamInput) (Team, error)
}
```

This can be problematic for all consumers of the api if it can return a null value when it was specified in the schema as not null. 

This might be the expected behavior, but haven't seen it documented anywhere (although the getting started docs define the mutation as returning a non nullable type)

**Comment by sdalezman** [comment]
I should say this happens when upgrading to >=`0.8.1`, prior to this it didn't generate pointers in the mutation

**Comment by mathewbyrne** [comment]
See #375 — all resolvers now return pointers.  We explicitly check for nullability after the resolver has run and throw an error if `nil` was returned for a non-nullable field.

I think you're right that docs might need updating around this change.
