### ISSUE TITLE
WebSockets - how large should the channel buffer be?

### ISSUE THREAD

**Issue by tgwizard** [99designs/gqlgen#642]
There is currently no documentation about websockets on https://gqlgen.com, but there's this example: https://github.com/99designs/gqlgen/blob/master/example/chat/resolvers.go. I think the example suffices quite well for documentation, except around the returned channel. In the example the buffer size is set to 1. Why 1? Are there cases where the buffer size should be larger?

Perhaps this could be added to a docs page about websockets, along side with any solution to https://github.com/99designs/gqlgen/issues/259.

**Comment by vektah** [comment]
It could be bigger if you want more buffering, but I would recommend against using 0 in because it requires the writer and marshaler in separate goroutines which I dont think will always be the case.

**Comment by tgwizard** [comment]
Thanks. Is it affected at all by how quickly the data can be put on the underlying websocket connection, so that slow clients might be a factor?

**Comment by vektah** [comment]
Nah, low level network buffers for that down in the http server.
