### ISSUE TITLE
$go get github.com/99designs/gqlgen command error

### ISSUE THREAD

**Issue by conanchen** [99designs/gqlgen#643]
### Expected Behaviour
install gqlgen sucessfully 
### Actual Behavior
install gqlgen failed

### env
1. window7
2.  cmd> go version
       go version go1.12.1 windows/amd64
3. cmd> go get github.com/99designs/gqlgen
   # github.com/99designs/gqlgen/codegen/config
..\..\99designs\gqlgen\codegen\config\binder.go:31:8: e.Kind undefined (type error has no field or method Kind)
..\..\99designs\gqlgen\codegen\config\binder.go:31:17: undefined: packages.ListError

**Comment by mtibben** [comment]
Try `GO111MODULE=on go get github.com/99designs/gqlgen`

**Comment by mtibben** [comment]
Or on windows it might be something like this?
```
set GO111MODULE=on
go get github.com/99designs/gqlgen
```
