### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by ravilution** [99designs/gqlgen#645]
Hi, I am a little confused. Is there anything I will have to do additionally inside the resolver functions to achieve concurrency? I come from the NodeJS background of async-await. If I am correct `gqlgen` handles concurrency as part of the generated code. Can you please confirm? If I have to do anything, can you please share a sample concurrency-hello-world?

**Comment by mathewbyrne** [comment]
Resolver functions are called concurrently, there's nothing additional you need to do to get this behaviour.
