### ISSUE TITLE
using sqlboiler, null.string fields in structs, field resolvers created

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#646]
I have this table:

```sql
CREATE TABLE "user_profiles" (
  "id" INT NOT NULL,
  "user_id" int NOT NULL,
  "username" text,
  "img" text,
)
```

SQLBoiler is generating this entity:

```go
import "github.com/volatiletech/null"

type UserProfile struct {
	ID        int
	UserID    int
	Username  null.String
	Img       null.String
}
```

My `schema.graphql`:

```graphql
type User{
    id : ID!
    userProfile : UserProfile!
}

type UserProfile{
    username : String
    img : String
}
```

My `gqlgen.yml`:

```yml
UserProfile:
    model: project/entities.UserProfile
```

### Expected Behaviour

I thought `gqlgen` must generate just:

```go
func (r *userResolver) UserProfile(ctx context.Context, obj *entities.User) (*entities.UserProfile, error) {
```

### Actual Behavior

`gqlgen` now generates also:

```go
func (r *userProfileResolver) Username(ctx context.Context, obj *entities.UserProfile) (*string, error) {
	panic("not implemented")
}
func (r *userProfileResolver) Img(ctx context.Context, obj *entities.UserProfile) (*string, error) {
	panic("not implemented")
}
```

and in logging during generation:

```log
String has type compatible with github.com/volatiletech/null.String
String has type compatible with github.com/volatiletech/null.String
```

If I use this in `gqlgen.yml`:

```yml
String:
  model:
    - github.com/99designs/gqlgen/graphql.String
    - github.com/volatiletech/null.String
```

it works (doesn't generate Username and Img resolvers) but something is wrong in `gqlgen_generated.go` at runtime:

```error
gqlgen_generated.go:3041:2: not enough arguments to return
gqlgen_generated.go:3041:11: ec.unmarshalInputString undefined (type *executionContext has no field or method unmarshalInputString)
gqlgen_generated.go:3048:11: ec._String undefined (type *executionContext has no field or method _String)
```

**Where am I doing wrong?**

**Comment by mathewbyrne** [comment]
You will need to implement a custom scalar to `null.String` — [take a look at our documentation on custom scalars for third party types](https://gqlgen.com/reference/scalars/#custom-scalars-with-third-party-types) for how to do this.

We could potentially be better at detecting that your type mapping wont work at runtime and not generate invalid code.

**Comment by frederikhors** [comment]
@mathewbyrne oh, thanks a lot for the hint.

I have read but I am too inexperienced to be able to create one myself.

How can I create a custom scalar for `null.String`? In the `Unmarshal` part what can I return? Maybe `nil`?

Do you have a nullable string scalar already?

**Comment by frederikhors** [comment]
@mathewbyrne I have made progress, but something is still not entirely clear to me.

_As soon I understand and solve the problem I can write a small Wiki for newbies like me._

I wrote this:

```go
package graphql

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/volatiletech/null"
	"io"
	"strconv"
)

func MarshalMyNullString(ns null.String) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		if !ns.Valid {
			_, err := w.Write([]byte("null")) // Is this correct?
			DieIfErr(err)
		}
		_, err := io.WriteString(w, strconv.Quote(ns.String))
		DieIfErr(err)
	})
}

func UnmarshalMyNullString(v interface{}) (null.String, error) {
	
	// What to do here?

	// return v.(null.String), nil
}
```

**TWO QUESTIONS**:

- Is `Marshal()` correct and without performance problems?

- As I read that `Unmarshal()` is only used if the scalar appears as an input (right?):

  - What I can check there?
  - I need to use `v interface{}`?
  - Can it ever be that my input model is an object with `null.String` fields?

Maybe I don't understand the point entirely here, but I'm close, @vektah.

Thanks a lot and please appreciate my commitment.

**Comment by vektah** [comment]
> Is Marshal() correct and without performance problems?

Probably for most cases, but there are some fairly sublte differences between strconv.Quote and valid json strings. Would probably recommend just casing and calling the [default string implementation](https://github.com/99designs/gqlgen/blob/master/graphql/string.go#L11).

```go
func MarshalMyNullString(ns null.String) graphql.Marshaler {
	if !ns.Valid {
		// this is also important, so we can detect if this scalar is used in a not null context and return an appropriate error
		return graphql.Null  
	}
	return graphql.MarshalString(ns.String)
}
```

**Comment by mathewbyrne** [comment]
Hopefully @vektah's response solves your issue. I'm going to close this out.

**Comment by frederikhors** [comment]
@mathewbyrne yes, thanks. Amazing, gqlgen is a stellar project! :)

@vektah, you mean `return null.String{String: s}, err` instead of `return null.String{Value: s}, err`, right?

**Comment by RichardLindhout** [comment]
@frederikhors How did you workaround this?

**Comment by RichardLindhout** [comment]
I just let gqlgen generate pure models and I'm generating a custom convert plugin for it which generates a convert file.

It's work in progress, and I work on this when I have some spare time
https://github.com/web-ridge/gqlgen-sqlboiler

**Comment by RichardLindhout** [comment]
<img width="745" alt="Schermafbeelding 2019-09-24 om 23 00 56" src="https://user-images.githubusercontent.com/6492229/65550136-33f22c00-df1f-11e9-89ae-151713a2c375.png">

**Comment by RichardLindhout** [comment]
It's more advanced right know and can create pure converts from boiler to gqlgen if the name and type are the same thing (e.g. *string and null.String)
![Schermafbeelding 2019-11-08 om 16 37 35](https://user-images.githubusercontent.com/6492229/68488784-16b2bc00-0246-11ea-86e3-a9a71dcee6a3.png)

![Schermafbeelding 2019-11-08 om 16 48 37](https://user-images.githubusercontent.com/6492229/68489558-a3aa4500-0247-11ea-9317-9aeff658877a.png)
