### ISSUE TITLE
How can i get query param in raw graphql

### ISSUE THREAD

**Issue by exfly** [99designs/gqlgen#659]
### What happened?
```graphql
{
   todo(id: "some_id"){
       id
    }
}
# or 
query todoq($id:ID!){
   todo(id: $id){
       id
    }
}
```

I want to get query/mutation param("some_id" or id in query param), How can I do that?

### versions
 - `gqlgen version`: 0.8.1
 - `go version`: 12
 - dep or go modules: go mod

**Comment by deepnirmal** [comment]
+1
