### ISSUE TITLE
Custom Error Type

### ISSUE THREAD

**Issue by jonatasbaldin** [99designs/gqlgen#660]
I need to return a custom error message for backward compatibility with older systems, where the `extension` field was not implemented.

The end result of what I need to return in an error situation is:

```
{
  "errors": [
    {
      "message": "failed",
      "path": [
        "myPah"
      ],
	  "extensions": {
        "code": "not_found"
      }
	  "code": "failed_code" # <- this is what I need to add
    }
  ],
  "data": null
}
```

As you can see, I'm adding the `code` inside `extensions`, but I really need it as a root field of the `errors` object.

I took a look into [the errors documentation](https://gqlgen.com/reference/errors/) but I couldn't understand how to do this (or if this is even possible).

Can someone help me around?

**Comment by mathewbyrne** [comment]
I don't believe this is possible; our current error presenter expects a `*graphql.Error` returned.  I'm not sure allowing this to be entirely custom makes sense, but I suppose it could be refactored to be some sort of error interface, but the spec is clear on the shape of errors.

Another work-around you might consider could be doing this transformation as a HTTP middleware and modify the response after GraphQL.

**Comment by jonatasbaldin** [comment]
Thanks! I'll try that tomorrow :)

**Comment by jonatasbaldin** [comment]
I've tried a bunch of things in the Gin middleware space, but couldn't do it :(

The [ErrorPresenter](https://gqlgen.com/reference/errors/#hooks) also expects a `*graphql.Error`, so I couldn't use it :(

For now, we will go the right way with using only the extensions, but it would be nice to be able to customize the error – even if that's outside of the spec.

If you have any ideas on that, please let me know.

For now, I'll close this.
