### ISSUE TITLE
Filter for sub type missing

### ISSUE THREAD

**Issue by gigo1980** [99designs/gqlgen#661]
## Given
I have the Following schema, minified for this request.

```
schema {
    query: Query
    mutation: Mutation
}


type Group{
    id: ID!
    active: Boolean!
    owners(filter: FilterOwners): [GroupOwner!]!
}

type GroupOwner{
    accountId: ID!
    createdAt: String!
    updatedAt: String!
    active: Boolean!
}

input FilterGroups{
    active: Boolean
    customerId: ID
}

input FilterOwners{
    active: Boolean
}

type Query {
    groups(filter: FilterGroups): [Group!]!
    group(id: ID!): Group
}
```

What i whant, i should have an resolver for the owners in the Group type.

## My Question
On Generation I only get something like the following method signature.
```
func (r *groupResolver) Owners(ctx context.Context, obj *Group) ([]GroupOwner, error) {
```

But i need also the FilterOwners inside.

What does i have to do?

**Comment by vektah** [comment]
I cant see anything wrong with your example. Did the interfaces in the generated output get updated?

Please be aware that gqlgen currently doesn't update the `resolvers.go` if it exists, thats up to you.
