### ISSUE TITLE
Error "float64 is not an int"

### ISSUE THREAD

**Issue by Rustavil** [99designs/gqlgen#664]
I ran into a small problem. 
For example, I created a simple graphql scheme.
```
type Value {
  id: Int
}
input ValueInput {
  id: Int
}

type Query {
  get: Value
}
type Mutation {
  put(input: ValueInput!): Value!
}
```

When I execute the query:
```
mutation {
  put(input: {
    id:10
  }) {
    id
  }
}
```
I get the result of success.

But, if run next query:
```
mutation put($value: ValueInput!) {
  put(input: $value) {
    id
  }
}
```

with variable:
```
{
  "value": {
    "id":10
  }
}
```
Then receive **"float64 is not an int"** message.

### versions
 - v0.8.3
 - go1.12.1
 - go modules

**Comment by vektah** [comment]
Weird, are you running a custom transport? Numbers coming in from the standard transport (`handler`) should be json.Numbers.

**Comment by Rustavil** [comment]
@vektah No. I'm use standard http handler implementation

**Comment by parsnips** [comment]
>Weird, are you running a custom transport? Numbers coming in from the standard transport (handler) should be json.Numbers not float/int.

Is this in a graphql spec? This definitely violates the principal of least surprise.

**Comment by shadowera** [comment]
I met the same problem, but I don't know what's wrong. Can you share how you solved it?

**Comment by shadowera** [comment]
oh , i also find my mistake..

**Comment by lexyehia** [comment]
What is the solution to this? I'm having the same issue...

**Comment by shadowera** [comment]
For my case , changing my json variables from 
```
{
  "value": {
    "id":10
  }
}
```
to 
```
{
  "value": {
    "id":"10"
  }
}
```
can solve it . 
The root cause was that when I tried to unmarshal the variable json to a map[string]interface{}, the json lib will change every number type to float64 .
```var p map[string]interface{}
		err := json.Unmarshal([]byte(*h.req.Variables), &p)
```

**Comment by lexyehia** [comment]
I'm having that same issue, I feel like switching to String isn't the right solution in all cases, if my schema says `Int` and my resolver expects `int`, why isn't gqlgen not parsing the json number into int?
