### ISSUE TITLE
gqlgen is confused when the configured model type is a string

### ISSUE THREAD

**Issue by MichaelMure** [99designs/gqlgen#670]
### What happened?

In [this PR](https://github.com/MichaelMure/git-bug/pull/113) for my project, there is a `Label` type in the schema, mapped to a `Label` go type, which is also a `string`. In this case, gqlgen is confused and return the data is if it was a scalar:

the go type:
```
type Label string
```

relevant part of the schema:
```graphql
"""Label for a bug."""
type Label {
    """The name of the label."""
    name: String!
    """Color of the label."""
    color: Color!
}
```

query:
```graphql
{
  defaultRepository {
    allBugs(first: 1) {
      nodes {
        labels {
          name
          color {
            R
            G
            B
          }
        }
      }
    }
  }
}
```

result:
```json
{
  "data": {
    "defaultRepository": {
      "allBugs": {
        "nodes": [
          {
            "labels": [
              "Core",
              "RFC"
            ]
          }
        ]
      }
    }
  }
}
```

### What did you expect?

The data should have the same shape than the query. Color should be present as well.

### versions
 - `gqlgen version`: 0.8.3
 - `go version`? go1.11.6
 - dep or go modules? dep

**Comment by mathewbyrne** [comment]
I'm not sure I understand. Why have you mapped a GraphQL object type to a Go scalar?

**Comment by MichaelMure** [comment]
Because it make sense in my project. A label is no more than a string, but in go I can still attach some function on it like the color (computed from the string). Having a struct hold a string is quite ackward.

**Comment by mathewbyrne** [comment]
Sure I understand that part.  I mean why have you explicitly mapped it in `gqlgen.yml`?  How can gqlgen know how to transform your Go string into a GraphQL object?

**Comment by MichaelMure** [comment]
Sorry I forgot that part in the issue, but I mapped to the `Label` type, not `string`. I feel like that should work.

**Comment by mathewbyrne** [comment]
Ah ok I understand your problem now, so this looks like a bug to me if it's generating you the Label resolvers, but returning the scalar value before hitting them.

**Comment by vektah** [comment]
@MichaelMure could you take a look over #706 and see if you can reproduce this issue in a test?

**Comment by MichaelMure** [comment]
@vektah as my initial bug report was about a mapping to a string,I tried that (https://github.com/MichaelMure/gqlgen/tree/mapping-primitive, feel free to pull).

It's failing with:
```
=== RUN   TestPrimitiveStringObjects
=== RUN   TestPrimitiveStringObjects/can_fetch_value
panic: 2 error(s) decoding:

* 'PrimitiveStringObject[0]' expected a map, got 'string'
* 'PrimitiveStringObject[1]' expected a map, got 'string' [recovered]
	panic: 2 error(s) decoding:

* 'PrimitiveStringObject[0]' expected a map, got 'string'
* 'PrimitiveStringObject[1]' expected a map, got 'string'

goroutine 22 [running]:
testing.tRunner.func1(0xc000126800)
	/home/michael/dev/go-1.11/src/testing/testing.go:792 +0x387
panic(0x8bfa60, 0xc00000c620)
	/home/michael/dev/go-1.11/src/runtime/panic.go:513 +0x1b9
github.com/99designs/gqlgen/client.(*Client).MustPost(0xc0000a6c60, 0x95ee0b, 0x37, 0x881ca0, 0xc0000a6ca0, 0x0, 0x0, 0x0)
	/home/michael/go/src/github.com/99designs/gqlgen/client/client.go:60 +0xae
github.com/99designs/gqlgen/codegen/testserver.TestPrimitiveStringObjects.func4(0xc000126800)
	/home/michael/go/src/github.com/99designs/gqlgen/codegen/testserver/primitive_objects_test.go:67 +0x89
testing.tRunner(0xc000126800, 0xc00008d540)
	/home/michael/dev/go-1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/home/michael/dev/go-1.11/src/testing/testing.go:878 +0x353

Process finished with exit code 1
```

Let me know if I got something wrong.
