### ISSUE TITLE
Add Template To templates.Options

### ISSUE THREAD

**Issue by marwan-at-work** [99designs/gqlgen#672]
The plugin system currently walks the filepath of the directory to where the plugin was originally written, but if you want to publish a plugin as a binary that others download, that binary might not have the associated template files. 

We should allow the templates package to accept a template string to bypass looking up the file location.

**Comment by mathewbyrne** [comment]
I think this change makes sense.  I don't think you could currently publish a plugin as a binary currently though, unless you published a full custom gqlgen binary.

**Comment by vektah** [comment]
Yeah, I think I've given up on the idea that gqlgen could be shipped as a binary, its too closely tied to the local go version. Plugin loading also becomes much tricker, and there isnt much benefit - everyone is going to have a go toolchain installed where they are generating code.

**Comment by marwan-at-work** [comment]
Yes, the go toolchain is still required. But more in the sense that someone could potentially download the plugin binary from Github Releases and not from `go get` and therefore the `.gotpl` files would be missing.

**Comment by mathewbyrne** [comment]
Sure, but what is a plugin binary?  How does gqlgen use this binary as a plugin?  Currently this is not possible, and as @vektah mentioned probably isn't the direction gqlgen is headed.

That said I still think it's a good change, just because it gives plugins a bit more flexibility in how they provide templates.

**Comment by marwan-at-work** [comment]
@mathewbyrne  my current use case is that I have a `protoc` plugin that generates a GraphQL server from a Twirp `service.proto` file. So `gqlgen` does not use the binary as a plugin. But the plugin itself does what `gqlgen generate` does and adds my custom plugins within it.

**Comment by vektah** [comment]
Cool, I think that makes sense. :+1:
