### ISSUE TITLE
Run GraphQL Playground while offline

### ISSUE THREAD

**Issue by jonatasbaldin** [99designs/gqlgen#674]
Hey there 👋 

Today, `gqlgen` has no offline support for the GraphQL Playground handler, since it uses CND for its files.

I was thinking if we could download the necessary files (css, js etc) and insert it in the template.

I made a *non-working* example of what I want to achieve, but we need a `/static` endpoint to work, which I don't think its the best way. 

Another idea is to read the files and append it to the template, on the string level.

What do you think?

Thanks!

**Comment by mathewbyrne** [comment]
I think my preference would be to _not_ include these files in the repo; the current method is easier to update and means we aren't committing third party javascript into the repo.  If you want to run offline, I would recommend downloading the [desktop version](https://github.com/prisma/graphql-playground) of the Playground.

**Comment by jonatasbaldin** [comment]
Yeah, I agree! Closed the PR and closing this too :)

**Comment by TalShperling** [comment]
There is another solution I came up with.

If you are working on other network/locally you can clone this project:
https://github.com/TalShperling/graphql-playground-offline

and run the CDN locally for your/your environment's needs.
