### ISSUE TITLE
Trying to make gqlgen and dataloaden work

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#677]
### What happened?

Most likely the problem I am describing is due to my deficit. So I apologize in advance.

But since I am learning and I am aware of disturbing smart people like you, @vektah, with great care I create all the possible conditions to quickly understand the problem.

I foked the project "gqlgen-tutorials-master" here: https://github.com/frederikhors/gqlgen-dataloaden.

As you can see in the screen below the `UserLoader` way is the same as `UserRaw`.

Why?

![image](https://user-images.githubusercontent.com/41120635/56102058-0e9dd280-5f2a-11e9-9e89-1dce162f5bb0.png)

### Minimal graphql.schema and models to reproduce

https://github.com/frederikhors/gqlgen-dataloaden

### versions
 - `gqlgen version`? 0.8.3
 - `go version`? 1.12.2
 - dep or go modules? go.mod

**Comment by andcan** [comment]
Every call to `UserLoader` resolver instantiates a new `UserLoader`.

The loader should be created using a middleware and kept into context, for example:
```
func UserLoaderMiddleware(ctx context.Context) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := context.WithValue(r.Context(), userLoaderKey, newUserLoader())
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
```
Later you retrieve the loader using requests context:
```
func GetUserLoader(ctx context.Context) *UserLoader {
	l := ctx.Value(userLoaderKey)
	if nil != l {
		return l.(*UserLoader)
	}
	return nil
}
```
This way the loader will be shared for current context
[dataloaders](https://gqlgen.com/reference/dataloaders/) section has a good example

**Comment by frederikhors** [comment]
@andcan it works now. Thanks a lot.
