### ISSUE TITLE
Schema merging

### ISSUE THREAD

**Issue by divya1c** [99designs/gqlgen#679]
I would like to be able to have my queries/mutations in separate files and merge them while generation. I see that there is schema stitching, which i do use, but is there anyway i can have query type in more than one file and merge them together? 

Thanks!

**Comment by lwc** [comment]
This is already supported - you can provide multiple schema files in the gqlgen config, see https://gqlgen.com/config/ for more details

**Comment by divya1c** [comment]
hi @lwc i tried having two schemas with type Query in them and i get 
```
Cannot redeclare type Query
```

This is how i have my gqlgen.yaml file:
```
schema:
- geojson.graphql
- schema.graphql
- privsector.graphql
```

And this is how i try to generate:
```
func main() {
	fmt.Fprintln(os.Stderr, "Generating graphql code ...")
	log.SetOutput(os.Stderr)

	config, err := config.LoadConfigFromDefaultLocations()
	if err != nil {
		die("load config: %v", err)
	}

	if err = api.Generate(config); err != nil {
		die("codegen: %v", err)
	}

	fmt.Fprintln(os.Stderr, "Done generating graphql code.")
}
```

**Comment by mathewbyrne** [comment]
In order to have a valid schema across multiple files you need to use [Type extensions](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System-Extensions)

So define your main `Query` type somewhere, then in your other files:

```
extend type Query {
    // additional fields
}
```

**Comment by divya1c** [comment]
Thank you! that worked!! 💯

**Comment by pjvds** [comment]
What about having an interface type defined in one schema file, and implementing it in the other? Does give me a undefined type at the moment?

**Comment by mahendraHegde** [comment]
I want to have just one server(no federation) but would like to separate schema across(`gqlgen.yaml` supports it) different folders and also want to have separate resolvers for each schema in the same folder. 

In short I want to have monolith server but want to structure my app properly. 

How can I achieve it?
