### ISSUE TITLE
How to get argument values for nested fields a-la CollectFields?

### ISSUE THREAD

**Issue by stereosteve** [99designs/gqlgen#681]
Here is an example that enables a product search page with facets on the left hand side.
The `top_brands`, `top_sellers`, `top_categories` are the facets (or "aggregations" as it is powered by ElasticSearch).

For this example I provide arguments on each that allow you to independently control the size + timeout for each aggregation.

```
type Query {
  product_search(q: String, start: Int, size: Int): ProductResultSet
}

type ProductResultSet {
  total: Int!
  top_brands(size: Int, timeout: String): [CompanyBucket]
  top_sellers(size: Int, timeout: String): [CompanyBucket]
  top_categories(size: Int, timeout: String): [CategoryBucket]
  products: [Product]
}

type CompanyBucket {
  company: Company!
  doc_count: Int!
}

type CategoryBucket {
  category: Category!
  doc_count: Int!
}

type Company {
  id: String!
  name: String!
}

type Category {
  id: ID!
  name: String!
  ancestors: [Category]
  children: [Category]
}
```

example query:

```
{
  product_search(q: "vacuum") {
    top_brands(size: 20, timeout: "500ms") {
      company {
        name
      }
      doc_count
    }
    top_sellers(size: 100, timeout: "1s") {
      company {
        name
      }
      doc_count
    }
    top_category(size: 5) {
      category {
        name
      }
      doc_count
    }
    products {
      brand {
        name
      }
      ...
    }
  }
}
```

Currently using `CollectFields` to perform the aggregations in the `ProductSearch` resolver, which works pretty well, but doesn't expose the argument values: `(size: Int, timeout: String)`.

The other thing I investigated was forcing resolver generation for these fields, but this would require threading information from `ProductSearch` resolver into the `TopBrands` resolver (like `q` parameter for instance).  In general this seems like a worse approach.

But I'll ask both ways:

* Is there a way to get field arguments a-la `CollectFields`?
* Is there a way to pass information from a parent resolver into nested resolvers?  I was half considering using an approach like [gorilla/context](https://github.com/gorilla/context) but seems like a bad idea.

### versions
 - `gqlgen version`?  0.8.4
 - `go version`? 1.12.4
 - dep or go modules? modules

**Comment by stereosteve** [comment]
This looks like it can do the trick:

```
	for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
		fmt.Println(f.Name)
		for _, a := range f.Arguments {
			fmt.Println(a.Name, a.Value)
		}
	}
```

**Comment by stereosteve** [comment]
For posterity, you can also get arguments from parents:

```
	rezCtx := graphql.GetResolverContext(ctx)
	fmt.Println(rezCtx.Path())
	for k, v := range rezCtx.Parent.Parent.Parent.Args {
		fmt.Println(k, "=", v)
	}
```

**Comment by brackendawson** [comment]
> This looks like it can do the trick:
> 
> ```
> 	for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
> 		fmt.Println(f.Name)
> 		for _, a := range f.Arguments {
> 			fmt.Println(a.Name, a.Value)
> 		}
> 	}
> ```

This is not dependable, if the argument uses a query variable then `a.Value` will be the name of the variable, not its value. Here's a fixed version for args of type string. You'll need to dig more if you want to stay generic.

```go
	for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
		fmt.Println(f.Name)
		for _, a := range f.Arguments {
			rawValue, err := arg.Value.Value(graphql.GetOperationContext(ctx))
			if err != nil {
				panic(fmt.Errorf("error getting value for %s: %w", a.Name, err))
			}
			value, ok := rawValue.(string)
			if !ok {
				panic(fmt.Errorf("value for %s was not string", a.Name))
			}
			fmt.Println(a.Name, a.Value)
		}
	}
```
