### ISSUE TITLE
Re-order items in dataloader after DB call: performance and correctness doubts

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#682]
_Question for newbies like me. Eventually, if that's okay with you, I can open a wiki page to collect all these FAQs for newbies._

I'm experimenting with **gqlgen** and _dataloader pattern_ using **dataloaden**.

These are the models:

```go
type School struct {
  ID   int
  Desc string
}

type Author struct {
  ID       int
  Name     string
  SchoolID int
}

type Book struct {
  ID       int
  Pages    int
  AuthorID int
}
```

This is the `schema.graphql`:

```graphql
type School {
  id: ID
  desc: String
  authors: [Author]
}

type Author {
  id: ID
  name: String
  books: [Book]
}

type Book {
  id: ID
  pages: Int
  author: Author
}
```

I'm also using **go-pg** ORM (sqlboiler is planned) like this:

```go
loaders.authorByBooks = &AuthorLoader{
  wait:     1 * time.Millisecond,
  maxBatch: 100,
  fetch: func(keys []int) ([]*Author, []error) {
    var dbItems []*Author
    if err := DB.Model(&dbItems).Where("id in (?)", pg.In(keys)).Select(); err != nil {
      return nil, []error{err}
    }
    // Golang code for dbItems sorting here using keys order: itemsSortedByKeys []*Author
    return itemsSortedByKeys, nil
  },
}
```

### QUESTION

I was wondering if there is a way to directly retrieve from DB the sorted by keys `[]*Author` array (also to avoid the `range` in Go code and the multiple arrays for sort every time).

And also if I'm not an expert I think I found it:

```go
loaders.authorByBooks = &AuthorLoader{
  wait:     1 * time.Millisecond,
  maxBatch: 100,
  fetch: func(keys []int) ([]*Author, []error) {
    var dbItems []*Author
    keysIn := pg.In(keys)
    if err := DB.Model(&dbItems).Where("id in (?)", keysIn).OrderExpr("array_position(ARRAY[?]::int[], id::int)", keysIn).Select(); err != nil {
      return nil, []error{err}
    }
    return dbItems, nil
  },
}
```

This is the same for 1:M and M:M I think:

```go
loaders.booksByAuthor = &BooksSliceLoader{
  wait:     1 * time.Millisecond,
  maxBatch: 100,
  fetch: func(keys []int) ([][]Book, []error) {
    var dbItems []Book
    keysIn := pg.In(keys)
    if err := DB.Model(&dbItems).Where("author_id in (?)", keysIn).OrderExpr("array_position(ARRAY[?]::int[], author_id::int)", keysIn).Select(); err != nil {
      return nil, []error{err}
    }
    items := make([][]Book, len(keys))
    for i, key := range keys {
      for _, dbItem := range dbItems {
        if dbItem.AuthorID == key {
          items[i] = append(items[i], dbItem)
        }
      }
    }
    return items, nil
  },
}
```

Am I totally wrong?

Is this ok with the Garbage Collector?

### QUESTION 2

Except from the DB is there another way to do this other than `for i, v := range {}`?

Maybe something like this? https://outcrawl.com/graphql-postgresql-window-functions

Inspiration:
- https://gist.github.com/cpjolicoeur/3590737

**Comment by longfellowone** [comment]
You can take a look what Ive done here while messing around with gqlgen (pretty sloppy code, just been playing around with it). What I did was use the postgres array_agg() function with ORDER BY to load the IDs required for the next resolver. I also used LoadAll() from dataloaden for the nested arrays.

Maybe this will help?

https://github.com/longfellowone/relay-test/blob/d2f12f61cd36485bbb6322e0e42ec90747eb2d8f/dataloader/resolvers2.go#L221
https://github.com/longfellowone/relay-test/blob/d2f12f61cd36485bbb6322e0e42ec90747eb2d8f/dataloader/dataloaders.go#L74
https://github.com/longfellowone/relay-test/blob/d2f12f61cd36485bbb6322e0e42ec90747eb2d8f/dataloader/resolvers2.go#L105

**Comment by vektah** [comment]
This is going to be highly orm + database dependent, its really up to you to work out how best to fetch the data.

**Comment by frederikhors** [comment]
@vektah question 2 at least:

Except from the DB is there another way to do this other than `for i, v := range {}`?
