### ISSUE TITLE
Version updates problem of "cannot use ctx (type context.Context) as type *graphql.RequestContext in argument to graphql.CollectFields"

### ISSUE THREAD

**Issue by outsidebedisdoor** [99designs/gqlgen#685]
### What happened?

My AWS code build is running golang1.11 and my local is using golang1.12. Locally, I can run go get ./... without error out. However, for code build, it will errors: "cannot use ctx (type context.Context) as type *graphql.RequestContext in argument to graphql.CollectFields" 

### What did you expect?
I expect the code build can run go get ./... without any problem

### Minimal graphql.schema and models to reproduce
type Query {
    pilots(limit: Int): [Pilot!]!
    getPilot(uuid: String!): Pilot!
}

type Mutation {
    createPilot(input: NewPilot!): Pilot!
    updatePilot(input: UpdatePilot!): Pilot!
    deletePilot(uuid: String!): Pilot!
}

### versions
 - `gqlgen version`?  8.3
 - `go version`? 1.11
 - dep or go modules? go modules

**Comment by asp24** [comment]
you use master version of gqlgen, not 8.3
Just run `go generate`

**Comment by medcampus** [comment]
same issue using docker with go modules

**Comment by stoffern** [comment]
https://github.com/99designs/gqlgen/commit/7ba1b3b298695a7382abda437d3417d0aeae9c5b
This is a breaking change for people that generated schema before this commit.

**Comment by vektah** [comment]
Mixing runtime and generated code versions is not supported, things will break.

Please follow https://gqlgen.com/getting-started/ and make sure you are pinned to a release tag.
