### ISSUE TITLE
Feature request: default schema validation translations

### ISSUE THREAD

**Issue by bestxp** [99designs/gqlgen#695]
I would like to be able to translate messages like

` "message": "Field InputTest.Field of required type Int! was not provided.",`

for non english speaking user frendly messages from api

**Comment by mathewbyrne** [comment]
This isn't a core priority for us at the moment.  It would also involve changes to https://github.com/vektah/gqlparser to support translated messages. It also affects our ability to keep inline with the `graphql-js` error messages.  So there's a bit of complexity in doing this.
