### ISSUE TITLE
Character after numeric digit in method name not capitalised on generation.

### ISSUE THREAD

**Issue by pocockn** [99designs/gqlgen#696]
### What happened?
I am creating a mutation that has a numeric digit in the method name. For example:

`UploadToS3Success(ID String!): String!`

### What did you expect?
After the code is generated for my interface method to be called 

`type MutationResolver interface {
	VariantUploadToS3Success(ctx context.Context, briefID string) (string, error)`

However the method name is being generated as 

`VariantUploadToS3success(ctx context.Context, briefID string) (string, error)`

With the `s` in lowercase.

### versions
 - `gqlgen 0.8.3`?
 - `go1.11.5`

**Comment by JulienBreux** [comment]
Label: BUG

;)
