### ISSUE TITLE
Allow for disabling common initial check

### ISSUE THREAD

**Issue by scraymondjr** [99designs/gqlgen#697]
### What happened?
Using a user defined struct with an `Id` field and an `ID` func defined causes invalid code to be generated. The "common initial" check is causing generated code to attempt to set `it.ID` rather than `it.Id`.

### What did you expect?
No name conversion on the defined field names to be done when a user struct or explicit field name is given for the object config.

### Minimal graphql.schema and models to reproduce
.graphql
```
type Object {
  id ID
}
```
Go
```
package models

type MyObject struct {
  Id string `json:"id"`
}

func (o MyObject) ID() string {
  return o.Id
}
```
gqlgen.yml
```
struct_tag: json
models:
  Object:
    model: models.MyObject
```

### versions
 - `gqlgen version`? 
`v0.8.3`
 - `go version`?
`go version go1.12.3 darwin/amd64`
 - dep or go modules?
go modules

Would at least like to have a config option to explicitly disable any name modifications.

**Comment by vektah** [comment]
I cant reproduce this, and it doesnt appear to be related to common initial check.

> Using a user defined struct with an Id field and an ID func defined causes invalid code to be generated. The "common initial" check is causing generated code to attempt to set it.ID rather than it.Id.

You have a method called `ID` which should be called over the field.

> Would at least like to have a config option to explicitly disable any name modifications.

Thats unlikely to happen, its required to:
 - deal with go's public private by first letter case
 - avoid go keywords
 - resolve duplicate fields

**Comment by scraymondjr** [comment]
I looked back at my usage and saw the problem was actually specific for Mutation. So, to clarify my full use case, i have schema of 
```
type Query {
  readObject(id: ID!): Object
}

type Mutation {
  createObject(input: ObjectInput): Object
}

type Object {
  id ID!
  someOtherField String
}

type ObjectInput {
  id ID!
  someOtherField String
}
```
specifying both `Object` and `ObjectInput` to be the same Go type mentioned previously. This results in the `id` setting to be generated as:
```
var it models.Object
var asMap = v.(map[string]interface{})

for k, v := range asMap {
	switch k {
	case "id":
		var err error
		it.ID, err = ec.unmarshalOID2string(ctx, v)
		if err != nil {
			return it, err
		}
```
which causes compilation error like
```
graphql_gen.go:4631:15: cannot assign to it.ID
```

FWIW, I think the relevant code that is modifying the field name reference to be generated as `ID` rather than `Id` is at `codegen/templates/templates.go#ToGo`. I would argue that it is a not great UX when I provide a Go struct and the field name from the struct is not used in the generated code.
