### ISSUE TITLE
Field collection involving children

### ISSUE THREAD

**Issue by sagikazarmark** [99designs/gqlgen#703]
### What happened?

I wanted to prevent overfetching of a structure which has more than one level of descendants.

### What did you expect?

I expected the field collection API to return all requested fields, but it only returned the top level fields.

I found a recursive example here: https://github.com/99designs/gqlgen/issues/280#issuecomment-461814857

Is it the best option right now? What's the proper way of doing this?

### Minimal graphql.schema and models to reproduce

```graphql
type Provider {
	name: String!
	services: [Service!]!
}

type Service {
	name: String!
	regions: [Region!]!
}

type Region {
	name: String!
}
```

### versions
 - `gqlgen version`? v0.8.3
 - `go version`? go1.12.3
 - dep or go modules? go modules

**Comment by vektah** [comment]
Generally you would write these types yourself and leave off the recursive field, see https://gqlgen.com/getting-started/#create-the-database-models

You could also use "resolver: true", see https://gqlgen.com/config/

**Comment by sagikazarmark** [comment]
Thanks, I did that and it worked!
