### ISSUE TITLE
Proposal: Configure Custom Context

### ISSUE THREAD

**Issue by pvormste** [99designs/gqlgen#708]
Hello,

we have ran into an issue, where we do need a custom context. The current solution is to use a `context.WithValue` and put a generic map as value into the context.
It works, but it doesn't feel right and it is not really typesafe.

**Proposal**
Given a custom context:

```go
package mycontext

type MyContext struct {
    context.Context
    myValue string
}
```

There could be a value in the gqlgen.yml, where you can set a custom Context, e.g.:

```yml
context: github.com/my/app/mycontext.MyContext
```

The generated output would look like:
```go
type QueryResolver interface {
	Person(ctx mycontext.MyContext, name string) (*Person, error)
}
```
Because the custom context implements the context.Context interface it should not break anything else (I hope!).

**Comment by vektah** [comment]
That's not how context is supposed to work. Try something like this in its own package
```
package mycontextpackage

import "context"

type keyType struct {
	value string
}

var key = keyType{"mycontextkey"}

type MyContextObject struct {
	ValueA int
	ValueB string
}

func WithContext(ctx context.Context, obj *MyContextObject) context.Context {
	return context.WithValue(ctx, key, obj)
}

func ForCtx(ctx context.Context) *MyContextObject {
	return ctx.Value(key).(*MyContextObject)
}
```
then your revolvers stay pretty clean:
```
func (Query) Person(ctx context.Context, name string) (*Person, error) {
    fmt.Println(mycontextpackage.ForCtx(ctx).FieldB)
}
```

and because the key is a private type only that package can access it, giving back a fairly high degree of type safety.

You can see gqlgen using the same pattern [here](https://github.com/99designs/gqlgen/blob/master/graphql/context.go#L74)

**Comment by pvormste** [comment]
Thank you for your Feedback! Seems to be a good solution.
But this also seems to be a very common problem, so maybe this boilerplate code could be also generated?
