### ISSUE TITLE
Add website to the GitHub repo meta

### ISSUE THREAD

**Issue by jaydenseric** [99designs/gqlgen#709]
This is an easy one: Could someone with the auth please add the https://gqlgen.com website to the GitHub repo meta "Website" field?

I've had to go looking for the link in the readme a few times, it would be spiffy if it was displayed nicely by GitHub at the top :)

**Comment by mtibben** [comment]
![Done](https://media.giphy.com/media/3o7btNa0RUYa5E7iiQ/giphy.gif)
