### ISSUE TITLE
"panic: Query was not found" when running gqlgen init

### ISSUE THREAD

**Issue by mark-rushakoff** [99designs/gqlgen#711]
### What happened?

I am new to GraphQL and gqlgen. It's entirely possible I'm missing something obvious.

I was looking in to setting up a mock server for the GitHub v4 API. I downloaded https://github.com/octokit/graphql-schema/blob/911cf4c7963a73de3c53801ce5373a2134e0322c/schema.graphql, which I believe is supposed to reflect the official GitHub v4 GraphQL schema.

When I ran `go run github.com/99designs/gqlgen init`, it failed with this panic:

```
panic: Query was not found

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField.func1(0xc00491a510, 0xc0002c1630)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/codegen/field.go:81 +0xac
github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc0002c1630, 0xc0046bb900, 0xc00491a510, 0x0, 0x0)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/codegen/field.go:100 +0xf9b
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc0002c1630, 0xc0046bb900, 0xc00853ef50, 0xc00491a400, 0x0, 0x0)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/codegen/field.go:64 +0x31d
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc0002c1630, 0xc008538f00, 0x15cd693, 0x6, 0x0)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/codegen/object.go:73 +0x4ec
github.com/99designs/gqlgen/codegen.BuildData(0xc0001bc0c0, 0x16a6000, 0xc0001a23e0, 0x0)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/codegen/data.go:84 +0x461
github.com/99designs/gqlgen/api.Generate(0xc0001bc0c0, 0xc0000f9938, 0x1, 0x1, 0xc0001b6368, 0x6)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/api/generate.go:37 +0x243
github.com/99designs/gqlgen/cmd.GenerateGraphServer(0xc0001bc0c0, 0x15e6476, 0x10)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/cmd/init.go:75 +0xad
github.com/99designs/gqlgen/cmd.glob..func2(0xc0001c6160)
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/cmd/init.go:70 +0xc9
github.com/urfave/cli.HandleAction(0x1511f80, 0x160ce10, 0xc0001c6160, 0xc0000ba100, 0x0)
	/Users/mr/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0x15cb9d3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15f43ec, 0x1b, 0x0, ...)
	/Users/mr/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x996
github.com/urfave/cli.(*App).Run(0xc0001b8000, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/Users/mr/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6af
github.com/99designs/gqlgen/cmd.Execute()
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/cmd/root.go:40 +0x224
main.main()
	/Users/mr/go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/main.go:8 +0x20
exit status 2
```

There doesn't appear to be an extra output if I run `... init -v` instead. `models_gen.go` appears to be a valid Go file, but it does not have a Query type declared.

### What did you expect?

I thought `gqlgen init` would complete successfully. As far as I know, that schema.graphql file is used as-is in other projects, so I assume the input file is valid.

### Minimal graphql.schema and models to reproduce

I downloaded https://github.com/octokit/graphql-schema/blob/911cf4c7963a73de3c53801ce5373a2134e0322c/schema.graphql. It could probably be minimized. I started from an otherwise empty working tree, just that schema.graphql file and this go.mod:

```
module ghg

go 1.12

require github.com/99designs/gqlgen v0.9.0 // indirect
```

### versions
 - `gqlgen version` v0.9.0
 - `go version` 1.12.5
 - using go modules

**Comment by frederikhors** [comment]
Stale, my dear stale, this is a valid issue.

@mark-rushakoff did you find a way?

**Comment by mark-rushakoff** [comment]
Sorry @frederikhors, I had to find a totally different approach for the project I was working on at that time. Good luck.
