### ISSUE TITLE
How to define schema for one line go struct

### ISSUE THREAD

**Issue by 0xApe** [99designs/gqlgen#725]
### What happened?
Try to map simple Go map struct into the gql schema

### What did you expect?
A way to define simle go map struct in gql schema

### Minimal graphql.schema and models to reproduce

go Models

```
type Example struct {
	ID       int       `json:"id"`
	External MapStruct `json:"external"`
}

type MapStruct map[string]interface{}

func (m *MapStruct) someFunc() {}
```

schema

```
type Example {
  id: Int!
  external: External
}
```

then how to define the `External` schema?

### versions
 - `gqlgen version`?  0.9.0
 - `go version`? 1.12.5
 - dep or go modules? dep

**Comment by mathewbyrne** [comment]
GraphQL itself does not have a way for you to define an arbitrary string to anything Type.  So currently this is not possible, but not through a limitation of gqlgen.  You _can_ map a GraphQL Type to a Go map, but this will still have static keys on the GrapQL side.
