### ISSUE TITLE
Is it possible to execute a raw query?

### ISSUE THREAD

**Issue by akashbdj** [99designs/gqlgen#730]
### What happened?
This is not an issue in the existing code. I just to want execute a raw query. Is there some method available like it's present in graph-gophers/graphql-go [here](https://github.com/graph-gophers/graphql-go/blob/master/graphql.go#L157). 

Is it possible to execute the query if I pass the query(`string`), operationName(`string`), and variables(`map[string]interface{}`)?

### versions
 - `gqlgen version`? v0.9.0
 - `go version`?  go1.12.5 darwin/amd64
 - dep or go modules? go modules

**Comment by lwc** [comment]
It can be done - the `graphql.ExecutableSchema` interface has what you're after, but you need to build your own `ast.OperationDefinition`

https://github.com/99designs/gqlgen/blob/master/graphql/exec.go#L14

**Comment by akashbdj** [comment]
Hi @lwc ,
Thanks for pointing it out. 

Can I use [this](https://github.com/99designs/gqlgen/blob/e49d44f7464a05347691bfa9ed9eab44bf4ffe5f/handler/graphql.go#L431) as a reference while building my own `ast.OperationDefinition`? That's how `ast.OperationDefinition` is build, right?

If you've some better resource, please do share.

Regards,
Akash

**Comment by technoweenie** [comment]
I extracted a public Executor type in #1050, so this is possible now. There's no convenient `func(query, op string, vars map[string]interface{})` to call, but it wouldn't be difficult to write one tailored to a specific edge case (such as from a CLI tool).
