### ISSUE TITLE
Documentation is needed on how to use Tracers

### ISSUE THREAD

**Issue by keyneston** [99designs/gqlgen#731]
### versions
 - `gqlgen version`? 

v0.9.0

I'm attempting to add a minimal tracer to the program. Mostly for logging which step we are at during devel debugging. I'm currently unable to find anyway to add it to the request context. Would it be possible to get a simple code example of how to add it and/or add it to the documentation?

Thanks

**Comment by protochron** [comment]
@keyneston If you have a tracer implemented, you add it to the graphql handler like so:

```go
// Assuming your generated code lives in a package called `generated`
func main () {
	http.Handle("/query", handler.GraphQL(generated.NewExecutableSchema(generated.Config{
		Resolvers: &generated.Resolver{},
	}),
	handler.Tracer(mytracer.Tracer{}),
))
}
```
`handler.Tracer` configures the handler to call your tracer on each request. As long as it implements the `graphql.Tracer` interface then you should be good.

**Comment by karthikraobr** [comment]
https://github.com/99designs/gqlgen-contrib/blob/master/gqlopentracing/tracer.go
