### ISSUE TITLE
How do I keep the implementation of exisiting resolver fns when generating code?

### ISSUE THREAD

**Issue by akashbdj** [99designs/gqlgen#736]
Hi,

Our schema is growing everyday –– adding new queries/mutations and types to it. On generating code, `models_gen.go` and `generated.go` reflect new changes, but `resolver.go`(if already present) skips generation part. We want to generate resolver stub of the newly added queries/mutations also.

Currently, as suggested by documentation, the way to go is to delete the `resolver.go` file and re-generate everything again. But there is one problem, removing `resolver.go` file will remove the existing resolver functions implementations. We want to keep those intact while adding new resolver stub to `resolver.go`. How to do it?  I apologize if it's already present somewhere in docs but I can't seem to find it.

Let me know if you need more info, I'd be happy to provide more context and example.

Also, how can I split `resolver.go` into multiple files? Generated resolver structs are un-exported, so I can't even extend them to multiple files.

`resolver.go:`
```
type Resolver struct{}

func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}
func (r *Resolver) Search() generated.SearchResolver {
	return &searchResolver{r}
}

// UNEXPORTED
type queryResolver struct{ *Resolver }

func (r *queryResolver) Search(ctx context.Context, q string, offset *int, rows *int) (*search.Search, error) {
     // my implementation. 
     // I want to keep this implementation while adding resolver stub of newly added queries/mutations.
     return nil, nil
}

func (r *queryResolver) GetSearchClusters(ctx context.Context, q string, offset *int, rows *int, productsPerCluster *int, selectedCluster *string) (*models.SearchClustersResponse, error) {
	panic("not implemented")
}

// UNEXPORTED
type searchResolver struct{ *Resolver }
```

Thanks,
Akash

### versions
 - `gqlgen version`? `v0.9.0`
 - `go version`? `1.12`
 - dep or go modules? `go modules`

**Comment by maria-jabon** [comment]
+1 this will be an issue for us

**Comment by akashbdj** [comment]
If anyone else is looking for it, here's the project that does it : https://github.com/MichaelMure/git-bug/tree/master/graphql

**Comment by austincollinpena** [comment]
The example is nice, but does anyone know how this can be achieved, outside of just copy and pasting?

**Comment by vektah** [comment]
Take a look at https://github.com/99designs/gqlgen/pull/993, its the default for new projects now.

To get it in existing projects you will need to set:
```yml
resolver:
  layout: follow-schema
```
in gqlgen.yml
