### ISSUE TITLE
Make gqlgen more idiomatic?

### ISSUE THREAD

**Issue by rucuriousyet** [99designs/gqlgen#739]
First off.. love the work going on here. You all have done a great job. That being said  I feel like a lot could be done to make gqlgen more idiomatic and easier to work with. IMO, generated code should be read-only.. the best way to enforce this is to gitignore generated code, and make code generation part of the build process (totally open to better suggestions). I've started structuring my project to fit this, but I wonder if this isn't something that all gqlgen users would benefit from.

The purpose of this issue is to find out how people feel about the changes I'd like to make, before I start writing code (that would later become a PR). If you don't like my changes, just downvote this issue and Ill just maintain a fork within my startup instead (but I'd prefer not to divide the community, better to share efforts).

The changes I'd like to make are the following:
- The init command should create all files required for the project. In my mind, this would include the go mod files, gitignore (with generated go files included) and a set-up readme. 
- generated.go should live in the server directory (or something similar)
- server.go should be renamed to main.go and live in the project root (this is nice because it's very obvious what you need to do to run the application.. no digging required!)
- models_gen.go should be part of the model package and live in the model directory
- If possible, it would be nice to remove the pointer returns from resolvers. It's better to return an empty object and error (and error check early) then to make everything a pointer. I'm not sure if this was just a way to handle nullable fields or not, but even the non-nullable fields in my schema are generated as pointers.
- (A nice to have) Would be great to see the generated.go file broken up a bit
- Would also be nice to have resolvers broken up a bit. I created a resolver package/directory and moved the stubs to a file named after their type (user -> user.go)

I know that's a lot of misc, no worries if you don't like the way I see things.. either way I really appreciate all your efforts!

Last thing: If the above isn't desirable, I think a great alternative route would be to make the core of this project into a simple-to-use library providing the base parsing/resolver interface functionality. This would be a nice way to enable users to easily write their own custom generators based on their wants and needs. I know the generators are all plugins, but my attempt to write a customer generator was a lot harder than I thought it would/should be.

Thanks! I look forward to hearing back from you all!

**Comment by lwc** [comment]
Wow, a lot to unpack here!

>  ...generated code should be read-only.. the best way to enforce this is to gitignore generated code, and make code generation part of the build process

I'd view this as more of a go thing than a gqlgen specific thing thanks to `go generate`. We always have something like this in our CI lint/test step:

```sh
echo "+++ Checking go generate is up to date"
go generate ./...
if ! git diff --quiet  ; then
  echo "Looks like go generate needs to be run:"
  git --no-pager diff HEAD --color
  exit 1
fi
```

Agreed that the init command is pretty undercooked at the moment, but really it's just meant to be the bare minimum to get started, and it's expected that you'll flesh it out into a proper production ready app. 

In regards to the location of the generated files and etc, I think most of that should be configurable via `gqlgen.yml` - granted, the defaults init provides may not be ideal, but you should be able to change them to your liking, if not it's probably worth a bug issue.

In regards to pointers vs values, it was discussed to some extent in https://github.com/99designs/gqlgen/issues/375 and related PRs. 

Once a project is initialised, it's pretty much expected that you take charge of structuring your resolver code, as it's never re-generated. We typically split it out into separate files as a project grows. 

As an example, here's a gqlgen.yml from a current project:

```yaml
schema:
    - core.graphql
    - user.graphql
    - projects.graphql
exec:
    filename: generated/generated.go # the runtime just lives on it's own
model:
    filename: models/models_gen.go # generated models live with non generated models
resolver:
    filename: graph/resolvers.go # our code is rooted in package graph
    type: Resolver
```

Also worth noting - the parser is a separate project and I think it may be most accurate Go parser with respect to the current spec: https://github.com/vektah/gqlparser

Agreed on codegen internals though - the seam between plugins and the core is still pretty undercooked and needs some love. We're tracking the plugin system here: https://github.com/99designs/gqlgen/issues/228

**Comment by rucuriousyet** [comment]
Cool. I like the use of go generate above!

Nice to know I'm not completely crazy 😆 . Is there anything here I could help with?

**Comment by mathewbyrne** [comment]
Thanks for your input. Please see our [contribution guidelines](https://github.com/99designs/gqlgen/blob/master/CONTRIBUTING.md) if you'd like to help out.
