### ISSUE TITLE
CollectAllFields doesn't include nested fields 

### ISSUE THREAD

**Issue by Baggerone** [99designs/gqlgen#746]
### What happened?
This is my code ...
```
	requested := graphql.CollectAllFields(ctx)
	fmt.Printf("\nRequested Fields:   %v\n", requested)
```
This is the graphql request ...
```
{user(id:"1") {name, nickname}, cars{registration}}
```
Just the top level fields were returned ...
```
Requested Fields:   [name nickname]
```

### What did you expect?
That even the nested fields would be returned
```
Requested Fields: name, nickname, cars, registration
```

### Minimal graphql.schema and models to reproduce

```
type User {
  id: ID
  name: String!
  nickname: String
  cars: [Car!]
}

type Car {
  id: ID
  registration: String!
}
```

### versions
 - `gqlgen version`?   dev
 - `go version`? g01.11.10
 - dep or go modules? dep

**Comment by mathewbyrne** [comment]
This is intentional, as it is a convenience wrapper around `CollectFieldsCtx` to account for the most common case, where you just want to limit querying your data source by the actual fields requested.  If you have a more complex use-case, use that instead.

See also our [field collection docs](https://gqlgen.com/reference/field-collection/).

**Comment by Baggerone** [comment]
@mathewbyrne,

Thank you for your reply.  Using my graphql request (above) and CollectFieldsCtx, I still can't see cars.registration getting returned.  (I still only see user.name and user.nickname.) It still seems like those Collect functions don't look inside the nested part of the graphql request.

Maybe I'm missing something.  

E.g. If I have ... 
```
	requested := []string{}
	satisfiesFields := graphql.CollectFieldsCtx(ctx, []string{"registration"})
	fmt.Printf("\nSatisfies Fields:   \n")
	for _, f := range satisfiesFields {
		requested = append(requested, f.Name)
		fmt.Printf("   %v\n", f.Name)
	}
```
I get ...
```
Satisfies Fields:   
   name
   nickname
```

Also, if I replace "registration", with "car", "Car,  "cars" or "Cars", I still get that result.

Can you give me a concrete example of what I would need to do to get the car.registration field included in the results?

Thank you for your help.

**Comment by RichardLindhout** [comment]
I have the same use-case.

My query:
```
 flowBlocks {
            id
            block {
              id
              title
              type
              choices {
                id
                title
                description
                slug
              }
            }
          }
        }
```

Code
```
	requested := graphql.CollectFieldsCtx(ctx, []string{"block", "choices"})
	for _, column := range requested {
		r.l.Debug(column.Name)
	}
```

Response
```
2019-07-18T20:49:09.829+0200    DEBUG   backend/resolver.go:71  id
2019-07-18T20:49:09.830+0200    DEBUG   backend/resolver.go:71  block
```

Regardless of what I put in the satisfies argument I only got id and block

**Comment by RichardLindhout** [comment]
CollectAllFields the same. looks like it won't will nested further

**Comment by RichardLindhout** [comment]
@Baggerone  After spitting through source got something working now



```
fields := graphql.CollectFieldsCtx(ctx, []string{"Block"})
	for _, column := range fields {
		r.l.Debug(column.Alias)
		fields2 := graphql.CollectFields(reqCtx, column.SelectionSet, []string{"BlockChoices"})
		for _, c := range fields2 {
			r.l.Debug(c.Alias)
		}
		// graphql.CollectFields(ctx, []string{"Block"})
		// for _, c := range column.SelectionSet {
		// 	r.l.Debug(c.GetPosition().Src.Name)
		// }

	}
```

**Comment by RichardLindhout** [comment]
I've created some nice helpers which get's al the request fields

```json
["flowBlocks.id", "flowBlocks.block", "flowBlocks.block.id", "flowBlocks.block.title", "flowBlocks.block.type", "flowBlocks.block.choices", "flowBlocks.block.choices.id", "flowBlocks.block.choices.title", "flowBlocks.block.choices.description", "flowBlocks.block.choices.slug"]
```

```golang

func getPreloads(ctx context.Context) []string {
	reqCtx := graphql.GetRequestContext(ctx)
	resCtx := graphql.GetResolverContext(ctx)

	fields := graphql.CollectFieldsCtx(ctx, nil)
	return getPreloadsSimple(reqCtx, fields, resCtx.Field.Name)
}

func getPreloadsSimple(ctx *graphql.RequestContext, fields []graphql.CollectedField, prefix string) (preloads []string) {
	for _, column := range fields {
		prefixColumn := getPreloadString(prefix, column.Name)
		preloads = append(preloads, prefixColumn)
		preloads = append(preloads, getPreloadsSimple(ctx, graphql.CollectFields(ctx, column.SelectionSet, nil), prefixColumn)...)
	}
	return
}

func getPreloadString(prefix, name string) string {
	if len(prefix) > 0 {
		return prefix + "." + name
	}
	return name
}

```

**Comment by Baggerone** [comment]
Thank you, @RichardLindhout.  That's helpful.

**Comment by RichardLindhout** [comment]
My code does not include all selected fields somehow I forgot 

```
	preloads = append(preloads, GetNestedPreloads(ctx, graphql.CollectFields(ctx, column.SelectionSet, nil), prefixColumn)...)
++++!!		preloads = append(preloads, GetNestedPreloads(ctx, graphql.CollectFields(ctx, column.Selections, nil), prefixColumn)...)
```

**Comment by RichardLindhout** [comment]
I've updated the code

**Comment by RichardLindhout** [comment]
I've updated the examples above since there were cases of duplicated preloads. And it's updated to the new OperationContext

**Comment by mtatarau90** [comment]
Hi guys, is a way to get this fields in a middleware instead of a resolver ?

**Comment by RichardLindhout** [comment]
@mtatarau90 Sure, you have a ctx variable in your resolver right? Or else try a directive

https://gqlgen.com/reference/field-collection/
https://gqlgen.com/reference/directives/

**Comment by mtatarau90** [comment]
@RichardLindhout i will use directives, thanks. Btw in middleware seems do not work, and gqlgen return a context error.

**Comment by AndrewRayCode** [comment]
Is there a trivial way to also include arguments on the fields? For a query like
```graphql
fields {
   field(x: 1) {
     id
   }
}
```
The returned fields don't include the argument:
```javascript
["fields", "fields.field", "fields.field.id"]
```
My context is I'm trying to reconstruct the query sent to my Go service, to re-send a nearly identical query to an underlying service.
