### ISSUE TITLE
Add gqlgen to awesome-go

### ISSUE THREAD

**Issue by Pokerkoffer** [99designs/gqlgen#749]
Hi,

i'd like to add this awesome library to [awesome-go](https://github.com/avelino/awesome-go), a curated list of awesome golang libraries and tools. Personally, I use this list quite often to get an overview which libraries exist for a specific topic I want to implement.

They require some quality standards like test coverage and documentation for libraries to be added. 

However, [gocover.io](https://gocover.io/github.com/99designs/gqlgen) reports an error when running: `strconv.ParseFloat: parsing "": invalid syntax
`

Are you guys interested in adding this library to the list and look into the error? This can lead some new folk to this library and support development as well as some more attention, which is always good :)

I've read the docs about testing and you write that it isn't that easy to test generated code. Is it possible that the syntax error is occurring due to generated code?

PR: https://github.com/avelino/awesome-go/pull/2566
Greetings

**Comment by vektah** [comment]
code coverage over generated code is hard.  I tried with coveralls but couldn't get it to exclude the generated code. No idea what gocover.io is doing though.

https://coveralls.io/github/99designs/gqlgen


I personally really dislike that golint rule `XXX should have comment or be unexported`. It leads to useless comments most of the time. At least golint excludes generated files.

**Comment by MichaelMure** [comment]
FWIW, I get the exact same gocover error when trying on [my project](https://github.com/MichaelMure/git-bug). Possibly because gqlgen is a dependency ?

**Comment by MichaelMure** [comment]
Actually that seems to be a timeout on the gocover side ... https://github.com/vieux/gocover.io/issues/41
