### ISSUE TITLE
Propagate context through middlewares?

### ISSUE THREAD

**Issue by sneko** [99designs/gqlgen#777]
Hi everyone,

I'm getting some values from the initpayload (inside `gqlgenhandler.WebsocketInitFunc`) and put them inside the context. But at the next middleware it seems my context has not those values, nor the subscription the user is subscribing.

How could I propagate the new context back to gqlgen management for this connection (including subscriptions triggered)?

Thank you,

**Comment by vektah** [comment]
It's a little tricky, we will need to update this func to return a context. It's not a middleware so its interface doesn't naturally lend itself to this.

**Comment by sneko** [comment]
Hi @vektah , thanks for the answer.

What would be the better way to go through? Getting some initPayload data and check them inside `WebsocketInitFunc`, and then within the `RequestMiddleware` getting them and putting them inside the context?
