### ISSUE TITLE
Wrong query interface type [update code break]

### ISSUE THREAD

**Issue by robert-zaremba** [99designs/gqlgen#782]
### What happened?

After updating to v0.9.1 (from 0.8) gqlgen generates different interfaces.

For example for the following query:
```
users: [User!]!
```

**Before** the generated interface was:

```
 Users(ctx context.Context) ([]model.User, error)
```

**NOW** it changed to:
```
Users(ctx context.Context) ([]*model.User, error)
```

Is it possible to instrument `gqlgen` to about query interfaces as we can do with types?

**Comment by robert-zaremba** [comment]
EDIT - wrong copy paste, the **NOW** part should use pointers in return types:

```
Users(ctx context.Context) ([]*model.User, error)
```

**Comment by robert-zaremba** [comment]
Hi. Can anyone from the project give a feedback, pleay?

**Comment by vektah** [comment]
you can opt back into the old behaviour using the config option `omit_slice_element_pointers: true` 
see https://github.com/99designs/gqlgen/pull/874
