### ISSUE TITLE
dataloader alternative

### ISSUE THREAD

**Issue by bugzpodder** [99designs/gqlgen#790]
I am trying an alternative to dataloader for dealing with N+1 queries.  I want to see if this proposal is reasonable.

The underlying idea is pretty simple:
If you are resolving a field for a struct, eagerly resolve it for all other structs.
for example, if you have a User {} and you want to resolve its Todos, just resolve any other User's Todos at the same time.

See https://github.com/99designs/gqlgen/pull/808 for a working example.

Consider the models:
```
package api

type User struct {
  Todos []*Todo
}
```

What happens is that you'll need a UserLoader { users []api.User }, and you can expose a method LoadTodos().  This will get all todo ids from each user struct, and instantiate a TodoLoader that will load all the Todos for you.

Any time you need to resolve the TODOs field for a user, just go back to the UserLoader and call LoadTodos.

```
package loader

type UserLoader {
  users []api.User
}

func UserLoaderByIds(ids []int) *UserLoader {...}
func (s *UserLoader) LoadTodos() {
  uids := []int{}
  for _, user := s.users {
     uids = append(uids, user.id)
   }
  todoIds = db.LoadTodosByUserIds(uids)
  todoLoader = TodoLoaderByIds(todoIds)
  // Put todos in users
}
```

See https://github.com/99designs/gqlgen/pull/808 for a working example.

**Comment by bugzpodder** [comment]
I have a working prototype, I can send a PR with an example app if this sounds interesting.  Works well with 1k items with nested resolvers.

I don't like dataloader that much because of having to deal with context and blocking for 1ms every time, but that approach may work better if your service handle multiple requests simutaneously (so it will batch data from these requests at the same time, while my approach only batches per request).

**Comment by molon** [comment]
```
{
  users(first:2) {
    nickname
    orders(first: 2) {
      nodes {
        id
        seller {
          nickname
        }
      }
    }
  }
}
```

If user list has two elements, then there are two orders every user. 
The order_ids: "a","b","c","d".
Then if all orders have same `seller_id:xxx`
How do you ensure that execute sql `select nickname from user where id = 'xxx'` once?

**Comment by bugzpodder** [comment]
In my implementation,  select nickname from user where id = 'xxx' will execute twice (even if first = 100 for both instances). 

So here is what happens in the request:
1. graphql sees users(first:2) query.  It constructs a UserLoader and it will contain two rows of users.  This will execute select nickname from user where id = 'xxx' once here.
2. graphql tries to resolve orders(first:2) for both users using go routines.  Second one will block until first one is done and does noop.
3. When executing the orders(first: 2), the user defers to the UserLoader.
4. User loader assumes that we are executing orders(first:2) for *all* users it has.  
I am not 100% sure how this (load ids of first 2 orders from all users in one query) would be done in SQL using a single query actually, but you'll have to deal with this with any batch loading methodology.  so let me know if you know how.  Let's just say we execute this and get "a","b","c","d" back.
4. A orderLoader is constructed from userLoader with these 4 orders.  It seems there are some relay style edge representation in your example, haven't thought 100% through but it should affect batch loading too much I think.
5. graphql tries to resolve seller field on each of these orders, the last three will block like before, while the first one will defer to orderLoader, which will pre-fetch seller on each order.
