### ISSUE TITLE
<-ctx.Done() seems never called when closing my browser tab

### ISSUE THREAD

**Issue by sneko** [99designs/gqlgen#791]
Hi everyone,

I'm storing the created channels inside a map to use them later, and I just figured out the map was growing without being cleaned even when closing the websocket connections.

I put more logs and it seems the following section of the code is never triggered :
```
func (r *subscriptionResolver) XXXUpdated(ctx context.Context) (<-chan *graph.XXX, error) {
	...
	go func() {
		<-ctx.Done()

		... THIS IS NEVER REACHED

	}()
```

What could explain my ctx.Done() channel never sends any termination packet despite me closing all my browser tabs?

Do I need to do something special to handle closing websocket connections?

Thank you,

**Comment by sneko** [comment]
1. An explicit would be from my client side, having time to say "hey, goodbye" before closing the tab. This would be done by sending "connection_terminate" from the client according to:
https://github.com/99designs/gqlgen/blob/726a94f4895cb9d7ca031e97893e60eac3ac0e5d/handler/websocket.go#L24

But we cannot count on it (network, process killed/crashed...).

2. Since there is the keep-alive sent from the server to the client (https://github.com/99designs/gqlgen/blob/726a94f4895cb9d7ca031e97893e60eac3ac0e5d/handler/websocket.go#L171-L181), how can the server knows about the user not being at the other side of the "wire"?

The keep-alive loop tries to send forever a message, but I'm not sure to understand if no one is at the other side. Does it reaches an error? If yes, which one? This one https://github.com/99designs/gqlgen/blob/726a94f4895cb9d7ca031e97893e60eac3ac0e5d/handler/websocket.go#L163 closing calling `cancel()` and triggering the `<-ctx.Done()`?

@sinamt I saw you worked on it, could you please provide some details on how it works? And maybe do you have some thoughts why that's never triggered please?

Thank you!

**Comment by roffe** [comment]
Im running into issues with this as well now. i'm not finding any way to know when he subscriber has disconnected and ctx.Done() never fires

**Comment by sneko** [comment]
Did you find something about this @roffe ?

I'm now working on another project and still facing this (but more obvious for us since devices loose connections really frequently).

@vektah @lwc @vvakame , does anyone of you have faced this issue? When looking at the code:
https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/websocket.go#L163-L169
and
https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/websocket.go#L232-L255

I don't see `gqlgen` closing the subscriptions in case of an error with the websocket connection. Maybe I'm doing something wrong? Just listening to the `<-ctx.Done()` for each subscription.

Thank you,

**Comment by maeglindeveloper** [comment]
Same for me :-1:

**Comment by sneko** [comment]
@lwc having your thoughts would be great to move forward. Even if I need to make a PR, willing too, but just wanted to be sure the current behavior is wrong.

Thank you,

**Comment by maeglindeveloper** [comment]
hey everyone, @vektah @lwc , any advice on this ?

**Comment by sneko** [comment]
Is any of the maintainers can look at this thread please? Reopening would be great :)

@MichaelJCompton
@lwc 
@wilhelmeek 
@StevenACoffman
@a8m

**Comment by StevenACoffman** [comment]
There's been a lot of changes to the current websocket handling, so if someone can verify this problem persists, can you open a new issue? In that case, a reproduction would be very helpful and a pull request would be welcome.

**Comment by sneko** [comment]
@StevenACoffman I checked with `v0.16.0` and it works fine!

It's seem immediate so I guess the context is properly closed now (and that's not due to the ping-pong feature).

Really glad it has been released, thank you all!

**Comment by StevenACoffman** [comment]
Yay! Thanks for circling back to let us know!
