### ISSUE TITLE
Schema override feature request

### ISSUE THREAD

**Issue by soqt** [99designs/gqlgen#792]
I'm using several schemas, one includes a generated graphql schema. I hope to override several type in that file. Currently when I list all schema files in `schema` directory, it throws an error ` Cannot redeclare type Query.`. I know we can extend `Query` type, but in this case I hope to override `Query`. A feature that bottom schema can override higher schema would be awesome.

**Comment by bugzpodder** [comment]
How do you know which one is bottom?

**Comment by soqt** [comment]
According to the order in yml file. `schema` accepts a list of graphQL files. bottom means bigger index.

**Comment by vektah** [comment]
There is no concept of order for schema even within files.
