### ISSUE TITLE
Generated return type: Mandatory array item is a pointer

### ISSUE THREAD

**Issue by Invertisment** [99designs/gqlgen#793]
### What happened?
I've updated gqlgen from 0.8.3 to 0.9.1 and noticed a change in generated interfaces.

Does this mean that exclamation mark doesn't mean anything?

### What did you expect?
```
type Query {
    users: [User!]!
}
```
```
Users(ctx context.Context) ([]model.User, error)  // before upgrade to 0.9.1
Users(ctx context.Context) ([]*model.User, error)  // after upgrade to 0.9.1
```
I expected to not change anything in my API interfaces. And currently it expects an array of pointers.
In my case it doesn't make sense to return an array populated in `nil` values, but the schema allows it :man_shrugging: 

I ended up creating many boxing functions... And as golang doesn't have generics the functions add up :fearful: 

### Minimal graphql.schema and models to reproduce

I explicitly ask to return mandatory elements in the schema:
```
type Query {
    users: [User!]!
}
type User {
  id: ID!
}
```
I would like to return an array of structs (not pointers) because I query that from my database.
This is the interface that was generated:
```
Users(ctx context.Context) ([]*model.User, error)
```
Interestingly this is the same thing that would be generated with this API definition:
```
type Query {
    users: [User]! # Notice the lack of first exclamation mark
}
```

I also noticed that examples don't follow exclamation marks too. Some methods expect boxed output and some expect unboxed:
Non-boxed:
https://github.com/99designs/gqlgen/blob/master/example/starwars/schema.graphql#L5
https://github.com/99designs/gqlgen/blob/master/example/starwars/generated/exec.go#L138
Boxed:
https://github.com/99designs/gqlgen/blob/master/example/starwars/schema.graphql#L4
https://github.com/99designs/gqlgen/blob/master/example/starwars/generated/exec.go#L137

### versions
 - gqlgen: 0.9.1
 - go: 1.12.5 linux/amd64
 - go modules

**Comment by andcan** [comment]
See #375
