### ISSUE TITLE
Typo in README.md?

### ISSUE THREAD

**Issue by xpol** [99designs/gqlgen#803]
The example code for custom resolver:

```go
func (r *userResolver) User(ctx context.Context, obj *User) ([]*User, error) {
    // select * from user where friendid = obj.ID
    return friends,  nil
}
``` 

the function `User` should be `Friends` ?

**Comment by dannywolfmx** [comment]
Hi.

Acording to the User type, the friends field is a list of User types. The example seems to be correct.

But it is true that it would be interesting to create a Friend type so that it is more readable, but for the purpose of an example I think it's fine as well as this

**Comment by vektah** [comment]
Fixed, thanks
