### ISSUE TITLE
improve information at RequestContext for rich logging

### ISSUE THREAD

**Issue by vvakame** [99designs/gqlgen#804]
I want to get `operationName` and `persistedQueryHash` to logging in `handler.RequestMiddleware`.

![gql-log](https://user-images.githubusercontent.com/125332/61849980-fdcc0800-aeed-11e9-9cc5-dddea87ada82.png)

Currently, We can't get accurate information.

for example, We can't detect which operation is in execute from RequestContext.
https://github.com/99designs/gqlgen-contrib/blob/c654377d611cfcf5b77012b5814af5a14a79bc86/gqlopencensus/tracer.go#L136-L147

```
query A {
  a: viewer {
    email
  }
}

query B {
  b: viewer {
    email
  }
}
```

Current tracer implementations can't get operationName `B` when it chosen.

so, I think `func NewRequestContext(doc *ast.QueryDocument, query string, variables map[string]interface{}) *RequestContext` is not extensible without breaking change.
I suggest to make `func (rctx *RequestContext) Validate() error` to check and fill empty field and deprecate `NewRequestContext`.

What do you think about my suggestion? ✨

**Comment by vektah** [comment]
Sounds good to me
