### ISSUE TITLE
Utilize gorilla websocket's ping/pong mechanism to avoid leaking connections

### ISSUE THREAD

**Issue by KopiasCsaba** [99designs/gqlgen#806]
### What happened?
If you subscribe to a subscription, then when you kill the connection abruptly* then  `<-ctx.Done` never fires.

So a connection and the goroutines surrounding it were leaked.

*: E.g: disabling wifi, plugging out the cable, turning off the router. (not ctrl+c, not reboot, not tab/app close those are different those situations are handled well). 

### What did you expect?
I have expected the connection to time out after a while if the client is not reachable.

### Minimal code to reproduce
In the chat example here in this repo, add this:

```go
	go func() {
		fmt.Println("Client IN")
		<-ctx.Done()
	        fmt.Println("Client OUT")
	}()
```

to resolvers.go / MessageAdded function.

Connect to your server through some external device (or ip from the same machine) and abruptly (see above) reset the connection.

### versions
 - `gqlgen version`?  0.9
 - `go version`? go1.11.4
 - dep or go modules? dep

### Proposal for fix:
I have researched this quite a lot, and after many hours of testing i've concluded this:

Although gqlgen has keepAlive but it does not do anything if there is no answer for that.
Also gqlgen  does not use the lower level websocket feature called ping/pong, that is a protocol feature, that whenever the server sends a special packet (ping) the client should respond with another special packet (pong).

The good news is, that the underlying websocket library of gqlgen, gorilla websocket has ways for handling it, and an even better news is: there is a working example that solves this issue.

The aforementioned example is the [chat](https://github.com/gorilla/websocket/tree/master/examples/chat) example. I have tested it, and it is registering disconnection properly when the connection is silently closed.

The way to test this is similar, just update hub.go's run() to start like this:
```go
func (h *Hub) run() {
	for {
		select {
		case client := <-h.register:
			log.Println("client in")
			h.clients[client] = true
		case client := <-h.unregister:
			log.Println("client out")
//...
```

The way this works is by re-setting the read deadline whenever it reads anything in readPump:
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L56

Also in here there is a SetPongHandler call, that just updates the read deadline again, this deadline will kill the conenction when nothing is arrived in the given timeframe (no pong, no nothing).

Upon reading from the channel, readPump looks for exceptions, and returns if it should. Upon that defer unregisters the client. This is the path it takes when the deadline is missed.

The pair of this with the ticker that sends ping messages can be found in writePump.

So i think the soultion would be to use the same method in gqlgen where the ws connection is handled. (It might be important, that gqlgen's keepalive just sends a message that might be responded to by some javascript, websocket's ping/pong on the other way is implemented by the client, in this case the browser itself)

Thank you for this library, thank you for your work and looking forward to hear your thoughts on this.

**Comment by vektah** [comment]
PR welcome :)

**Comment by sotoslammer** [comment]
We're seeing an issue of leaking websocket connections.  Our dev server was crashing periodically because it would run out of file descriptors.  After a lot of digging I found that a refresh on the client side was leaving connections just hanging in a CLOSE_WAIT state.  I believe this is because connections aren't explicitly being closed on defer in the websocket run function

**Comment by sneko** [comment]
Hi @KopiasCsaba ,

We are looking for the same feature, did you solve your issue?

Thank you,

**Comment by maeglindeveloper** [comment]
Aligned with @sneko :) ! Love to here more about that :+1:

**Comment by maeglindeveloper** [comment]
I made a PR that might help on this https://github.com/99designs/gqlgen/pull/1513
Any comments are appreciated :+1:
