### ISSUE TITLE
Generated struct from schema causes compiler error due to struct size 

### ISSUE THREAD

**Issue by apoggi-carecloud** [99designs/gqlgen#810]
The Go compilers throws the error "internal compiler error: name too long:" due to the generated struct representing the schema being too long. Is there any way for this generated struct to be broken apart?

**Comment by JulienBreux** [comment]
Hi @apoggi-carecloud 

Do you have an example of your GQL schema please?

Thanks, have a good day!

**Comment by apoggi-carecloud** [comment]
[schema.txt](https://github.com/99designs/gqlgen/files/3447452/schema.txt)
Here is an example with all text scrambled

**Comment by JulienBreux** [comment]
Sorry @apoggi-carecloud unable to read file

**Comment by apoggi-carecloud** [comment]
@JulienBreux 

[schema.txt](https://github.com/99designs/gqlgen/files/3447973/schema.txt)

**Comment by JulienBreux** [comment]
:/
I think that's an infinite interface expansion by the Go compiler.

Your schema is very big 🎉

Maybe use the latest version of Go.

🔗 https://github.com/golang/go/issues/27256

**Comment by apoggi-carecloud** [comment]
Using the latest version (1.12) unfortunately results in the same error

**Comment by apoggi-carecloud** [comment]
@JulienBreux Do you think forking and modifying gqlgen so that the resulting struct generated from the schema is broken up into multiple structs is an option? Infinite interface expansion is not an issue here. The go compiler simply has a limit on the size of structs that is being exceeded https://github.com/golang/go/issues/18920

**Comment by JulienBreux** [comment]
Hello @apoggi-carecloud  👋 
I think that the schema is too big for compiling 😕

**Comment by vektah** [comment]
Sorry, I don't think there's anything we can do here. Perhaps try decomposing query into smaller chunks of related stuff.
