### ISSUE TITLE
I hope to filter the return results of a few interfaces after a request. It is not a good solution to @direct processing. Is there a better solution?

### ISSUE THREAD

**Issue by exfly** [99designs/gqlgen#812]
I hope to filter the return results of a few interfaces after a request. It is not a good solution to @direct processing. Is there a better solution?

type SubMod {
    id: String
}
type Model{
    sub: SubMod
}

query{
    listModel: []Model
}

get:
```
[
    {
        Model{sub:SubMod{id:"id"}}, 
        Model{sub:null}
    }
]
```

want filter sub is null:
want:
```
[
    {
        Model{sub:SubMod{id:"id"}}, 
    }
]
```

It is heavy for me to clean the db.

can there add some hook for it or help me to give me an example that can solve this problem.

**Comment by vektah** [comment]
Yeah, go isnt great for filtering.
```
var ret []*Items
for_, i := range db.GetItems() {
   if i.id == "" {
      continue
   }
    ret = append(ret, i)
}
return ret, nil
```
