### ISSUE TITLE
errors on init key "deprecated" already set in map

### ISSUE THREAD

**Issue by bjm88** [99designs/gqlgen#815]
### What happened?
While running
go run github.com/99designs/gqlgen init
got errors:
unable to parse config: yaml: unmarshal errors:
  line 18: key "deprecated" already set in map
  line 20: key "include" already set in map
  line 22: key "skip" already set in map
exit status 1

### What did you expect?
To not get errors and see all the generated files.  My schema.graphql validates against online validators and VSCode validator.  I used the todo example as reference, seems to match...any idaes?

### Minimal graphql.schema and models to reproduce
type Communication {
  identifier: [Identifier!]
  status: String!
  category: [CodeableConcept!]
  priority: String!
  medium: [CodeableConcept!]
  subject: Patient!
  topic: CodeableConcept!
  sent: Time!
  received: Time!
  recipient: [Patient!]
  sender: Organization!
  reasonCode: [CodeableConcept!]
  payload: [Message!]
}

type Message {
  contentString: String!
}

type CodeableConcept {
  system: String!
  version: String!
  code: String!
  display: String!
  userSelected: Boolean!
}

type Organization {
  identifier: [Identifier!]
  type: [CodeableConcept]
  name: String!
  endpoint: [Endpoint!]
}

type Patient {
  identifier: [Identifier!]
  name: [HumanName]
  gender: String!
  birthDate: Time!
  address: [Address!]
}

type Identifier {
  use: String!
  type: CodeableConcept!
  system: String!
  value: String!
}

type HumanName {
  family: String!
  given: [String!]
}

type Address {
  use: String!
  type: String!
  line: [String!]
  city: String!
  district: String!
  state: String!
  postalCode: String!
  country: String!
}

type Endpoint {
  address: String!
}

type Query {
  communication(identifier: Identifier!): Communication
  communications: [Communication!]!
}

type Mutation {
  createCommunication(communication: Communication!): Communication!
  updateTodo(id: Identifier!, communication: Communication!): Communication
}

schema {
  query: Query
  mutation: Mutation
}

### versions
latest - v0.9.1

**Comment by bjm88** [comment]
if anyone else runs into this its b/c the schema had validation issues and the gqlgen.yml partially generated.  Must delete it to re-run init.

**Comment by adamclerk** [comment]
I'm attempting the [GettingStarted](https://gqlgen.com/getting-started/) and I'm running into this issue.
