### ISSUE TITLE
parseOperation and validateOperation should not return their contexts

### ISSUE THREAD

**Issue by edsrzf** [99designs/gqlgen#817]
### What happened?

I've been working on a [honeycomb.io](https://honeycomb.io)-based `Tracer` implementation, and my implementation adds spans to the trace for `StartOperationParsing` and `StartOperationValidation`. However, due to `parseOperation` and `validateOperation` returning their contexts ([1](https://github.com/99designs/gqlgen/blob/v0.9.1/handler/graphql.go#L595), [2](https://github.com/99designs/gqlgen/blob/v0.9.1/handler/graphql.go#L631)), my trace ends up with the wrong hierarchy, like this:

![image](https://user-images.githubusercontent.com/369904/62522124-23a9c300-b885-11e9-960a-e92b80d99250.png)

### What did you expect?

Parsing, validating, and executing the query should all be on the same level, happening in series.

I can't see any reason to want to return contexts from these methods, but thought I'd file an issue here for discussion in case there's something I didn't pick up on.

### versions
 - `gqlgen version`? 0.9.1

**Comment by vektah** [comment]
I'm not seeing the issue here, that context is there so they can add to the context if required.

context should not be automatically tied to span creation though?

**Comment by edsrzf** [comment]
I'm not necessarily arguing for tying context to span creation, but I don't see the sense in returning the context from these functions. Contexts generally get passed down the call stack, but don't get passed back up again.

For argument's sake, let's say I don't want to attach a span to the context, but instead I want to add a parse time metric to the current span as you suggest. I might try something like this:

```go
func (tracer) StartOperationParsing(ctx context.Context) context.Context {
	// assume startTimer creates a new context with a timer
	ctx = startTimer(ctx)
	return ctx
}

func (tracer) EndOperationParsing(ctx context.Context) {
	duration := stopTimer(ctx)
	addSpanField(ctx, "operation-parse", duration)
}
```

This is all doable. And then `parseOperation` looks like this:

```go
func (gh *graphqlHandler) validateOperation(ctx context.Context, args *validateOperationArgs) (context.Context, *ast.OperationDefinition, map[string]interface{}, gqlerror.List) {
	ctx = gh.cfg.tracer.StartOperationValidation(ctx)
	defer func() { gh.cfg.tracer.EndOperationValidation(ctx) }()

	// ...

	return ctx, op, vars, nil
}
```

This `return` returns the context with the (used-up) timer still attached. Why is this useful? I guess in this case it's not doing any real harm except for having that extra layer of unnecessary context, but I can't see why you'd want it.

**Comment by edsrzf** [comment]
I looked into this a bit more and I think I have a better understanding of why this works the way it does, but I still disagree with it.

I can see that the Apollo tracer implementation in `gqlgen-contrib` treats `StartOperationParsing` as the [starting point for the entire trace](https://github.com/99designs/gqlgen-contrib/blob/c654377d611cfcf5b77012b5814af5a14a79bc86/gqlapollotracing/tracer.go#L40) and then treats `EndOperationExecution` as the [end of the trace](https://github.com/99designs/gqlgen-contrib/blob/c654377d611cfcf5b77012b5814af5a14a79bc86/gqlapollotracing/tracer.go#L104).

I would prefer to have some sort of `StartOperation` and `EndOperation` methods that clearly mark where the operation starts and ends rather than assuming it starts at `StartOperationParsing` and ends at `EndOperationExecution`. Then for my case I could either choose to add another span for `StartOperation` or just leave the method empty, and `parseOperation` and `validateOperation` could handle their contexts "normally".

**Comment by vektah** [comment]
Yeah I think your totally correct, the existing hook is serving two roles. The base context for the request, and timing. I'm happy to break these interfaces if we get a few heads in the game and figure out what's needed

**Comment by vektah** [comment]
I'm thinking as part of https://github.com/99designs/gqlgen/pull/885 I'm going to simplyfy the tracing right down to just collecting timing internally for parse/validate.

Thoughts? also @vvakame

**Comment by edsrzf** [comment]
Does that mean you'd _only_ allow collecting timing and remove the resolver tracing, or you'd leave the resolver tracing as is?

**Comment by vektah** [comment]
Nah, keep the resolver tracing, there needs to be enough to service [apollo tracing](https://github.com/apollographql/apollo-tracing)

The [tracer](https://github.com/99designs/gqlgen/blob/master/graphql/tracer.go#L9-L20) interface is pretty large - just hoping to trim a few off.

**Comment by vvakame** [comment]
hi, sorry for late response.

> Parsing, validating, and executing the query should all be on the same level, happening in series.

 I agreed.

My bad is embed operation wise object to context in StartOperationParsing.
https://github.com/99designs/gqlgen-contrib/blob/de8886ed1b47cdc8f3732441fbb449d7571fd5a0/gqlapollotracing/tracer.go#L34-L40
This code occurred that `parsing` level context propagate to `query` level.
gqlapollotracing tracer should be embed object at RequestMiddleware.
https://github.com/99designs/gqlgen-contrib/blob/master/gqlapollotracing/middleware.go

so, I looked https://github.com/99designs/gqlgen/pull/885 , It's nice.
I'll add some comments.

> I would prefer to have some sort of StartOperation and EndOperation methods

sounds good to me.
gqlapollotracing requires use `RequestMiddleware`, but it is not much clearly and developer tend to forget add middlewares.
