### ISSUE TITLE
remote schema

### ISSUE THREAD

**Issue by exfly** [99designs/gqlgen#827]
Need some help!
We have multiple graphql services, one of which needs to provide services externally. We don't want to re-generate some models in the gateway and re-implement the resolver but can access the functions implemented on other servers and not implemented on the gateway. Now we use the http proxy method to cal a graphlq query to forward to other services, and then return to the user, but this is equivalent to losing some of the gqlgen function.What elegant ways can we solve this problem?

like this https://www.apollographql.com/docs/graphql-tools/remote-schemas/
Thanks.

> ps: I am sorry that I have not described the problem in detail before.

#5

**Comment by JulienBreux** [comment]
You can create a script before schema generation to fetch your remote schema.

But I think that's not the role of `gqlgen` (as-code-generator).

Appollo is a full (server) framework.

Have a good day ;)
