### ISSUE TITLE
resolver of  schema "[User!]!"   is not []User but []*User, why?

### ISSUE THREAD

**Issue by zltgo** [99designs/gqlgen#830]
1)  I defined a schema as fllowing:

    type Store {
       id: ID!
       users(unscoped:Boolean! = false): [User!]!
    }

2)  go run github.com/99designs/gqlgen
    the generated resolver is:
    type StoreResolver interface {
	    Users(ctx context.Context, obj *model.Store, unscoped bool) ([]*model.User, error)
    }

why the return value is []*model.User, but not []model.User ?

thanks.

**Comment by bugzpodder** [comment]
https://github.com/99designs/gqlgen/issues/715
