### ISSUE TITLE
How to do field check？

### ISSUE THREAD

**Issue by maiguangyang** [99designs/gqlgen#835]
I tried using instructions and middleware, and I can't implement field validation. Is there an example?

The following example, it can still be updated into the database

```

type Task {
    title: String @length(min: 3, max: 7, message: "not valid")
}

func Length(ctx context.Context, obj interface{}, next graphql.Resolver, min int, max *int, message *string) (interface{}, error) {
    return nil, errors.New("error")
}

```

![image](https://user-images.githubusercontent.com/22783048/63152664-f0aebe80-c03e-11e9-9876-2755af28d80e.png)

![image](https://user-images.githubusercontent.com/22783048/63152681-fc9a8080-c03e-11e9-91bb-be7361a3acf2.png)

**Comment by vektah** [comment]
`type` is for returning data from the server, any directives here fire after the mutation has run and its response is available.

For input validation, you would need to put the directive on the mutation arguments (or define an `input` so you don't have so many params).
