### ISSUE TITLE
How to log schema errors using middleware?

### ISSUE THREAD

**Issue by pavan-sokke-nagaraj** [99designs/gqlgen#836]
### What happened?
For queries, when I pass data over schema, In `schema_gen.go` the schema errors are returned as part of response
```go
	return &graphql.Response{
		Data:       buf,
		Errors:     ec.Errors,
		Extensions: ec.Extensions,
	}
```
response
```json
{
  "errors": [
    {
      "message": "must not be null",
      "path": [
        "systems",
        "products",
        0,
        "id",
      ]
    },
  ],
  "data": {
    "systems": {
   ... partial valid data which matches schema...
  },
  "extensions": {
    "example": "value"
  }
}
```
### What did you expect?
I tried using middleware to log errors. But I could not find a proper solution.
https://gqlgen.com/reference/errors/#the-error-presenter
```go
handler.ErrorPresenter(
			func(ctx context.Context, e error) *gqlerror.Error {
				rctx := graphql.GetRequestContext(ctx)
				err:= graphql.DefaultErrorPresenter(ctx, e)
				log.Error(rctx.RawQuery +`   `+err.Error())
				return err
			}),
```
This will generate log for each error.

**Is there a way I can intercept a graphql response and log all result.errors?**

### versions
 - `gqlgen version`?   version = "0.9.1"
 - `go version`? go version go1.12.5 
 - dep or go modules?

**Comment by bugzpodder** [comment]
this may help you:
https://github.com/99designs/gqlgen-contrib/blob/master/prometheus/prometheus.go
