### ISSUE TITLE
Mutate schema using plugin

### ISSUE THREAD

**Issue by jakubknejzlik** [99designs/gqlgen#837]
### Question
Is it possible to change graphql schema in plugin’s mutate config method? Or maybe create new method to update schema.

### Reason
Allow creating plugins for stuff like Apollo federation support etc. which require changes to schema.

**Comment by bugzpodder** [comment]
see https://github.com/99designs/gqlgen/issues/740

**Comment by jakubknejzlik** [comment]
@bugzpodder thanks for pointing that out. I already know this issue, but I'm unable to figure out how to use plugin to change the schema (the apollo federation is just an example).

**Comment by vektah** [comment]
The WIP branch linked to in that issue is adding `InjectSchema` for plugins

https://github.com/99designs/gqlgen/compare/master...marwan-at-work:fed-wip#diff-6edbafe93c80509bb043690f2a456213R74

**Comment by jakubknejzlik** [comment]
Ah, didn't notice that. Thanks! 🙇
