### ISSUE TITLE
How to implement unmarshaler for external ObjectID in resolver.go

### ISSUE THREAD

**Issue by nigel-sperinck** [99designs/gqlgen#840]
I have built a gqlgen application reading from MongoDB. This is working with a single exception. The id is blank. 

MongoDB stores the ID as a primitive.ObjectID in data field _id.

If I update models_gen.go, from ID string `json:"_id" as follows:

ID string `json:"_id" bson:"_id"`

This change causes the following runtime error:

cannot decode objectID into a string type

If I update models_gen.go ID as primitive.ObjectID

This change causes the following runtime errors:

interface conversion: interface {} is primitive.ObjectID, not string

goroutine 422 [running]:
runtime/debug.Stack(0x1, 0x0, 0x0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/99designs/gqlgen/graphql.DefaultRecover(0xbdc760, 0xc0004675c0, 0x9dd360, 0xc0004675f0, 0xc0002f0c18, 0x40d069)
    /home/developer/projects/src/pkg/mod/github.com/99designs/gqlgen@v0.9.3/graphql/recovery.go:16 +0xa7
github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext)._Property_id.func1(0xc0001d31a0, 0xc0004bd390, 0xc0002f0d40)
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:325 +0xac
panic(0x9dd360, 0xc0004675f0)
    /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext)._Property_id(0xc0001d31a0, 0xbdc760, 0xc00047f6b0, 0xc000283000, 0x0, 0x0, 0x0, 0xc00035e690, 0x0, 0x0)
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:352 +0x637
github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext)._Property(0xc0001d31a0, 0xbdc760, 0xc00047f6b0, 0xc00035e4d0, 0x7, 0x7, 0xc00035e690, 0x20, 0xc0004cef50)
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:1870 +0x4a8
github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext).marshalNProperty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋexampleᚋPrototype_PropertyᚗNet1ᚐProperty(0xc0001d31a0, 0xbdc760, 0xc00047f6b0, 0xc00035e4d0, 0x7, 0x7, 0xc00035e690, 0xc0004ac6a0, 0x8)
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:2280 +0x163
github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext).marshalNProperty2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋexampleᚋPrototype_PropertyᚗNet1ᚐProperty.func1(0x2)
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:2260 +0x111
created by github.com/99designs/gqlgen/example/Prototype_Property%2eNet1.(*executionContext).marshalNProperty2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋexampleᚋPrototype_PropertyᚗNet1ᚐProperty
    /home/developer/projects/src/src/github.com/99designs/gqlgen/example/Prototype_Property.Net1/generated.go:2265 +0x299

Google shows the following links as an example of using an external ObjectID:

https://github.com/99designs/gqlgen/issues/712

https://github.com/99designs/gqlgen/blob/master/example/scalars/model/model.go

Would you be able to provide an example of how to implement the external ObjectID unmarshaler within the resolver.go?

**Comment by gissleh** [comment]
You need to make a pair of functions and hook them up with gqlgen.yml. There's examples for that in the docs:

https://gqlgen.com/reference/scalars/#custom-scalars-with-third-party-types
