### ISSUE TITLE
how to use CollectFieldsCtx in dataloader middleware

### ISSUE THREAD

**Issue by imjm** [99designs/gqlgen#842]
### What happened?
https://github.com/99designs/gqlgen/blob/master/example/dataloader/dataloaders.go#L28
following this dataloader example to make a middleware, however, we need call `CollectFieldsCtx` in the loader, and it does not work in the middleware before resolve has been created.

### What did you expect?
any way to use `CollectFieldsCtx` in the middleware?

### versions
 - `gqlgen version`? 0.9.1
 - `go version`? 1.12.9
 - dep or go modules? modules

**Comment by vektah** [comment]
you cant by design to avoid this issue:
 - user 1 queries for a post, only asks for { message, id }
 - user 2 queries for a post, asks for { message, author, id }, gets the cached object back that only has { message, id }
