### ISSUE TITLE
Stitching gqlgen subscription results in null resolved values

### ISSUE THREAD

**Issue by apoggi-carecloud** [99designs/gqlgen#844]
When schema stitching subscriptions into another service, subscription data received when connecting from the parent service comes back as null. We are using Apollo Server as our stitching client. Subscriptions work normally when connecting to the stitched service directly.

**Comment by raphaelvigee** [comment]
I'm experiencing the same issue, have you found a solution?

**Comment by apoggi-carecloud** [comment]
This was actually an issue with the graphql-tools dependency. There is an npm package called graphql-tools-fork that solved this is for me. Subscriptions were not respecting the schema transforms being applied in the gateway, causing data to not resolve properly.
