### ISSUE TITLE
Unexpected Name "fragment"

### ISSUE THREAD

**Issue by tobias-kuendig** [99designs/gqlgen#848]
### What happened?

Using the schema below, when I run `go run github.com/99designs/gqlgen` the following error occurs:

> schemaconfig: schema.graphql:6: Unexpected Name "fragment"

What am I missing? Fragments are supported, right?

### Minimal graphql.schema and models to reproduce

```graphql
type TreeNode {
    id: Int!
    children: [TreeNode!]
}

fragment TreeRecursive on TreeNode {
    id
    children {
        id
        children {
            id
            children {
                id
            }
        }
    }
}
```

### versions
 - v0.9.3
 - go version go1.12.5 linux/amd64
 - go modules

**Comment by vektah** [comment]
fragments are for queries, they arent a server feature.
