### ISSUE TITLE
Generate stubs for methods that do not exist in resolver

### ISSUE THREAD

**Issue by award28** [99designs/gqlgen#849]
### What happened?
When adding to schema and a resolver already exists, stubs are not added into the resolver

### What did you expect?
when rerunning `go run github.com/99designs/gqlgen` I expected stubs for new GraphQL objects to be added into the resolver

### Minimal graphql.schema and models to reproduce
? 

### versions
 - `gqlgen version`?  latest
 - `go version`? 1.12
 - dep or go modules? go mod

**Comment by vektah** [comment]
see https://github.com/99designs/gqlgen/issues/216
