### ISSUE TITLE
Customize the panic code

### ISSUE THREAD

**Issue by csilvers** [99designs/gqlgen#855]
We have a logrus logger that adds extra info to our log messages (notably the request-id).  On error, we use logger.Panic(...), instead of normal panic(), so the log message has this extra info.

We'd like to extend gqlgen so we can use logger.Panic in the generated graphql code as well.

My thought is there could a be a config option in the yaml file where you could specify (somehow) what function to call on panic.  That function must take two arguments, ctx and a panic messsage, and must terminate with a panic (something that can be recover-ed).  Then the gql codegen would use that config option in lieu of just calling panic(), if specified.

Does this make sense?  Is it something that you'd be likely to accept?  If so, I can work on creating a PR.  (Or feel free to do yourselves if you'd prefer!)

**Comment by vektah** [comment]
Have you seen https://gqlgen.com/reference/errors/#the-panic-handler?

**Comment by csilvers** [comment]
No!  Silly me.  It looks like that should work; I'll check and close this issue if so.

**Comment by bem7** [comment]
Just to pitch in, we're using a custom middleware to catch and handle panics for all our services (to get consistent panic handling). However, there's currently no way to disable gqlgen's panic recovery. As a workaround, we trigger a new panic in a custom panic handler, but it would be nice with a configuration to simply disable gqlgen's built-in panic handling (which would yield prettier stack traces).

**Comment by vektah** [comment]
> Just to pitch in, we're using a custom middleware to catch and handle panics for all our services (to get consistent panic handling). However, there's currently no way to disable gqlgen's panic recovery. As a workaround, we trigger a new panic in a custom panic handler, but it would be nice with a configuration to simply disable gqlgen's built-in panic handling (which would yield prettier stack traces).

Have you tested that panics don't kill your server @bem? gqlgen creates lots of goroutines internally and if a panic makes it back up to a root `go func()` go will kill the entire binary. middleware isn't enough, hence gqlgens panic handler.

**Comment by bem7** [comment]
@vektah We haven't yet seen our server crash on that account, but thanks for the heads up. Would it be very difficult to allow handling panics with a HTTP middleware? We're already using middleware for so many purposes – authentication, rate limiting, CORS, etc.

**Comment by vektah** [comment]
Not with multiple goroutines, any time a new goroutine is spawned it needs its own panic handler.
