### ISSUE TITLE
Make resolver return values configurable

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#856]
gqlgen generates `[]*Thing` instead of `[]Thing`.

It is debatable what to use, because different projects have different needs, and ORMs or libraries use either of the two methods.

This means that it's cumbersome to work with depending on your setup, which means it needs to be configurable.

At least, there should be a setting to generate slices of pointers or slices of arrays. Additionally, there may be a setting to also use a pointer or struct for single return values.

For info and discussion, see #375 & #738

**Comment by Invertisment** [comment]
Different wording of the same thing:
https://github.com/99designs/gqlgen/issues/793

**Comment by vektah** [comment]
see https://github.com/99designs/gqlgen/issues/738
