### ISSUE TITLE
Support adding additional headers in client

### ISSUE THREAD

**Issue by jamesabbottsmith** [99designs/gqlgen#857]
### What happened?
Current client implementation does not support adding additional Headers

### What did you expect?
The ability to set custom Headers using the client when making a req. 
This is handy for testing against GraphQL servers that have authentication.

For example

`client.Header.Add("authorization",` "abcd1234")`

(I've hacked it locally to make it work for me, happy to submit a PR. Should be backward compatible)

### versions
 - v0.9.3-dev
 - go version go1.13 darwin/amd64

**Comment by vektah** [comment]
Fixed by https://github.com/99designs/gqlgen/pull/861 in 0.10

**Comment by harmnot** [comment]
I got issue with this
here is my client:
```
	clientTest := client.New(handler.NewDefaultServer(resolver.NewExecutableSchema(config)))

```

when I mutation query which need header
```
	client.MustPost(
			mutation,
			&respond,
                       client.AddHeader("Token", TOKEN_HERE)
		)
```
It doesn't read my header at all, any idea ? I have look your PR and implement it, no luck to me 
I am using
`latest gqlgen`
`latest go version`

**Comment by lwc** [comment]
@harmnot how are you reading the header back into context? seems like you need some middleware to move the value from the http header into context?
