### ISSUE TITLE
Constraints for validation

### ISSUE THREAD

**Issue by patrickandroid** [99designs/gqlgen#868]
Hi, Is it currently possible to use constraints for validation, or does it require a plugin? This would be a nice feature to have. e.g

```
type SignUpInput {
  email: String! @constraint(format: "email", maxLength: 255)
  password: String! @constraint(maxLength: 255)
  firstName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
  lastName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
}
```

https://blog.apollographql.com/graphql-validation-using-directives-4908fd5c1055

**Comment by vektah** [comment]
Will be addressed via plugins - https://github.com/99designs/gqlgen/issues/228

**Comment by ravilution** [comment]
Hi @vektah 

I was able to achieve the `constraint` directive with the code below. However, I also want to sanitize my input values. How can I change the `obj` value that goes to the resolver inside the directive? For example, how can I change the input that comes into `lowercase`?

```go
func ConstraintDirective(ctx context.Context, obj interface{}, next graphql.Resolver, pattern string, max int, min int, isLower bool) (res interface{}, err error) {
	v := obj.(string)
	r := regexp.MustCompile(pattern)

	if !r.MatchString(v) || len(v) < min || len(v) > max {
		return nil, gqlerror.Errorf("format")
	}

	return next(ctx)
}
```

**Comment by Penthious** [comment]
@ravilution How did you get that to work?

I have
```
schema.graphql
directive @length(min: Int, max: Int) on INPUT_FIELD_DEFINITION
input NewMeetup @goModel(model: "github.com/penthious/go-gql-meetup/models.NewMeetup") {
    name: String! @length(min: 3)
    description: String!
}

```
and then I have
```
	c := go_gql_meetup.Config{
		Resolvers: &go_gql_meetup.Resolver{Domain: *g},
	}
	c.Directives.Length = func(ctx context.Context, obj interface{}, next graphql.Resolver, min *int, max *int) (interface{}, error) {

		return next(ctx)
	}
```
when I print out the `obj` it contains both the name and description when I only want the name
