### ISSUE TITLE
support variables or not?

### ISSUE THREAD

**Issue by lzxm160** [99designs/gqlgen#881]
### What happened?
using variables,but actual value is not passed:
```
query Query($address:String!){
  x{
    byAddress(address: $address){
    }
    }
  }
}
 { "address": "xxxxx"} 
```
passed address is "$address",not "xxxxx"
### What did you expect?
address="xxxxx"
### versions
 - `gqlgen version`?  0.8.3
 - `go version`?go1.12.5
 - dep or go modules?

does this version support variables or not,or need users to parse? where can find an example?

**Comment by vektah** [comment]
It should, we use variables everywhere. Are you running a gqlgen server or calling the parser directly?

**Comment by lzxm160** [comment]
> a gqlgen server

a gqlgen server,can you give me an example for gqlgen parse variables ?I use graphql.CollectFieldsCtx and graphql.CollectFields cannot get the right value

**Comment by vektah** [comment]
Why do you need to use CollectFields? It's a low-level API that should only be needed for special cases like ORM field optimizations. 

Resolvers should get their arguments as simple params, eg the id here:
https://github.com/99designs/gqlgen/blob/master/example/todo/todo.go#L76

Have you read https://github.com/99designs/gqlgen#how-do-i-prevent-fetching-child-objects-that-might-not-be-used? I think that might be whats tripping you up.

**Comment by lzxm160** [comment]
It's recursived schema:
type Query {
    account: Account
}
type Account {
    activeAccounts(count: Int!): [String!]
    alias(operatorAddress: String!): Alias
    operatorAddress(aliasName: String!): OperatorAddress
}

change gqlgen.yml could work for this kind of schema?
# gqlgen.yml
models:
  User:
    fields:
      friends:
        resolver: true # force a resolver to be generated

**Comment by vektah** [comment]
Yep, you want a resolver for anything that goes back to the database.
