### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by CelsoSantos** [99designs/gqlgen#884]
Hello everyone,

Has anyone considered Bazel support/Bazel rules in order to execute gqlgen?
My platform is entirely built with Bazel and I don't see any Bazel rules that would execute gqlgen on github or any other place like the docs. A Google search also didn't return anything.

So, is there any WIP towards this or would contributions be welcomed to tackle this scenario?

**Comment by vektah** [comment]
What would be required to support bazel? I'm not very familiar with it.

Usually, we commit all generated code so and keep it in sync by checking in CI that it is up to date. Wouldnt that mean this would use a standard go setup.

**Comment by CelsoSantos** [comment]
In terms of gqlgen, I don't thinks it's necessary to do much (if anything).

However, this would probably be a new project/repo with Bazel rules that, effectively, would do the same job as `gqlgen init`.

Meanwhile, while continuing digging on Google, I did find what looks like it's an initial approach to this right here (though I can't find any GH repo for it): https://stackoverflow.com/questions/57482616/trying-to-write-a-custom-rule
