### ISSUE TITLE
Value of an inline argument passed as a variable

### ISSUE THREAD

**Issue by thepatrik** [99designs/gqlgen#890]
Let me start off with a big kudos for the awesome library you have built!

I am struggling with extracting data from an inline argument when it is being passed as a variable. The query looks like this:
```
query($sid: String) {
  lists {
    items(storeId: $sid) {
      itemNo
    }
  }
}
```

Variables:
```
{
  "sid": "123"
}
```

When I try to get hold of the passed variable in the resolver with:
```
for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
    for _, a := range f.Arguments {
        if a.Name == "storeId" {
            fmt.Println(a.Value)
        }
    }
}
```

...I get the name of the variable: "$sid" and not "123". Perhaps I am getting it all wrong, but how do I extract the value of the variable?

### versions
 - `gqlgen v0.10.1`
 - `go1.13`
 - dep or go modules: go modules

**Comment by danishsatkut** [comment]
Please try:

```
for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
    if f.Name == "items" {
        args := field.ArgumentMap(graphql.GetRequestContext(ctx).Variables)

        if v, ok := args["storeId"].(string); ok {
          fmt.Println(v)
        }
    }
}
```

**Comment by vektah** [comment]
Are you sure you need to pull the value out of context? Unless you are writing optimized database mapping code you shouldn't need to use that API. 

Have you read https://github.com/99designs/gqlgen#how-do-i-prevent-fetching-child-objects-that-might-not-be-used?

related to https://github.com/99designs/gqlgen/issues/881

**Comment by thepatrik** [comment]
Thanks @vektah! Generating a new resolver makes more sense in this case.
