### ISSUE TITLE
When one or more of multi queries returns error, none of queries are returned

### ISSUE THREAD

**Issue by edin-coralic** [99designs/gqlgen#892]
### What happened?
When making one request with multiple queries, and one of this queries returns error, whole request fails, even for queries that returned valid response.

```json
{
  "errors": [
    {
      "message": "error B",
      "path": [
        "b"
      ]
    }
  ],
  "data": null
}
```

### What did you expect?
Return data for all queries that don't have error.

```json
{
  "errors": [
    {
      "message": "error B",
      "path": [
        "b"
      ]
    }
  ],
  "data": {
    "a": {
      "id": "ID for A"
    }
  }
}
```

### Minimal graphql.schema and models to reproduce

request:
```
{
  a { id }
  b { id }
}
```

schema.graphql
```graphql
type WithoutError {
  id: ID!
}
type WithError {
  id: ID!
}
type Query {
  a: WithoutError!
  b: WithError!
}
```

resolver.go
```go
func (r *queryResolver) A(ctx context.Context) (*WithoutError, error) {
	return &WithoutError{"ID for A"}, nil
}
func (r *queryResolver) B(ctx context.Context) (*WithError, error) {
	return nil, errors.New("error B")
}
```

### versions
 - `gqlgen version`? v0.10.1
 - `go version`? v1.13.1 
 - dep or go modules? go mod

**Comment by edin-coralic** [comment]
I know this could be "solved" with non-mandatory returns on queries, but we would like to preserve mandatory returns on our queries/mutations.

schema.graphql
```graphql
type WithoutError {
  id: ID!
}
type WithError {
  id: ID!
}
type Query {
  a: WithoutError!
  b: WithError!
}
```

resolver.go
```go
func (r *queryResolver) A(ctx context.Context) (*WithoutError, error) {
	return &WithoutError{"ID for A"}, nil
}
func (r *queryResolver) B(ctx context.Context) (*WithError, error) {
	return nil, errors.New("error B")
}
```

request:
```
{
  a { id }
  b { id }
}
```

response:
```
{
  "errors": [
    {
      "message": "error B",
      "path": [
        "b"
      ]
    }
  ],
  "data": {
    "a": {
      "id": "ID for A"
    },
    "b": null
  }
}
```

**Comment by danishsatkut** [comment]
@edin-coralic This behaviour is in accordance with [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors):

> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.
