### ISSUE TITLE
Visual Studio Code extensions (with formatter) for .graphql files

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#893]
I was wondering about an extension with linting and formatting in VS Code for `schema.graphql` files.

It is difficult to find out a good one. Can you suggest something?

**Comment by olivierlemasle** [comment]
"Apollo GraphQL" plugin works well for me: https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo

**Comment by yuya-kanai** [comment]
I couldn't find a formatter for graphql but I used [better align](https://marketplace.visualstudio.com/items?itemName=wwm.better-align) and it seems to work fine.
However I haven't yet figured out how to automatically run it on save.

**Comment by BitPhinix** [comment]
Prettier should work as well (https://github.com/prettier/prettier-vscode/issues/989)

**Comment by vektah** [comment]
Maybe try over at https://github.com/microsoft/vscode

**Comment by zyllus17** [comment]
You can use [Prettier - Code formatter extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#:~:text=Prettier%20is%20an%20opinionated%20code,account%2C%20wrapping%20code%20when%20necessary.) on VSCode, the latest version supports GraphQL formatter as shown in the pic below.

<img width="1440" alt="Screenshot 2022-11-23 at 7 57 55 PM" src="https://user-images.githubusercontent.com/50977126/203571686-7ea7f844-5f4e-4d31-a0ea-c0d0939196a3.png">

**Comment by nguyentruongtoan1309** [comment]
Now I use extension "vscode-graphql", and it work in my case: https://marketplace.visualstudio.com/items?itemName=luyizhi.vscode-graphql 
I hope it can help you.
