### ISSUE TITLE
Nondeterministic output when query and subscription return (non)nullable list elements

### ISSUE THREAD

**Issue by zannen** [99designs/gqlgen#896]
With the schema below, output is nondeterministic.

This behaviour occurs when a query returns a list of nullable things and a subscription returns a list of non-nullable things (or vice versa), the generated code for the _subscription_ (it seems to always be the subscription) flips between using the normal function (`marshalOThing2ᚖgqlgentestᚐThing`) and the function with the null check (`marshalNThing2ᚖgqlgentestᚐThing`).

This behaviour does **not** occur:
* with _two queries_, one returning `[Thing]` and one returning `[Thing!]`
* with _two subscriptions_, one returning `[Thing]` and one returning `[Thing!]`
* with one query and one subscription, if _`Thing` is replaced by `String`_

### What did you expect?
Deterministic output.

### Minimal graphql.schema to reproduce
```gql
schema {
  query: Query
  subscription: Subscription
}

type Thing {id: Int}

type Query {
  things1: [Thing] # Note the "!" or lack thereof.
}

type Subscription {
  things2: [Thing!] # Note the "!" or lack thereof.
}
```

### gqlgen.yml
```yaml
---
schema: graphql.schema
exec:
  filename: generated.go
model:
  filename: models.go
```

Here's the script I've been using to test. Run it and wait for a while to see if files with different checksums get created.

```bash
rm -f *generated.go
while test "$(find -name '*-generated.go' | wc -l)" -lt 2 ; do
  date
  gqlgen -c gqlgen.yml
  cp -a generated.go "$(md5sum generated.go | awk '{print $1}')-generated.go"
  sleep 1
done
```

### versions
 - `gqlgen version` v0.10.1
 - `go version` go1.11.13 linux/amd64
 - dep or go modules? go modules: `go.mod`
    ```
    module gqlgentest
    
    require (
    	github.com/99designs/gqlgen v0.10.1
    	github.com/vektah/gqlparser v1.1.2
    )
    ```

**Comment by alexsn** [comment]
I have the exact some issue.

**Comment by zannen** [comment]
The template creating the code line that flips is [codegen/type.gotpl L93](https://github.com/99designs/gqlgen/blob/master/codegen/type.gotpl#L93).

**Comment by zannen** [comment]
PR https://github.com/99designs/gqlgen/pull/900 should fix this.

**Comment by colinschoen** [comment]
Pretty sure I am running into this too. Thanks for the PR @zannen.

**Comment by zannen** [comment]
Thanks @vektah.
