### ISSUE TITLE
Question: Suggestions on Documentation strategies?

### ISSUE THREAD

**Issue by qhenkart** [99designs/gqlgen#901]
This is more of an open-ended question. I'm curious how people manage documentation with the graphql playground. Obviously documentation is quite easy with the graphql playground, however we've found that adding the amount of documentation we need to replace our deprecated swagger docs, e.g explaining filters, authorization, usage etc, it makes the schema very difficult to read.

I was wondering if anyone has any strategies to manage this. I was considering working on a side project to decouple the documentation from the schema file and combine it during generation

**Comment by JulienBreux** [comment]
Hello @qhenkart 👋 

Personally, I use this project to external documentation ; https://github.com/2fd/graphdoc

Because I like the Github documentation way ; https://developer.github.com/v4/

But it necessarily to be strict on doc.

```
"User represents the user of my awesome app."
type User {
  "User's firstname."
  firstname: String!
}

//...
```

**Comment by qhenkart** [comment]
@JulienBreux wow thank you so much. Exactly what I was looking for!

**Comment by JulienBreux** [comment]
> @JulienBreux wow thank you so much. Exactly what I was looking for!

Sound good to me! Have a good day!
