### ISSUE TITLE
StartOperationParsing not called on subscriptions

### ISSUE THREAD

**Issue by jacksontj** [99designs/gqlgen#903]
### What happened?
I enabled tracing on my gqlgen server which had a Subscription added to it. After doing so I immediately hit https://github.com/99designs/gqlgen-contrib/issues/10 -- which stems from the fact that `StartOperationParsing` is never called for Subscription calls. It seems that the websocket handler has its own query parsing (separate from the [the on in graphql.go](https://github.com/99designs/gqlgen/blob/master/handler/graphql.go#L578) which starts the trace).

### What did you expect?
I would expect that `StartOperationParsing` would still be called in subscriptions (since request parsing, etc. still happens).

**Comment by jacksontj** [comment]
This is still an issue, so it shouldn't be marked stale

**Comment by vvakame** [comment]
We have a big change in #885 .
I think this issue will be fixed in master / HEAD.
