### ISSUE TITLE
How to get the field names of directives?

### ISSUE THREAD

**Issue by yuya-kanai** [99designs/gqlgen#906]
### What happened?
```
directive @isID on FIELD_DEFINITION
type Salesperson {

	Name  : String!
	Age: Int! 
	UserID: Int! @isID
}
```
For something like this, with directive `IsID` how would you get `'UserID'` as a string?
I can get the entire field with obj,  or the value of UserID but that is not enough to infer `'UserID'` 

`UserID: Int! @isID(FieldName:"UserID")`
This seems to be the best I can do.

### versions
 - `gqlgen version`? v0.10.1-dev
 - `go version`? go version go1.12.7 linux/amd64
 - dep or go modules? mod

**Comment by JulienBreux** [comment]
Hi @yuya-kanai 👋 

You can't read this info in the `ctx context.Context`?

**Comment by yuya-kanai** [comment]
Thank you @JulienBreux that worked

I guess it was mentioned [here](https://gqlgen.com/reference/field-collection/) in the documentation.
I completely went past it.
I'll leave a minimum code for the directive implementation for anybody with the same issue

```
import "github.com/99designs/gqlgen/graphql"
c.Directives.IsID = func(ctx context.Context, obj interface{}, next graphql.Resolver) (interface{}, error) {
		ctxValue := graphql.GetResolverContext(ctx)
		fmt.Printf("context: %#v\n", ctxValue)
}
```

**Comment by yuya-kanai** [comment]
`graphql.GetResolverContext(ctx).Object` returns 'Salesperson' not UserID and
`graphql.CollectAllFields(ctx)` returns empty array.

**Comment by o1egl** [comment]
Based on docs https://gqlgen.com/reference/directives/ 
```
- obj: the object containing the value this was applied to, eg:
for field definition directives, the object/input object that contains the field
for argument directives, a map containing all arguments
```
but I see in generated code that obj is always set as nil. Looks like it is a bug

**Comment by yuya-kanai** [comment]
@o1egl Thanks. Good to know it's a bug.

@vvakame Thanks for the label, also your MTC2018 blog was amazing (sorry for off topic)

**Comment by dtrckd** [comment]
Hello,
Any upcoming news about this bug ?
Or  is there any reason why the field name of the given directive shouldn't be visible from directive resolver ???
