### ISSUE TITLE
 Input types: cant use methods for setters

### ISSUE THREAD

**Issue by jszwedko** [99designs/gqlgen#909]
Copied from #506 which was closed by stalebot. Hopefully this is an ok practice as this issue is still very relevant to us as well (seemingly also to others based on the other comments and emoji reactions).

It is relevant to us specifically as a solution to #505 

> ### Expected Behaviour
> 
> As per https://gqlgen.com/reference/resolvers/ for types to bind to a method, I want to have the same ability for inputs.
> ### Actual Behavior
> 
> gqlgen errors out.
> ### Minimal graphql.schema and models to reproduce
> 
> It should be possible to define
> 
> ```
> type SomeInput struct {
> 	ID string `json:"id"`
> }
> 
> func (i *SomeInput) SomeField(v string) {
> }
> ```
> 
> to be able to set `SomeField: String!` through a method.
> 
> On a side note: This is one potential solution to #505 because we then know if the field has been specified or not.

**Comment by vvakame** [comment]
I just reopened #506 & close this issue. thanks!
