### ISSUE TITLE
Exclude Trivial Resolvers from Tracing

### ISSUE THREAD

**Issue by cliedeman** [99designs/gqlgen#914]
### What happened?
Implemented Tracing. 

![Screenshot 2019-10-27 at 16 01 04](https://user-images.githubusercontent.com/3578740/67635795-1ffd6980-f8d3-11e9-9834-1aeb826b547e.png)

### What did you expect?
A way to reduce the noise by removing trival resolvers or simple struct lookup resolvers.
 
The simplest solution seems to be wrapping the trace methods for field in a conditional using this [expression](https://github.com/99designs/gqlgen/blob/master/codegen/field.gotpl#L20)

Open Questions:
What happens if there are resolvers lower down in the tree

```
type Query {
  viewer: Viewer!
}

type Viewer {
  user: User! # struct value
}

type User {
  username # struct value
  email # struct value
  balance # expensive call
}
```

If The user field span is removed will that break existing tracing

**Comment by vektah** [comment]
0.11 removes tracing middleware, replacing it with exposed timing information and better metrics out of fields.

see https://github.com/99designs/gqlgen/blob/master/graphql/handler/apollotracing/tracer.go

**Comment by cliedeman** [comment]
@vektah Thanks. But I would still like to exclude tracing information from scalar retrieval at template generation time.

**Comment by vektah** [comment]
you can use `graphql.GetFieldContext(ctx).IsMethod` to determine if the current field might have some code. 

This doesn't really help though, as there are plent of trivial resolver methods (eg no db access, just returning another property or turning an int to a string). For those you're better looking at the wall time and setting a threshold then simply dropping spans that don't meet the threshold.

**Comment by cliedeman** [comment]
@vektah Ah thanks I see now.

I see in master you removed the timing checks due to performance. 
Thats sort of the same problem of trying to solve.

For example we could possible [revert](https://github.com/99designs/gqlgen/commit/631b48a56ac159cd03dbc67e15f4a8dfef7dc266#diff-c8f84f9dafb0af18ac536c527135d68d) if it was not executed on leaf nodes.

I created a sample PR to see how the above idea would work with the current extension style - #1021

Ciaran

**Comment by vektah** [comment]
You probably don't even need resolver spans, as long as you are tracing everything on the way out. There's great go middleware for wrapping db/api calls etc.

With **no resolver spans at all**:
![image](https://user-images.githubusercontent.com/2247982/74100909-f0275880-4b87-11ea-8f2f-0dfc2fd24566.png)
