### ISSUE TITLE
a variable named `if`

### ISSUE THREAD

**Issue by jney** [99designs/gqlgen#925]
### What happened?

When running `go run github.com/99designs/gqlgen -v`, I've got the following error:

```
gofmt failed on generated.go: /.../graphql/generated.go:61:76: expected 'IDENT', found 'if' (and 1 more errors)
```

Indeed, a generated variable is named `if`. `generated.go`:

```go
type DirectiveRoot struct {

	Deprecated func(ctx context.Context, obj interface{}, next graphql.Resolver, reason *string) (res interface{}, err error)

	Include func(ctx context.Context, obj interface{}, next graphql.Resolver, if bool) (res interface{}, err error)

	Skip func(ctx context.Context, obj interface{}, next graphql.Resolver, if bool) (res interface{}, err error)

}
```

### What did you expect?

Generated variables shouldn't use keywords

### versions
 - `gqlgen version`? `v0.10.1`
 - `go version`? `go version go1.13.4 darwin/amd64`
 - dep or go modules? modules

**Comment by danabrams** [comment]
Having the same issue on Fedora 30

**Comment by MShoaei** [comment]
Could you try creating an empty project wich includes just a .yaml file to begin with? I did get this error a while ago and fixed it by re creating almost everything😝. I suggest copying all the logic and after re-creating the boiler plates move the logic back.

**Comment by danabrams** [comment]
For me, at least, this occurs when following the tutorial at https://gqlgen.com/getting-started/, starting from scratch.
