### ISSUE TITLE
Can Client MustPost also send back HeadersMap

### ISSUE THREAD

**Issue by ravilution** [99designs/gqlgen#928]
https://github.com/99designs/gqlgen/blob/9cfd817e013b951206bc969ba517c98ff208a11c/client/client.go#L88

Can we also send back the `HeadersMap` in addition to the JSON response? I want to read `SET-COOKIE` value. I am sure others would want to read other forms of header tokens.

**Comment by ravilution** [comment]
I was thinking of adding two variables in `Client struct {
		h    http.Handler
		opts []Option
	}` and assigning `w` and `r` after line number 89.  The change is simple and whoever needs the final raw request and raw response object can access it. What do you think?

**Comment by vektah** [comment]
Client probably isnt the right spot, it can send many requests.

What about something like this:
```go
	Request struct {
		Query         string                 `json:"query"`
		Variables     map[string]interface{} `json:"variables,omitempty"`
		OperationName string                 `json:"operationName,omitempty"`
		HTTP          *http.Request          `json:"-"`

		ResponseVisitor []func(w *httptest.ResponseRecorder)
	}
```
so that Options could do things like

```go
func GetHeaders(headers *http.Header) Option {
	return func(r *http.Request) {
		r.InterceptResponse(func(w httptest.ResponseRecorder) {
			headers = &w.Headers()
		}
        }
}
```

used like
```go
var headers *http.Header
c.MustPost(`{ whatever }`, client.GetHeaders(&headers))

require.Equal(t, "asdf", headers["Set-Cookie"))
```

**Comment by ravilution** [comment]
I like your solution. It is elegant.

**Comment by ravilution** [comment]
I ended up find a solution where I don't rely on Response Headers for testing. However, It will be great if we add this PR.
