### ISSUE TITLE
Resusing generated structs in tests

### ISSUE THREAD

**Issue by hcliff** [99designs/gqlgen#934]
### What happened?
It's difficult/impossible to use existing models in tests when using custom types

### What did you expect?

```
import gqlclient "github.com/99designs/gqlgen/client"
resp := OrganisationsConnection{}
gqlc = gqlclient.New(server, gqlclient.Path("/v4.0/query"))
gqlc.MustPost(`{organisationsConnection(first:3, after:0){
			totalCount,
				organisations{
					id,
				},
}}`, &resp)
```
should work, however 
1) the `unpack` method uses json tags, not gqlgen tags (manageable)
2) the unpack method does respect custom unmarshallers, which breaks any custom scalars and in my case my integer ID

love the library, really appreciate the work :)

**Comment by sobiso** [comment]
Can you put some details about this 'server' variable` ? Server with graphql should working ?
