### ISSUE TITLE
[FAILURE] go get github.com/99designs/gqlgen

### ISSUE THREAD

**Issue by kevin-kraus** [99designs/gqlgen#935]
### What happened?
Install by `go get github.com/99designs/gqlgen` fails with the following error:
`# github.com/99designs/gqlgen/cmd
../../99designs/gqlgen/cmd/gen.go:17:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
 cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/gen.go:18:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
 cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/gen.go:20:2: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
../../99designs/gqlgen/cmd/init.go:61:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
 cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/init.go:62:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
 cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/init.go:63:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
 cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/init.go:64:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
 cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../../99designs/gqlgen/cmd/init.go:66:2: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
../../99designs/gqlgen/cmd/root.go:34:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
../../99designs/gqlgen/cmd/version.go:13:2: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
../../99designs/gqlgen/cmd/root.go:34:15: too many errors`
### What did you expect?
Installation succeeds.
### Minimal graphql.schema and models to reproduce
None.
### versions
 - `gqlgen version`? 
 **Installation fails, so no version.**
 - `go version`?
 **go version go1.13.4 linux/arm**

**Comment by vektah** [comment]
Dont use go get unless you are using go modules, gqlgen has pinned dependencies.

https://gqlgen.com/getting-started/
