### ISSUE TITLE
Support Casbin as the ACL/RBAC/ABAC authorization solution for GraphQL

### ISSUE THREAD

**Issue by hsluoyz** [99designs/gqlgen#937]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (Gorm or Xorm or any popular DBs).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security to this project. It is also a request from our user: https://github.com/casbin/casbin/issues/327.

Let me know if there's any question:) Thanks.

**Comment by hsluoyz** [comment]
@vvakame any update?

**Comment by vvakame** [comment]
I don't have interest for it now, sorry.
@vektah how about you?

someone make auth middleware with casbin, I think we write useful link on https://gqlgen.com/recipes/authentication/ . 👍

**Comment by kejiro** [comment]
I don't think that authorization belongs in the graphql layer at all. 
Graphql.org makes a good case for why (https://graphql.org/learn/authorization/)

But it's also easy to add without locking down to a specific authorization framework:

```go
func main() {
	router := chi.NewRouter()

	router.Use(auth.Middleware(db))
        enforcer, _ := casbin.NewEnforcer("model.conf", "policy.csv")

	router.Handle("/", handler.Playground("Starwars", "/query"))
	router.Handle("/query",
		handler.GraphQL(
                     starwars.NewExecutableSchema(starwars.NewResolver()),
                     handler.RequestMiddleware(authorization(enforcer)),
                ),
	)

	err := http.ListenAndServe(":8080", router)
	if err != nil {
		panic(err)
	}
}

func authorization(enforcer *casbin.Enforcer) graphql.RequestMiddleware {
	return func(ctx context.Context, next func(ctx context.Context) []byte) []byte {
		return next(auth.WithEnforcer(ctx, enforcer))
	}
}

func (r *queryResolver) Hero(ctx context.Context, episode Episode) (Character, error) {
	if user := auth.ForContext(ctx) ; user == nil {
		return Character{}, fmt.Errorf("Access denied")
	}
        enforcer := auth.EnforcerContext(ctx)
        if granted, err := enforcer.Enforce(user, "hero", "read"); !granted || err != nil {
		return Character{}, fmt.Errorf("Insufficient privileges")
        } 

	if episode == EpisodeEmpire {
		return r.humans["1000"], nil
	}
	return r.droid["2001"], nil
}
```

**Comment by vektah** [comment]
Yeah, I think this is outside of gqlgens responsibility, as long as we provide the right hooks that let you build it (directives and middleware)

**Comment by hsluoyz** [comment]
Here's an example of integrating Casbin into gqlgen: https://github.com/WenyXu/gqlgen_casbin_RBAC_example
