### ISSUE TITLE
Getting Started guide should be updated to reflect deprecation of handler.Playground method

### ISSUE THREAD

**Issue by tgrander** [99designs/gqlgen#949]
### What happened?
Starting the server using `go server/server.go` with the code from the [Getting Started](https://gqlgen.com/getting-started/) guide in docs throws an error that `handler.Playground` is undefined. I went into the source code and saw comment that `handler.Playground` has been deprecated and to use `playground.Handler` function. 

### What did you expect?
The code in the getting started guide to work as is.

### versions
 - `gqlgen version`: v0.10.2
 - `go version`: 1.13
 - dep or go modules? neither

**Comment by vektah** [comment]
If you follow the guide (using go mod) you should get the latest stable version, and the docs are for the latest stable version.

If you're on master you will need to use the master docs https://gqlgen.com/master/getting-started/
