### ISSUE TITLE
using interfaces as models fails.

### ISSUE THREAD

**Issue by jacklaaa89** [99designs/gqlgen#955]
### What happened?
Generating code from a schema succeeds but I am unable to run the generated code because it fails to compile. I use an interface as a type declared in the gqlgen.yml file and then have two different concrete implementations of that interface. It used to compile correctly prior to v0.10.2
### What did you expect?
I expected to be able to compile and run the generated code.
### Minimal graphql.schema and models to reproduce
**schema.graphql**
```
type Object {
    field: String!
}

type Interface {
    object: Object!
}

type Query {
    interface(typ: String!): Interface!
}
```
**gqlgen.yml**
```
models:
   Object:
       model: example/code.Object
   Interface:
       model: example/code.Interface
```
**model.go**
```go
package code

import "context"

type Object struct {
     Field string `json:"field"`
}

type Interface interface {
    Object() (Object, error)
}

type A struct {}
func (a *A) Object() (Object, error) {
    return Object{Field: `A`}
}

type B struct {}
func (b *B) Object() (Object, error) {
    return Object{Field: `B`}
}

type QueryResolver struct {}
func (QueryResolver) Interface(_ context.Context, typ string) (Interface, error) {
     switch typ {
     case `A`:
         return &A{}
     case `B`:
         return &B{}
     }
}
```

I seem to be getting an error similar to:
```
example\code\generated.go:<line>:<char>: cannot use v (type code.Interface) as type *code.Interface in argument to ec._Interface:
	*code.Interface is pointer to interface, not interface
```

Code similar to this is correctly working on v0.9.3, but failed to compile when I upgraded to v.10.2

### versions
 - `gqlgen version`?  v.0.10.2
 - `go version`? v.1.13.5
 - dep or go modules? go modules

**Comment by MichaelMure** [comment]
I think I have the same problem here: https://github.com/99designs/gqlgen/issues/920

It's fairly annoying as it restrict what gqlgen can do and when trying to get around it cascade relatively quickly into an intricate mess.
