### ISSUE TITLE
handler.ErrorPresenter not getting called when invalid mutation name sent

### ISSUE THREAD

**Issue by aschade92** [99designs/gqlgen#962]
### What happened?

schema validation error doesn't call error presentor. This is problematic because a bug in production wasn't being logged because the wrong mutation name was being used.

### What did you expect?

that the `graphql.ErrorPresenterFunc` would be called after this type of query or schema validation error happens.

### Minimal graphql.schema and models to reproduce

schema
```
type Query {
    """
    placeHolder is just a placeholder since we need a method defined for gqlgen to be able to build
    """
    placeHolder: Boolean!
}

type Mutation {
    test(input: Boolean!): Boolean
}
```

server:
```
package main

import (
	"context"
	"log"

	"github.com/99designs/gqlgen/handler"
	"github.com/gin-gonic/gin"
	"github.com/vektah/gqlparser/gqlerror"
)

// Defining the Graphql handler
func graphqlHandler() gin.HandlerFunc {
	schema := NewExecutableSchema(Config{
		Resolvers: &Resolver{},
	})
	// NewExecutableSchema and Config are in the generated.go file
	// Resolver is in the resolver.go file
	h := handler.GraphQL(schema,
		handler.ErrorPresenter(graphqlError),
	)

	return func(c *gin.Context) {
		h.ServeHTTP(c.Writer, c.Request)
	}
}

func graphqlError(ctx context.Context, e error) *gqlerror.Error {
	log.Printf("error found: %v", e)
	return nil
}

func main() {
	// Setting up Gin
	r := gin.Default()
	r.POST("/query", graphqlHandler())
	r.Run()
}
```

send any query to `http://localhost:8080` that uses an invalid mutation name, ie the following query:
```
# Write your query or mutation here
mutation {
  wrongMutationName(input:true)
}
```

the following is returned from the handler:

```
{
    "errors": [
        {
            "message": "Cannot query field \"wrongMutationName\" on type \"Mutation\".",
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ]
        }
    ],
    "data": null
}
```
but i would also expect that the error presenter would also get called for logging purposes. in the test example above nothing gets logged.

### versions
 - `gqlgen version`? 
0.10.2
 - `go version`?
go version go1.12.5 darwin/amd64
 - dep or go modules?
dep

**Comment by sdalezman** [comment]
Hi gqlgen team - 

Not being able to get the final error that gqlgen is rendering into the handler is actually pretty problematic. We had a bug that went out bec our monitoring couldn't capture all errors that gqlgen renders. 

Understand that the presenter is probably limited to the methods on the resolver - but that means we can't handle all errors in gqlgen. 

We're happy to help fix this issue, but before we do we want to confirm that all errors flowing through the handler should call the error presenter?

**Comment by vektah** [comment]
The new 0.11 transports dispatch errors back into the presenter - https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_post.go#L47
