### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by landrade** [99designs/gqlgen#964]
Hi There! 

I'd like to know how is your development workflow with Gqlgen. 

In my current project, we are keeping intact the generated resolvers file and copy the content to another file manually. In every schema change, we run `git diff` on the generated file to find the differences and apply them in our copy. The problem is the manual action to change/add/remove in our copy.

There is something more painless than my workflow or maybe more "magical"? 

[]'s

**Comment by ramonberrutti** [comment]
Hi,

I only generate the models and the exec (core code), so it is the same as gRPC.
Then I use the generated Interfaces for the implementation.

You don’t need to keep the resolver. If you add a new function, and not implemented, your code will not compile (missing implementation), also if you change a parameter or type.

**Comment by fwojciec** [comment]
I also keep a copy of the generated resolvers file for reference. I apply the updates/changes by hand in my own implementation of the resolvers and usually also update/write new tests at the same time. Yes, it's a bit of manual work, but it's never seemed like too much of a chore.

**Comment by Niondir** [comment]
I would like some generated interface assertion because my IDE (GoLand) can then auto implement missing methods.

For now I'm adding them my self.

**Comment by vektah** [comment]
Fixed in https://github.com/99designs/gqlgen/pull/993
