### ISSUE TITLE
Generate invalid code when using not alphabetical names or reserved keywords

### ISSUE THREAD

**Issue by ramonberrutti** [99designs/gqlgen#966]
### What happened?
```shell
schemagen/generated.go:249:48: methods must have a unique non-blank name
schemagen/generated.go:582:27: cannot refer to blank field or method
```

```golang
type EmptyResolver interface {
	_(ctx context.Context, obj *Empty) (*bool, error)
}
```

### What did you expect?
A valid function.
We can try to generate a random function.
```
[name]_[UUIDRANDOM]()
```
```
__969befec_486c_4ad4_9045_38b5920c7b8d()
```

Also, if you use a Golang keyword like if it gives problems.
and we can use this also
```
if_969befec_486c_4ad4_9045_38b5920c7b8d()
```

and if we don’t want to be more deterministic, we can use
```
[name]_gqlgen()
```

### Minimal graphql.schema and models to reproduce
```graphql
type Empty {
    _: Boolean
}
```

### versions
 - gqlgen version: v0.10.2
 - Go Version: 1.13
 - Go Modules

**Comment by danteay** [comment]
This sthill happening!!!
