### ISSUE TITLE
What about generate CRUD method and types?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#968]
Have you ever considered generating CRUD methods (and types) for entities defined in the schema?

- roughly like json-graphql-server (https://github.com/marmelab/json-graphql-server): they start from a .json file

- or like graphback (https://github.com/aerogear/graphback)

Am I wrong?

**Comment by vektah** [comment]
Out of scope for gqlgen. Try prisma or postgraphile.
