### ISSUE TITLE
Decoding incoming request via middleware

### ISSUE THREAD

**Issue by genert** [99designs/gqlgen#971]
I was wondering if there was any way to decode incoming HTTP request? See this article - https://itnext.io/graphql-data-hiding-using-apollo-stack-ad1ea92fa85c

The idea is fairly simple: use middleware and within that detect based on Content-Transfer-Encoding header whether the body requires decoding (base64) or not.

How would you do that with gqlgen? I tried with HTTP middleware but that did not work at all, resolver middleware seems also not to be place to do it. Any ideas?

**Comment by vektah** [comment]
You would need to implement your own transport using 0.11+  https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/http_get.go

**Comment by genert** [comment]
Awesome. Thanks!
