### ISSUE TITLE
Rate limit example?

### ISSUE THREAD

**Issue by sneko** [99designs/gqlgen#972]
Hi,

I would like to know if someone has an example managing the rate limit to avoid users crashing the API with crazy requests haha :) ?

Like GitHub is using it: https://developer.github.com/v4/guides/resource-limitations/

Thank you,

**Comment by sneko** [comment]
Hi @vektah , have you seen something like that in Go?

**Comment by ramonberrutti** [comment]
Hi

For complexity: https://gqlgen.com/reference/complexity/

And for the rate limit, you can implement any of the available libraries.

**Comment by sneko** [comment]
Oh my bad, didn't look for the right wording!

About `you can implement any of the available libraries.`, do you have a favorite one? I saw Tollbooth, Limiter & co... having your feedback may help choosing 😄

Thank you @ramonberrutti!

**Comment by vektah** [comment]
Take a look at https://github.com/throttled/throttled for GCRA

**Comment by kidoman** [comment]
> Hi
> 
> For complexity: https://gqlgen.com/reference/complexity/
> 
> And for the rate limit, you can implement any of the available libraries.

Hi, we are so thankful for the gqlgen library!

Any tips on what would be the best way to implement a rate limit library idiomatically into gqlgen?
