### ISSUE TITLE
Injecting custom tags through a directive

### ISSUE THREAD

**Issue by raxosiris** [99designs/gqlgen#973]
Is there a way to add custom tags to fields through a directive? We'd like to change field names and create tags only for certain fields.

**Comment by vektah** [comment]
I'm not really sure what you're asking - you can use the config directives to bind to different field names?
```
type User {
    id: ID!         @goField(name: "todoId")
```

**Comment by mojtabacazi** [comment]
@vektah I think what's being asked here is to have something like this:

```
type User {
    id: ID!         @goField(tags: 'db:"abc" pg:"some other tag"')

```
Which then should result in 
type User struct {
   id string `json:"id" db:"abc" pg:"some other tag"` 
}
```

Also is it possible to remove those @goField from the introspection ? since they have no meaning outside of gql
