### ISSUE TITLE
IsNode() method on models which implement Node interface?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#976]
### What happened?

I'm following the "Getting started" section.

I'm using this schema: https://github.com/frederikhors/issuegqlgenisnode/blob/master/schema.graphql

which has:

```graphql
interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  username: String!
}
```

and something is broken because the server doesn't start with this error:

```log
# issuegqlgenisnode
.\generated.go:1870:2: impossible type switch case: obj (type Node) cannot have dynamic type *models.User (missing IsNode method)
```

### Minimal graphql.schema and models to reproduce

Reproduction: https://github.com/frederikhors/issuegqlgenisnode

### versions
 - `gqlgen version`? v0.10.2
 - `go version`? go1.13.5 windows/amd64
 - dep or go modules? go mod

**Comment by lwc** [comment]
Looks like your binding to your own user model, but generating the interface. 

These days when we generate interfaces we stick an empty function on them to tightly scope the usage on the Go side.

Your options are either to chuck that function on your user type and implement the interface, or opt out of generating the interface and bind to your own type without the function.

I guess we need to fix the docs!

**Comment by frederikhors** [comment]
I would like to understand more of what you wrote.

_I am a newbye, forgive my inexperience._

Could you add some details using the example `schema.graphql`?

Why the empty function `IsNode()`?

**Comment by vektah** [comment]
Without that method the generated interface would be be empty, eg
```
interface Node {
}
```
Thats the same thing as `interface{}`. Everything implements `interface{}`!

The signpost methods just puts something unique in our interface, so we know what types are actually implementing it.
