### ISSUE TITLE
Provide an optional CDN to the playground

### ISSUE THREAD

**Issue by ihgann** [99designs/gqlgen#981]
### What happened?

When running my app online, I wanted to be able to utilize GraphIQL from the Playground handler, but it currently has hardcoded CDN. I think this is a reasonable default, but breaks offline flows (or what happens when the CDN goes down)?

### What did you expect?

More of a feature request - potentially I could even submit the pull, but a way to optionally set the CDN for the GraphIQL javascript files (either globally or via instantiation of the handler, etc.).

### Minimal graphql.schema and models to reproduce
n/a

### versions
Latest of all

**Comment by vektah** [comment]
This is out of scope for gqlgen. You can bundle up whatever you like in your asset pipeline. The embedded (and optional) playground handler is just there to make it easy to get started.
