### ISSUE TITLE
[feature]  how can i generate Id  , not ID ,  like  protocol-buffers generate

### ISSUE THREAD

**Issue by betty200744** [99designs/gqlgen#984]
### What did you expect?

i want id  is also Camel-Case ~

### versions
gqlgen version: v0.10.2
go version: 1.13.5
go modules

**Comment by betty200744** [comment]
gqlgen version:  v0.10.2
go version: 1.13.5
go modules


![image](https://user-images.githubusercontent.com/16930356/72118970-dda1df80-338d-11ea-936b-6f82c5a1b0a5.png)

**Comment by ramonberrutti** [comment]
This feature will be a breaking change. Maybe with an option can be done.

**Comment by vektah** [comment]
Sorry this isnt going to happen, gqlgen tries to generate code that passes go lint, its complicated enough to get it right once.
