### ISSUE TITLE
is gqlgen support RelayJS?

### ISSUE THREAD

**Issue by xuanlongvts** [99designs/gqlgen#986]
hi gqlgen team,

if gqlgen supports relay is very cool

**Comment by ihgann** [comment]
@xuanlongvts Not OOTB, but you can implement the Relay spec yourself. I believe there is discussion over incorporating it as a potential plugin for the proposed plugin system (i.e. see #228 and #752 / #224)

**Comment by vektah** [comment]
Closing as dupe
