### ISSUE TITLE
INPUT_FIELD_DEFINITION directive doesn't give value or name

### ISSUE THREAD

**Issue by swkumar** [99designs/gqlgen#990]
### What happened?
I have a schema where I want to log the name and value for an input field, but I am unable to get the name and value of the input field associated with the directive
### What did you expect?
I would expect the name and value to be printed as mentioned in the type extension examples: https://github.com/99designs/gqlgen/blob/master/example/type-system-extension/directive.go
### Minimal graphql.schema and models to reproduce

Schema:
```
directive @inputLog on INPUT_FIELD_DEFINITION
input NewTodo {
  text: String! @inputLog
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

Directive definition:
```
func InputLog(
	ctx context.Context,
	obj interface{},
	next graphql.Resolver,
) (res interface{}, err error) {
	rc := graphql.GetResolverContext(ctx)
	strToBeLogged := fmt.Sprintf("field: %v has value %+v", rc.Field.Name, obj)
	fmt.Println(strToBeLogged)
	return next(ctx)
}
```

prints: `field: createTodo has value {Text: UserID:}`
I would expect `field: text has value foo`
### versions
 - `gqlgen version`: 0.8.0
 - `go version`: 1.13.4

**Comment by vektah** [comment]
`next()` gives you the value, it also allows authentication directives to prevent calling it.

obj is the thing surrounding the thing the directive was attached do.

**Comment by swkumar** [comment]
Thanks for the information @vektah. The value part makes sense. How do you propose I get the name for the field?

**Comment by vektah** [comment]
is `graphql.GetFieldContext(ctx).Field.Name` what you're looking for?

**Comment by swkumar** [comment]
Ah yes, I think that should do it. Thanks a ton!

**Comment by swkumar** [comment]
I ended up working around this to do some parsing at the level when the input is created. So, my new schema looks as follows:

```
directive @inputLog(blacklist:String) on INPUT_FIELD_DEFINITION
input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo! @inputLog(blacklist: "userId")): Todo!
}
```

I get a handle to the `NewTodo` object which is of the type `map[string]interface{}` and proceed to log the fields from there using JSON

**Comment by swkumar** [comment]
https://github.com/99designs/gqlgen/issues/1084 is the issue tracking the field directive issue

**Comment by davidolrik** [comment]
> Thanks for the information [@vektah](https://github.com/vektah). The value part makes sense. How do you propose I get the name for the field?

You can find a way to get the field name in this related issue: https://github.com/99designs/gqlgen/issues/1084
