### ISSUE TITLE
"Undefined type" error when attempting to use 3rd party model

### ISSUE THREAD

**Issue by raginjason** [99designs/gqlgen#997]
I am attempting to use a 3rd party library for some of my model. It's quite possible that I'm doing something wrong or that this is a gap in documentation. The command I ran was ```go run github.com/99designs/gqlgen -v```

### What happened?
```
$ go run github.com/99designs/gqlgen -v
schemaconfig: schema.graphql:3: Undefined type DiscordUser.
exit status 3
```

### What did you expect?
```go run github.com/99designs/gqlgen -v``` to execute cleanly

### Minimal graphql.schema and models to reproduce
gqlgen.yml:
```yaml
models:
  DiscordUser:
    model: github.com/bwmarrin/discordgo.User
```

schema.graphql:
```
type User {
  uuid: ID!
  discord: DiscordUser
}
```

### versions
 - `gqlgen version`? v0.10.2
 - `go version`?  v1.13 darwin/amd64
 - dep or go modules? modules

**Comment by lwc** [comment]
Looks like you don't have a GrapQL definition for `DiscordUser` in your schema?

gqlgen treats the gql schema as authoritative, and won't include fields from `github.com/bwmarrin/discordgo.User` on `DiscordUser` automatically.

**Comment by raginjason** [comment]
I sort of follow. My schema.graphql is now:
```
type User {
  uuid: ID!
  discord: DiscordUser
}

type DiscordUser {
  id:             ID!
  username:       String!
  discriminator:  String!
  email:          String
}
```

But that returns 

```
merging type systems failed: query entry point missing
exit status 3
```

**Comment by lwc** [comment]
You need to define a top level `Query` type in your schema
